/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib
import AlgebraicJacobian.Algebra.ABRegularQuotient
import AlgebraicJacobian.Algebra.ABRegularDomain
import AlgebraicJacobian.Albanese.Milne33CMEquidim

/-!
# Kernels of surjections of regular local rings are dim-difference generated

The diagonal-ideal brick of Milne Lemma 3.3, substep 4b-transport
(`informal/m33-spec.md` D5(a)/(c), point-agnostic form). Main result:

* `RingTheory.CohenMacaulay.exists_ofList_eq_ker_of_surjective` — for a
  surjective ring map `φ : B →+* A` of **regular local** Noetherian rings,
  the kernel is generated by `dim B − dim A` elements:
  there is a list `xs` with `Ideal.ofList xs = ker φ` and
  `xs.length + dim A = dim B` (stated with `spanFinrank` of the maximal
  ideals, which equals the Krull dimension by regularity; the
  `ringKrullDim` form is `…exists_ofList_eq_ker_length_add_ringKrullDim`).

The proof is a downward induction on `n = spanFinrank 𝔪_B`, entirely
two-residue-field-free:

* if `spanFinrank 𝔪_A = n`, then `coheight (ker φ) = dim (B/ker φ) = dim A
  = dim B`, so `ker φ` is a **minimal** prime (`coheight` strict
  antitonicity, `mem_minimalPrimes_of_coheight_eq_ringKrullDim`) of the
  **domain** `B` (landed `isDomain_of_regularLocal`), hence `ker φ = ⊥`;
* otherwise `spanFinrank 𝔪_A < n` forces some `x ∈ ker φ ∖ 𝔪_B²` — else
  lifts of generators of `𝔪_A` would generate `𝔪_B` modulo `𝔪_B²`, and
  Nakayama (`sup_eq_sup_smul_of_le_smul_of_le_jacobson`) would give
  `spanFinrank 𝔪_B ≤ spanFinrank 𝔪_A`. The quotient `B/(x)` is again
  regular local with `spanFinrank` dropped by one (landed
  `regularLocal_quotient_isRegularLocal_of_notMemSq`), `φ` descends, and
  the inductive kernel generators lift along `Ideal.ker_quotient_lift` +
  `comap_map_of_surjective`.

The 4b-transport consumes this at the diagonal: for the closed immersion
`δ : X ⟶ X ×_{k̄} X` and `z̃ = δ(z)`, the stalk surjection
`𝒪_{Y,z̃} ↠ 𝒪_{X,z}` has kernel generated by `dim 𝒪_{Y,z̃} − dim 𝒪_{X,z}`
elements, which feeds Krull's height theorem against (K) at height one
(`Milne33CMEquidim`).

Blueprint reference: `lem:milne_codim1_indeterminacy` (Milne, *Abelian
Varieties* §I.3 Lemma 3.3; EGA 0_IV 17.1.9).
-/

set_option autoImplicit false
set_option linter.overlappingInstances false

universe u v

open IsLocalRing

namespace RingTheory

/-- A prime whose coheight equals the (finite) Krull dimension is a minimal
prime. -/
lemma mem_minimalPrimes_of_coheight_eq_ringKrullDim {R : Type u} [CommRing R]
    [FiniteRingKrullDim R] {p : Ideal R} [hpr : p.IsPrime]
    (hp : (Order.coheight (⟨p, hpr⟩ : PrimeSpectrum R) : WithBot ℕ∞)
      = ringKrullDim R) :
    p ∈ minimalPrimes R := by
  by_contra hpm
  obtain ⟨q₀, hq₀min, hq₀le⟩ := Ideal.exists_minimalPrimes_le (bot_le (a := p))
  haveI : q₀.IsPrime := hq₀min.1.1
  have hlt : q₀ < p := hq₀le.lt_of_ne fun h => hpm (h ▸ hq₀min)
  have hstep : Order.coheight (⟨p, hpr⟩ : PrimeSpectrum R) + 1
      ≤ Order.coheight (⟨q₀, ‹q₀.IsPrime›⟩ : PrimeSpectrum R) :=
    Order.coheight_add_one_le (by exact_mod_cast hlt)
  have hcap : (Order.coheight (⟨q₀, ‹q₀.IsPrime›⟩ : PrimeSpectrum R)
      : WithBot ℕ∞) ≤ ringKrullDim R := Order.coheight_le_krullDim _
  have hne_top : Order.coheight (⟨p, hpr⟩ : PrimeSpectrum R) ≠ ⊤ := by
    intro h
    apply ringKrullDim_ne_top (R := R)
    rw [← hp, h]
    rfl
  have hle : Order.coheight (⟨q₀, ‹q₀.IsPrime›⟩ : PrimeSpectrum R)
      ≤ Order.coheight (⟨p, hpr⟩ : PrimeSpectrum R) := by
    have h := hcap.trans_eq hp.symm
    exact_mod_cast h
  exact lt_irrefl _ ((ENat.add_one_le_iff hne_top).mp (hstep.trans hle))

/-- In a domain, the only minimal prime is `⊥`. -/
lemma eq_bot_of_mem_minimalPrimes_of_isDomain {R : Type u} [CommRing R]
    [IsDomain R] {p : Ideal R} (hp : p ∈ minimalPrimes R) : p = ⊥ :=
  le_antisymm (hp.2 ⟨Ideal.isPrime_bot, le_rfl⟩ bot_le) bot_le

namespace CohenMacaulay

section KernelGeneration

variable {B : Type u} {A : Type v} [CommRing B] [CommRing A]

/-- A surjection out of a local ring onto a nontrivial ring maps the maximal
ideal onto the maximal ideal (no `IsLocalHom` hypothesis needed). -/
lemma map_maximalIdeal_eq_of_surjective [IsLocalRing B] [IsLocalRing A]
    (φ : B →+* A) (hφ : Function.Surjective φ) :
    (IsLocalRing.maximalIdeal B).map φ = IsLocalRing.maximalIdeal A := by
  have hker_le : RingHom.ker φ ≤ IsLocalRing.maximalIdeal B :=
    IsLocalRing.le_maximalIdeal (RingHom.ker_ne_top φ)
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro b hb
    by_contra hnb
    have hunit : IsUnit (φ b) := by
      by_contra h
      exact hnb ((IsLocalRing.mem_maximalIdeal _).mpr h)
    obtain ⟨c, hc⟩ := hunit.exists_right_inv
    obtain ⟨c', rfl⟩ := hφ c
    have hker : b * c' - 1 ∈ RingHom.ker φ := by
      rw [RingHom.mem_ker, map_sub, map_mul, map_one, hc, sub_self]
    have h1 : (1 : B) ∈ IsLocalRing.maximalIdeal B := by
      have hbc : b * c' ∈ IsLocalRing.maximalIdeal B :=
        Ideal.mul_mem_right _ _ hb
      simpa using sub_mem hbc (hker_le hker)
    exact (IsLocalRing.maximalIdeal.isMaximal B).ne_top
      ((Ideal.eq_top_iff_one _).mpr h1)
  · intro a ha
    obtain ⟨b, rfl⟩ := hφ a
    have hb : b ∈ IsLocalRing.maximalIdeal B := by
      by_contra hnb
      exact (IsLocalRing.mem_maximalIdeal _).mp ha
        ((IsLocalRing.notMem_maximalIdeal.mp hnb).map φ)
    exact Ideal.mem_map_of_mem φ hb

/-- The span-rank of the maximal ideal can only drop along a surjection of
local Noetherian rings. -/
lemma spanFinrank_maximalIdeal_le_of_surjective [IsLocalRing B]
    [IsNoetherianRing B] [IsLocalRing A] (φ : B →+* A)
    (hφ : Function.Surjective φ) :
    (IsLocalRing.maximalIdeal A).spanFinrank
      ≤ (IsLocalRing.maximalIdeal B).spanFinrank := by
  obtain ⟨s, hscard, hsspan⟩ :=
    (IsNoetherian.noetherian (IsLocalRing.maximalIdeal B)
      : (IsLocalRing.maximalIdeal B).FG).exists_span_finset_card_eq_spanFinrank
  have hsspan' : Ideal.span (↑s : Set B) = IsLocalRing.maximalIdeal B := hsspan
  have hAspan : Ideal.span (φ '' ↑s) = IsLocalRing.maximalIdeal A := by
    rw [← Ideal.map_span, hsspan', map_maximalIdeal_eq_of_surjective φ hφ]
  calc (IsLocalRing.maximalIdeal A).spanFinrank
      = (Ideal.span (φ '' ↑s)).spanFinrank := by rw [hAspan]
    _ ≤ (φ '' ↑s).ncard :=
        Submodule.spanFinrank_span_le_ncard_of_finite (s.finite_toSet.image φ)
    _ ≤ (↑s : Set B).ncard := Set.ncard_image_le s.finite_toSet
    _ = s.card := Set.ncard_coe_finset _
    _ = _ := hscard

/-- **The cotangent detection step**: if the target of a surjection of local
Noetherian rings has strictly smaller `spanFinrank`, some element of the
kernel is not in `𝔪_B²` — otherwise lifts of generators of `𝔪_A` would
generate `𝔪_B` by Nakayama. -/
lemma exists_mem_ker_notMem_sq [IsLocalRing B] [IsNoetherianRing B]
    [IsLocalRing A] [IsNoetherianRing A] (φ : B →+* A)
    (hφ : Function.Surjective φ)
    (hlt : (IsLocalRing.maximalIdeal A).spanFinrank
      < (IsLocalRing.maximalIdeal B).spanFinrank) :
    ∃ x ∈ RingHom.ker φ, x ∉ (IsLocalRing.maximalIdeal B) ^ 2 := by
  classical
  by_contra hcon
  push Not at hcon
  -- generators of `𝔪_A` and their lifts into `𝔪_B`
  obtain ⟨t, htcard, htspan⟩ :=
    (IsNoetherian.noetherian (IsLocalRing.maximalIdeal A)
      : (IsLocalRing.maximalIdeal A).FG).exists_span_finset_card_eq_spanFinrank
  have hmap := map_maximalIdeal_eq_of_surjective φ hφ
  have hlift : ∀ a : A, a ∈ IsLocalRing.maximalIdeal A →
      ∃ b, b ∈ IsLocalRing.maximalIdeal B ∧ φ b = a := by
    intro a ha
    rw [← hmap] at ha
    exact (Ideal.mem_map_iff_of_surjective φ hφ).mp ha
  choose bfun hbmem hbval using hlift
  have htsub : (↑t : Set A) ⊆ IsLocalRing.maximalIdeal A := by
    rw [← htspan]
    exact Submodule.subset_span
  -- the lifted finset
  set bF : Finset B :=
    t.attach.image (fun a => bfun a.1 (htsub a.2)) with hbFdef
  have hbFsub : (↑bF : Set B) ⊆ IsLocalRing.maximalIdeal B := by
    intro b hb
    simp only [hbFdef, Finset.coe_image, Set.mem_image] at hb
    obtain ⟨a, -, rfl⟩ := hb
    exact hbmem _ _
  -- `𝔪_B ≤ span bF ⊔ 𝔪_B • 𝔪_B`
  have hkey : IsLocalRing.maximalIdeal B
      ≤ Ideal.span ↑bF ⊔ IsLocalRing.maximalIdeal B • IsLocalRing.maximalIdeal B := by
    intro u hu
    have hφu : φ u ∈ Submodule.span A (↑t : Set A) := by
      have hm : φ u ∈ IsLocalRing.maximalIdeal A :=
        hmap ▸ Ideal.mem_map_of_mem φ hu
      rwa [← htspan] at hm
    rw [Submodule.mem_span_finset] at hφu
    obtain ⟨f, -, hf⟩ := hφu
    -- lift the coefficients
    have hcoef : ∀ a : A, ∃ g : B, φ g = f a := fun a => hφ (f a)
    choose gfun hgval using hcoef
    set v : B := ∑ a ∈ t.attach, gfun a.1 * bfun a.1 (htsub a.2) with hvdef
    have hvmem : v ∈ Ideal.span (↑bF : Set B) := by
      refine Submodule.sum_mem _ fun a _ => ?_
      refine Ideal.mul_mem_left _ _ (Submodule.subset_span ?_)
      simp only [hbFdef, Finset.coe_image, Set.mem_image]
      exact ⟨a, by simp, rfl⟩
    have hφv : φ v = φ u := by
      rw [hvdef, map_sum]
      rw [← hf, ← Finset.sum_attach t (fun a => f a • a)]
      refine Finset.sum_congr rfl fun a _ => ?_
      rw [map_mul, hgval, hbval, smul_eq_mul]
    have huv : u - v ∈ RingHom.ker φ := by
      rw [RingHom.mem_ker, map_sub, hφv, sub_self]
    have huvsq := hcon _ huv
    have : u = v + (u - v) := by ring
    rw [this]
    refine Submodule.add_mem _ (Ideal.mem_sup_left hvmem) (Ideal.mem_sup_right ?_)
    rwa [Ideal.smul_eq_mul, ← pow_two]
  -- Nakayama: `𝔪_B = span bF`, contradicting the spanFinrank gap
  have hsup := Submodule.sup_eq_sup_smul_of_le_smul_of_le_jacobson
    (I := IsLocalRing.maximalIdeal B) (J := ⊥) (N := Ideal.span ↑bF)
    (N' := IsLocalRing.maximalIdeal B)
    (IsNoetherian.noetherian _) (IsLocalRing.maximalIdeal_le_jacobson ⊥) hkey
  rw [Submodule.bot_smul, sup_bot_eq] at hsup
  have hMle : IsLocalRing.maximalIdeal B ≤ Ideal.span ↑bF := by
    rw [← hsup]
    exact le_sup_right
  have hMeq : Ideal.span (↑bF : Set B) = IsLocalRing.maximalIdeal B :=
    le_antisymm (Ideal.span_le.mpr hbFsub) hMle
  have hcount : (IsLocalRing.maximalIdeal B).spanFinrank
      ≤ (IsLocalRing.maximalIdeal A).spanFinrank := by
    calc (IsLocalRing.maximalIdeal B).spanFinrank
        = (Ideal.span (↑bF : Set B)).spanFinrank := by rw [hMeq]
      _ ≤ (↑bF : Set B).ncard :=
          Submodule.spanFinrank_span_le_ncard_of_finite bF.finite_toSet
      _ = bF.card := Set.ncard_coe_finset _
      _ ≤ t.attach.card := by rw [hbFdef]; exact Finset.card_image_le
      _ = t.card := Finset.card_attach
      _ = _ := htcard
  exact absurd (hlt.trans_le hcount) (lt_irrefl _)

omit [CommRing B] in
/-- Lift a list along a surjection. -/
private lemma exists_list_map_eq {B₁ : Type u} (f : B → B₁)
    (hf : Function.Surjective f) (l' : List B₁) :
    ∃ l : List B, l.map f = l' := by
  induction l' with
  | nil => exact ⟨[], rfl⟩
  | cons b' tl' ih =>
    obtain ⟨tl, htl⟩ := ih
    obtain ⟨b, hb⟩ := hf b'
    exact ⟨b :: tl, by simp [hb, htl]⟩

/-- **The equal-dimension case**: a surjection of regular local rings with
equal maximal-ideal span-ranks has trivial kernel — the kernel is a prime of
coheight `dim B`, hence a minimal prime of the domain `B`. -/
lemma ker_eq_bot_of_spanFinrank_eq [IsRegularLocalRing B] [IsRegularLocalRing A]
    (φ : B →+* A) (hφ : Function.Surjective φ)
    (h : (IsLocalRing.maximalIdeal A).spanFinrank
      = (IsLocalRing.maximalIdeal B).spanFinrank) :
    RingHom.ker φ = ⊥ := by
  haveI : IsDomain B := isDomain_of_regularLocal B
  haveI : IsDomain A := isDomain_of_regularLocal A
  haveI hDpr : (RingHom.ker φ).IsPrime := RingHom.ker_isPrime φ
  have hdimB : (((IsLocalRing.maximalIdeal B).spanFinrank : ℕ) : WithBot ℕ∞)
      = ringKrullDim B := IsRegularLocalRing.spanFinrank_maximalIdeal
  have hdimA : (((IsLocalRing.maximalIdeal A).spanFinrank : ℕ) : WithBot ℕ∞)
      = ringKrullDim A := IsRegularLocalRing.spanFinrank_maximalIdeal
  have hquot : ringKrullDim (B ⧸ RingHom.ker φ) = ringKrullDim A :=
    ringKrullDim_eq_of_ringEquiv (RingHom.quotientKerEquivOfSurjective hφ)
  have hcoh : (Order.coheight
        (⟨RingHom.ker φ, hDpr⟩ : PrimeSpectrum B) : WithBot ℕ∞)
      = ringKrullDim B := by
    rw [← ringKrullDim_quotient_eq_coheight (RingHom.ker φ), hquot, ← hdimA,
      h, hdimB]
  exact eq_bot_of_mem_minimalPrimes_of_isDomain
    (mem_minimalPrimes_of_coheight_eq_ringKrullDim hcoh)

/-- **Kernels of surjections of regular local rings, spanFinrank form**: the
kernel of a surjective ring map `φ : B →+* A` of regular local Noetherian
rings is generated by a list of `spanFinrank 𝔪_B − spanFinrank 𝔪_A`
elements. -/
theorem exists_ofList_eq_ker_of_surjective
    [IsRegularLocalRing B] [IsRegularLocalRing A]
    (φ : B →+* A) (hφ : Function.Surjective φ) :
    ∃ xs : List B, Ideal.ofList xs = RingHom.ker φ ∧
      xs.length + (IsLocalRing.maximalIdeal A).spanFinrank
        = (IsLocalRing.maximalIdeal B).spanFinrank := by
  suffices haux : ∀ (n : ℕ) (B : Type u) [CommRing B] [IsRegularLocalRing B]
      (φ : B →+* A), Function.Surjective φ →
      (IsLocalRing.maximalIdeal B).spanFinrank = n →
      ∃ xs : List B, Ideal.ofList xs = RingHom.ker φ ∧
        xs.length + (IsLocalRing.maximalIdeal A).spanFinrank = n by
    obtain ⟨xs, h1, h2⟩ :=
      haux (IsLocalRing.maximalIdeal B).spanFinrank B φ hφ rfl
    exact ⟨xs, h1, h2⟩
  intro n
  induction n with
  | zero =>
    intro B _ _ φ hφ hn
    -- `spanFinrank 𝔪_A ≤ 0`, so both span-ranks agree and the kernel is
    -- trivial.
    have hle := spanFinrank_maximalIdeal_le_of_surjective φ hφ
    rw [hn, Nat.le_zero] at hle
    refine ⟨[], ?_, by simp [hle]⟩
    rw [Ideal.ofList_nil]
    exact (ker_eq_bot_of_spanFinrank_eq φ hφ (by rw [hn, hle])).symm
  | succ k ih =>
    intro B _ _ φ hφ hn
    rcases eq_or_lt_of_le (spanFinrank_maximalIdeal_le_of_surjective φ hφ)
      with heq | hlt
    · -- equal spanFinranks: kernel is `⊥`
      refine ⟨[], ?_, by rw [heq, hn]; simp⟩
      rw [Ideal.ofList_nil]
      exact (ker_eq_bot_of_spanFinrank_eq φ hφ heq).symm
    · -- strict drop: peel one kernel element off `𝔪_B ∖ 𝔪_B²`
      rw [hn] at hlt
      obtain ⟨x, hxker, hxsq⟩ := exists_mem_ker_notMem_sq φ hφ (by rwa [hn])
      have hx𝔪 : x ∈ IsLocalRing.maximalIdeal B :=
        IsLocalRing.le_maximalIdeal (RingHom.ker_ne_top φ) hxker
      obtain ⟨hNT, hLR, hReg, hspan₁⟩ :=
        regularLocal_quotient_isRegularLocal_of_notMemSq hn x hx𝔪 hxsq
      haveI := hNT
      haveI := hLR
      haveI := hReg
      -- descend `φ` to `B/(x)`
      have hxle : Ideal.span ({x} : Set B) ≤ RingHom.ker φ := by
        rwa [Ideal.span_singleton_le_iff_mem]
      set φ₁ : B ⧸ Ideal.span ({x} : Set B) →+* A :=
        Ideal.Quotient.lift _ φ (fun y hy => hxle hy) with hφ₁def
      have hφ₁surj : Function.Surjective φ₁ := by
        intro a
        obtain ⟨b, rfl⟩ := hφ a
        exact ⟨Ideal.Quotient.mk _ b, by simp [hφ₁def]⟩
      obtain ⟨ys', hys'span, hys'len⟩ := ih _ φ₁ hφ₁surj hspan₁
      -- lift the generators
      obtain ⟨ys, hysmap⟩ :=
        exists_list_map_eq (Ideal.Quotient.mk (Ideal.span ({x} : Set B)))
          Ideal.Quotient.mk_surjective ys'
      refine ⟨x :: ys, ?_, ?_⟩
      · -- span equality through `map`/`comap` along the quotient
        have hmapof : Ideal.map (Ideal.Quotient.mk (Ideal.span ({x} : Set B)))
            (Ideal.ofList (x :: ys)) = RingHom.ker φ₁ := by
          rw [Ideal.ofList_cons, Ideal.map_sup, Ideal.map_ofList, hysmap,
            hys'span]
          have hx0 : Ideal.map (Ideal.Quotient.mk (Ideal.span ({x} : Set B)))
              (Ideal.span ({x} : Set B)) = ⊥ := by
            rw [Ideal.map_span]
            simp
          rw [hx0, bot_sup_eq]
        have hkerφ₁ : RingHom.ker φ₁
            = Ideal.map (Ideal.Quotient.mk (Ideal.span ({x} : Set B)))
              (RingHom.ker φ) := Ideal.ker_quotient_lift φ _
        have hcomap := congrArg
          (Ideal.comap (Ideal.Quotient.mk (Ideal.span ({x} : Set B))))
          (hmapof.trans hkerφ₁)
        rw [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
          Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
          ← RingHom.ker_eq_comap_bot, Ideal.mk_ker] at hcomap
        have hxle' : Ideal.span ({x} : Set B) ≤ Ideal.ofList (x :: ys) := by
          rw [Ideal.ofList_cons]
          exact le_sup_left
        rwa [sup_eq_left.mpr hxle', sup_eq_left.mpr hxle] at hcomap
      · -- length bookkeeping
        have hlen : ys.length = ys'.length := by
          rw [← hysmap, List.length_map]
        simp only [List.length_cons, hlen]
        omega

/-- **Kernels of surjections of regular local rings, Krull-dimension form**
(the shape consumed by the Milne 3.3 4b-transport at the diagonal stalk
surjection `𝒪_{Y,z̃} ↠ 𝒪_{X,z}`): the kernel is generated by a list `xs`
with `xs.length + dim A = dim B`. -/
theorem exists_ofList_eq_ker_length_add_ringKrullDim
    [IsRegularLocalRing B] [IsRegularLocalRing A]
    (φ : B →+* A) (hφ : Function.Surjective φ) :
    ∃ xs : List B, Ideal.ofList xs = RingHom.ker φ ∧
      (xs.length : WithBot ℕ∞) + ringKrullDim A = ringKrullDim B := by
  obtain ⟨xs, hspan, hlen⟩ := exists_ofList_eq_ker_of_surjective φ hφ
  refine ⟨xs, hspan, ?_⟩
  have hdimB : (((IsLocalRing.maximalIdeal B).spanFinrank : ℕ) : WithBot ℕ∞)
      = ringKrullDim B := IsRegularLocalRing.spanFinrank_maximalIdeal
  have hdimA : (((IsLocalRing.maximalIdeal A).spanFinrank : ℕ) : WithBot ℕ∞)
      = ringKrullDim A := IsRegularLocalRing.spanFinrank_maximalIdeal
  rw [← hdimA, ← hdimB, ← hlen]
  push_cast
  ring

end KernelGeneration

end CohenMacaulay

end RingTheory
