/-
Copyright (c) 2026 The AlgebraicJacobian Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Unramified.Basic
import Mathlib.RingTheory.Ideal.IdempotentFG
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Algebra.Polynomial.Div

/-!
# The diagonal ideal of an étale-coordinatised algebra (brick B0)

Let `k` be a commutative ring and `B` a commutative `k`-algebra which is also a
`Polynomial k`-algebra compatibly (an *étale coordinate* `u := algebraMap (Polynomial k) B X`
in the intended application, where `Polynomial k → B` is étale).  This file is the pure
commutative-algebra core (deg-D4b, sub-brick B0) computing the `k`-diagonal ideal of
`B ⊗[k] B` after localising away from an idempotent lift.

The geometric picture: `Spec B` is a standard-smooth chart of a relative curve, the étale
coordinate `u` cuts it out over `𝔸¹ = Spec (Polynomial k)`, and the diagonal `Δ` of
`Spec B ×_k Spec B` is, on a basic open containing all of `Δ`, the vanishing locus of the
single equation `u ⊗ 1 - 1 ⊗ u`.

## Main results

* `AlgebraicJacobian.Diagonal.ker_baseChange`
  (deliverable **(a)**): the kernel of the base-change surjection
  `π : B ⊗[k] B → B ⊗[Polynomial k] B` is `Ideal.span {u ⊗ₜ 1 - 1 ⊗ₜ u}`.
* `AlgebraicJacobian.Diagonal.exists_idempotent_lift`
  (deliverable **(b)**): when `Polynomial k → B` is (formally) unramified and essentially
  of finite type, the `Polynomial k`-diagonal ideal `ker (mul : B ⊗[Polynomial k] B → B)`
  is generated by an idempotent `e = π elift`.
* `AlgebraicJacobian.Diagonal.ker_map_localization_eq`
  (deliverable **(c)**): for such an idempotent lift `elift`, the `k`-diagonal ideal
  `ker (mul : B ⊗[k] B → B)`, extended to any localisation away from `1 - elift`, is the
  principal ideal generated by `u ⊗ 1 - 1 ⊗ u`.
* `AlgebraicJacobian.Diagonal.exists_diagonalLocalization`: the packaged existence
  statement consumed by the assembly brick (B5): a frozen `elift` with `mul elift = 0` and
  the localised principality.

Together with `AlgebraicJacobian.Diagonal.lmul'_diagGen` (`mul (u⊗1 − 1⊗u) = 0`) and
`AlgebraicJacobian.Diagonal.lmul'_lift` (`mul elift = 0`) these are exactly the B0
deliverables of `informal/deg-d4b-worksheet.md` §D1.

Everything is stated over an abstract `(B, Polynomial k → B, elift)` package (no scheme
imports); the curve-level chart data is frozen only in the assembly brick.
-/

set_option autoImplicit false

open scoped TensorProduct
open Polynomial

namespace AlgebraicJacobian.Diagonal

variable {k B : Type*} [CommRing k] [CommRing B] [Algebra k B]
  [Algebra (Polynomial k) B] [IsScalarTower k (Polynomial k) B]

variable (k B) in
/-- The étale coordinate `u := algebraMap (Polynomial k) B X`. 


 * Provenance: CUSTOM.
-/
noncomputable def coord : B := algebraMap (Polynomial k) B X

/-- The diagonal equation `u ⊗ 1 - 1 ⊗ u ∈ B ⊗[k] B`. 


 * Provenance: CUSTOM.
-/
noncomputable def diagGen : B ⊗[k] B := coord k B ⊗ₜ[k] (1 : B) - (1 : B) ⊗ₜ[k] coord k B

/-- The base-change surjection `π : B ⊗[k] B →ₐ[k] B ⊗[Polynomial k] B`, sending
`x ⊗ y ↦ x ⊗ y`. Its kernel is the ideal generated by `u ⊗ 1 - 1 ⊗ u`
(`ker_baseChange`). 


 * Provenance: CUSTOM.
-/
noncomputable def baseChange : B ⊗[k] B →ₐ[k] B ⊗[Polynomial k] B :=
  Algebra.TensorProduct.lift
    ((Algebra.TensorProduct.includeLeft :
        B →ₐ[Polynomial k] B ⊗[Polynomial k] B).restrictScalars k)
    ((Algebra.TensorProduct.includeRight :
        B →ₐ[Polynomial k] B ⊗[Polynomial k] B).restrictScalars k)
    (fun _ _ => Commute.all _ _)

@[simp] lemma baseChange_tmul (x y : B) :
    baseChange (x ⊗ₜ[k] y) = x ⊗ₜ[Polynomial k] y := by
  rw [baseChange, Algebra.TensorProduct.lift_tmul]
  change Algebra.TensorProduct.includeLeft x * Algebra.TensorProduct.includeRight y = _
  rw [Algebra.TensorProduct.includeLeft_apply, Algebra.TensorProduct.includeRight_apply,
    Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one]

lemma baseChange_surjective : Function.Surjective (baseChange (k := k) (B := B)) := by
  intro z
  induction z with
  | zero => exact ⟨0, map_zero _⟩
  | tmul x y => exact ⟨x ⊗ₜ[k] y, baseChange_tmul x y⟩
  | add a b ha hb =>
      obtain ⟨a', ha'⟩ := ha; obtain ⟨b', hb'⟩ := hb
      exact ⟨a' + b', by rw [map_add, ha', hb']⟩

/-- The `k`-multiplication `B ⊗[k] B → B` factors through the base-change map `π` followed
by the `Polynomial k`-multiplication: `mul_P (π z) = mul_k z`. 


 * Provenance: CUSTOM.
-/
lemma lmul'_baseChange (z : B ⊗[k] B) :
    Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B) (baseChange z)
      = Algebra.TensorProduct.lmul' k z := by
  induction z with
  | zero => simp
  | tmul x y => rw [baseChange_tmul, Algebra.TensorProduct.lmul'_apply_tmul,
      Algebra.TensorProduct.lmul'_apply_tmul]
  | add a b ha hb => simp only [map_add, ha, hb]

omit [IsScalarTower k (Polynomial k) B] in
/-- `mul (u ⊗ 1 - 1 ⊗ u) = 0` (deliverable): the diagonal equation lies in the
`k`-diagonal ideal. 
 * Provenance: CUSTOM.
-/
@[simp] lemma lmul'_diagGen :
    Algebra.TensorProduct.lmul' k (diagGen (k := k) (B := B)) = 0 := by
  rw [diagGen, map_sub, Algebra.TensorProduct.lmul'_apply_tmul,
    Algebra.TensorProduct.lmul'_apply_tmul, mul_one, one_mul, sub_self]

omit [Algebra k B] [IsScalarTower k (Polynomial k) B] in
/-- In `B ⊗[Polynomial k] B` the coordinate commutes across the tensor: `u ⊗ 1 = 1 ⊗ u`,
because `u = X • 1` and `X` is a scalar of the tensor product. -/
lemma coord_tmul_one :
    coord k B ⊗ₜ[Polynomial k] (1 : B) = (1 : B) ⊗ₜ[Polynomial k] coord k B := by
  have h1 : (coord k B : B) = (X : Polynomial k) • (1 : B) := by
    rw [Algebra.smul_def, mul_one]; rfl
  rw [h1, TensorProduct.smul_tmul]

/-- `π` kills the diagonal equation. 


 * Provenance: CUSTOM.
-/
lemma baseChange_diagGen : baseChange (diagGen (k := k) (B := B)) = 0 := by
  rw [diagGen, map_sub, baseChange_tmul, baseChange_tmul, coord_tmul_one, sub_self]

/-! ### The telescoping identity and the kernel computation (deliverable (a)) -/

/-- `algebraMap (Polynomial k) B` is the `k`-algebra evaluation `p ↦ p(u)`. -/
lemma algebraMap_eq_aeval (p : Polynomial k) :
    algebraMap (Polynomial k) B p = aeval (coord k B) p := by
  have h : (IsScalarTower.toAlgHom k (Polynomial k) B) = aeval (coord k B) := by
    apply Polynomial.algHom_ext; simp [coord]
  simpa [IsScalarTower.toAlgHom_apply] using DFunLike.congr_fun h p

omit [Algebra (Polynomial k) B] [IsScalarTower k (Polynomial k) B] in
/-- Difference of evaluations at two points is divisible by the difference of the points. -/
lemma aeval_sub_dvd (a b : B ⊗[k] B) (p : Polynomial k) :
    a - b ∣ aeval a p - aeval b p := by
  rw [aeval_def, aeval_def, eval₂_eq_eval_map, eval₂_eq_eval_map]
  exact sub_dvd_eval_sub a b _

/-- **Telescoping.** For every `p`, the element `g(p) ⊗ 1 - 1 ⊗ g(p)` lies in the ideal
generated by `u ⊗ 1 - 1 ⊗ u`, where `g = algebraMap (Polynomial k) B`. This is the
`k`-derivation Leibniz identity for the polynomial base. 


 * Provenance: CUSTOM.
-/
lemma algebraMap_tmul_sub_mem_span (p : Polynomial k) :
    (algebraMap (Polynomial k) B p) ⊗ₜ[k] (1 : B)
        - (1 : B) ⊗ₜ[k] (algebraMap (Polynomial k) B p)
      ∈ Ideal.span {diagGen (k := k) (B := B)} := by
  rw [Ideal.mem_span_singleton, diagGen, algebraMap_eq_aeval]
  have hL : (aeval (coord k B) p) ⊗ₜ[k] (1 : B)
      = aeval (coord k B ⊗ₜ[k] (1 : B)) p := by
    rw [← Algebra.TensorProduct.includeLeft_apply (S := k),
      ← Polynomial.aeval_algHom_apply, Algebra.TensorProduct.includeLeft_apply]
  have hR : (1 : B) ⊗ₜ[k] (aeval (coord k B) p)
      = aeval ((1 : B) ⊗ₜ[k] coord k B) p := by
    rw [← Algebra.TensorProduct.includeRight_apply,
      ← Polynomial.aeval_algHom_apply, Algebra.TensorProduct.includeRight_apply]
  rw [hL, hR]
  exact aeval_sub_dvd _ _ p

/-- The right inclusion `b ↦ 1 ⊗ b` into the quotient by the diagonal equation, promoted to
a `Polynomial k`-algebra homomorphism using the telescoping identity. This is one half of
the section `ψ` of `π`. 


 * Provenance: CUSTOM.
-/
noncomputable def qRight : B →ₐ[Polynomial k] (B ⊗[k] B) ⧸ Ideal.span {diagGen (k := k) (B := B)}
    where
  toFun b := Ideal.Quotient.mk _ ((1 : B) ⊗ₜ[k] b)
  map_one' := by rw [← Algebra.TensorProduct.one_def]; exact map_one _
  map_mul' a b := by rw [← map_mul, Algebra.TensorProduct.tmul_mul_tmul, one_mul]
  map_zero' := by simp
  map_add' a b := by rw [← map_add, TensorProduct.tmul_add]
  commutes' p := by
    change Ideal.Quotient.mk _ ((1 : B) ⊗ₜ[k] algebraMap (Polynomial k) B p)
      = algebraMap (Polynomial k) ((B ⊗[k] B) ⧸ Ideal.span {diagGen (k := k) (B := B)}) p
    have h : algebraMap (Polynomial k) ((B ⊗[k] B) ⧸ Ideal.span {diagGen (k := k) (B := B)}) p
        = Ideal.Quotient.mk _ ((algebraMap (Polynomial k) B p) ⊗ₜ[k] (1 : B)) := rfl
    rw [h, Ideal.Quotient.eq, ← neg_sub]
    exact neg_mem (algebraMap_tmul_sub_mem_span p)

/-- The section `ψ : B ⊗[Polynomial k] B → (B ⊗[k] B) ⧸ (u⊗1 − 1⊗u)` of `π`, sending
`x ⊗ y ↦ x ⊗ y`. Composed with `π` it is the quotient map, which forces
`ker π ⊆ (u⊗1 − 1⊗u)`. 


 * Provenance: CUSTOM.
-/
noncomputable def sectionMap :
    B ⊗[Polynomial k] B →ₐ[Polynomial k] (B ⊗[k] B) ⧸ Ideal.span {diagGen (k := k) (B := B)} :=
  Algebra.TensorProduct.lift
    ((Ideal.Quotient.mkₐ (Polynomial k) _).comp Algebra.TensorProduct.includeLeft)
    qRight (fun _ _ => Commute.all _ _)

lemma sectionMap_tmul (x y : B) :
    sectionMap (x ⊗ₜ[Polynomial k] y)
      = Ideal.Quotient.mk (Ideal.span {diagGen (k := k) (B := B)}) (x ⊗ₜ[k] y) := by
  rw [sectionMap, Algebra.TensorProduct.lift_tmul]
  change (Ideal.Quotient.mk _ (x ⊗ₜ[k] 1)) * (Ideal.Quotient.mk _ (1 ⊗ₜ[k] y)) = _
  rw [← map_mul, Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]

/-- `ψ ∘ π` is the quotient map: the key identity forcing `ker π ⊆ (u⊗1 − 1⊗u)`. 


 * Provenance: CUSTOM.
-/
lemma sectionMap_baseChange (z : B ⊗[k] B) :
    sectionMap (baseChange z)
      = Ideal.Quotient.mk (Ideal.span {diagGen (k := k) (B := B)}) z := by
  induction z with
  | zero => simp
  | tmul x y => rw [baseChange_tmul, sectionMap_tmul]
  | add a b ha hb => simp only [map_add, ha, hb]

/-- **Deliverable (a).** The kernel of the base-change surjection `π : B ⊗[k] B →
B ⊗[Polynomial k] B` is exactly the principal ideal generated by `u ⊗ 1 - 1 ⊗ u`. 


 * Provenance: CUSTOM.
-/
theorem ker_baseChange :
    RingHom.ker (baseChange (k := k) (B := B)) = Ideal.span {diagGen (k := k) (B := B)} := by
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker] at hx
    have hmk : Ideal.Quotient.mk (Ideal.span {diagGen (k := k) (B := B)}) x = 0 := by
      rw [← sectionMap_baseChange x, hx, map_zero]
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hmk
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker]
    exact baseChange_diagGen

/-! ### The idempotent generator of the `Polynomial k`-diagonal ideal (deliverable (b)) -/

section Unramified
variable [Algebra.FormallyUnramified (Polynomial k) B] [Algebra.EssFiniteType (Polynomial k) B]

/-- **Deliverable (b).** When `Polynomial k → B` is (formally) unramified and essentially of
finite type, the `Polynomial k`-diagonal ideal `ker (mul : B ⊗[Polynomial k] B → B)` is
generated by an idempotent `e`; moreover `e = π elift` for a lift `elift ∈ B ⊗[k] B`. 


 * Provenance: CUSTOM.
-/
lemma exists_idempotent_lift :
    ∃ elift : B ⊗[k] B, IsIdempotentElem (baseChange elift) ∧
      RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B))
        = Ideal.span {baseChange elift} := by
  have hfg : (KaehlerDifferential.ideal (Polynomial k) B).FG := KaehlerDifferential.ideal_fg _ _
  have hidem : IsIdempotentElem (KaehlerDifferential.ideal (Polynomial k) B) :=
    (Ideal.cotangent_subsingleton_iff _).mp <|
      inferInstanceAs <| Subsingleton Ω[B⁄Polynomial k]
  obtain ⟨e, he, hsp⟩ := (Ideal.isIdempotentElem_iff_of_fg _ hfg).mp hidem
  obtain ⟨elift, rfl⟩ := baseChange_surjective e
  refine ⟨elift, he, ?_⟩
  simpa [Ideal.span] using hsp

end Unramified

/-! ### The localised principality (deliverable (c)) -/

section Localization

variable (elift : B ⊗[k] B)
  (hidem : IsIdempotentElem (baseChange elift))
  (hgen : RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B))
    = Ideal.span {baseChange elift})

include hgen in
/-- **Deliverable.** `mul elift = 0`: the idempotent lift lies in the `k`-diagonal ideal, so
the basic open `D(1 - elift)` contains all of the diagonal. 


 * Provenance: CUSTOM.
-/
lemma lmul'_lift : Algebra.TensorProduct.lmul' k elift = 0 := by
  have hmem : baseChange elift ∈ RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k)
      (S := B)) := by
    rw [hgen]; exact Ideal.subset_span rfl
  rw [RingHom.mem_ker] at hmem
  rw [← lmul'_baseChange elift]; exact hmem

include hgen in
/-- The `k`-diagonal ideal is contained in the sum of the diagonal-equation ideal and the
principal ideal of the lift `elift`; this is the algebraic content of `I = ker π + (elift)`. -/
lemma ker_lmul'_le_sup :
    RingHom.ker (Algebra.TensorProduct.lmul' k (S := B))
      ≤ Ideal.span {diagGen (k := k) (B := B)} ⊔ Ideal.span {elift} := by
  intro x hx
  rw [RingHom.mem_ker] at hx
  -- `π x` lies in the `Polynomial k`-diagonal ideal `(π elift)`
  have hπx : baseChange x ∈ RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k)
      (S := B)) := by
    rw [RingHom.mem_ker, lmul'_baseChange x, hx]
  rw [hgen, Ideal.mem_span_singleton] at hπx
  obtain ⟨c, hc⟩ := hπx
  obtain ⟨w, rfl⟩ := baseChange_surjective c
  -- `x - elift * w ∈ ker π = (u⊗1 − 1⊗u)`
  have hkey : x - elift * w ∈ Ideal.span {diagGen (k := k) (B := B)} := by
    rw [← ker_baseChange, RingHom.mem_ker, map_sub, map_mul, hc]
    ring
  have hx' : x = (x - elift * w) + elift * w := by ring
  rw [hx']
  exact add_mem (Ideal.mem_sup_left hkey)
    (Ideal.mem_sup_right (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)))

variable (L : Type*) [CommRing L] [Algebra (B ⊗[k] B) L]
  [IsLocalization.Away (1 - elift) L]

include hidem hgen in
/-- **Deliverable (c).** For an idempotent lift `elift`, the `k`-diagonal ideal
`ker (mul : B ⊗[k] B → B)`, extended along any localisation away from `1 - elift`, is the
principal ideal generated by the diagonal equation `u ⊗ 1 - 1 ⊗ u`. 


 * Provenance: CUSTOM.
-/
theorem ker_map_localization_eq :
    (RingHom.ker (Algebra.TensorProduct.lmul' k (S := B))).map (algebraMap (B ⊗[k] B) L)
      = Ideal.span {algebraMap (B ⊗[k] B) L (diagGen (k := k) (B := B))} := by
  -- `elift` becomes a multiple of `u⊗1 − 1⊗u` after inverting `1 - elift`
  have hdvd : algebraMap (B ⊗[k] B) L elift ∈
      Ideal.span {algebraMap (B ⊗[k] B) L (diagGen (k := k) (B := B))} := by
    have hunit : IsUnit (algebraMap (B ⊗[k] B) L (1 - elift)) :=
      IsLocalization.map_units L (⟨1 - elift, Submonoid.mem_powers _⟩ : Submonoid.powers _)
    obtain ⟨v, hv⟩ := hunit.exists_right_inv
    have hmem : elift * (1 - elift) ∈ Ideal.span {diagGen (k := k) (B := B)} := by
      rw [← ker_baseChange, RingHom.mem_ker, map_mul, map_sub, map_one, mul_sub, mul_one,
        hidem.eq, sub_self]
    have hfmem : algebraMap (B ⊗[k] B) L (elift * (1 - elift)) ∈
        Ideal.span {algebraMap (B ⊗[k] B) L (diagGen (k := k) (B := B))} := by
      have hmap := Ideal.mem_map_of_mem (algebraMap (B ⊗[k] B) L) hmem
      rwa [Ideal.map_span, Set.image_singleton] at hmap
    have heq : algebraMap (B ⊗[k] B) L elift
        = algebraMap (B ⊗[k] B) L (elift * (1 - elift)) * v := by
      rw [map_mul, mul_assoc, hv, mul_one]
    rw [heq]; exact Ideal.mul_mem_right _ _ hfmem
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine (ker_lmul'_le_sup elift hgen).trans ?_
    rw [sup_le_iff]
    refine ⟨?_, ?_⟩
    · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, Ideal.mem_comap]
      exact Ideal.subset_span rfl
    · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, Ideal.mem_comap]
      exact hdvd
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    exact Ideal.mem_map_of_mem _ (by rw [RingHom.mem_ker]; exact lmul'_diagGen)

end Localization

/-! ### Packaged existence for the assembly brick -/

/-- The B5-facing existence statement: a frozen idempotent lift `elift` with `mul elift = 0`
and the localised principality of the `k`-diagonal ideal on the basic open `D(1 - elift)`.
Combines deliverables (a)–(c). For a localisation other than `Localization.Away (1 - elift)`
(e.g. the sections of a scheme-theoretic basic open) apply `ker_map_localization_eq` directly
to the returned `elift`, `hidem`, `hgen`. 


 * Provenance: CUSTOM.
-/
theorem exists_diagonalLocalization
    [Algebra.FormallyUnramified (Polynomial k) B] [Algebra.EssFiniteType (Polynomial k) B] :
    ∃ elift : B ⊗[k] B, Algebra.TensorProduct.lmul' k elift = 0 ∧
      IsIdempotentElem (baseChange elift) ∧
      RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B))
        = Ideal.span {baseChange elift} ∧
      (RingHom.ker (Algebra.TensorProduct.lmul' k (S := B))).map
          (algebraMap (B ⊗[k] B) (Localization.Away (1 - elift)))
        = Ideal.span {algebraMap (B ⊗[k] B) (Localization.Away (1 - elift))
            (diagGen (k := k) (B := B))} := by
  obtain ⟨elift, hidem, hgen⟩ := exists_idempotent_lift (k := k) (B := B)
  exact ⟨elift, lmul'_lift elift hgen, hidem, hgen,
    ker_map_localization_eq elift hidem hgen (Localization.Away (1 - elift))⟩

end AlgebraicJacobian.Diagonal
