/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Algebra.LaurentNilpotentCoeff

/-!
# EVERY UNIT CONGRUENT TO `1` MODULO NILPOTENTS IS A ℙ¹ COBOUNDARY

`Algebra/LaurentNilpotentCoboundary.lean` proves that `1 + C e · f` is a two-chart coboundary when
`e` is nilpotent — the **single-generator** case, where the whole nilpotent deformation is a
multiple of one element `e`.  The arbitrary-ring ℙ¹ Picard computation needs the **multi-generator**
statement: a Laurent unit `1 + z` with `z` an *arbitrary* nilpotent Laurent polynomial (whose
coefficients generate an arbitrary nilpotent ideal, not a principal one) is a coboundary.

This file proves that.  It is the keystone that `Algebra/LaurentReducedReduction.lean` needs but
does not contain: with the reduced-ring characterisation (`Algebra/LaurentCoboundaryReduced.lean`)
it upgrades the ℙ¹ coboundary computation from reduced rings to **arbitrary** commutative rings —
`Pic(ℙ¹_A)` is computed with no domain, reducedness, or field hypothesis.

## The mechanism: halving on ideal powers

The single-generator proof halves the nilpotency *index* by squaring the deforming element.  Here
the deformation is along a whole ideal `I` (generated by `z`'s coefficients), so we halve on the
*ideal power*: the induction is over `n` with `I ^ (2 ^ n) = ⊥`.

Given `z` with all coefficients in `I`, split `z = P + Q` into its non-negative-degree part
`P = toLaurent (posPoly z)` (a unit of the left chart `A[t]`, since `posPoly z` is nilpotent) and
its negative-degree part `Q = rightChart (negPoly z)` (a unit of the right chart `A[t⁻¹]`).  Their
product is a coboundary `c` with

`c = (1 + P)(1 + Q) = 1 + z + P·Q`,

and the **cross term `P·Q` has coefficients in `I²`** (`coeff_mul_mem_mul`).  So the residual
`c⁻¹ · (1 + z) = 1 - c⁻¹ · P·Q` is `1 + w` with `w`'s coefficients in `I²`, and `(I²) ^ (2 ^ (n-1))
= I ^ (2 ^ n) = ⊥`: the induction hypothesis applies to `w`, and coboundaries are a subgroup, so
`1 + z = c · (c⁻¹ (1 + z))` is a coboundary.  The cross term is fed back at twice the ideal power,
exactly as the single-generator proof feeds it back at twice the element's nilpotency order.

## Main declarations

* `AlgebraicGeometry.laurentCoboundary_one_add_of_coeffs_mem` — the ideal-power halving: if
  `I ^ (2 ^ n) = ⊥` and every coefficient of `z` is in `I`, then `1 + z` is a coboundary.
* `AlgebraicGeometry.nilpotent_one_add_mem_laurentCoboundaryUnits` — **the headline**: a unit
  congruent to `1` modulo an arbitrary nilpotent Laurent polynomial is a coboundary.
-/

set_option autoImplicit false

universe u

open CategoryTheory LaurentPolynomial

namespace AlgebraicGeometry

variable {A : Type u} [CommRing A]

/-! ## The two chart truncations of a Laurent polynomial -/

/-- The non-negative-degree part of `z`, as a genuine polynomial (left chart `A[t]`). -/
noncomputable def posPoly (z : LaurentPolynomial A) : Polynomial A :=
  ∑ i ∈ z.support.filter (0 ≤ ·), Polynomial.monomial i.toNat (z i)

/-- The negative-degree part of `z`, as a polynomial in the right chart coordinate `t⁻¹`. -/
noncomputable def negPoly (z : LaurentPolynomial A) : Polynomial A :=
  ∑ i ∈ z.support.filter (¬ 0 ≤ ·), Polynomial.monomial (-i).toNat (z i)

/-- `rightChart` on a monomial: `X ↦ T (-1)`, so `monomial n c ↦ C c · T (-n)`. -/
theorem rightChart_monomial (c : A) (n : ℕ) :
    rightChart A (Polynomial.monomial n c)
      = LaurentPolynomial.C c * LaurentPolynomial.T (-(n : ℤ)) := by
  rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, rightChart_C, map_pow, rightChart_X,
    LaurentPolynomial.T_pow]
  congr 2
  ring

/-- Coefficients of the left-chart truncation lie in any ideal containing `z`'s coefficients. -/
theorem posPoly_coeff_mem {I : Ideal A} {z : LaurentPolynomial A} (hz : ∀ i, z i ∈ I) (m : ℕ) :
    (posPoly z).coeff m ∈ I := by
  classical
  unfold posPoly
  rw [Polynomial.finsetSum_coeff]
  refine Ideal.sum_mem _ (fun i _ => ?_)
  rw [Polynomial.coeff_monomial]
  split
  · exact hz i
  · exact Ideal.zero_mem _

/-- Coefficients of the right-chart truncation lie in any ideal containing `z`'s coefficients. -/
theorem negPoly_coeff_mem {I : Ideal A} {z : LaurentPolynomial A} (hz : ∀ i, z i ∈ I) (m : ℕ) :
    (negPoly z).coeff m ∈ I := by
  classical
  unfold negPoly
  rw [Polynomial.finsetSum_coeff]
  refine Ideal.sum_mem _ (fun i _ => ?_)
  rw [Polynomial.coeff_monomial]
  split
  · exact hz i
  · exact Ideal.zero_mem _

/-- The left-chart truncation, evaluated coefficientwise. -/
theorem toLaurent_posPoly_apply (z : LaurentPolynomial A) (j : ℤ) :
    (Polynomial.toLaurent (posPoly z)) j = if 0 ≤ j then z j else 0 := by
  classical
  unfold posPoly
  rw [map_sum]
  have hterm : ∀ i ∈ z.support.filter (0 ≤ ·),
      Polynomial.toLaurent (Polynomial.monomial i.toNat (z i))
        = (Finsupp.single i (z i) : LaurentPolynomial A) := by
    intro i hi
    rw [Finset.mem_filter] at hi
    rw [Polynomial.toLaurent_C_mul_T, ← LaurentPolynomial.single_eq_C_mul_T,
      Int.toNat_of_nonneg hi.2]
  rw [Finset.sum_congr rfl hterm]
  change (Finset.sum (z.support.filter (0 ≤ ·))
    (fun i => (Finsupp.single i (z i) : ℤ →₀ A)) : ℤ →₀ A) j = _
  rw [Finset.sum_apply']
  simp only [Finsupp.single_apply]
  by_cases hj : 0 ≤ j
  · rw [if_pos hj]
    by_cases hmem : j ∈ z.support.filter (0 ≤ ·)
    · rw [Finset.sum_eq_single j]
      · rw [if_pos rfl]
      · intro b _ hbj; rw [if_neg hbj]
      · intro h; exact absurd hmem h
    · rw [Finset.sum_eq_zero]
      · rw [Finset.mem_filter, not_and] at hmem
        by_cases hjs : j ∈ z.support
        · exact absurd hj (hmem hjs)
        · rw [Finsupp.notMem_support_iff] at hjs; rw [hjs]
      · intro b hb; rw [if_neg]; rintro rfl; exact hmem hb
  · rw [if_neg hj, Finset.sum_eq_zero]
    intro b hb
    rw [Finset.mem_filter] at hb
    rw [if_neg]; rintro rfl; exact hj hb.2

/-- The right-chart truncation, evaluated coefficientwise. -/
theorem rightChart_negPoly_apply (z : LaurentPolynomial A) (j : ℤ) :
    (rightChart A (negPoly z)) j = if ¬ 0 ≤ j then z j else 0 := by
  classical
  unfold negPoly
  rw [map_sum]
  have hterm : ∀ i ∈ z.support.filter (¬ 0 ≤ ·),
      rightChart A (Polynomial.monomial (-i).toNat (z i))
        = (Finsupp.single i (z i) : LaurentPolynomial A) := by
    intro i hi
    rw [Finset.mem_filter] at hi
    rw [rightChart_monomial, ← LaurentPolynomial.single_eq_C_mul_T]
    congr 1
    have : (0 : ℤ) ≤ -i := by omega
    rw [Int.toNat_of_nonneg this]; ring
  rw [Finset.sum_congr rfl hterm]
  change (Finset.sum (z.support.filter (¬ 0 ≤ ·))
    (fun i => (Finsupp.single i (z i) : ℤ →₀ A)) : ℤ →₀ A) j = _
  rw [Finset.sum_apply']
  simp only [Finsupp.single_apply]
  by_cases hj : ¬ 0 ≤ j
  · rw [if_pos hj]
    by_cases hmem : j ∈ z.support.filter (¬ 0 ≤ ·)
    · rw [Finset.sum_eq_single j]
      · rw [if_pos rfl]
      · intro b _ hbj; rw [if_neg hbj]
      · intro h; exact absurd hmem h
    · rw [Finset.sum_eq_zero]
      · rw [Finset.mem_filter, not_and] at hmem
        by_cases hjs : j ∈ z.support
        · exact absurd hj (hmem hjs)
        · rw [Finsupp.notMem_support_iff] at hjs; rw [hjs]
      · intro b hb; rw [if_neg]; rintro rfl; exact hmem hb
  · rw [if_neg hj, Finset.sum_eq_zero]
    intro b hb
    rw [Finset.mem_filter] at hb
    rw [if_neg]; rintro rfl; exact hj hb.2

/-- The two truncations reconstruct `z`. -/
theorem posPoly_add_negPoly (z : LaurentPolynomial A) :
    Polynomial.toLaurent (posPoly z) + rightChart A (negPoly z) = z := by
  apply Finsupp.ext
  intro j
  have hsum : (Polynomial.toLaurent (posPoly z) + rightChart A (negPoly z)) j
      = (Polynomial.toLaurent (posPoly z)) j + (rightChart A (negPoly z)) j := rfl
  rw [hsum, toLaurent_posPoly_apply, rightChart_negPoly_apply]
  by_cases hj : 0 ≤ j <;> simp [hj]

/-- Coefficients of the left-chart image lie in any ideal containing `z`'s coefficients. -/
theorem toLaurent_posPoly_coeff_mem {I : Ideal A} {z : LaurentPolynomial A}
    (hz : ∀ i, z i ∈ I) (j : ℤ) : (Polynomial.toLaurent (posPoly z)) j ∈ I := by
  rw [toLaurent_posPoly_apply]
  split
  · exact hz j
  · exact Ideal.zero_mem _

/-- Coefficients of the right-chart image lie in any ideal containing `z`'s coefficients. -/
theorem rightChart_negPoly_coeff_mem {I : Ideal A} {z : LaurentPolynomial A}
    (hz : ∀ i, z i ∈ I) (j : ℤ) : (rightChart A (negPoly z)) j ∈ I := by
  rw [rightChart_negPoly_apply]
  split
  · exact hz j
  · exact Ideal.zero_mem _

/-! ## The ideal-power halving -/

/-- A polynomial with all coefficients in a nilpotent ideal is nilpotent. -/
theorem poly_nilpotent_of_coeffs_mem {I : Ideal A} (hI : IsNilpotent I) {p : Polynomial A}
    (hp : ∀ m, p.coeff m ∈ I) : IsNilpotent p := by
  rw [Polynomial.isNilpotent_iff]
  intro m
  obtain ⟨N, hN⟩ := hI
  exact ⟨N, by have := Ideal.pow_mem_pow (hp m) N; rw [hN] at this; simpa using this⟩

/-- **THE IDEAL-POWER HALVING**: if `I ^ (2 ^ n) = ⊥` and every coefficient of the Laurent
polynomial `z` lies in `I`, then `1 + z` is a two-chart coboundary.

The deformation is along the whole ideal `I` (not a single generator), so the induction halves the
*ideal power*.  Split `z = P + Q` into its non-negative and negative degree parts; `1 + P` and
`1 + Q` are chart units (`P, Q` nilpotent, coefficients in the nilpotent `I`), their product is a
coboundary `c = 1 + z + P·Q`, and the cross term `P·Q` has coefficients in `I²`
(`coeff_mul_mem_mul`).  The residual `c⁻¹·(1 + z) = 1 + w` has `w`'s coefficients in `I²`, and
`(I²) ^ (2 ^ n) = I ^ (2 ^ (n+1)) = ⊥`, so the induction hypothesis applies and coboundaries are a
subgroup. -/
theorem laurentCoboundary_one_add_of_coeffs_mem (n : ℕ) :
    ∀ (I : Ideal A), I ^ (2 ^ n) = ⊥ → ∀ (z : LaurentPolynomial A), (∀ i, z i ∈ I) →
      ∀ (u : (LaurentPolynomial A)ˣ), (u : LaurentPolynomial A) = 1 + z →
        u ∈ laurentCoboundaryUnits A := by
  induction n with
  | zero =>
    intro I hI z hz u hu
    have hIbot : I = ⊥ := by simpa using hI
    have hz0 : z = 0 := by
      apply Finsupp.ext; intro i
      have hzi : z i ∈ (⊥ : Ideal A) := hIbot ▸ hz i
      rw [Ideal.mem_bot] at hzi
      rw [hzi]; rfl
    have h1 : (u : LaurentPolynomial A) = 1 := by rw [hu, hz0, add_zero]
    rw [show u = 1 from Units.ext (by rw [h1, Units.val_one])]
    exact Subgroup.one_mem _
  | succ n ih =>
    intro I hI z hz u hu
    have hInil : IsNilpotent I := ⟨2 ^ (n + 1), hI⟩
    set P : Polynomial A := posPoly z with hP
    set Q : Polynomial A := negPoly z with hQ
    have hPu : IsUnit (1 + P) :=
      (poly_nilpotent_of_coeffs_mem hInil (posPoly_coeff_mem hz)).isUnit_one_add
    have hQu : IsUnit (1 + Q) :=
      (poly_nilpotent_of_coeffs_mem hInil (negPoly_coeff_mem hz)).isUnit_one_add
    set c : (LaurentPolynomial A)ˣ :=
      (hPu.unit.map (Polynomial.toLaurent).toMonoidHom)
        * (hQu.unit.map (rightChart A).toMonoidHom) with hc
    have hcmem : c ∈ laurentCoboundaryUnits A :=
      TruncExpCech.mem_cechCoboundaryUnits.mpr ⟨hPu.unit, hQu.unit, rfl⟩
    have hcval : (c : LaurentPolynomial A)
        = 1 + z + Polynomial.toLaurent P * rightChart A Q := by
      rw [hc, Units.val_mul, Units.coe_map, Units.coe_map, IsUnit.unit_spec, IsUnit.unit_spec]
      change Polynomial.toLaurent (1 + P) * rightChart A (1 + Q)
        = 1 + z + Polynomial.toLaurent P * rightChart A Q
      rw [map_add, map_add, map_one, map_one]
      rw [show (1 + Polynomial.toLaurent P) * (1 + rightChart A Q)
          = 1 + (Polynomial.toLaurent P + rightChart A Q)
            + Polynomial.toLaurent P * rightChart A Q from by ring, posPoly_add_negPoly z]
    set w : LaurentPolynomial A :=
      -((↑c⁻¹ : LaurentPolynomial A) * (Polynomial.toLaurent P * rightChart A Q)) with hw
    have hwmem : ∀ m, w m ∈ I ^ 2 := by
      intro m
      have hxy : ∀ j, (Polynomial.toLaurent P * rightChart A Q) j ∈ I * I :=
        coeff_mul_mem_mul (toLaurent_posPoly_coeff_mem hz) (rightChart_negPoly_coeff_mem hz)
      have h2 : ((↑c⁻¹ : LaurentPolynomial A) * (Polynomial.toLaurent P * rightChart A Q)) m
          ∈ (⊤ : Ideal A) * (I * I) := coeff_mul_mem_mul (fun _ => Submodule.mem_top) hxy m
      rw [Ideal.top_mul] at h2
      have hwm : w m = -(((↑c⁻¹ : LaurentPolynomial A)
          * (Polynomial.toLaurent P * rightChart A Q)) m) := rfl
      rw [hwm, sq]
      exact Submodule.neg_mem _ h2
    have hcu : ((c⁻¹ * u : (LaurentPolynomial A)ˣ) : LaurentPolynomial A) = 1 + w := by
      have hinv : (↑c⁻¹ : LaurentPolynomial A) * (c : LaurentPolynomial A) = 1 := by
        rw [← Units.val_mul, inv_mul_cancel, Units.val_one]
      rw [Units.val_mul, hu, hw]
      rw [show (1 : LaurentPolynomial A) + z
          = (1 + z + Polynomial.toLaurent P * rightChart A Q)
            - Polynomial.toLaurent P * rightChart A Q from by ring, ← hcval]
      rw [mul_sub, hinv]; ring
    have hI2 : (I ^ 2) ^ (2 ^ n) = ⊥ := by rw [← pow_mul, ← pow_succ']; exact hI
    have hr : c⁻¹ * u ∈ laurentCoboundaryUnits A := ih (I ^ 2) hI2 w hwmem (c⁻¹ * u) hcu
    rw [show u = c * (c⁻¹ * u) from by group]
    exact Subgroup.mul_mem _ hcmem hr

/-- **THE HEADLINE**: a Laurent unit congruent to `1` modulo an *arbitrary* nilpotent Laurent
polynomial is a two-chart coboundary, over an arbitrary commutative ring.

The nilpotent ideal generated by `z`'s coefficients has some power `2 ^ n` killing it
(`Ideal.FG.isNilpotent_iff_le_nilradical` — a finitely-generated nil ideal is nilpotent), and
`laurentCoboundary_one_add_of_coeffs_mem` closes it.  This is the multi-generator generalisation of
`nilpotent_isUnit_mem_laurentCoboundaryUnits`, and the keystone the arbitrary-ring ℙ¹ Picard
computation needs. -/
theorem nilpotent_one_add_mem_laurentCoboundaryUnits {z : LaurentPolynomial A}
    (hz : IsNilpotent z) (u : (LaurentPolynomial A)ˣ)
    (hu : (u : LaurentPolynomial A) = 1 + z) : u ∈ laurentCoboundaryUnits A := by
  classical
  -- the ideal generated by z's (finitely many) coefficients
  set I : Ideal A := Ideal.span (Set.range fun i : z.support => z i) with hI
  have hzmem : ∀ i, z i ∈ I := by
    intro i
    by_cases hi : i ∈ z.support
    · exact Ideal.subset_span ⟨⟨i, hi⟩, rfl⟩
    · rw [Finsupp.notMem_support_iff.mp hi]; exact Ideal.zero_mem _
  have hIfg : I.FG := ⟨(Set.finite_range _).toFinset, by rw [hI, Set.Finite.coe_toFinset]⟩
  have hInil : IsNilpotent I := by
    refine (Ideal.FG.isNilpotent_iff_le_nilradical hIfg).mpr ?_
    rw [hI, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact coeff_isNilpotent_of_isNilpotent hz i
  obtain ⟨N, hN⟩ := hInil
  obtain ⟨n, hn⟩ : ∃ n, N ≤ 2 ^ n := ⟨N, Nat.le_of_lt (Nat.lt_two_pow_self)⟩
  have hIpow : I ^ (2 ^ n) = ⊥ := by
    obtain ⟨j, hj⟩ : ∃ j, 2 ^ n = N + j := ⟨2 ^ n - N, by omega⟩
    rw [hj, pow_add, hN, zero_mul]; rfl
  exact laurentCoboundary_one_add_of_coeffs_mem n I hIpow z hzmem u hu

end AlgebraicGeometry
