/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Algebra.DiagonalIdeal

/-!
# The point-fiber ideal of an étale-coordinatised algebra (G-D8, ideal input)

Let `k` be a commutative ring, `B` a `k`-algebra with a compatible `Polynomial k`-coordinate
`u := coord k B` (the brick-B0 package of `AlgebraicJacobian.Algebra.DiagonalIdeal`), and
`F` a second `k`-algebra with a compatible `Polynomial k`-structure, receiving `B` through a
`Polynomial k`-algebra homomorphism `c : B →ₐ[Polynomial k] F` (in the intended application
`F` is the section ring of the affine field test and `c` the pullback along a `K`-point of
the curve, with the `Polynomial k`-structure on `F` *defined* as `c ∘ algebraMap`).

This file computes the kernel of the **point evaluation**
`pointEv c : B ⊗[k] F → F`, `x ⊗ λ ↦ c x · λ` — the ideal of the graph section inside the
chart of the curve fiber — after localising away from the pushed idempotent lift: it is the
principal ideal on the **point generator** `pointGen = u ⊗ 1 − 1 ⊗ u_F`.  Everything mirrors
the diagonal computation of `DiagonalIdeal.lean` (deliverables (a)–(c)), with the second
tensor factor specialised along `c`; the idempotent input is *pushed* from the frozen
diagonal package — no unramifiedness of `F` is ever invoked.

## Main results

* `AlgebraicJacobian.Diagonal.ker_pointBaseChange` (mirror of (a)): the kernel of
  `B ⊗[k] F → B ⊗[Polynomial k] F` is `Ideal.span {pointGen}`.
* `AlgebraicJacobian.Diagonal.ker_pointEvTwo` (mirror of (b)): given the diagonal-package
  kernel presentation `ker (mul : B ⊗[Polynomial k] B → B) = (e)`, the kernel of the
  `Polynomial k`-level evaluation `B ⊗[Polynomial k] F → F` is the principal ideal on the
  push of `e` — by the section trick `mk ∘ includeRight ∘ ev₂ = mk`, whose generators
  `x ⊗ 1 − 1 ⊗ c x` are pushes of diagonal-ideal elements.
* `AlgebraicJacobian.Diagonal.ker_pointEv_map_localization_eq` (mirror of (c), the
  consumer-facing keystone): for the frozen idempotent lift `elift` of the diagonal package,
  the point-evaluation kernel, extended to any localisation away from `1 − eliftF`
  (`eliftF` the push of `elift`), is the principal ideal generated by `pointGen`.
-/

set_option autoImplicit false

open scoped TensorProduct
open Polynomial

namespace AlgebraicJacobian.Diagonal

variable {k B F : Type*} [CommRing k] [CommRing B] [Algebra k B]
  [Algebra (Polynomial k) B] [IsScalarTower k (Polynomial k) B]
  [CommRing F] [Algebra k F] [Algebra (Polynomial k) F] [IsScalarTower k (Polynomial k) F]

/-! ### The point generator and the evaluations -/

variable (k B F) in
/-- The point generator `u ⊗ 1 − 1 ⊗ u_F ∈ B ⊗[k] F`: the two étale coordinates spread
across the tensor factors.  In the application `u_F = c u` is the coordinate of the tracked
point (`map_coord`). 


 * Provenance: CUSTOM.
-/
noncomputable def pointGen : B ⊗[k] F :=
  coord k B ⊗ₜ[k] (1 : F) - (1 : B) ⊗ₜ[k] coord k F

variable (c : B →ₐ[Polynomial k] F)

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
/-- A `Polynomial k`-algebra homomorphism matches the étale coordinates. 


 * Provenance: CUSTOM.
-/
lemma map_coord : c (coord k B) = coord k F :=
  c.commutes X

/-- The `k`-level point evaluation `B ⊗[k] F → F`, `x ⊗ λ ↦ c x · λ`: the section ring of
the graph point inside the chart of the fiber. 


 * Provenance: CUSTOM.
-/
noncomputable def pointEv : B ⊗[k] F →ₐ[k] F :=
  Algebra.TensorProduct.lift (c.restrictScalars k) (AlgHom.id k F)
    (fun _ _ => Commute.all _ _)

/-- Provenance: CUSTOM. -/
@[simp] lemma pointEv_tmul (x : B) (y : F) : pointEv c (x ⊗ₜ[k] y) = c x * y := by
  rw [pointEv, Algebra.TensorProduct.lift_tmul]
  rfl

/-- The point evaluation kills the point generator. 
 * Provenance: CUSTOM.
-/
@[simp] lemma pointEv_pointGen : pointEv c (pointGen k B F) = 0 := by
  rw [pointGen, map_sub, pointEv_tmul, pointEv_tmul, map_one, map_coord c, mul_one, one_mul,
    sub_self]

variable (B F) in
/-- The base-change surjection `B ⊗[k] F →ₐ[k] B ⊗[Polynomial k] F` (mirror of
`Diagonal.baseChange`); its kernel is `(pointGen)` (`ker_pointBaseChange`). 


 * Provenance: CUSTOM.
-/
noncomputable def pointBaseChange : B ⊗[k] F →ₐ[k] B ⊗[Polynomial k] F :=
  Algebra.TensorProduct.lift
    ((Algebra.TensorProduct.includeLeft :
        B →ₐ[Polynomial k] B ⊗[Polynomial k] F).restrictScalars k)
    ((Algebra.TensorProduct.includeRight :
        F →ₐ[Polynomial k] B ⊗[Polynomial k] F).restrictScalars k)
    (fun _ _ => Commute.all _ _)

@[simp] lemma pointBaseChange_tmul (x : B) (y : F) :
    pointBaseChange B F (x ⊗ₜ[k] y) = x ⊗ₜ[Polynomial k] y := by
  rw [pointBaseChange, Algebra.TensorProduct.lift_tmul]
  change Algebra.TensorProduct.includeLeft x * Algebra.TensorProduct.includeRight y = _
  rw [Algebra.TensorProduct.includeLeft_apply, Algebra.TensorProduct.includeRight_apply,
    Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one]

/-- Provenance: CUSTOM. -/
lemma pointBaseChange_surjective : Function.Surjective (pointBaseChange (k := k) B F) := by
  intro z
  induction z with
  | zero => exact ⟨0, map_zero _⟩
  | tmul x y => exact ⟨x ⊗ₜ[k] y, pointBaseChange_tmul x y⟩
  | add a b ha hb =>
      obtain ⟨a', ha'⟩ := ha; obtain ⟨b', hb'⟩ := hb
      exact ⟨a' + b', by rw [map_add, ha', hb']⟩

/-- The `Polynomial k`-level point evaluation `B ⊗[Polynomial k] F → F`. 


 * Provenance: CUSTOM.
-/
noncomputable def pointEvTwo : B ⊗[Polynomial k] F →ₐ[Polynomial k] F :=
  Algebra.TensorProduct.lift c (AlgHom.id (Polynomial k) F)
    (fun _ _ => Commute.all _ _)

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
@[simp] lemma pointEvTwo_tmul (x : B) (y : F) :
    pointEvTwo c (x ⊗ₜ[Polynomial k] y) = c x * y := by
  rw [pointEvTwo, Algebra.TensorProduct.lift_tmul]
  rfl

/-- The `k`-level evaluation factors through the base change. 


 * Provenance: CUSTOM.
-/
lemma pointEvTwo_pointBaseChange (z : B ⊗[k] F) :
    pointEvTwo c (pointBaseChange B F z) = pointEv c z := by
  induction z with
  | zero => simp
  | tmul x y => rw [pointBaseChange_tmul, pointEvTwo_tmul, pointEv_tmul]
  | add a b ha hb => simp only [map_add, ha, hb]

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
/-- In `B ⊗[Polynomial k] F` the two coordinates agree across the tensor: both are
`X • (1 ⊗ 1)`. 


 * Provenance: CUSTOM.
-/
lemma coord_tmul_one_point :
    coord k B ⊗ₜ[Polynomial k] (1 : F) = (1 : B) ⊗ₜ[Polynomial k] coord k F := by
  have h1 : (coord k B : B) = (X : Polynomial k) • (1 : B) := by
    rw [Algebra.smul_def, mul_one]; rfl
  have h2 : (coord k F : F) = (X : Polynomial k) • (1 : F) := by
    rw [Algebra.smul_def, mul_one]; rfl
  rw [h1, h2, TensorProduct.smul_tmul]

/-- The base change kills the point generator. 


 * Provenance: CUSTOM.
-/
lemma pointBaseChange_pointGen : pointBaseChange B F (pointGen k B F) = 0 := by
  rw [pointGen, map_sub, pointBaseChange_tmul, pointBaseChange_tmul, coord_tmul_one_point,
    sub_self]

/-! ### The telescoping identity and the kernel of the base change (mirror of (a)) -/

omit [Algebra (Polynomial k) B] [IsScalarTower k (Polynomial k) B]
  [Algebra (Polynomial k) F] [IsScalarTower k (Polynomial k) F] in
/-- Difference of evaluations at two points is divisible by the difference of the points
(the `B ⊗[k] F` copy of `Diagonal.aeval_sub_dvd`). 


 * Provenance: CUSTOM.
-/
lemma aeval_sub_dvd_point (a b : B ⊗[k] F) (p : Polynomial k) :
    a - b ∣ aeval a p - aeval b p := by
  rw [aeval_def, aeval_def, eval₂_eq_eval_map, eval₂_eq_eval_map]
  exact sub_dvd_eval_sub a b _

/-- **Telescoping** (mirror): for every `p`, the element
`g_B(p) ⊗ 1 − 1 ⊗ g_F(p)` lies in the ideal generated by the point generator. 


 * Provenance: CUSTOM.
-/
lemma algebraMap_tmul_sub_mem_span_point (p : Polynomial k) :
    (algebraMap (Polynomial k) B p) ⊗ₜ[k] (1 : F)
        - (1 : B) ⊗ₜ[k] (algebraMap (Polynomial k) F p)
      ∈ Ideal.span {pointGen k B F} := by
  rw [Ideal.mem_span_singleton, pointGen, algebraMap_eq_aeval,
    algebraMap_eq_aeval (B := F)]
  have hL : (aeval (coord k B) p) ⊗ₜ[k] (1 : F)
      = aeval (coord k B ⊗ₜ[k] (1 : F)) p := by
    rw [← Algebra.TensorProduct.includeLeft_apply (S := k),
      ← Polynomial.aeval_algHom_apply, Algebra.TensorProduct.includeLeft_apply]
  have hR : (1 : B) ⊗ₜ[k] (aeval (coord k F) p)
      = aeval ((1 : B) ⊗ₜ[k] coord k F) p := by
    rw [← Algebra.TensorProduct.includeRight_apply,
      ← Polynomial.aeval_algHom_apply, Algebra.TensorProduct.includeRight_apply]
  rw [hL, hR]
  exact aeval_sub_dvd_point _ _ p

variable (B F) in
/-- The right inclusion `λ ↦ 1 ⊗ λ` into the quotient by the point generator, promoted to a
`Polynomial k`-algebra homomorphism by telescoping (mirror of `Diagonal.qRight`). 


 * Provenance: CUSTOM.
-/
noncomputable def pointQRight :
    F →ₐ[Polynomial k] (B ⊗[k] F) ⧸ Ideal.span {pointGen k B F} where
  toFun y := Ideal.Quotient.mk _ ((1 : B) ⊗ₜ[k] y)
  map_one' := by rw [← Algebra.TensorProduct.one_def]; exact map_one _
  map_mul' a b := by rw [← map_mul, Algebra.TensorProduct.tmul_mul_tmul, one_mul]
  map_zero' := by simp
  map_add' a b := by rw [← map_add, TensorProduct.tmul_add]
  commutes' p := by
    change Ideal.Quotient.mk _ ((1 : B) ⊗ₜ[k] algebraMap (Polynomial k) F p)
      = algebraMap (Polynomial k) ((B ⊗[k] F) ⧸ Ideal.span {pointGen k B F}) p
    have h : algebraMap (Polynomial k) ((B ⊗[k] F) ⧸ Ideal.span {pointGen k B F}) p
        = Ideal.Quotient.mk _ ((algebraMap (Polynomial k) B p) ⊗ₜ[k] (1 : F)) := rfl
    rw [h, Ideal.Quotient.eq, ← neg_sub]
    exact neg_mem (algebraMap_tmul_sub_mem_span_point p)

variable (B F) in
/-- The section `B ⊗[Polynomial k] F → (B ⊗[k] F) ⧸ (pointGen)` of the base change (mirror
of `Diagonal.sectionMap`). 


 * Provenance: CUSTOM.
-/
noncomputable def pointSectionMap :
    B ⊗[Polynomial k] F →ₐ[Polynomial k] (B ⊗[k] F) ⧸ Ideal.span {pointGen k B F} :=
  Algebra.TensorProduct.lift
    ((Ideal.Quotient.mkₐ (Polynomial k) _).comp Algebra.TensorProduct.includeLeft)
    (pointQRight B F) (fun _ _ => Commute.all _ _)

lemma pointSectionMap_tmul (x : B) (y : F) :
    pointSectionMap B F (x ⊗ₜ[Polynomial k] y)
      = Ideal.Quotient.mk (Ideal.span {pointGen k B F}) (x ⊗ₜ[k] y) := by
  rw [pointSectionMap, Algebra.TensorProduct.lift_tmul]
  change (Ideal.Quotient.mk _ (x ⊗ₜ[k] 1)) * (Ideal.Quotient.mk _ (1 ⊗ₜ[k] y)) = _
  rw [← map_mul, Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]

/-- The section composed with the base change is the quotient map. 


 * Provenance: CUSTOM.
-/
lemma pointSectionMap_pointBaseChange (z : B ⊗[k] F) :
    pointSectionMap B F (pointBaseChange B F z)
      = Ideal.Quotient.mk (Ideal.span {pointGen k B F}) z := by
  induction z with
  | zero => simp
  | tmul x y => rw [pointBaseChange_tmul, pointSectionMap_tmul]
  | add a b ha hb => simp only [map_add, ha, hb]

variable (B F) in
/-- **Mirror of deliverable (a).** The kernel of the base-change surjection
`B ⊗[k] F → B ⊗[Polynomial k] F` is exactly the principal ideal on the point generator. 


 * Provenance: CUSTOM.
-/
theorem ker_pointBaseChange :
    RingHom.ker (pointBaseChange (k := k) B F) = Ideal.span {pointGen k B F} := by
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker] at hx
    have hmk : Ideal.Quotient.mk (Ideal.span {pointGen k B F}) x = 0 := by
      rw [← pointSectionMap_pointBaseChange x, hx, map_zero]
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hmk
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker]
    exact pointBaseChange_pointGen

/-! ### The kernel of the `Polynomial k`-level evaluation (mirror of (b)) -/

/-- The second-factor push `B ⊗[Polynomial k] B → B ⊗[Polynomial k] F` along `c`. 


 * Provenance: CUSTOM.
-/
noncomputable def mapRightTwo :
    B ⊗[Polynomial k] B →ₐ[Polynomial k] B ⊗[Polynomial k] F :=
  Algebra.TensorProduct.map (AlgHom.id (Polynomial k) B) c

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
@[simp] lemma mapRightTwo_tmul (x y : B) :
    mapRightTwo c (x ⊗ₜ[Polynomial k] y) = x ⊗ₜ[Polynomial k] c y :=
  rfl

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
/-- The `Polynomial k`-evaluation of a pushed element is `c` of its multiplication. 


 * Provenance: CUSTOM.
-/
lemma pointEvTwo_mapRightTwo (z : B ⊗[Polynomial k] B) :
    pointEvTwo c (mapRightTwo c z)
      = c (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B) z) := by
  induction z with
  | zero => simp
  | tmul x y => rw [mapRightTwo_tmul, pointEvTwo_tmul,
      Algebra.TensorProduct.lmul'_apply_tmul, map_mul]
  | add a b ha hb => simp only [map_add, ha, hb]

section EvTwoKernel

variable {e : B ⊗[Polynomial k] B}
  (hgen : RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B))
    = Ideal.span {e})

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
include hgen in
/-- The pushed generators of the point ideal lie in the pushed diagonal ideal:
`x ⊗ 1 − 1 ⊗ c x` is the push of the diagonal-ideal element `x ⊗ 1 − 1 ⊗ x`. 


 * Provenance: CUSTOM.
-/
lemma tmul_sub_tmul_mem_span_mapRightTwo (x : B) :
    x ⊗ₜ[Polynomial k] (1 : F) - (1 : B) ⊗ₜ[Polynomial k] c x
      ∈ Ideal.span {mapRightTwo c e} := by
  have hker : x ⊗ₜ[Polynomial k] (1 : B) - (1 : B) ⊗ₜ[Polynomial k] x
      ∈ RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B)) := by
    rw [RingHom.mem_ker, map_sub, Algebra.TensorProduct.lmul'_apply_tmul,
      Algebra.TensorProduct.lmul'_apply_tmul, mul_one, one_mul, sub_self]
  rw [hgen, Ideal.mem_span_singleton] at hker
  obtain ⟨w, hw⟩ := hker
  rw [Ideal.mem_span_singleton]
  refine ⟨mapRightTwo c w, ?_⟩
  have := congrArg (mapRightTwo c) hw
  rw [map_sub, mapRightTwo_tmul, mapRightTwo_tmul, map_one, map_mul] at this
  rw [this]

omit [Algebra k B] [IsScalarTower k (Polynomial k) B]
  [Algebra k F] [IsScalarTower k (Polynomial k) F] in
include hgen in
/-- **Mirror of deliverable (b).** Given the diagonal-package kernel presentation, the
kernel of the `Polynomial k`-level point evaluation is the principal ideal on the push of
the diagonal generator — the section trick `mk ∘ includeRight ∘ ev₂ = mk`. 


 * Provenance: CUSTOM.
-/
theorem ker_pointEvTwo :
    RingHom.ker (pointEvTwo c) = Ideal.span {mapRightTwo c e} := by
  have he : Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B) e = 0 := by
    have : e ∈ RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B)) := by
      rw [hgen]; exact Ideal.subset_span rfl
    rwa [RingHom.mem_ker] at this
  apply le_antisymm
  · -- the section trick
    intro w hw
    rw [RingHom.mem_ker] at hw
    have key : ∀ z : B ⊗[Polynomial k] F,
        Ideal.Quotient.mk (Ideal.span {mapRightTwo c e}) z
          = Ideal.Quotient.mk (Ideal.span {mapRightTwo c e})
              ((1 : B) ⊗ₜ[Polynomial k] (pointEvTwo c z)) := by
      intro z
      induction z with
      | zero => simp
      | tmul x y =>
          rw [pointEvTwo_tmul, Ideal.Quotient.eq]
          have hfac : x ⊗ₜ[Polynomial k] y - (1 : B) ⊗ₜ[Polynomial k] (c x * y)
              = (x ⊗ₜ[Polynomial k] (1 : F) - (1 : B) ⊗ₜ[Polynomial k] c x)
                * ((1 : B) ⊗ₜ[Polynomial k] y) := by
            rw [sub_mul, Algebra.TensorProduct.tmul_mul_tmul,
              Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one, one_mul]
          rw [hfac]
          exact Ideal.mul_mem_right _ _ (tmul_sub_tmul_mem_span_mapRightTwo c hgen x)
      | add a b ha hb =>
          rw [map_add, map_add, ha, hb, TensorProduct.tmul_add, map_add]
    have hz := key w
    rw [hw, TensorProduct.tmul_zero, map_zero] at hz
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hz
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker,
      pointEvTwo_mapRightTwo, he, map_zero]

end EvTwoKernel

/-! ### The localised point-fiber ideal (mirror of (c)) -/

/-- The second-factor push `B ⊗[k] B → B ⊗[k] F` along `c` (the `k`-level). 


 * Provenance: CUSTOM.
-/
noncomputable def mapRight : B ⊗[k] B →ₐ[k] B ⊗[k] F :=
  Algebra.TensorProduct.map (AlgHom.id k B) (c.restrictScalars k)

@[simp] lemma mapRight_tmul (x y : B) : mapRight c (x ⊗ₜ[k] y) = x ⊗ₜ[k] c y :=
  rfl

/-- The point generator is the push of the diagonal generator. 


 * Provenance: CUSTOM.
-/
lemma mapRight_diagGen : mapRight c (diagGen (k := k) (B := B)) = pointGen k B F := by
  rw [diagGen, pointGen, map_sub, mapRight_tmul, mapRight_tmul, map_one, map_coord c]

/-- Naturality of the base changes with the second-factor pushes. 


 * Provenance: CUSTOM.
-/
lemma pointBaseChange_mapRight (z : B ⊗[k] B) :
    pointBaseChange B F (mapRight c z) = mapRightTwo c (baseChange z) := by
  induction z with
  | zero => simp
  | tmul x y => rw [mapRight_tmul, pointBaseChange_tmul, baseChange_tmul, mapRightTwo_tmul]
  | add a b ha hb => simp only [map_add, ha, hb]

section Localization

variable (elift : B ⊗[k] B)
  (hidem : IsIdempotentElem (baseChange elift))
  (hgen : RingHom.ker (Algebra.TensorProduct.lmul' (R := Polynomial k) (S := B))
    = Ideal.span {baseChange elift})

include hgen in
/-- The point-evaluation kernel is contained in the sum of the point-generator ideal and
the principal ideal of the pushed lift (mirror of `ker_lmul'_le_sup`). 


 * Provenance: CUSTOM.
-/
lemma ker_pointEv_le_sup :
    RingHom.ker (pointEv c)
      ≤ Ideal.span {pointGen k B F} ⊔ Ideal.span {mapRight c elift} := by
  intro x hx
  rw [RingHom.mem_ker] at hx
  have hπx : pointBaseChange B F x ∈ RingHom.ker (pointEvTwo c) := by
    rw [RingHom.mem_ker, pointEvTwo_pointBaseChange, hx]
  rw [ker_pointEvTwo c hgen, Ideal.mem_span_singleton] at hπx
  obtain ⟨d, hd⟩ := hπx
  obtain ⟨w, rfl⟩ := pointBaseChange_surjective d
  have hkey : x - mapRight c elift * w ∈ Ideal.span {pointGen k B F} := by
    rw [← ker_pointBaseChange, RingHom.mem_ker, map_sub, map_mul, hd,
      pointBaseChange_mapRight]
    ring
  have hx' : x = (x - mapRight c elift * w) + mapRight c elift * w := by ring
  rw [hx']
  exact add_mem (Ideal.mem_sup_left hkey)
    (Ideal.mem_sup_right (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)))

variable (L : Type*) [CommRing L] [Algebra (B ⊗[k] F) L]
  [IsLocalization.Away (1 - mapRight c elift) L]

include hidem hgen in
/-- **The consumer-facing keystone** (mirror of deliverable (c)): the kernel of the point
evaluation `B ⊗[k] F → F`, extended along any localisation away from `1 − eliftF` (the
push of the frozen idempotent lift), is the principal ideal generated by the point
generator `u ⊗ 1 − 1 ⊗ u_F`.  This is the ideal of the graph section on the chart of the
curve fiber. 


 * Provenance: CUSTOM.
-/
theorem ker_pointEv_map_localization_eq :
    (RingHom.ker (pointEv c)).map (algebraMap (B ⊗[k] F) L)
      = Ideal.span {algebraMap (B ⊗[k] F) L (pointGen k B F)} := by
  have hidemF : IsIdempotentElem (pointBaseChange B F (mapRight c elift)) := by
    rw [pointBaseChange_mapRight]
    exact IsIdempotentElem.map hidem (mapRightTwo c)
  have hdvd : algebraMap (B ⊗[k] F) L (mapRight c elift) ∈
      Ideal.span {algebraMap (B ⊗[k] F) L (pointGen k B F)} := by
    have hunit : IsUnit (algebraMap (B ⊗[k] F) L (1 - mapRight c elift)) :=
      IsLocalization.map_units L
        (⟨1 - mapRight c elift, Submonoid.mem_powers _⟩ : Submonoid.powers _)
    obtain ⟨v, hv⟩ := hunit.exists_right_inv
    have hmem : mapRight c elift * (1 - mapRight c elift)
        ∈ Ideal.span {pointGen k B F} := by
      rw [← ker_pointBaseChange, RingHom.mem_ker, map_mul, map_sub, map_one, mul_sub,
        mul_one, hidemF.eq, sub_self]
    have hfmem : algebraMap (B ⊗[k] F) L (mapRight c elift * (1 - mapRight c elift)) ∈
        Ideal.span {algebraMap (B ⊗[k] F) L (pointGen k B F)} := by
      have hmap := Ideal.mem_map_of_mem (algebraMap (B ⊗[k] F) L) hmem
      rwa [Ideal.map_span, Set.image_singleton] at hmap
    have heq : algebraMap (B ⊗[k] F) L (mapRight c elift)
        = algebraMap (B ⊗[k] F) L (mapRight c elift * (1 - mapRight c elift)) * v := by
      rw [map_mul, mul_assoc, hv, mul_one]
    rw [heq]; exact Ideal.mul_mem_right _ _ hfmem
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine (ker_pointEv_le_sup c elift hgen).trans ?_
    rw [sup_le_iff]
    refine ⟨?_, ?_⟩
    · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, Ideal.mem_comap]
      exact Ideal.subset_span rfl
    · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, Ideal.mem_comap]
      exact hdvd
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    exact Ideal.mem_map_of_mem _ (by rw [RingHom.mem_ker]; exact pointEv_pointGen c)

end Localization

end AlgebraicJacobian.Diagonal
