/-
Copyright (c) 2026 The StacksPart01Lib authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The StacksPart01Lib Contributors
-/

import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic
import Mathlib.RingTheory.Finiteness.ModuleFinitePresentation

/-!
# StacksPart01Lib.FiniteTypeExtras

Finite ring maps give finite-type ring maps (Stacks Project, Tag `0D46`).
-/

namespace StacksPart01Lib

/-- A finite ring homomorphism is of finite type.

The finite condition says that the target is finite as a module over the
source, and hence its module generators also generate it as an algebra.  This
is the first assertion of the Stacks Project's finite-to-finite-type lemma
(Tag `0D46`); the finite transitivity lemmas are Tags `00GJ` and `00GL`.
-/
theorem ringHom_finiteType_of_finite {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (hf : f.Finite) : f.FiniteType := by
  exact RingHom.FiniteType.of_finite hf

/-- A finite presentation as a module gives a finite presentation of the
associated algebra map (Stacks, Tag `0D46`). -/
theorem algebraMap_finitePresentation_of_module_finitePresentation
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (h : Module.FinitePresentation R S) :
    (algebraMap R S).FinitePresentation := by
  rw [RingHom.finitePresentation_algebraMap]
  letI : Module.FinitePresentation R S := h
  infer_instance

/-- Finite ring maps are stable under composition
(Stacks, Tag `00GL`). -/
theorem ringHom_finite_comp {R S T : Type*} [CommRing R] [CommRing S]
    [CommRing T] (f : R →+* S) (g : S →+* T) (hf : f.Finite)
    (hg : g.Finite) : (g.comp f).Finite := by
  exact RingHom.Finite.comp hg hf

/-- If a composite ring map is finite, then its second factor is finite
(Stacks, Tag `00GL`, converse direction). -/
theorem ringHom_finite_of_comp {R S T : Type*} [CommRing R] [CommRing S]
    [CommRing T] (f : R →+* S) (g : S →+* T)
    (h : (g.comp f).Finite) : g.Finite := by
  exact RingHom.Finite.of_comp_finite h

/-! ### Integral ring maps

The finite/integral comparison and transitivity statements below package the
basic extension lemmas from Tags `00GK`, `00GN`, and `02JJ`.
-/

/-- A finite ring homomorphism is integral (Stacks, Tag `00GK`). -/
theorem ringHom_isIntegral_of_finite {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (hf : f.Finite) : f.IsIntegral := by
  exact RingHom.IsIntegral.of_finite hf

/-- Integral ring maps are stable under composition (Stacks, Tag `00GN`). -/
theorem ringHom_isIntegral_comp {R S T : Type*} [CommRing R] [CommRing S]
    [CommRing T] (f : R →+* S) (g : S →+* T) (hf : f.IsIntegral)
    (hg : g.IsIntegral) : (g.comp f).IsIntegral := by
  exact hf.trans f g hg

/-- A ring map is finite iff it is integral and of finite type
(Stacks, Tag `02JJ`). -/
theorem ringHom_finite_iff_isIntegral_and_finiteType
    {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S) :
    f.Finite ↔ f.IsIntegral ∧ f.FiniteType := by
  exact RingHom.finite_iff_isIntegral_and_finiteType

/-- An algebra is finite as a module exactly when it is generated by finitely
many integral elements (Stacks, Tags `00GM` and `02JJ`). -/
theorem module_finite_iff_exists_integral_generators
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] :
    Module.Finite R S ↔
      ∃ t : Finset S, Algebra.adjoin R (t : Set S) = ⊤ ∧
        ∀ x ∈ t, IsIntegral R x := by
  constructor
  · intro hfin
    letI : Module.Finite R S := hfin
    obtain ⟨t, ht⟩ := Algebra.FiniteType.out (R := R) (A := S)
    exact ⟨t, ht, fun x _ => Algebra.IsIntegral.isIntegral x⟩
  · rintro ⟨t, ht, hti⟩
    have hI : Algebra.IsIntegral R S := by
      refine ⟨fun x => IsIntegral.of_mem_of_fg
        (Algebra.adjoin R (t : Set S)) ?_ x ?_⟩
      · exact fg_adjoin_of_finite t.finite_toSet hti
      · rw [ht]
        trivial
    letI : Algebra.IsIntegral R S := hI
    letI : Algebra.FiniteType R S := ⟨t, ht⟩
    exact Algebra.IsIntegral.finite

end StacksPart01Lib
