import Mathlib.RingTheory.Spectrum.Prime.Basic

/-!
# Elementary ideal and zero-locus identities

These are the affine ideal-theoretic identities used repeatedly in the
Stacks Project's preliminaries (for example, `V(IJ) = V(I) ∪ V(J)`).
-/

namespace StacksPart01

open Set

/- For a prime ideal, membership of a product is equivalent to membership of
either factor (Stacks, Tag 00E0). -/
theorem prime_mul_mem_iff {R : Type*} [CommSemiring R] {I : Ideal R}
    (hI : I.IsPrime) (f g : R) :
    f * g ∈ I ↔ f ∈ I ∨ g ∈ I := by
  exact hI.mul_mem_iff_mem_or_mem

/-- In a prime ideal, a positive power belongs exactly when its base does. -/
theorem prime_pow_mem_iff {R : Type*} [CommSemiring R] {I : Ideal R}
    (hI : I.IsPrime) (f : R) {n : ℕ} (hn : 0 < n) :
    f ^ n ∈ I ↔ f ∈ I := by
  exact hI.pow_mem_iff_mem n hn

/-- The zero locus of a product of ideals is the union of their zero loci
(Stacks, Tag 00E0). -/
theorem zeroLocus_mul {R : Type*} [CommSemiring R] (I J : Ideal R) :
    PrimeSpectrum.zeroLocus (↑(I * J) : Set R) =
      PrimeSpectrum.zeroLocus (↑I : Set R) ∪ PrimeSpectrum.zeroLocus (↑J : Set R) := by
  exact PrimeSpectrum.zeroLocus_mul I J

/-- The zero locus of an intersection of ideals is the union of their zero
loci (Stacks, Tag `00E0`, part (9)). -/
theorem zeroLocus_inf {R : Type*} [CommSemiring R] (I J : Ideal R) :
    PrimeSpectrum.zeroLocus (↑(I ⊓ J) : Set R) =
      PrimeSpectrum.zeroLocus (↑I : Set R) ∪ PrimeSpectrum.zeroLocus (↑J : Set R) := by
  exact PrimeSpectrum.zeroLocus_inf I J

/-- The zero locus of the zero ideal is the whole spectrum. -/
theorem zeroLocus_bot {R : Type*} [CommSemiring R] :
    PrimeSpectrum.zeroLocus (↑(⊥ : Ideal R) : Set R) = Set.univ := by
  exact PrimeSpectrum.zeroLocus_bot

/-- The zero locus of a sum of ideals is the intersection of their zero loci
(Stacks, Tag 00E0). -/
theorem zeroLocus_sup {R : Type*} [CommSemiring R] (I J : Ideal R) :
    PrimeSpectrum.zeroLocus (↑(I ⊔ J) : Set R) =
      PrimeSpectrum.zeroLocus (↑I : Set R) ∩ PrimeSpectrum.zeroLocus (↑J : Set R) := by
  exact PrimeSpectrum.zeroLocus_sup I J

/-- Passing to the radical does not change a zero locus (Stacks, Tag 00E0). -/
theorem zeroLocus_radical {R : Type*} [CommSemiring R] (I : Ideal R) :
    PrimeSpectrum.zeroLocus (↑I.radical : Set R) =
      PrimeSpectrum.zeroLocus (↑I : Set R) := by
  exact PrimeSpectrum.zeroLocus_radical I

/- The zero locus only depends on the ideal generated by a set of elements
(Stacks, Tag 00E0). -/
theorem zeroLocus_span {R : Type*} [CommSemiring R] (s : Set R) :
    PrimeSpectrum.zeroLocus (↑(Ideal.span s) : Set R) =
      PrimeSpectrum.zeroLocus s := by
  exact PrimeSpectrum.zeroLocus_span s

/- Enlarging the defining set shrinks its zero locus. -/
theorem zeroLocus_anti_mono {R : Type*} [CommSemiring R]
    {s t : Set R} (hst : s ⊆ t) :
    PrimeSpectrum.zeroLocus t ⊆ PrimeSpectrum.zeroLocus s := by
  exact PrimeSpectrum.zeroLocus_anti_mono hst

/- A union of equations cuts out the intersection of the corresponding loci. -/
theorem zeroLocus_union {R : Type*} [CommSemiring R] (s t : Set R) :
    PrimeSpectrum.zeroLocus (s ∪ t) =
      PrimeSpectrum.zeroLocus s ∩ PrimeSpectrum.zeroLocus t := by
  exact PrimeSpectrum.zeroLocus_union s t

/- Arbitrary unions of equations become arbitrary intersections of loci. -/
theorem zeroLocus_iUnion {R : Type*} [CommSemiring R] {ι : Sort*}
    (s : ι → Set R) :
    PrimeSpectrum.zeroLocus (⋃ i, s i) = ⋂ i, PrimeSpectrum.zeroLocus (s i) := by
  exact PrimeSpectrum.zeroLocus_iUnion s

/-- A family of ideal equations cuts out the intersection of its zero loci.

This ideal-shaped wrapper keeps the orientation used in the Stacks Project
while exposing the underlying set identity from `zeroLocus_iUnion`. -/
theorem zeroLocus_iUnion_ideal {R : Type*} [CommSemiring R] {ι : Sort*}
    (I : ι → Ideal R) :
    PrimeSpectrum.zeroLocus (⋃ i, (I i : Set R)) =
      ⋂ i, PrimeSpectrum.zeroLocus (I i : Set R) := by
  exact PrimeSpectrum.zeroLocus_iUnion (fun i => (I i : Set R))

/-- Every ideal is contained in its radical (Stacks, Tag 00E0). -/
theorem ideal_le_radical {R : Type*} [CommSemiring R] (I : Ideal R) :
    I ≤ I.radical := by
  exact Ideal.le_radical

/-- Radical is monotone with respect to inclusion of ideals. -/
theorem radical_mono_of_le {R : Type*} [CommSemiring R]
    {I J : Ideal R} (hIJ : I ≤ J) : I.radical ≤ J.radical := by
  exact Ideal.radical_mono hIJ

/-- Taking the radical twice has no further effect. -/
theorem radical_idempotent {R : Type*} [CommSemiring R] (I : Ideal R) :
    I.radical.radical = I.radical := by
  exact Ideal.radical_idem I

/-- The radical of an intersection is the intersection of the radicals. -/
theorem radical_inf_eq_inf {R : Type*} [CommSemiring R] (I J : Ideal R) :
    (I ⊓ J).radical = I.radical ⊓ J.radical := by
  exact Ideal.radical_inf I J

/-- The radical of a product is the intersection of the radicals. -/
theorem radical_mul_eq_inf {R : Type*} [CommSemiring R] (I J : Ideal R) :
    (I * J).radical = I.radical ⊓ J.radical := by
  exact Ideal.radical_mul I J

/- The zero locus of an ideal is empty exactly for the unit ideal. -/
theorem zeroLocus_empty_iff_top {R : Type*} [CommSemiring R] {I : Ideal R} :
    PrimeSpectrum.zeroLocus (↑I : Set R) = ∅ ↔ I = ⊤ := by
  exact PrimeSpectrum.zeroLocus_empty_iff_eq_top

/-- A prime ideal containing a product of ideals contains one factor
(Stacks, Tag 07K1). -/
theorem prime_ideal_contains_mul {R : Type*} [CommSemiring R]
    {I J P : Ideal R} (hP : P.IsPrime) (hIJ : I * J ≤ P) :
    I ≤ P ∨ J ≤ P := by
  exact hP.mul_le.mp hIJ

end StacksPart01
