/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.RiemannRoch.Adelic.BoundedVanishing

/-!
# Adelic Riemann–Roch — global generation above the bound

This file closes the **third** of the three gaps the vanishing lane kept apart
(`Adelic/BoundedVanishing.lean`, module docstring): *global generation*.  Until now
that gap was recorded as "not addressed at all"; the statements below address it, and
the docstrings there and in `Adelic/SectionBounds.lean` are updated accordingly.

## What global generation means here

`𝒪(D)` is **generated by global sections at a prime divisor `P`** exactly when some
global section attains the pole bound at `P`:

`∃ f ∈ Γ(⊤, 𝒪(D)), f ≠ 0 ∧ ord_P f = -D(P)`.

Such an `f` differs from a local generator of `𝒪(D)` at `P` by a unit of the DVR
`𝒪_P`, so it generates the stalk.  This is `GeneratedAt` below.  The sharper
statement is that the *whole* residue field is reached — the evaluation map

`Γ(⊤, 𝒪(D)) / Γ(⊤, 𝒪(D − P)) → κ(P)`

is not merely nonzero but **onto** (`evalMap_surjective`).

## The mechanism: two vanishings, not one

## A note on the ledger hypothesis

Inbox item I-0394 objects, correctly, that `hledger : ∀ D, χ(D) = χ(0) + deg_k D` is much
stronger than a consumer usually needs — and, quantified over *all* divisors, silently
carries finiteness content, since `Module.finrank` of an infinite-dimensional space is `0`.

The theorems here that need the ledger at *specific* divisors therefore take it **only
there**: `ell_sub_ell_sub_pointDivisor_eq`, `evalMap_surjective` and
`generatedAt_of_vanishing` take two named instances, `hledgerD` and `hledgerDP`, rather
than the universal binder.  That is exactly what their proofs use, and it means a caller
with the ledger at only those divisors can still use them.

The `∃ b, ∀ D, …` threshold theorems of §4 keep the universal form, and that is not
laziness: their conclusion quantifies over *all* divisors above a numerical bound, so they
genuinely need the ledger at every such `D` — and at `D − P` for each, which is not a set
that can be named in advance.

**Both concerns are now moot as gaps, though the sharpening is still worth having.**
`LedgerClosure.chi_eq_of_bump` proves the closed ledger at **every** Weil divisor from the
one-point bump alone, so the universal binder is dischargeable and there is no longer a
caller who "can produce the ledger only on the effective cone".  An earlier version of this
paragraph named `chi_eq_of_bump_of_nonneg` as the best available and described the
effective-cone restriction as a real limitation; that is out of date.  The ledger-free forms
of the §4 thresholds are `LedgerClosure.exists_bound_forall_generatedAt_of_bump` and
siblings.

The evaluation map is *always* injective — that is `localStepMapₖ_injective`, the
elementary half of node N14, and it is what makes `ℓ(D) − ℓ(D−P) ≤ [κ(P):k]`.  It is
onto exactly when that inequality is an equality, and the ledger converts the
equality into a statement about `h¹`:

`ℓ(D) − ℓ(D−P) = [κ(P):k] + h¹(D) − h¹(D−P)`.

So surjectivity follows from `h¹(D) = 0` **and** `h¹(D−P) = 0`.  This is why global
generation is *strictly* more than bounded vanishing and why the threshold moves:
`deg_k (D − P) = deg_k D − [κ(P):k]`, so to put `D − P` above the vanishing bound `b`
one needs `deg_k D ≥ b + [κ(P):k]` — the bound raised by the residue degree *at that
point*.

## The three gaps, restated

With this file the ledger of gaps reads:

1. **Single-field bounded vanishing** — assembled in `BoundedVanishing.lean` from
   three named inputs (base vanishing, peel, closed ledger); the first two are jointly
   equivalent to cone-vanishing (`coneVanishing_iff_base_and_peel`), so this is a
   reduction and not a discharge.
2. **Extension uniformity** — still unproved, but **statable**, as
   `Adelic.UniformlyBoundedVanishing` (`Adelic/ResidueField.lean` §5).  An earlier version of
   this entry said "not even *statable*: the invariants here are pinned on a chosen 2-affine
   cover, and `RiemannRoch/CurveBaseChange.lean` does not transport that cover to `C_κ`" — the
   second half is false, `AffineCoverMVSquare.baseChangeField` transports it.  What is missing
   is flat base change for the section spaces and a `WeilDivisor` pullback along `C_κ ⟶ C`.
3. **Global generation** — **this file**, conditional on exactly the same inputs as
   (1) and nothing more, with the threshold shifted by the residue degree.  The
   pointwise form (`exists_bound_generatedAt`) is unconditional in `P`; the *uniform*
   form (`exists_bound_forall_generatedAt`) needs a bound `r` on residue
   degrees, which is a genuine extra hypothesis over a general `k` (residue degrees of
   closed points are unbounded over a finite field) and is `r = 1` over an
   algebraically closed base.

## Provenance

Rederived in the AJC adelic abstractions.  The sibling `AJCR` proves global generation
on the `divisorSheaf` substrate via an evaluation-map/`Serre`-twist argument; none of
those identifiers exist here.  What is reused is the *idea* that global generation is
the equality case of the section-drop bound; the mechanism above (rank–nullity against
`finrank_localStepTgt`) is the adelic form and is cheaper, since the injectivity half
is already landed as N14.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits IsDedekindDomain
open scoped WithZero

namespace AlgebraicGeometry
namespace Adelic

/-! ## §1. The one-point-down divisor `D − P` -/

section PointDown

variable {X : Scheme.{u}} [IsIntegral X] [IsLocallyNoetherian X]
    [Scheme.IsRegularInCodimensionOne X]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **The coefficient of `D − P` at `P` is one less.** -/
theorem sub_pointDivisor_apply_self (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P =
      (show X.PrimeDivisor →₀ ℤ from D) P - 1 := by
  rw [show (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P =
        (show X.PrimeDivisor →₀ ℤ from D) P -
          (show X.PrimeDivisor →₀ ℤ from pointDivisor P) P from Finsupp.sub_apply _ _ _,
    pointDivisor, Finsupp.single_eq_same]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **`D − P` agrees with `D` off `P`.** -/
theorem sub_pointDivisor_apply_of_ne (D : X.WeilDivisor) {P Q : X.PrimeDivisor}
    (h : Q ≠ P) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q =
      (show X.PrimeDivisor →₀ ℤ from D) Q := by
  rw [show (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q =
        (show X.PrimeDivisor →₀ ℤ from D) Q -
          (show X.PrimeDivisor →₀ ℤ from pointDivisor P) Q from Finsupp.sub_apply _ _ _,
    pointDivisor, Finsupp.single_eq_of_ne h, sub_zero]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **`D − P ≤ D`.** -/
theorem sub_pointDivisor_le (D : X.WeilDivisor) (P Q : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) Q ≤
      (show X.PrimeDivisor →₀ ℤ from D) Q := by
  rcases eq_or_ne Q P with rfl | hne
  · rw [sub_pointDivisor_apply_self]; omega
  · rw [sub_pointDivisor_apply_of_ne D hne]

omit [IsIntegral X] [IsLocallyNoetherian X] [X.IsRegularInCodimensionOne] in
/-- **The one-point step hypothesis for the pair `(D − P, D)`.** -/
theorem sub_pointDivisor_step (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    (show X.PrimeDivisor →₀ ℤ from D) P =
      (show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P + 1 := by
  rw [sub_pointDivisor_apply_self]; omega

end PointDown

/-! ## §2. The evaluation map and its surjectivity

The **evaluation map** at `P` for the divisor `D` is `localStepMapₖ` for the pair
`(D − P, D)` at `U = ⊤`:

`Γ(⊤, 𝒪(D)) / Γ(⊤, 𝒪(D − P)) → orderGe P (-D(P)+1-1) ⧸ orderGe P (-D(P)+1) ≅ κ(P)`.

It is always injective (`localStepMapₖ_injective`).  It is surjective exactly when the
section drop is maximal, and rank–nullity turns that into the two-vanishing condition.
-/

section Evaluation

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **The evaluation map at `P`.**  `localStepMapₖ` for the one-point step
`D − P ≤ D` on the whole space; its target is a single-point valuation quotient, which
`finrank_localStepTgt` identifies numerically with the residue field `κ(P)`. -/
noncomputable def evalMap (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    localStepDom k ⊤ (D - pointDivisor P) D →ₗ[k]
      localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P) :=
  localStepMapₖ k (TopologicalSpace.Opens.mem_top P.point)
    (sub_pointDivisor_step D P)

/-- **The evaluation map is injective** — the elementary half of node N14, restated at
the pair `(D − P, D)`.  Unconditional: no ledger, no vanishing. -/
theorem evalMap_injective (D : X.WeilDivisor) (P : X.PrimeDivisor) :
    Function.Injective (evalMap k D P) :=
  localStepMapₖ_injective k (TopologicalSpace.Opens.mem_top P.point)
    (sub_pointDivisor_step D P) (sub_pointDivisor_le D P)
    (fun _ hQ => sub_pointDivisor_apply_of_ne D hQ)

end Evaluation

section EvalSurjective

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **The section drop is exactly the residue degree when both `h¹` vanish.**

The closed ledger reads `χ(D) − χ(D−P) = deg_k D − deg_k (D−P) = [κ(P):k]`, and
`χ = ℓ − h¹`, so

`ℓ(D) − ℓ(D−P) = [κ(P):k] + h¹(D) − h¹(D−P)`.

Under the two vanishings `h¹(D) = h¹(D−P) = 0` the correction terms drop out and the
section drop is *maximal*.  Compare `ell_le_ell_add_residueDeg` (`SectionBounds.lean`),
which gives the inequality `≤` unconditionally: this is its equality case, and the
input needed for equality is precisely a pair of vanishings, not one. -/
theorem ell_sub_ell_sub_pointDivisor_eq
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hledgerD : chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (hledgerDP : chi k U₀ U₁ (D - pointDivisor P) =
      chi k U₀ U₁ 0 + degK k (D - pointDivisor P))
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P))) :
    (ell k D : ℤ) - ell k (D - pointDivisor P) = residueDeg k P := by
  have h1 := h1dim_eq_zero_of_subsingleton k U₀ U₁ hD
  have h2 := h1dim_eq_zero_of_subsingleton k U₀ U₁ hDP
  have hchiD := hledgerD
  have hchiDP := hledgerDP
  have hdeg : degK k D - degK k (D - pointDivisor P) = residueDeg k P := by
    rw [degK_sub, degK_pointDivisor]; ring
  rw [chi, h1] at hchiD
  rw [chi, h2] at hchiDP
  omega

/-- **The evaluation map is surjective** — hence bijective, since it is always
injective.  Global generation in its sharpest adelic form: not merely "some section
attains the pole bound at `P`", but "*every* residue class at `P` is attained".

The proof is a rank count: the domain has dimension `ℓ(D) − ℓ(D−P)`
(`finrank_localStepDom`, rank–nullity), the target has dimension `[κ(P):k]`
(`finrank_localStepTgt`), the two agree by
`ell_sub_ell_sub_pointDivisor_eq`, and an injective map between spaces of equal finite
dimension is onto (`LinearMap.injective_iff_surjective_of_finrank_eq_finrank`).

Note which finiteness is needed and which is not: `Module.Finite k (sectionSub k ⊤ D)`
enters through rank–nullity, and `Module.Finite k (localStepTgt k P 1)` is the residue
finiteness `[κ(P):k] < ∞` — the same binder node N14 takes, and no longer an open gate:
`Adelic.finite_localStepTgt_one_of_isAlgClosed_curve` discharges it on curve hypotheses.
The section finiteness is a different matter and remains open. -/
theorem evalMap_surjective
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hledgerD : chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (hledgerDP : chi k U₀ U₁ (D - pointDivisor P) =
      chi k U₀ U₁ 0 + degK k (D - pointDivisor P))
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P)))
    [Module.Finite k (sectionSub k ⊤ D)]
    [Module.Finite k (localStepTgt k P 1)] :
    Function.Surjective (evalMap k D P) := by
  -- the domain is finite-dimensional (a quotient of a finite-dimensional space)
  haveI : Module.Finite k (localStepDom k ⊤ (D - pointDivisor P) D) := inferInstance
  haveI : Module.Finite k
      (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    have hrank := finrank_localStepTgt k P
      (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)
    obtain ⟨t, ht, htord⟩ :=
      exists_order_eq P (1 - -(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)
    exact Module.Finite.equiv
      (LinearEquiv.ofBijective (residueShift k t ht htord)
        ⟨residueShift_injective k t ht htord,
          residueShift_surjective k t ht htord⟩).symm
  -- the two dimensions agree
  have hdim : Module.finrank k (localStepDom k ⊤ (D - pointDivisor P) D) =
      Module.finrank k
        (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    rw [finrank_localStepTgt]
    have hrn := finrank_localStepDom k ⊤
      (sectionSub_mono k ⊤ (sub_pointDivisor_le D P))
    have hdrop := ell_sub_ell_sub_pointDivisor_eq k U₀ U₁ D P hledgerD hledgerDP hD hDP
    simp only [ell] at hdrop
    omega
  exact (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hdim).mp
    (evalMap_injective k D P)

end EvalSurjective

/-! ## §3. Global generation as a statement about sections

`evalMap_surjective` is the sharp form, but it is phrased on a subquotient.  The form a
consumer wants is about an actual rational function: *some global section of `𝒪(D)`
attains the pole bound at `P`*.  That is `GeneratedAt` below, and it follows from
surjectivity together with the nontriviality of `κ(P)` (`1 ≤ [κ(P):k]`).
-/

section GeneratedAt

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **`𝒪(D)` is generated by global sections at `P`.**  Some global section attains the
pole bound at `P` exactly: `ord_P f = -D(P)`.

Such an `f` generates the stalk `𝒪(D)_P` over `𝒪_P`, since any two elements of the
fractional ideal `𝔪_P^{-D(P)}` of minimal order differ by a unit.  Stated on the order
rather than on the stalk so that it is checkable in the adelic language; a section with
`ord_P f > -D(P)` is exactly one that *fails* to generate, i.e. vanishes at `P` as a
section of the twist. -/
def GeneratedAt (D : X.WeilDivisor) (P : X.PrimeDivisor) : Prop :=
  ∃ f : X.functionField, f ∈ sectionSub k ⊤ D ∧ f ≠ 0 ∧
    Scheme.RationalMap.order P f = -(show X.PrimeDivisor →₀ ℤ from D) P

/-- **Surjectivity of the evaluation map gives global generation at `P`.**

`κ(P)` is nontrivial (`1 ≤ [κ(P):k]`, `one_le_residueDeg`), so the target of `evalMap`
has a nonzero element; a preimage of it is a global section `f` of `𝒪(D)` whose class in
`orderGe P (-D(P)) / orderGe P (-D(P)+1)` is nonzero, i.e. with
`ord_P f < -D(P) + 1`.  Being a section of `𝒪(D)` gives the reverse `ord_P f ≥ -D(P)`,
so `ord_P f = -D(P)`. -/
theorem generatedAt_of_evalMap_surjective (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hsurj : Function.Surjective (evalMap k D P))
    [Module.Finite k (localStepTgt k P 1)] :
    GeneratedAt k D P := by
  -- the target is nontrivial: its dimension is `[κ(P):k] ≥ 1`
  haveI : Nontrivial
      (localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P)) := by
    refine Module.nontrivial_of_finrank_pos (R := k) ?_
    rw [finrank_localStepTgt]
    exact one_le_residueDeg k P
  obtain ⟨z, hz⟩ := exists_ne (0 :
    localStepTgt k P (-(show X.PrimeDivisor →₀ ℤ from D - pointDivisor P) P))
  obtain ⟨q, hq⟩ := hsurj z
  obtain ⟨f, rfl⟩ := Submodule.Quotient.mk_surjective _ q
  refine ⟨(f : X.functionField), f.2, ?_, ?_⟩
  · -- a section whose class is nonzero cannot be `0`
    intro hf0
    apply hz
    rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply]
    rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
      Submodule.coe_inclusion, mem_orderGeSub, hf0]
    exact (orderGe _ _).zero_mem
  · -- the two inequalities
    have hlow : -(show X.PrimeDivisor →₀ ℤ from D) P ≤
        Scheme.RationalMap.order P (f : X.functionField) := by
      rcases eq_or_ne (f : X.functionField) 0 with hf0 | hf0
      · exact absurd hf0 (by
          intro h
          apply hz
          rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply,
            Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
            Submodule.coe_inclusion, mem_orderGeSub, h]
          exact (orderGe _ _).zero_mem)
      exact (mem_sectionOfDivisor_of_ne_zero hf0).mp f.2 P
        (TopologicalSpace.Opens.mem_top P.point)
    have hhigh : Scheme.RationalMap.order P (f : X.functionField) <
        -(show X.PrimeDivisor →₀ ℤ from D) P + 1 := by
      by_contra hge
      apply hz
      rw [← hq, evalMap, localStepMapₖ, Submodule.mapQ_apply,
        Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
        Submodule.coe_inclusion, mem_orderGeSub]
      refine Or.inr ?_
      rw [sub_pointDivisor_apply_self]
      omega
    omega

/-- **Global generation at `P` from the two vanishings** — `evalMap_surjective`
composed with `generatedAt_of_evalMap_surjective`.

**Conjunction audit** (the check memory I-0399 requires for this task, run for this
theorem): the hypotheses are *not* equivalent to the conclusion, so this is a reduction
and not a re-indexing.  `GeneratedAt k D P` yields a section attaining the bound at `P`,
which is exactly the statement that some section of `𝒪(D)` is **not** a section of
`𝒪(D − P)` — i.e. a *strict* drop `ℓ(D − P) < ℓ(D)`.  The hypotheses give the **maximal**
drop `ℓ(D) − ℓ(D − P) = [κ(P):k]`.  Those differ as soon as `[κ(P):k] ≥ 2`, so the
converse fails and the vanishing input is doing real work.  (Over an algebraically closed
base they coincide, which is the degenerate case, not the general one.) -/
theorem generatedAt_of_vanishing
    (D : X.WeilDivisor) (P : X.PrimeDivisor)
    (hledgerD : chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (hledgerDP : chi k U₀ U₁ (D - pointDivisor P) =
      chi k U₀ U₁ 0 + degK k (D - pointDivisor P))
    (hD : Subsingleton (H1Mod k U₀ U₁ D))
    (hDP : Subsingleton (H1Mod k U₀ U₁ (D - pointDivisor P)))
    [Module.Finite k (sectionSub k ⊤ D)]
    [Module.Finite k (localStepTgt k P 1)] :
    GeneratedAt k D P :=
  generatedAt_of_evalMap_surjective k D P
    (evalMap_surjective k U₀ U₁ D P hledgerD hledgerDP hD hDP)

end GeneratedAt

/-! ## §4. The threshold: how far above the vanishing bound

`generatedAt_of_vanishing` needs vanishing at `D` *and* at `D − P`.  Feeding it the
bounded-vanishing theorem requires both divisors above the threshold `b`, and

`deg_k (D − P) = deg_k D − [κ(P):k]`,

so the generation threshold is `b + [κ(P):k]` — the vanishing bound raised by the
residue degree **at that point**.  Two forms follow.

*Pointwise* (`exists_bound_generatedAt`): for each `P` separately, no extra hypothesis.

*Uniform* (`exists_bound_forall_generatedAt`): the same `D` generating at
**every** `P` at once needs a uniform bound `r` on residue degrees, `∀ P, [κ(P):k] ≤ r`.
That is a real hypothesis and not a formality: over a finite field the residue degrees
of closed points are unbounded, so no such `r` exists there, whereas over an
algebraically closed base `r = 1` works.  This is the precise sense in which global
generation is "the bound raised by the maximum residue degree" — and the maximum has to
exist.
-/

section Threshold

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **Global generation above the shifted bound, pointwise in `P`.**

Given the three inputs of `exists_bound_subsingleton_h1Mod` there is a threshold `b`
such that for every `P` and every `D` with `deg_k D ≥ b + [κ(P):k]`, the sheaf `𝒪(D)`
is generated by global sections at `P`.

The shift by `[κ(P):k]` is exactly what puts `D − P` above `b` as well; it is not
slack. -/
theorem exists_bound_generatedAt
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D₀ : X.WeilDivisor) (hbase : Subsingleton (H1Mod k U₀ U₁ D₀))
    (hpeel : ∀ D' : X.WeilDivisor,
      (∀ P : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D₀) P ≤
        (show X.PrimeDivisor →₀ ℤ from D') P) →
      Peel k U₀ U₁ D₀ D')
    [∀ D : X.WeilDivisor, Module.Finite k (sectionSub k ⊤ D)]
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)] :
    ∃ b : ℤ, ∀ (D : X.WeilDivisor) (P : X.PrimeDivisor),
      b + residueDeg k P ≤ degK k D → GeneratedAt k D P := by
  obtain ⟨b, hb⟩ :=
    exists_bound_subsingleton_h1Mod k U₀ U₁ hledger D₀ hbase hpeel
  refine ⟨b, fun D P hD => ?_⟩
  have hdegDP : degK k (D - pointDivisor P) = degK k D - residueDeg k P := by
    rw [degK_sub, degK_pointDivisor]
  exact generatedAt_of_vanishing k U₀ U₁ D P (hledger D)
    (hledger (D - pointDivisor P)) (hb D (by omega))
    (hb (D - pointDivisor P) (by omega))

/-- **Uniform global generation above the shifted bound.**  With a uniform bound `r` on
residue degrees, one threshold `b + r` works for **every** point at once: above it,
`𝒪(D)` is generated by global sections at every prime divisor.

This is the strongest global-generation statement reachable in AJC today.  It remains
**single-field** — `k`, the cover `U₀, U₁` and `D₀` are all fixed, and nothing here
quantifies over field extensions, so extension uniformity is untouched (gap 2 of the
module docstring). -/
theorem exists_bound_forall_generatedAt
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D₀ : X.WeilDivisor) (hbase : Subsingleton (H1Mod k U₀ U₁ D₀))
    (hpeel : ∀ D' : X.WeilDivisor,
      (∀ P : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D₀) P ≤
        (show X.PrimeDivisor →₀ ℤ from D') P) →
      Peel k U₀ U₁ D₀ D')
    (r : ℕ) (hr : ∀ P : X.PrimeDivisor, residueDeg k P ≤ r)
    [∀ D : X.WeilDivisor, Module.Finite k (sectionSub k ⊤ D)]
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)] :
    ∃ b : ℤ, ∀ D : X.WeilDivisor, b ≤ degK k D →
      ∀ P : X.PrimeDivisor, GeneratedAt k D P := by
  obtain ⟨b, hb⟩ :=
    exists_bound_generatedAt k U₀ U₁ hledger D₀ hbase hpeel
  refine ⟨b + r, fun D hD P => ?_⟩
  refine hb D P ?_
  have := hr P
  omega

end Threshold

/-! ## §5. What `[κ(P):k] = 1` actually says

Both the uniform generation statement (`r = 1`) and the open geometric leaf
`Scheme.WeilDivisor.principal_degree_zero` (through
`degree_principal_eq_zero_of_residueDeg_eq_one`, `SectionBounds.lean` §4) reduce to the
single fact `residueDeg k P = 1`.  It has been carried as an informal remark — "over an
algebraically closed base every closed point has residue field `k̄`".  This section
replaces the remark by a **machine-checked equivalence** to a concrete, checkable
statement about rational functions:

`residueDeg k P = 1 ↔ every function of order ≥ 0 at `P` agrees with a constant to
first order at `P`.`

That is `residueDeg_eq_one_iff_hasRationalResidues`.  It converts the remaining leaf from
a claim about residue fields — which in this substrate would require identifying
`localStepTgt k P 1` with `IsLocalRing.ResidueField (X.presheaf.stalk P.point)`, an
identification this project does not have — into an approximation statement in the order
language the substrate already speaks.

Note what is **not** claimed *in this section*: `HasRationalResidues` is not proved here for
an algebraically closed base.  Doing so needs the multiplicative structure of `κ(P)` (a
finite-dimensional *field* extension of an algebraically closed `k` is trivial —
`IsAlgClosed.algebraMap_bijective_of_isIntegral`), and `localStepTgt k P 1` is
constructed here as a quotient of `k`-submodules with no ring structure on it.  Finite
dimensionality alone does not give dimension one for a mere vector space, so the gap is
real and is exactly the missing ring-structure identification.

**It is proved elsewhere now**, for a curve: `Adelic.hasRationalResidues_of_isAlgClosed_curve`
(`Adelic/ResidueField.lean`).  Note how it escapes the obstruction just described — it never
identifies `localStepTgt k P 1` with the stalk residue field.  It proves the *approximation
statement* directly, by lifting to the stalk and using that `k → κ_P` is onto there, and then
feeds it back through this section's equivalence to reach `residueDeg k P = 1`.  So the `iff`
above is what makes the discharge possible: the ring-structure identification is still absent,
and is still not needed.
-/

section RationalResidues

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **Every function regular at `P` agrees with a constant to first order.**
`∀ f` with `ord_P f ≥ 0`, some `c ∈ k` has `ord_P (f − c) ≥ 1`.

This is the concrete content of "`κ(P) = k`", phrased in the order language rather than
through the residue field: the residue of `f` at `P` is the constant `c`.  Over an
algebraically closed base field it is the standard fact that a closed point of a curve
has residue field the base field; here it is an explicit hypothesis, and
`residueDeg_eq_one_iff_hasRationalResidues` shows it is *exactly* equivalent to
`[κ(P):k] = 1`. -/
def HasRationalResidues (P : X.PrimeDivisor) : Prop :=
  ∀ f : X.functionField, f ∈ orderGe P 0 →
    ∃ c : k, f - algebraMap k X.functionField c ∈ orderGe P 1

/-- **`[κ(P):k] = 1` is equivalent to first-order approximation by constants.**

`→` The quotient `localStepTgt k P 1 = orderGe P 0 / orderGe P 1` has dimension one and
its class of `1` is nonzero (`nontrivial_localStepTgt_one`), hence spans; so the class of
any `f` is `c • [1] = [c]`, i.e. `f − c ∈ orderGe P 1`.

`←` Conversely, approximation says every class is a `k`-multiple of `[1]`, so the
quotient is spanned by one vector and has dimension `≤ 1`; with `1 ≤ [κ(P):k]`
(`one_le_residueDeg`) it is exactly `1`.

The `→` direction needs no finiteness instance; `←` produces one, since a space spanned
by a single vector is finite-dimensional. -/
theorem residueDeg_eq_one_iff_hasRationalResidues (P : X.PrimeDivisor)
    [Module.Finite k (localStepTgt k P 1)] :
    residueDeg k P = 1 ↔ HasRationalResidues k P := by
  have hone : (1 : X.functionField) ∈ orderGeSub k P (1 - 1) := by
    rw [mem_orderGeSub]
    exact Or.inr (by rw [Scheme.RationalMap.order_one]; norm_num)
  constructor
  · -- dimension one: the class of `1` spans
    intro hdeg f hf
    -- `[1] ≠ 0`, and in a 1-dimensional space a nonzero vector spans
    have hspan : ∀ z : localStepTgt k P 1, ∃ c : k,
        z = c • Submodule.Quotient.mk (p := Submodule.comap
          (orderGeSub k P (1 - 1)).subtype (orderGeSub k P 1)) ⟨1, hone⟩ := by
      intro z
      haveI := nontrivial_localStepTgt_one k P
      have hne : Submodule.Quotient.mk (p := Submodule.comap
          (orderGeSub k P (1 - 1)).subtype (orderGeSub k P 1))
          (⟨1, hone⟩ : orderGeSub k P (1 - 1)) ≠ 0 := by
        intro h
        rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
          mem_orderGeSub] at h
        rcases h with h0 | h0
        · exact one_ne_zero h0
        · rw [Scheme.RationalMap.order_one] at h0; norm_num at h0
      -- a nonzero vector in a space of rank 1 spans it
      have hfr : Module.finrank k (localStepTgt k P 1) = 1 := hdeg
      obtain ⟨c, hc⟩ := (finrank_eq_one_iff_of_nonzero' _ hne).mp hfr z
      exact ⟨c, hc.symm⟩
    obtain ⟨c, hc⟩ := hspan (Submodule.Quotient.mk
      (p := Submodule.comap (orderGeSub k P (1 - 1)).subtype (orderGeSub k P 1))
      ⟨f, (mem_orderGeSub k).mpr hf⟩)
    refine ⟨c, ?_⟩
    -- unwind `[f] = c • [1]` into `f - c ∈ orderGe P 1`
    rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.eq, Submodule.mem_comap,
      Submodule.subtype_apply] at hc
    rw [mem_orderGeSub] at hc
    have : ((⟨f, (mem_orderGeSub k).mpr hf⟩ : orderGeSub k P (1 - 1)) -
        c • ⟨1, hone⟩ : orderGeSub k P (1 - 1)) =
        (⟨f - algebraMap k X.functionField c, by
          have h1 : algebraMap k X.functionField c ∈ orderGeSub k P (1 - 1) := by
            have := (orderGeSub k P (1 - 1)).smul_mem c hone
            rwa [Algebra.smul_def, mul_one] at this
          exact (orderGeSub k P (1 - 1)).sub_mem ((mem_orderGeSub k).mpr hf) h1⟩ :
          orderGeSub k P (1 - 1)) := by
      apply Subtype.ext
      change f - c • (1 : X.functionField) = f - algebraMap k X.functionField c
      rw [Algebra.smul_def, mul_one]
    rw [this] at hc
    exact hc
  · -- approximation: the class of `1` spans, so the rank is at most one
    intro happrox
    have hle : residueDeg k P ≤ 1 := by
      rw [residueDeg]
      -- the quotient is spanned by the single class of `1`
      have hspan : (⊤ : Submodule k (localStepTgt k P 1)) ≤
          Submodule.span k {Submodule.Quotient.mk (p := Submodule.comap
            (orderGeSub k P (1 - 1)).subtype (orderGeSub k P 1)) ⟨1, hone⟩} := by
        intro z _
        obtain ⟨g, rfl⟩ := Submodule.Quotient.mk_surjective _ z
        obtain ⟨c, hc⟩ := happrox (g : X.functionField)
          (by
            have hg2 := g.2
            rw [mem_orderGeSub] at hg2
            exact orderGe_antitone (by norm_num) hg2)
        rw [Submodule.mem_span_singleton]
        refine ⟨c, ?_⟩
        rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.eq, Submodule.mem_comap,
          Submodule.subtype_apply]
        have hval : ((c • ⟨1, hone⟩ - g : orderGeSub k P (1 - 1)) :
            X.functionField) = -(g - algebraMap k X.functionField c) := by
          change c • (1 : X.functionField) - (g : X.functionField) = _
          rw [Algebra.smul_def, mul_one]
          ring
        rw [mem_orderGeSub, hval]
        exact (orderGe P 1).neg_mem hc
      have := Submodule.finrank_mono hspan
      rw [finrank_top] at this
      refine this.trans ?_
      rcases eq_or_ne (Submodule.Quotient.mk (p := Submodule.comap
          (orderGeSub k P (1 - 1)).subtype (orderGeSub k P 1))
          (⟨1, hone⟩ : orderGeSub k P (1 - 1))) 0 with h0 | h0
      · rw [h0, Submodule.span_zero_singleton, finrank_bot]; norm_num
      · rw [finrank_span_singleton h0]
    have := one_le_residueDeg k P
    omega

end RationalResidues

/-! ## §6. The rational-residue case: `r = 1` and the unweighted degree

Under `HasRationalResidues` at every prime divisor — the substrate's form of "the base
field is algebraically closed" — the two hypotheses that §4 and `SectionBounds.lean` §4
left open both become discharged simultaneously, because both were the same fact:

* the uniform generation bound gets `r = 1`, so the threshold is `b + 1`;
* `deg_k = deg` (`degK_eq_degree_of_residueDeg_eq_one`), so the weighted statements
  become statements about the geometric degree — in particular the principal-degree-zero
  leaf.

This is the precise pay-off of §5: one approximation hypothesis, two consequences.
-/

section RationalResidueConsequences

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **Rational residues everywhere give residue degree one everywhere.** -/
theorem residueDeg_eq_one_of_hasRationalResidues
    (hres : ∀ P : X.PrimeDivisor, HasRationalResidues k P)
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)]
    (P : X.PrimeDivisor) : residueDeg k P = 1 :=
  (residueDeg_eq_one_iff_hasRationalResidues k P).mpr (hres P)

/-- **Uniform global generation with threshold `b + 1`.**  With rational residues at
every point, the residue-degree bound of `exists_bound_forall_generatedAt` is `r = 1`, so
one threshold works for every point and the shift over the vanishing bound is a single
unit.

This is the classical shape: above `deg D ≥ b + 1`, `𝒪(D)` is generated by global
sections everywhere.  It remains single-field. -/
theorem exists_bound_forall_generatedAt_of_hasRationalResidues
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D₀ : X.WeilDivisor) (hbase : Subsingleton (H1Mod k U₀ U₁ D₀))
    (hpeel : ∀ D' : X.WeilDivisor,
      (∀ P : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D₀) P ≤
        (show X.PrimeDivisor →₀ ℤ from D') P) →
      Peel k U₀ U₁ D₀ D')
    (hres : ∀ P : X.PrimeDivisor, HasRationalResidues k P)
    [∀ D : X.WeilDivisor, Module.Finite k (sectionSub k ⊤ D)]
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)] :
    ∃ b : ℤ, ∀ D : X.WeilDivisor, b ≤ degK k D →
      ∀ P : X.PrimeDivisor, GeneratedAt k D P :=
  exists_bound_forall_generatedAt k U₀ U₁ hledger D₀ hbase hpeel 1
    (fun P => le_of_eq (residueDeg_eq_one_of_hasRationalResidues k hres P))

/-- **The weighted degree is the geometric degree, under rational residues.**  Together
with `degK_principal_eq_zero` this is the unweighted principal-degree-zero statement; see
`degree_principal_eq_zero_of_residueDeg_eq_one` (`SectionBounds.lean`), whose residue
hypothesis is now reduced to `HasRationalResidues`. -/
theorem degK_eq_degree_of_hasRationalResidues
    (hres : ∀ P : X.PrimeDivisor, HasRationalResidues k P)
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)]
    (D : X.WeilDivisor) : degK k D = Scheme.WeilDivisor.degree D :=
  degK_eq_degree_of_residueDeg_eq_one k
    (fun P _ => residueDeg_eq_one_of_hasRationalResidues k hres P)

/-- **Principal divisors have geometric degree zero, from the ledger plus rational
residues.**  The adelic route to the open leaf
`Scheme.WeilDivisor.principal_degree_zero`, with both of its inputs now named: the closed
ledger and the approximation statement `HasRationalResidues`.

Compare `degree_principal_eq_zero_of_residueDeg_eq_one`: that took residue-degree-one on
the support as a hypothesis; here it is derived from the approximation form, which is the
statement one can actually hope to discharge from algebraic closedness. -/
theorem degree_principal_eq_zero_of_hasRationalResidues
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (hres : ∀ P : X.PrimeDivisor, HasRationalResidues k P)
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)]
    {g : X.functionField} (hg : g ≠ 0) :
    Scheme.WeilDivisor.degree (Scheme.WeilDivisor.principal g hg) = 0 :=
  degree_principal_eq_zero_of_residueDeg_eq_one k U₀ U₁ hledger hg
    (fun P _ => residueDeg_eq_one_of_hasRationalResidues k hres P)

end RationalResidueConsequences

/-! ## §7. Discharging `HasRationalResidues` from algebraic closedness

§5 reduced `[κ(P):k] = 1` to the approximation statement, and §6 drew the consequences.
This section derives the approximation statement, for an algebraically closed `k`, from
stalk-level hypotheses that **this file** does not instantiate.

**SUPERSEDED — read `Adelic/ResidueField.lean` instead.**  The approximation statement is
now a *theorem* on AJC curve hypotheses, `hasRationalResidues_of_isAlgClosed_curve`, and
`residueDeg k P = 1` with it.  That module does not use this section's route: it takes the
three binders below off the table rather than building all of them, because mathlib's
`AlgebraicGeometry.residueFieldIsoBase` obtains integrality of `κ(x)` over `k` from
`LocallyOfFiniteType` (via the Jacobson-space finiteness criterion) instead of from a
residue-finiteness hypothesis.  What it *did* have to build is the compatibility of the
stalk `k`-algebra with this lane's `Algebra k K(X)`
(`Adelic.algebraMap_stalk_functionField`), which is what lets a stalk-level argument be read
in the order language at all.

This section is kept because its statement is more general — it asks nothing of the scheme
beyond the three binders, so it applies to a non-curve — and because the valuation bridge
`mem_orderGe_one_iff_mem_maximalIdeal` below is reused by the new module.  The honest
summary of *this theorem* is unchanged: it moves the obligation off the order subquotient
and onto standard commutative algebra about the stalk, and is a reformulation rather than a
discharge.

The argument, at the point `P` with stalk `R := 𝒪_{X,P}` (a DVR):

1. `ord_P f ≥ 0` lets `f` be lifted to `a ∈ R` (`exists_stalk_lift_of_order_nonneg`);
2. `k → IsLocalRing.ResidueField R` is an integral algebra map (finiteness), and `k` is
   algebraically closed, so it is **bijective**
   (`IsAlgClosed.algebraMap_bijective_of_isIntegral`); pick `c` with
   `residue a = c`;
3. then `a − c ∈ 𝔪_R`, and membership in the maximal ideal is `ord_P ≥ 1` — that is the
   valuation bridge `HeightOneSpectrum.valuation_lt_one_iff_mem` read through
   `order_eq_neg_log_pointValuation`.

Step 3 is the only place where the two languages have to be matched, and it is where the
work is: the project's `order` is `-log ∘ v_P`, so `ord_P x ≥ 1` is `v_P x < 1`, which is
exactly membership in the height-one ideal of the DVR.
-/

section AlgClosed

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **Membership in the maximal ideal of the stalk is membership in `orderGe P 1`.**  For
`a` in the DVR stalk `𝒪_P`, the image of `a` in `K(X)` lies in `orderGe P 1` exactly when
`a` lies in the maximal ideal.

This is the valuation bridge: `ord_P = -log ∘ v_P` (`order_eq_neg_log_pointValuation`), so
`ord_P ≥ 1` says `v_P < 1`, and for an element *of the DVR* that is membership in the
height-one ideal (`HeightOneSpectrum.valuation_lt_one_iff_mem`).  The maximal ideal of a
DVR is the `asIdeal` of its height-one place, which is how the two sides are matched.

**Why `orderGe P 1` and not `1 ≤ ord_P`.**  The project's `order` carries the junk
convention `ord_P 0 = 0` rather than `+∞`, so for `a = 0` — which *is* in the maximal
ideal — the inequality `1 ≤ ord_P 0` is false and the `←` direction would fail.
`orderGe P 1` admits the zero function through its separate `f = 0` disjunct, which is
exactly why the substrate is phrased on `orderGe` throughout; stating this bridge on the
raw inequality would be a false statement that happens to typecheck. -/
theorem mem_orderGe_one_iff_mem_maximalIdeal (P : X.PrimeDivisor)
    (a : X.presheaf.stalk P.point) :
    algebraMap (X.presheaf.stalk P.point) X.functionField a ∈ orderGe P 1 ↔
      a ∈ IsLocalRing.maximalIdeal (X.presheaf.stalk P.point) := by
  rcases eq_or_ne a 0 with rfl | ha0
  · simp only [map_zero]
    exact iff_of_true (Or.inl rfl) (Submodule.zero_mem _)
  have hane : algebraMap (X.presheaf.stalk P.point) X.functionField a ≠ 0 := by
    simpa using (FaithfulSMul.algebraMap_injective
      (X.presheaf.stalk P.point) X.functionField).ne_iff.mpr ha0
  rw [mem_orderGe_of_ne_zero hane]
  have hval := IsDedekindDomain.HeightOneSpectrum.valuation_lt_one_iff_mem
    (R := X.presheaf.stalk P.point) (K := X.functionField)
    (IsDiscreteValuationRing.maximalIdeal (X.presheaf.stalk P.point)) a
  rw [show (IsDiscreteValuationRing.maximalIdeal
      (X.presheaf.stalk P.point)).asIdeal =
      IsLocalRing.maximalIdeal (X.presheaf.stalk P.point) from rfl] at hval
  rw [← hval, order_eq_neg_log_pointValuation, pointValuation]
  set v := (IsDiscreteValuationRing.maximalIdeal
    (X.presheaf.stalk P.point)).valuation X.functionField with hv
  constructor
  · intro hord
    -- `-log (v x) ≥ 1` gives `log (v x) ≤ -1 < 0`, hence `v x < 1`
    by_contra hge
    rw [not_lt] at hge
    rcases eq_or_lt_of_le hge with heq | hlt
    · rw [← heq] at hord
      simp at hord
    · -- `1 < v x` gives `log (v x) > 0`, contradicting `-log (v x) ≥ 1`
      have hne : v (algebraMap (X.presheaf.stalk P.point) X.functionField a) ≠ 0 := by
        intro h0
        rw [h0] at hlt
        exact absurd hlt (by simp)
      have := (WithZero.log_lt_log (x := (1 : ℤᵐ⁰)) one_ne_zero hne).mpr hlt
      rw [WithZero.log_one] at this
      omega
  · intro hlt
    have hne : v (algebraMap (X.presheaf.stalk P.point) X.functionField a) ≠ 0 ∨
        v (algebraMap (X.presheaf.stalk P.point) X.functionField a) = 0 := by
      exact ne_or_eq _ _
    rcases hne with hne | h0
    · have := (WithZero.log_lt_log hne one_ne_zero).mpr hlt
      rw [WithZero.log_one] at this
      omega
    · exact absurd h0 (by
        simpa [hv] using (Valuation.zero_iff v).not.mpr hane)

omit [IsConstantField k X] in
/-- **`HasRationalResidues` holds over an algebraically closed base field.**

Given at `P`:
* an algebra structure `k → 𝒪_P` on the stalk, and compatibility with `k → K(X)` as an
  `IsScalarTower`;
* finiteness of the residue field of the *stalk* over `k`, `[κ_P : k] < ∞`;
* `IsAlgClosed k`,

every function of order `≥ 0` at `P` agrees with a constant to first order.

## READ THIS BEFORE CITING: prefer `Adelic/ResidueField.lean`

For a **curve** over an algebraically closed field, do not cite this theorem: cite
`Adelic.hasRationalResidues_of_isAlgClosed_curve`, which proves the same conclusion with no
open input.  This theorem's three binders below are still not instantiated *by this file*,
and two of the three are now available (`Adelic.isScalarTower_stalk_functionField` and the
`stalkAlgebra` it is stated over) — but the third, the residue finiteness, remains a gate
here, which is precisely why the new module avoids needing it.

An earlier version of this docstring claimed `Adelic/GateInstances.lean` "builds exactly
this" and that the residue finiteness is "the same keystone finiteness node N14 consumes".
**Both claims were false**, and a fresh-context review caught them.  Precisely:

* `GateInstances.lean` builds `IsScalarTower k Γ(C,⊤) K(C)` (over **global sections**) and
  a tower `IsScalarTower Γ(C,⊤) 𝒪_P K(C)` (over **`Γ(C,⊤)`**, not over `k`).  Neither is
  the `IsScalarTower k 𝒪_P K(X)` binder below.
* `Algebra k (X.presheaf.stalk P.point)` has an instance only for objects of
  `Over (Spec k)` (`Picard/TangentSpaceStalkAlgebra.lean`), not for the bare `Scheme X`
  this lane is stated over.  (For an `Over (Spec k)` curve this one *is* now settled:
  `Adelic.algebraMap_stalk_functionField` proves that structure compatible with this lane's
  `Algebra k K(X)` — which was the missing half, since the ring map itself always existed.
  Beware the diamond recorded in `ResidueField.lean`: at the generic point the scoped
  `overStalkAlgebra` competes with `Scheme.functionFieldAlgebra` and they are not defeq.)
* node N14 consumes `Module.Finite k (localStepTgt k P 1)`, which is a quotient of
  `k`-submodules of `K(X)`.  `Module.Finite k (IsLocalRing.ResidueField 𝒪_P)` is a
  **different** hypothesis about the stalk, and §5 above says in its own words that this
  project has no identification of the two.

So **this theorem** should be read as trading one unproved fact for three binders that it
does not itself supply, one of which (the stalk residue finiteness) is effectively a new
gate.  It is a genuine *reformulation* — it moves the obligation from "`κ(P)` as an order
subquotient has dimension one" to standard commutative algebra about the stalk, where
`IsAlgClosed.algebraMap_bijective_of_isIntegral` applies — but it is **not** a discharge.

The prediction in an earlier version of this paragraph, that constructing the binders was
"the obvious next step and looks routine", was half right.  The algebra structure and tower
were indeed routine (`Adelic/ResidueField.lean` §1).  The residue finiteness was *not*, and
the resolution was to **avoid it**: mathlib's `residueFieldIsoBase` derives what is needed
from `LocallyOfFiniteType` instead, so the curve-level theorem needs no residue-finiteness
gate at all.  The lesson worth keeping is that the substantive binder was dodged rather than
discharged.

Composed with §5–§6 this theorem therefore *reduces*, rather than discharges, the residue
hypothesis of `exists_bound_forall_generatedAt_of_hasRationalResidues` and of
`degree_principal_eq_zero_of_hasRationalResidues`.  For a curve, `Adelic/ResidueField.lean`
supplies the discharged forms of both.

Note that `IsConstantField k X` is **not** used (hence the `omit`): the approximation
statement is about the stalk and the order filtration only.  The constant-field gate is
needed to make the section spaces `k`-subspaces, which this proof never touches. -/
theorem hasRationalResidues_of_isAlgClosed [IsAlgClosed k] (P : X.PrimeDivisor)
    [Algebra k (X.presheaf.stalk P.point)]
    [IsScalarTower k (X.presheaf.stalk P.point) X.functionField]
    [Module.Finite k (IsLocalRing.ResidueField (X.presheaf.stalk P.point))] :
    HasRationalResidues k P := by
  intro f hf
  -- lift `f` to the stalk
  rcases eq_or_ne f 0 with rfl | hf0
  · refine ⟨0, ?_⟩
    rw [map_zero, sub_zero]
    exact (orderGe P 1).zero_mem
  obtain ⟨a, ha⟩ := exists_stalk_lift_of_order_nonneg hf0
    ((mem_orderGe_of_ne_zero hf0).mp hf)
  -- the residue field is trivial over an algebraically closed `k`
  haveI : Algebra.IsIntegral k
      (IsLocalRing.ResidueField (X.presheaf.stalk P.point)) :=
    Algebra.IsIntegral.of_finite k _
  have hbij : Function.Bijective
      (algebraMap k (IsLocalRing.ResidueField (X.presheaf.stalk P.point))) :=
    IsAlgClosed.algebraMap_bijective_of_isIntegral
  obtain ⟨c, hc⟩ := hbij.surjective
    (IsLocalRing.residue (X.presheaf.stalk P.point) a)
  refine ⟨c, ?_⟩
  -- `a - c ∈ 𝔪_P`, so its image has order `≥ 1`
  have hmem : a - algebraMap k (X.presheaf.stalk P.point) c ∈
      IsLocalRing.maximalIdeal (X.presheaf.stalk P.point) := by
    rw [← IsLocalRing.residue_eq_zero_iff, map_sub]
    have hcomp : IsLocalRing.residue (X.presheaf.stalk P.point)
        (algebraMap k (X.presheaf.stalk P.point) c) =
        algebraMap k (IsLocalRing.ResidueField (X.presheaf.stalk P.point)) c := rfl
    rw [hcomp, ← hc, sub_self]
  have himg := (mem_orderGe_one_iff_mem_maximalIdeal P
    (a - algebraMap k (X.presheaf.stalk P.point) c)).mpr hmem
  rw [map_sub, ha] at himg
  -- match the two `k`-algebra maps into `K(X)` through the tower
  rwa [show algebraMap (X.presheaf.stalk P.point) X.functionField
        (algebraMap k (X.presheaf.stalk P.point) c)
      = algebraMap k X.functionField c from
    (IsScalarTower.algebraMap_apply k (X.presheaf.stalk P.point)
      X.functionField c).symm] at himg

end AlgClosed

end Adelic
end AlgebraicGeometry
