/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.RiemannRoch.Adelic.ClassInvariance

/-!
# Adelic Riemann–Roch — the residue-weighted degree and the section-drop bounds

This file supplies two further legs of the campaign's cluster P
(`informal/pic-representability-campaign.md`, P3/P4):

* the **residue-weighted (adelic) degree** `deg_k D = Σ_P D(P)·[κ(P):k]`, which is
  the degree the χ-ledger actually telescopes to (the geometric
  `Scheme.WeilDivisor.degree` is its specialisation at residue degree one, i.e.
  over an algebraically closed base field);
* the **section-drop bounds** `ℓ(D) ≤ ℓ(D + P) ≤ ℓ(D) + [κ(P):k]`;
* **residue-degree positivity** `1 ≤ [κ(P):k]` and its consequence that a nonzero
  effective divisor has *positive* weighted degree.

The drop bounds are **unconditional** — they need neither the ledger's
connecting/surjectivity data nor the strong-approximation input, only the
finite-dimensionality instances.  The `≤` direction of the one-point step is
`localStep_finrank_le` (node N14, already landed) read through the rank–nullity
identity `finrank_localStepDom`; that is precisely the observation that the
*upper* bound of the χ-ledger does not need the residue map to be onto.

## Statements whose ledger input is explicit

The results that genuinely need the closed ledger `χ(D) = χ(0) + deg_k D` take it
as an explicit hypothesis `hledger`, in the same style as the existing
`Adelic.riemann_inequality`.  Nothing here introduces a new gate class, and no
statement is left as a `sorry`.  Under that hypothesis this file derives:

* `degK_principal_eq_zero` — **principal divisors have residue-weighted degree
  zero**, from the class-invariance of `χ` (`ClassInvariance.lean`).  This is the
  adelic form of the open geometric leaf
  `Scheme.WeilDivisor.principal_degree_zero`.
* `degK_eq_degree_of_residueDeg_eq_one` and
  `degree_principal_eq_zero_of_residueDeg_eq_one` — the collapse to the
  **unweighted** degree when every residue degree is one, and the resulting
  unweighted principal-degree-zero statement.  Together these reduce the open leaf
  to the single residue-field fact `[κ(P):k̄] = 1` plus instance plumbing; §4
  records why the `sorry` is nonetheless left in place.
* `ell_eq_zero_of_degK_neg` — `deg_k D < 0 ⟹ ℓ(D) = 0` (campaign P4(a)).
* `degK_add_chi_zero_le_ell` — the Riemann inequality in closed weighted form.

## What is NOT proved here (read this before consuming)

Three distinct gaps in the vanishing story are kept apart deliberately:

1. **Single-field bounded vanishing** — `∃ b, ∀ D, b ≤ deg_k D → h¹(D) = 0`, for
   one fixed base field `k`.  Not proved here and not derivable from the ledger
   alone: it needs a base vanishing `h¹(𝒪(n₀·x₀)) = 0` plus surjectivity of
   `Ȟ¹(D) → Ȟ¹(D')` (the "peel an effective divisor" step).  The sibling project
   proves its analogue (`AJCR RiemannRoch/UniformVanishing.lean`) from an
   FLV-class machine that has no counterpart **on this adelic carrier**.

   **AJC now proves it on a different carrier** (run 0074 r3): on the χ-ledger's
   divisor-sheaf carrier, `Ledger/DegreeVanishing.subsingleton_hModule_one_of_deg_ge`
   gives exactly `deg D ≥ deg D₀ + 1 − χ(𝒪_X) ⟹ H¹(𝒪(D)) = 0` from **one** base
   vanishing, with the peel a theorem rather than a hypothesis
   (`Ledger/SectionDrop`) and no cover chosen at all.  So the "no AJC counterpart"
   remark is true of the *adelic* machinery only, and a reader arriving here wanting
   bounded vanishing should go there.  Nothing transports between the two carriers:
   this file's `ell`/`degK` live on a chosen 2-affine cover, `Ledger`'s
   `Sheaf.h0`/`CurveDivisor.deg` do not.
2. **Extension uniformity** — the *same* `b` for every field extension `κ/k`.
   Strictly more than (1): it needs flat base change of the bound along
   `k → κ`.  Nothing in this file quantifies over extensions.  The predicate itself is written
   down as `Adelic.UniformlyBoundedVanishing` (`Adelic/ResidueField.lean` §5), so this gap is
   statable and open rather than unformulable.
3. **Global generation** — `𝒪(D)` generated by global sections above the bound.
   Strictly more than (1): it needs `h¹(D − x) = 0` at every closed point, i.e. the
   bound raised by the maximum residue degree.  Not addressed *in this file*, but
   proved in `Adelic/GlobalGeneration.lean` from the same inputs as (1); it is the
   equality case of this file's own drop bound `ell_le_ell_add_residueDeg`.  It is
   **not** more than (2): global generation and extension uniformity are independent,
   and (2) remains open.

## Provenance

The residue-weighted degree, the drop bound and the `deg < 0 ⟹ ℓ = 0` corollary
are **rederived in the AJC adelic abstractions**; they are not ports.  The
sibling `AJCR RiemannRoch/SectionBound.lean` / `Degree.lean` prove related
statements on the `CurveDivisor`/`divisorSheaf` substrate, whose names do not
exist in this project.  The argument reused from AJCR is the χ-transport step of
`deg_divOf`; its AJC counterpart is `chi_eq_of_principal_shift`.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits IsDedekindDomain
open scoped WithZero

namespace AlgebraicGeometry
namespace Adelic

/-! ## §1. The residue-weighted (adelic) degree -/

section DegK

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **The residue-weighted degree homomorphism `deg_k : Div(X) →+ ℤ`.**
`deg_k D = Σ_P D(P)·[κ(P):k]`, the degree the χ-ledger telescopes to
(`chi_telescope_list`).  Bundled as an `AddMonoidHom` through
`Finsupp.liftAddHom`, exactly as the unweighted `Scheme.WeilDivisor.degree_hom`
is, so additivity, `deg_k 0 = 0` and `deg_k (-D) = -deg_k D` come for free.

Over an algebraically closed base field every closed point of a smooth curve has
`[κ(P):k] = 1` and this is the geometric degree; over a general `k` the weighting
is what makes the degree a linear-equivalence invariant. -/
noncomputable def degKHom : X.WeilDivisor →+ ℤ :=
  Finsupp.liftAddHom (fun P : X.PrimeDivisor =>
    (AddMonoidHom.mulRight ((residueDeg k P : ℤ)) : ℤ →+ ℤ))

/-- **The residue-weighted degree of a Weil divisor.** -/
noncomputable def degK (D : X.WeilDivisor) : ℤ := degKHom k D

theorem degK_eq_sum (D : X.WeilDivisor) :
    degK k D = (show X.PrimeDivisor →₀ ℤ from D).sum
      (fun P n => n * (residueDeg k P : ℤ)) :=
  Finsupp.liftAddHom_apply (α := X.PrimeDivisor) (M := ℤ) (N := ℤ) _ _

@[simp] theorem degK_zero : degK k (0 : X.WeilDivisor) = 0 := map_zero _

theorem degK_add (D D' : X.WeilDivisor) :
    degK k (D + D') = degK k D + degK k D' := map_add _ _ _

@[simp] theorem degK_neg (D : X.WeilDivisor) : degK k (-D) = -degK k D :=
  map_neg _ _

theorem degK_sub (D D' : X.WeilDivisor) :
    degK k (D - D') = degK k D - degK k D' := map_sub _ _ _

/-- **The one-point divisor has weighted degree the residue degree.** -/
@[simp] theorem degK_pointDivisor (P : X.PrimeDivisor) :
    degK k (pointDivisor P : X.WeilDivisor) = (residueDeg k P : ℤ) := by
  rw [degK_eq_sum, pointDivisor]
  exact (Finsupp.sum_single_index (by simp)).trans (one_mul _)

/-- **The weighted degree of a list-effective divisor is the sum of the residue
degrees** — the numerical companion of `chi_telescope_list`. -/
theorem degK_divisorOfList (L : List X.PrimeDivisor) :
    degK k (divisorOfList L : X.WeilDivisor) = ((L.map (residueDeg k)).sum : ℤ) := by
  induction L with
  | nil => simp [divisorOfList]
  | cons P L ih =>
    rw [divisorOfList, degK_add, degK_pointDivisor, ih, List.map_cons, List.sum_cons]
    push_cast
    ring

/-- **An effective divisor has nonnegative weighted degree.**  Each summand
`D(P)·[κ(P):k]` is a product of nonnegative integers. -/
theorem degK_nonneg_of_nonneg {D : X.WeilDivisor}
    (hD : ∀ P : X.PrimeDivisor, 0 ≤ (show X.PrimeDivisor →₀ ℤ from D) P) :
    0 ≤ degK k D := by
  rw [degK_eq_sum, Finsupp.sum]
  exact Finset.sum_nonneg fun P _ =>
    mul_nonneg (hD P) (Int.natCast_nonneg _)

/-- **The residue field is nontrivial**: `1 ∈ orderGe P 0` but `1 ∉ orderGe P 1`,
since `ord_P 1 = 0`.  So the one-step valuation quotient
`localStepTgt k P 1 = orderGe P 0 ⧸ orderGe P 1` — the residue field `κ(P)` — is
not the zero space. -/
theorem nontrivial_localStepTgt_one (P : X.PrimeDivisor) :
    Nontrivial (localStepTgt k P 1) := by
  have hone : (1 : X.functionField) ∈ orderGeSub k P (1 - 1) := by
    rw [mem_orderGeSub]
    exact Or.inr (by rw [Scheme.RationalMap.order_one]; norm_num)
  refine ⟨Submodule.Quotient.mk ⟨1, hone⟩, 0, ?_⟩
  intro h
  rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_comap, Submodule.subtype_apply,
    mem_orderGeSub] at h
  rcases h with h0 | h0
  · exact one_ne_zero h0
  · rw [Scheme.RationalMap.order_one] at h0
    norm_num at h0

/-- **The residue degree is positive**: `1 ≤ [κ(P):k]`.  From the nontriviality of
`κ(P)` (`nontrivial_localStepTgt_one`) plus finite-dimensionality — a nontrivial
finite-dimensional space has positive rank.  Needed wherever a *nonzero* effective
divisor must be given *positive* degree. -/
theorem one_le_residueDeg (P : X.PrimeDivisor)
    [Module.Finite k (localStepTgt k P 1)] : 1 ≤ residueDeg k P := by
  haveI := nontrivial_localStepTgt_one k P
  rw [residueDeg, Nat.one_le_iff_ne_zero]
  intro h
  exact (not_subsingleton (localStepTgt k P 1))
    ((Module.finrank_zero_iff (R := k)).mp h)

/-- **A nonzero effective divisor has positive weighted degree.**  Some coefficient
`D(P₀)` is `≥ 1` (it is nonzero and `≥ 0`) and contributes `D(P₀)·[κ(P₀):k] ≥ 1`
by `one_le_residueDeg`, while every other summand is `≥ 0`.

This is the adelic counterpart of the sibling project's
`CurveDivisor.deg_pos_of_nonneg_of_ne_zero`; the argument is the standard one, but
the residue-degree positivity input (`one_le_residueDeg`) is proved here from the
project's own `orderGe` filtration rather than from a residue-field API. -/
theorem degK_pos_of_nonneg_of_ne_zero {D : X.WeilDivisor}
    (hD : ∀ P : X.PrimeDivisor, 0 ≤ (show X.PrimeDivisor →₀ ℤ from D) P)
    (hne : D ≠ 0)
    [∀ P : X.PrimeDivisor, Module.Finite k (localStepTgt k P 1)] :
    0 < degK k D := by
  classical
  -- some coefficient is nonzero, hence ≥ 1
  obtain ⟨P₀, hP₀⟩ : ∃ P₀ : X.PrimeDivisor,
      (show X.PrimeDivisor →₀ ℤ from D) P₀ ≠ 0 := by
    by_contra hno
    push Not at hno
    exact hne (Finsupp.ext hno)
  have hP₀supp : P₀ ∈ (show X.PrimeDivisor →₀ ℤ from D).support :=
    Finsupp.mem_support_iff.mpr hP₀
  rw [degK_eq_sum, Finsupp.sum, ← Finset.sum_erase_add _ _ hP₀supp]
  have hrest : 0 ≤ ∑ P ∈ (show X.PrimeDivisor →₀ ℤ from D).support.erase P₀,
      (show X.PrimeDivisor →₀ ℤ from D) P * (residueDeg k P : ℤ) :=
    Finset.sum_nonneg fun P _ => mul_nonneg (hD P) (Int.natCast_nonneg _)
  have hlast : 0 < (show X.PrimeDivisor →₀ ℤ from D) P₀ * (residueDeg k P₀ : ℤ) := by
    have h1 : 1 ≤ (show X.PrimeDivisor →₀ ℤ from D) P₀ := by
      have := hD P₀; omega
    have h2 : (1 : ℤ) ≤ (residueDeg k P₀ : ℤ) := by
      exact_mod_cast one_le_residueDeg k P₀
    calc (0 : ℤ) < 1 * 1 := by norm_num
      _ ≤ (show X.PrimeDivisor →₀ ℤ from D) P₀ * (residueDeg k P₀ : ℤ) :=
          mul_le_mul h1 h2 (by norm_num) (by linarith)
  linarith

/-- **The weighted degree agrees with the geometric degree when every residue
degree is one.**  `deg_k D = Σ_P D(P)·[κ(P):k]` collapses to
`Σ_P D(P) = Scheme.WeilDivisor.degree D` as soon as `[κ(P):k] = 1` at every prime
divisor in the support — which is the case over an algebraically closed base
field, every closed point of a smooth curve then having residue field `k` itself.

This is the **only** thing separating the adelic `degK_principal_eq_zero` from the
geometric leaf `Scheme.WeilDivisor.principal_degree_zero`; see §4.  The hypothesis
is stated pointwise on the support rather than globally so that a caller can
discharge it where it is actually needed. -/
theorem degK_eq_degree_of_residueDeg_eq_one {D : X.WeilDivisor}
    (h1 : ∀ P ∈ (show X.PrimeDivisor →₀ ℤ from D).support, residueDeg k P = 1) :
    degK k D = Scheme.WeilDivisor.degree D := by
  rw [degK_eq_sum, Scheme.WeilDivisor.degree, Finsupp.sum, Finsupp.sum]
  refine Finset.sum_congr rfl fun P hP => ?_
  rw [h1 P hP]
  simp

end DegK

/-! ## §2. The section-drop bounds (unconditional)

For a one-point twist `D' = D + P` the local step space
`Γ(⊤,𝒪(D'))/Γ(⊤,𝒪(D))` has dimension `ℓ(D') − ℓ(D)` (rank–nullity,
`finrank_localStepDom`) and dimension at most `[κ(P):k]` (node N14,
`localStep_finrank_le` applied at `U = ⊤`).  Both facts are already in the
project; combining them gives the classical section-drop sandwich
`ℓ(D) ≤ ℓ(D + P) ≤ ℓ(D) + [κ(P):k]` with **no** ledger exactness hypothesis and
**no** strong-approximation input — those are needed only for the `h¹` half of the
ledger, not for the `ℓ` half. -/

section Drops

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X]

/-- **`ℓ` is monotone in the divisor.**  `D ≤ D'` pointwise gives
`Γ(⊤,𝒪(D)) ⊆ Γ(⊤,𝒪(D'))`, hence `ℓ(D) ≤ ℓ(D')`. -/
theorem ell_mono {D D' : X.WeilDivisor}
    (hDD' : ∀ P : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D) P ≤
      (show X.PrimeDivisor →₀ ℤ from D') P)
    [Module.Finite k (sectionSub k ⊤ D')] :
    ell k D ≤ ell k D' :=
  Submodule.finrank_mono (sectionSub_mono k ⊤ hDD')

/-- **The one-point section-drop bound (unconditional).**  For a one-point twist
`D' = D + P`,
`ℓ(D) ≤ ℓ(D') ≤ ℓ(D) + [κ(P):k]`.

The upper bound is node N14 (`localStep_finrank_le` at `U = ⊤`) read through
rank–nullity (`finrank_localStepDom`); the lower bound is `ell_mono`.  Neither
half consumes the ledger's connecting/surjectivity data. -/
theorem ell_le_ell_add_residueDeg {D D' : X.WeilDivisor} {P : X.PrimeDivisor}
    (hstep : (show X.PrimeDivisor →₀ ℤ from D') P =
      (show X.PrimeDivisor →₀ ℤ from D) P + 1)
    (hle : ∀ Q : X.PrimeDivisor, (show X.PrimeDivisor →₀ ℤ from D) Q ≤
      (show X.PrimeDivisor →₀ ℤ from D') Q)
    (hoff : ∀ Q : X.PrimeDivisor, Q ≠ P →
      (show X.PrimeDivisor →₀ ℤ from D) Q = (show X.PrimeDivisor →₀ ℤ from D') Q)
    [Module.Finite k (sectionSub k ⊤ D')]
    [Module.Finite k (localStepTgt k P 1)] :
    ell k D ≤ ell k D' ∧ (ell k D' : ℤ) ≤ ell k D + residueDeg k P := by
  refine ⟨ell_mono k hle, ?_⟩
  have hrn := finrank_localStepDom k ⊤ (sectionSub_mono k ⊤ hle)
  have hN14 := localStep_finrank_le k (TopologicalSpace.Opens.mem_top P.point)
    hstep hle hoff
  have hcast : (Module.finrank k (localStepDom k ⊤ D D') : ℤ) ≤ (residueDeg k P : ℤ) := by
    exact_mod_cast hN14
  simp only [ell] at *
  omega

/-- **The one-point drop bound in `pointDivisor` spelling.**  For the concrete
twist `D' = 1·P + D` the three coordinate hypotheses of
`ell_le_ell_add_residueDeg` are discharged by the `pointDivisor` calculus of the
χ-ledger, leaving the clean statement
`ℓ(D) ≤ ℓ(P + D) ≤ ℓ(D) + [κ(P):k]`. -/
theorem ell_add_pointDivisor_le (D : X.WeilDivisor) (P : X.PrimeDivisor)
    [Module.Finite k (sectionSub k ⊤ (pointDivisor P + D))]
    [Module.Finite k (localStepTgt k P 1)] :
    ell k D ≤ ell k (pointDivisor P + D) ∧
      (ell k (pointDivisor P + D) : ℤ) ≤ ell k D + residueDeg k P :=
  ell_le_ell_add_residueDeg k (add_pointDivisor_apply_self D P)
    (le_add_pointDivisor D P)
    (fun _ hQ => (add_pointDivisor_apply_of_ne D hQ).symm)

end Drops

/-! ## §3. Consequences of the closed ledger

The **closed ledger** is the identity `χ(D) = χ(0) + deg_k D` for every Weil
divisor `D`.  The statements below take it as an explicit hypothesis

`hledger : ∀ D, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D`.

**Status update — it is now a theorem.**  An earlier version of this paragraph said "in this
project it is not a theorem", and that the extension from effective divisors to all divisors
needed the negative part.  `Adelic/LedgerClosure.chi_eq_of_bump` proves the closed ledger at
**every** Weil divisor from the one-point bump `hbump` alone, so the hypothesis below is
discharged wherever the bump is available.  The theorems here are kept in `hledger` form —
they are strictly more general, and the `hbump` forms are in `LedgerClosure.lean` §2 — but a
reader should not take the hypothesis as a record of an open gap.

What the bump costs is NOT merely one application of `chi_add_eq_residueDeg` per step: that theorem
requires `P.point ∈ U₀ ⊓ U₁`, so off the overlap it supplies no route to the bump at all.
Worse: `ChiUnconditional.not_bump_of_notMem_left` proves `hbump` outright **false**, and
`ChiUnconditional.ledger_refuted_of_notMem_left` the same for `hledger`, whenever a prime
divisor's point lies off a chart of a **genuine cover** (`U₀ ⊔ U₁ = ⊤`) whose three chart section
spaces are all finite-dimensional.  Under those side conditions the hypothesis of every theorem
in this section is unsatisfiable and the theorems are vacuous.  Note the side conditions are
extra — this section quantifies over arbitrary `U₀ U₁` and assumes finiteness only at `⊤` — so
this is a warning about which covers are usable, not a blanket vacuity claim.  At overlap primes
the bump is one
application of `chi_add_eq_residueDeg`, consuming that theorem's connecting/surjectivity data
plus the strong-approximation input `hsurj`.  So `hledger` is an honest hypothesis, not
a gate class and not a `sorry` — but the reader should look for the remaining mathematics
under the *bump*, not under the ledger. -/

section Ledger

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsLocallyNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **The ledger holds on list-effective divisors, given the one-point bump.**
`chi_telescope_list` computes `χ(Σ_{P ∈ L} P)` as `χ(0) + Σ_{P ∈ L} deg P`, and
`degK_divisorOfList` computes `deg_k` of the same divisor as the same sum, so the
two agree: `χ(D) = χ(0) + deg_k D` for `D = divisorOfList L`.

This is what pins `degK` as *the* degree of the ledger rather than one weighting
among several.  It used to be offered here as evidence that the `hledger` hypothesis of this
section "is not idle", on the grounds that it holds wherever the one-point bump `hbump` does.
**That reading is withdrawn.**  `hbump` is one application of `chi_add_eq_residueDeg` per step
**at overlap primes only**, and off the overlap that producer is unavailable; worse,
`ChiUnconditional.ledger_refuted_of_notMem_left` shows `hledger` is **false** on a genuine cover
(`U₀ ⊔ U₁ = ⊤`) with finite-dimensional chart sections having a prime divisor off a chart.  So
this identity is no evidence that `hledger` is satisfiable: on such a cover it is not, and this
section's conditionals are vacuous there.  Exhibiting a cover on which the ledger *can* hold is
the missing work, and it is a question about the cover, not about the bump.

An earlier version added that "extending from list-effective divisors to *all* divisors
additionally needs the negative part".  **That is false**: `LedgerClosure.chi_eq_of_bump`
gets all divisors from the same `hbump`, because `hbump` admits an arbitrary base divisor and
so the telescope need not start at `0`.  What `hbump` still costs is unchanged — the ledger's
connecting/surjectivity data plus the strong-approximation input. -/
theorem chi_divisorOfList_eq_degK (L : List X.PrimeDivisor)
    (hbump : ∀ (P : X.PrimeDivisor) (E : X.WeilDivisor),
      chi k U₀ U₁ (pointDivisor P + E) = chi k U₀ U₁ E + residueDeg k P) :
    chi k U₀ U₁ (divisorOfList L) =
      chi k U₀ U₁ 0 + degK k (divisorOfList L : X.WeilDivisor) := by
  rw [chi_telescope_list k U₀ U₁ L hbump, degK_divisorOfList]

/-- **The Riemann inequality in closed weighted form.**  Given the closed ledger,
`deg_k D + χ(0) ≤ ℓ(D)` for every `D` — the `h¹ ≥ 0` half applied to the
telescoped Euler characteristic.  (This is `Adelic.riemann_inequality` with its
`htel` hypothesis supplied from the ledger and the degree pinned to the
residue-weighted `deg_k`.) -/
theorem degK_add_chi_zero_le_ell
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    (D : X.WeilDivisor) :
    degK k D + chi k U₀ U₁ 0 ≤ (ell k D : ℤ) :=
  riemann_inequality k U₀ U₁ (hledger D)

end Ledger

section LedgerNoetherian

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **`deg_k D < 0 ⟹ ℓ(D) = 0`** (campaign P4(a)).  Given the closed ledger: a
nonzero `f ∈ L(D)` would make `D` linearly equivalent to an effective divisor
`E = D + div f` (`exists_effective_linearEquiv_of_ne_zero_mem`); `χ` is a
class invariant (`chi_eq_of_linearEquivalence`), so the ledger forces
`deg_k E = deg_k D < 0`, contradicting `deg_k E ≥ 0` for effective `E`
(`degK_nonneg_of_nonneg`).

Note the shape: the hypothesis is on `deg_k`, the *weighted* degree, and the
argument runs entirely through the class-invariance of `χ` — no vanishing input,
no duality. -/
theorem ell_eq_zero_of_degK_neg
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {D : X.WeilDivisor} (hdeg : degK k D < 0)
    [Module.Finite k (sectionSub k ⊤ D)] :
    ell k D = 0 := by
  by_contra hne
  -- a nonzero section exists
  obtain ⟨f, hfmem, hfne⟩ : ∃ f : X.functionField, f ∈ sectionSub k ⊤ D ∧ f ≠ 0 := by
    by_contra hno
    have hbot : sectionSub k ⊤ D = ⊥ := by
      apply le_antisymm _ bot_le
      intro x hx
      rcases eq_or_ne x 0 with rfl | hx0
      · exact Submodule.zero_mem _
      · exact absurd ⟨x, hx, hx0⟩ hno
    rw [ell, hbot] at hne
    simp at hne
  obtain ⟨E, hEnonneg, hEclass⟩ :=
    exists_effective_linearEquiv_of_ne_zero_mem hfne hfmem
  have hchi := chi_eq_of_linearEquivalence k U₀ U₁ hEclass
  rw [hledger E, hledger D] at hchi
  have : degK k E = degK k D := by omega
  have hEpos := degK_nonneg_of_nonneg k hEnonneg
  omega

/-- **Principal divisors have residue-weighted degree zero** — the adelic
counterpart of the geometric statement `Scheme.WeilDivisor.principal_degree_zero`.

Given the closed ledger, this is a two-line consequence of the class-invariance of
`χ` proved in `ClassInvariance.lean`: `0 − div g` is in the class of `0`, so
`χ(0 − div g) = χ(0)`, and the ledger reads off
`deg_k (0 − div g) = 0`, i.e. `deg_k (div g) = 0`.

This is the *weighted* statement.  It does **not** close the open geometric leaf
`principal_degree_zero`, which asserts the same for the unweighted degree
`Σ_P ord_P g`; see §4. -/
theorem degK_principal_eq_zero
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {g : X.functionField} (hg : g ≠ 0) :
    degK k (Scheme.WeilDivisor.principal g hg) = 0 := by
  have hchi := chi_eq_of_principal_shift k U₀ U₁ (0 : X.WeilDivisor) hg
  rw [hledger ((0 : X.WeilDivisor) - Scheme.WeilDivisor.principal g hg),
    hledger (0 : X.WeilDivisor), degK_sub, degK_zero] at hchi
  omega

/-- **`deg_k` descends to linear-equivalence classes.**  Given the closed ledger,
linearly equivalent divisors have equal weighted degree — the well-definedness
statement the Picard route consumes when it needs "the degree of a class". -/
theorem degK_eq_of_linearEquivalence
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {D D' : X.WeilDivisor} (h : Scheme.WeilDivisor.LinearEquivalence D D') :
    degK k D = degK k D' := by
  have hchi := chi_eq_of_linearEquivalence k U₀ U₁ h
  rw [hledger D, hledger D'] at hchi
  omega

end LedgerNoetherian

section GeometricDegree

variable (k : Type u) [Field k] {X : Scheme.{u}} [IsIntegral X]
    [IsNoetherian X] [Scheme.IsRegularInCodimensionOne X]
    [Algebra k X.functionField] [IsConstantField k X] (U₀ U₁ : X.Opens)

/-- **The geometric principal-degree-zero statement, reduced to residue degree
one.**  `Σ_P ord_P(g) = 0` follows from the closed ledger together with
`[κ(P):k] = 1` on the support of `div g`.

This makes the reduction of the open leaf `Scheme.WeilDivisor.principal_degree_zero`
machine-checked rather than merely asserted: the *whole* remaining content of that
leaf, given the ledger, is the residue-degree-one fact for a smooth proper curve
over an algebraically closed field.  It is stated here on the adelic hypotheses
(`Algebra k K(X)`, `IsConstantField`, a 2-affine cover, the ledger) rather than on
the leaf's own geometric hypotheses, which is why it does not literally close that
`sorry` — the missing step is instantiating these hypotheses from
`[IsProper] [SmoothOfRelativeDimension 1] [GeometricallyIrreducible]` over `k̄`,
together with `residueDeg k̄ P = 1`. -/
theorem degree_principal_eq_zero_of_residueDeg_eq_one
    (hledger : ∀ D : X.WeilDivisor, chi k U₀ U₁ D = chi k U₀ U₁ 0 + degK k D)
    {g : X.functionField} (hg : g ≠ 0)
    (h1 : ∀ P ∈ (show X.PrimeDivisor →₀ ℤ from
      Scheme.WeilDivisor.principal g hg).support, residueDeg k P = 1) :
    Scheme.WeilDivisor.degree (Scheme.WeilDivisor.principal g hg) = 0 := by
  rw [← degK_eq_degree_of_residueDeg_eq_one k h1]
  exact degK_principal_eq_zero k U₀ U₁ hledger hg

end GeometricDegree

/-! ## §4. `degK_principal_eq_zero` versus the geometric `principal_degree_zero`

`degK_principal_eq_zero` above and the open leaf
`Scheme.WeilDivisor.principal_degree_zero` are **different statements**, and the
first does not imply the second.  Recorded here because the difference is easy to
misread as a formality.

* `degK_principal_eq_zero` concerns `deg_k (div g) = Σ_P ord_P(g)·[κ(P):k]`.  Its
  proof is the χ-transport of `ClassInvariance.lean` plus the closed ledger, and
  it is stated over an **arbitrary** base field of constants `k`.
* `principal_degree_zero` concerns the **unweighted** `Σ_P ord_P(g)`, and is
  stated on a smooth proper curve over an algebraically **closed** `k̄` with no
  field of constants in sight and no ledger hypothesis.

Over `k̄` the two degrees coincide because every closed point of a smooth curve has
residue field `k̄`, i.e. `[κ(P):k̄] = 1`.  That collapse is
`degK_eq_degree_of_residueDeg_eq_one`, and composing it with
`degK_principal_eq_zero` gives `degree_principal_eq_zero_of_residueDeg_eq_one`:
the **unweighted** statement, proved, from the ledger plus residue-degree-one.

So the reduction is machine-checked, and the residue of the open leaf is now **one** item,
not two.  Item 1 below is closed; item 2 is what remains.

1. `residueDeg k̄ P = 1` — **DISCHARGED**, in `Adelic/ResidueField.lean`
   (`residueDeg_eq_one_of_isAlgClosed_curve`), for a prime divisor of a curve
   `C : Over (Spec k̄)` with `k̄` algebraically closed, under
   `[IsIntegral] [IsLocallyNoetherian] [IsRegularInCodimensionOne] [LocallyOfFiniteType]`
   and `[SmoothOfRelativeDimension 1]` — all of which the project's headline curve already
   carries, `LocallyOfFiniteType` because mathlib's `IsProper` extends it structurally.

   (An earlier version of this sentence said `LocallyOfFiniteType` "synthesizes from
   smoothness".  **That is false in the relevant import closure**: the
   `SmoothOfRelativeDimension 1 → Smooth` bridge lives in
   `AlgebraicJacobian/Curve/GeometricallyReduced.lean`, which `Adelic/ResidueField.lean` does
   not import, and `infer_instance` for `LocallyOfFiniteType` from smoothness alone fails
   there — machine-checked.  From `[IsProper]` it succeeds.  The applicability conclusion is
   unchanged, because `principal_degree_zero` and every other real consumer carries
   `[IsProper]`; only the stated reason was wrong.)

   Two earlier descriptions of this item are now history.  It was first an informal remark;
   then §5–§7 of `Adelic/GlobalGeneration.lean` made it a machine-checked *equivalence* to a
   first-order approximation statement plus a derivation of that statement from three
   stalk-level binders, and this paragraph correctly recorded that AJC constructs none of
   them, the last (`Module.Finite k κ_P`) being effectively a new gate.  The discharge did
   not build that gate: mathlib's `AlgebraicGeometry.residueFieldIsoBase` gets the
   integrality it needs from `LocallyOfFiniteType` through the Jacobson-space criterion, so
   the residue-finiteness binder is **avoided**, not supplied.  What did have to be built is
   the compatibility of the stalk `k`-algebra with this lane's `Algebra k K(X)`
   (`Adelic.algebraMap_stalk_functionField`) — without it a stalk-level argument cannot be
   read in the order language at all.
2. The instance plumbing that places `principal_degree_zero`'s own geometric
   hypotheses in adelic shape: an `Algebra k̄ K(C)` with `IsConstantField k̄ C.left`
   (available — `Adelic/GateInstances.lean`), a 2-affine cover, and **the closed ledger for
   that cover**.

   The ledger is no longer the substantive part: `LedgerClosure.chi_eq_of_bump` proves it from
   the one-point bump alone, so what item 2 now requires is the **bump** for a cover of `C`,
   i.e., at overlap primes, one application of `chi_add_eq_residueDeg` per step — which
   still consumes the ledger exact sequence's connecting/surjectivity data and the
   strong-approximation input `hsurj`.
   The leaf therefore remains open, but the open input has moved from a global identity over
   all divisors to a one-point local statement.  The assembled statement is now sharper:
   `Adelic.degree_principal_eq_zero_of_isAlgClosed_curve` proves the **unweighted**
   `deg (div g) = 0` on curve hypotheses from **the ledger alone** — the residue input is no
   longer a second hypothesis — and `Adelic.degK_eq_degree_of_isAlgClosed_curve` gives
   `deg_k = deg` with no open input whatsoever.  The ledger itself holds at **every** Weil
   divisor from the one-point bump (`Adelic/LedgerClosure.chi_eq_of_bump`) — this sentence
   previously said "on the whole *effective* cone", which was the stale claim this very item was
   correcting, left standing inside the correction.

The `sorry` in `WeilDivisor.lean` is deliberately **left in place**.  Replacing it
with a call to `degree_principal_eq_zero_of_residueDeg_eq_one` would require
producing the bump (equivalently, by `LedgerClosure.chi_eq_of_bump`, the ledger) for a cover
of `C`, and the bump is not yet a theorem here — so the substitution would move the gap
rather than close it, while making a theorem whose statement mentions no hypotheses depend
silently on one.  The Hartshorne II.6.10 route sketched in that docstring (build
`φ : C → ℙ¹` from `g`, use multiplicativity of degree under finite pullback) is a
*different*, heavier proof; the ledger route above is the cheaper one and is what
the campaign's P3 milestone anticipated. -/

end Adelic
end AlgebraicGeometry
