/-
Copyright (c) 2026 The AlgebraicJacobian Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Descent.TensorProductPushoutBaseChange
import AlgebraicJacobian.Descent.TensorProductFieldTowerMap

/-!
# Explicit data for tensor-product pushouts

`TensorProductPushoutBaseChange` proves the algebraic comparison between a scalar extension
of a tensor-product pushout and the tensor product of the scalar extensions.  Its result types
contain locally generated `Algebra` instances.  This file gives those instances names and keeps
them in a small data record.  The map entry points below therefore have stable dependent types:
the two `Algebra` witnesses are installed explicitly before the old comparison theorem is
invoked.

The record is intentionally data rather than a typeclass.  A caller can carry several tensor
pushouts over the same rings without asking instance search to choose between their dependent
presentations.
-/

set_option autoImplicit false

open scoped TensorProduct

universe u

namespace AlgebraicJacobian

noncomputable section

section Carriers

variable {M K A B₁ B₂ : Type u}
variable [CommRing M] [CommRing K] [CommRing A] [CommRing B₁] [CommRing B₂]
variable [Algebra M K] [Algebra M A]
variable [Algebra A B₁] [Algebra A B₂]
variable [Algebra M B₁] [Algebra M B₂]
variable [IsScalarTower M A B₁] [IsScalarTower M A B₂]

/-! ### Named carriers -/

/-- The scalar-extension base carrier `K ⊗[M] A`. -/
abbrev tensorProductPushoutBaseCarrier
    (M K A : Type u) [CommRing M] [CommRing K] [CommRing A]
    [Algebra M K] [Algebra M A] : Type u := K ⊗[M] A

/-- The left scalar-extension carrier `K ⊗[M] B₁`. -/
abbrev tensorProductPushoutLeftCarrier
    (M K B₁ : Type u) [CommRing M] [CommRing K] [CommRing B₁]
    [Algebra M K] [Algebra M B₁] : Type u := K ⊗[M] B₁

/-- The right scalar-extension carrier `K ⊗[M] B₂`. -/
abbrev tensorProductPushoutRightCarrier
    (M K B₂ : Type u) [CommRing M] [CommRing K] [CommRing B₂]
    [Algebra M K] [Algebra M B₂] : Type u := K ⊗[M] B₂

/-- The scalar extension of the original pushout. -/
abbrev tensorProductPushoutSourceCarrier
    (M K A B₁ B₂ : Type u)
    [CommRing M] [CommRing K] [CommRing A] [CommRing B₁] [CommRing B₂]
    [Algebra M K] [Algebra M A]
    [Algebra A B₁] [Algebra A B₂]
    [Algebra M B₁] [Algebra M B₂]
    [IsScalarTower M A B₁] [IsScalarTower M A B₂] : Type u :=
  K ⊗[M] (B₁ ⊗[A] B₂)

/-- The target tensor product, with its two base-algebra witnesses supplied explicitly. -/
abbrev tensorProductPushoutTargetCarrier
    (M K A B₁ B₂ : Type u)
    [CommRing M] [CommRing K] [CommRing A] [CommRing B₁] [CommRing B₂]
    [Algebra M K] [Algebra M A]
    [Algebra A B₁] [Algebra A B₂]
    [Algebra M B₁] [Algebra M B₂]
    [IsScalarTower M A B₁] [IsScalarTower M A B₂]
    (leftAlgebra : Algebra (K ⊗[M] A) (K ⊗[M] B₁))
    (rightAlgebra : Algebra (K ⊗[M] A) (K ⊗[M] B₂)) : Type u :=
  letI := leftAlgebra
  letI := rightAlgebra
  (K ⊗[M] B₁) ⊗[K ⊗[M] A] (K ⊗[M] B₂)

/-! ### Pinned algebra witnesses -/

/-- The `Algebra (K ⊗[M] A) (K ⊗[M] B₁)` generated by the canonical scalar-extension map. -/
@[reducible] noncomputable def tensorProductPushoutLeftAlgebra :
    Algebra (K ⊗[M] A) (K ⊗[M] B₁) :=
  (scalarExtensionMap (M := M) (K := K) (A := A) (B := B₁)).toRingHom.toAlgebra

/-- The `Algebra (K ⊗[M] A) (K ⊗[M] B₂)` generated by the canonical scalar-extension map. -/
@[reducible] noncomputable def tensorProductPushoutRightAlgebra :
    Algebra (K ⊗[M] A) (K ⊗[M] B₂) :=
  (scalarExtensionMap (M := M) (K := K) (A := A) (B := B₂)).toRingHom.toAlgebra

/-- Carriers and all algebra witnesses used by a scalar-extended pushout. -/
structure TensorProductPushoutCarriers
    (M K A B₁ B₂ : Type u)
    [CommRing M] [CommRing K] [CommRing A] [CommRing B₁] [CommRing B₂]
    [Algebra M K] [Algebra M A]
    [Algebra A B₁] [Algebra A B₂]
    [Algebra M B₁] [Algebra M B₂]
    [IsScalarTower M A B₁] [IsScalarTower M A B₂] where
  /-- The canonical map from the scalar-extended base to the left factor. -/
  leftMap : tensorProductPushoutBaseCarrier M K A →ₐ[K]
    tensorProductPushoutLeftCarrier M K B₁
  /-- The canonical map from the scalar-extended base to the right factor. -/
  rightMap : tensorProductPushoutBaseCarrier M K A →ₐ[K]
    tensorProductPushoutRightCarrier M K B₂
  /-- The selected algebra structure on the left factor. -/
  leftAlgebra : Algebra (K ⊗[M] A) (K ⊗[M] B₁)
  /-- The selected algebra structure on the right factor. -/
  rightAlgebra : Algebra (K ⊗[M] A) (K ⊗[M] B₂)
  /-- The left map is the canonical scalar-extension map. -/
  leftMap_spec : leftMap = scalarExtensionMap (M := M) (K := K) (A := A) (B := B₁)
  /-- The right map is the canonical scalar-extension map. -/
  rightMap_spec : rightMap = scalarExtensionMap (M := M) (K := K) (A := A) (B := B₂)
  /-- The left algebra witness is generated by the selected left map. -/
  leftAlgebra_spec : leftAlgebra = leftMap.toRingHom.toAlgebra
  /-- The right algebra witness is generated by the selected right map. -/
  rightAlgebra_spec : rightAlgebra = rightMap.toRingHom.toAlgebra
  /-- The scalar tower on the left scalar extension. -/
  leftTower :
    letI := leftAlgebra
    IsScalarTower K (K ⊗[M] A) (K ⊗[M] B₁)
  /-- The scalar tower on the right scalar extension. -/
  rightTower :
    letI := rightAlgebra
    IsScalarTower K (K ⊗[M] A) (K ⊗[M] B₂)

/-- The canonical carrier package. -/
noncomputable def tensorProductPushoutCarriers :
    TensorProductPushoutCarriers M K A B₁ B₂ :=
  { leftMap := scalarExtensionMap (M := M) (K := K) (A := A) (B := B₁)
    rightMap := scalarExtensionMap (M := M) (K := K) (A := A) (B := B₂)
    leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    leftMap_spec := rfl
    rightMap_spec := rfl
    leftAlgebra_spec := rfl
    rightAlgebra_spec := rfl
    leftTower := by
      let f₁ := scalarExtensionMap (M := M) (K := K) (A := A) (B := B₁)
      letI : Algebra (K ⊗[M] A) (K ⊗[M] B₁) := f₁.toRingHom.toAlgebra
      infer_instance
    rightTower := by
      let f₂ := scalarExtensionMap (M := M) (K := K) (A := A) (B := B₂)
      letI : Algebra (K ⊗[M] A) (K ⊗[M] B₂) := f₂.toRingHom.toAlgebra
      infer_instance }

/-- The target carrier selected by a carrier package. -/
abbrev TensorProductPushoutCarriers.target
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) : Type u :=
  tensorProductPushoutTargetCarrier M K A B₁ B₂ C.leftAlgebra C.rightAlgebra

end Carriers

section PinnedMaps

variable {M K A B₁ B₂ : Type u}
variable [CommRing M] [CommRing K] [CommRing A] [CommRing B₁] [CommRing B₂]
variable [Algebra M K] [Algebra M A]
variable [Algebra A B₁] [Algebra A B₂]
variable [Algebra M B₁] [Algebra M B₂]
variable [IsScalarTower M A B₁] [IsScalarTower M A B₂]

/-! ### Pinned map entry points -/

/-- The forward map with its two generated tensor-product algebra witnesses pinned. -/
noncomputable def tensorProductPushoutBaseChangeHomPinned :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutSourceCarrier M K A B₁ B₂ →ₐ[K]
      tensorProductPushoutTargetCarrier M K A B₁ B₂ leftAlgebra rightAlgebra := by
  dsimp only
  let leftAlgebra := tensorProductPushoutLeftAlgebra
    (M := M) (K := K) (A := A) (B₁ := B₁)
  let rightAlgebra := tensorProductPushoutRightAlgebra
    (M := M) (K := K) (A := A) (B₂ := B₂)
  letI := leftAlgebra
  letI := rightAlgebra
  exact @tensorProductPushoutBaseChangeHom M K A B₁ B₂
    _ _ _ _ _ _ _ _ _ _ _ _ _

/-- The inverse map with its two generated tensor-product algebra witnesses pinned. -/
noncomputable def tensorProductPushoutBaseChangeInvPinned :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutTargetCarrier M K A B₁ B₂ leftAlgebra rightAlgebra →ₐ[K]
      tensorProductPushoutSourceCarrier M K A B₁ B₂ := by
  dsimp only
  let leftAlgebra := tensorProductPushoutLeftAlgebra
    (M := M) (K := K) (A := A) (B₁ := B₁)
  let rightAlgebra := tensorProductPushoutRightAlgebra
    (M := M) (K := K) (A := A) (B₂ := B₂)
  letI := leftAlgebra
  letI := rightAlgebra
  exact @tensorProductPushoutBaseChangeInvHom M K A B₁ B₂
    _ _ _ _ _ _ _ _ _ _ _ _ _

/-- The base-change equivalence with its two generated tensor-product algebra witnesses pinned. -/
noncomputable def tensorProductPushoutBaseChangeEquivPinned :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutSourceCarrier M K A B₁ B₂ ≃ₐ[K]
      tensorProductPushoutTargetCarrier M K A B₁ B₂ leftAlgebra rightAlgebra := by
  dsimp only
  let leftAlgebra := tensorProductPushoutLeftAlgebra
    (M := M) (K := K) (A := A) (B₁ := B₁)
  let rightAlgebra := tensorProductPushoutRightAlgebra
    (M := M) (K := K) (A := A) (B₂ := B₂)
  letI := leftAlgebra
  letI := rightAlgebra
  exact @tensorProductPushoutBaseChange M K A B₁ B₂
    _ _ _ _ _ _ _ _ _ _ _ _ _

/-- The left factor inclusion in a pinned target carrier, over the tensor-product base. -/
noncomputable def tensorProductPushoutLeftInclusion
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutLeftCarrier M K B₁ →ₐ[K ⊗[M] A] C.target := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  exact Algebra.TensorProduct.includeLeft

/-- The right factor inclusion in a pinned target carrier, over the tensor-product base. -/
noncomputable def tensorProductPushoutRightInclusion
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutRightCarrier M K B₂ →ₐ[K ⊗[M] A] C.target := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  exact Algebra.TensorProduct.includeRight

/-- The left factor inclusion viewed over `K`, using the tower witness carried by `C`. -/
noncomputable def tensorProductPushoutLeftInclusionOverK
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    letI := C.leftTower
    letI := C.rightTower
    tensorProductPushoutLeftCarrier M K B₁ →ₐ[K] C.target := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  letI := C.leftTower
  letI := C.rightTower
  exact (Algebra.TensorProduct.includeLeft :
    tensorProductPushoutLeftCarrier M K B₁ →ₐ[K ⊗[M] A] C.target).restrictScalars K

/-- The right factor inclusion viewed over `K`, using the tower witness carried by `C`. -/
noncomputable def tensorProductPushoutRightInclusionOverK
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    letI := C.leftTower
    letI := C.rightTower
    tensorProductPushoutRightCarrier M K B₂ →ₐ[K] C.target := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  letI := C.leftTower
  letI := C.rightTower
  exact (Algebra.TensorProduct.includeRight :
    tensorProductPushoutRightCarrier M K B₂ →ₐ[K ⊗[M] A] C.target).restrictScalars K

/-! ### The full package -/

/-- Tensor pushout carriers, maps, inclusions, and the scalar-extension equivalence.

The map fields are explicit even though the canonical constructor below supplies them from
the pinned entry points.  This lets downstream records retain the exact maps they selected,
instead of reconstructing them under a potentially different instance environment.
-/
structure TensorProductPushoutData
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) where
  /-- The left factor inclusion into the target, over the tensor-product base. -/
  leftInclusion :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutLeftCarrier M K B₁ →ₐ[K ⊗[M] A] C.target
  /-- The right factor inclusion into the target, over the tensor-product base. -/
  rightInclusion :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutRightCarrier M K B₂ →ₐ[K ⊗[M] A] C.target
  /-- The forward base-change homomorphism. -/
  hom :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutSourceCarrier M K A B₁ B₂ →ₐ[K] C.target
  /-- The inverse base-change homomorphism. -/
  inv :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    C.target →ₐ[K] tensorProductPushoutSourceCarrier M K A B₁ B₂
  /-- The base-change equivalence. -/
  equiv :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    tensorProductPushoutSourceCarrier M K A B₁ B₂ ≃ₐ[K] C.target
  /-- The forward map agrees with the chosen equivalence. -/
  hom_equiv :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    hom = equiv.toAlgHom
  /-- The inverse map agrees with the inverse of the chosen equivalence. -/
  inv_equiv :
    letI := C.leftAlgebra
    letI := C.rightAlgebra
    inv = equiv.symm.toAlgHom

/-- The canonical tensor pushout data package. -/
noncomputable def tensorProductPushoutData :
    TensorProductPushoutData
      (tensorProductPushoutCarriers (M := M) (K := K) (A := A)
        (B₁ := B₁) (B₂ := B₂)) := by
  let C := tensorProductPushoutCarriers (M := M) (K := K) (A := A)
    (B₁ := B₁) (B₂ := B₂)
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  exact
    { leftInclusion := tensorProductPushoutLeftInclusion C
      rightInclusion := tensorProductPushoutRightInclusion C
      hom := tensorProductPushoutBaseChangeHomPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
      inv := tensorProductPushoutBaseChangeInvPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
      equiv := tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
      hom_equiv := by rfl
      inv_equiv := by rfl }

/-- The source carrier of a data package. -/
abbrev TensorProductPushoutData.source
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (_D : TensorProductPushoutData C) : Type u :=
  tensorProductPushoutSourceCarrier M K A B₁ B₂

/-- The target carrier of a data package. -/
abbrev TensorProductPushoutData.target
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (_D : TensorProductPushoutData C) : Type u := C.target

/-! ### Let-free pinned facade

`TensorProductPushoutData` remains the compatibility record used by the first-generation
descent files.  Its dependent fields deliberately retain local `letI` bindings.  The facade
below names the target algebra and uses fully explicit `AlgHom` parameters, so new consumers can
carry maps and inverse laws without replaying those bindings at every projection.
-/

/-- The target carrier of a carrier package, with both module structures pinned. -/
abbrev tensorProductPushoutPinnedTarget
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) : Type u :=
  tensorProductPushoutBaseChangeTarget C.leftAlgebra C.rightAlgebra

/-- The base-algebra structure on the pinned target carrier. -/
@[reducible] noncomputable def tensorProductPushoutPinnedTargetAlgebra
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    Algebra (K ⊗[M] A) (tensorProductPushoutPinnedTarget C) := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  exact Algebra.TensorProduct.instAlgebra

/-- The `K`-algebra structure on a pinned target carrier.

The target tensor product has two natural scalar structures: the base algebra
`K ⊗[M] A` and the outer scalar field `K`.  Leaving the latter to typeclass
inference in an `AlgHom` type is particularly fragile: a caller that rebuilds
the tensor tower gets a propositionally equal, but not definitionally equal,
`Algebra K` witness.  Naming the witness here gives every pinned map one
canonical target instance. -/
@[reducible] noncomputable def tensorProductPushoutPinnedTargetKAlgebra
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :
    Algebra K (tensorProductPushoutPinnedTarget C) := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  infer_instance

/-- The `K`-algebra structure on the scalar-extension source carrier.

This is named alongside the target witness so the two `AlgHom` aliases below
contain no hidden instance search at all. -/
@[reducible] noncomputable def tensorProductPushoutPinnedSourceKAlgebra :
    Algebra K (tensorProductPushoutSourceCarrier M K A B₁ B₂) := by
  infer_instance

/-- A left factor inclusion whose source and target algebra structures are explicit. -/
abbrev tensorProductPushoutPinnedLeftInclusion
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :=
  @AlgHom (K ⊗[M] A) (K ⊗[M] B₁) (tensorProductPushoutPinnedTarget C)
    _ _ _ C.leftAlgebra (tensorProductPushoutPinnedTargetAlgebra C)

/-- A right factor inclusion whose source and target algebra structures are explicit. -/
abbrev tensorProductPushoutPinnedRightInclusion
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :=
  @AlgHom (K ⊗[M] A) (K ⊗[M] B₂) (tensorProductPushoutPinnedTarget C)
    _ _ _ C.rightAlgebra (tensorProductPushoutPinnedTargetAlgebra C)

/-- The forward map type for a pinned carrier package. -/
abbrev tensorProductPushoutPinnedHom
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :=
  @AlgHom K (tensorProductPushoutSourceCarrier M K A B₁ B₂)
    (tensorProductPushoutPinnedTarget C) _ _ _
    tensorProductPushoutPinnedSourceKAlgebra
    (tensorProductPushoutPinnedTargetKAlgebra C)

/-- The inverse map type for a pinned carrier package. -/
abbrev tensorProductPushoutPinnedInv
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) :=
  @AlgHom K (tensorProductPushoutPinnedTarget C)
    (tensorProductPushoutSourceCarrier M K A B₁ B₂) _ _ _
    (tensorProductPushoutPinnedTargetKAlgebra C)
    tensorProductPushoutPinnedSourceKAlgebra

/-- A tensor pushout package with no dependent `letI` expressions in its public fields. -/
structure TensorProductPushoutPinnedData
    (C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)) where
  /-- The left factor inclusion into the pinned target. -/
  leftInclusion : tensorProductPushoutPinnedLeftInclusion C
  /-- The right factor inclusion into the pinned target. -/
  rightInclusion : tensorProductPushoutPinnedRightInclusion C
  /-- The forward scalar-extension map. -/
  hom : tensorProductPushoutPinnedHom C
  /-- The inverse scalar-extension map. -/
  inv : tensorProductPushoutPinnedInv C
  /-- The inverse followed by the forward map is the identity. -/
  left_inv : inv.comp hom = AlgHom.id K _
  /-- The forward followed by the inverse map is the identity. -/
  right_inv : hom.comp inv = AlgHom.id K _

namespace TensorProductPushoutPinnedData

/-- Recover the algebra equivalence represented by a pinned data package. -/
noncomputable def equiv
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    tensorProductPushoutSourceCarrier M K A B₁ B₂ ≃ₐ[K]
      tensorProductPushoutPinnedTarget C :=
  AlgEquiv.ofAlgHom D.hom D.inv D.right_inv D.left_inv

@[simp]
theorem left_inv_apply
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C)
    (x : tensorProductPushoutSourceCarrier M K A B₁ B₂) :
    D.inv (D.hom x) = x :=
  DFunLike.congr_fun D.left_inv x

@[simp]
theorem right_inv_apply
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C)
    (x : tensorProductPushoutPinnedTarget C) :
    D.hom (D.inv x) = x :=
  DFunLike.congr_fun D.right_inv x

/-! ### Explicit projections

The structure fields above already use pinned map aliases, but a consumer still had to know
which carrier and `Algebra K` witness each alias denoted.  These projections make that choice
part of the namespace API.  In particular, none of the result types below asks typeclass
inference to rebuild a tensor-product algebra, and no result type contains a `letI` binder.
-/

/-- The source carrier selected by a pinned data package. -/
abbrev source
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (_D : TensorProductPushoutPinnedData C) : Type u :=
  tensorProductPushoutSourceCarrier M K A B₁ B₂

/-- The target carrier selected by a pinned data package. -/
abbrev target
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (_D : TensorProductPushoutPinnedData C) : Type u :=
  tensorProductPushoutPinnedTarget C

/-- The explicit `K`-algebra witness on the source carrier. -/
abbrev sourceAlgebra
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) : Algebra K D.source :=
  tensorProductPushoutPinnedSourceKAlgebra

/-- The explicit `K`-algebra witness on the target carrier. -/
abbrev targetAlgebra
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) : Algebra K D.target :=
  tensorProductPushoutPinnedTargetKAlgebra C

/-- The forward map with both source and target `Algebra K` witnesses explicit. -/
abbrev forward
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    @AlgHom K D.source D.target _ _ _ D.sourceAlgebra D.targetAlgebra :=
  D.hom

/-- The inverse map with both source and target `Algebra K` witnesses explicit. -/
abbrev backward
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    @AlgHom K D.target D.source _ _ _ D.targetAlgebra D.sourceAlgebra :=
  D.inv

/-- The inverse followed by the forward map, with the identity algebra pinned. -/
@[simp]
theorem backward_comp_forward
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    D.backward.comp D.forward = @AlgHom.id K D.source _ _ D.sourceAlgebra :=
  D.left_inv

/-- The forward followed by the inverse map, with the identity algebra pinned. -/
@[simp]
theorem forward_comp_backward
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    D.forward.comp D.backward = @AlgHom.id K D.target _ _ D.targetAlgebra :=
  D.right_inv

/-- Pointwise cancellation of the forward and backward maps on the source. -/
@[simp]
theorem backward_comp_forward_apply
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) (x : D.source) :
    D.backward (D.forward x) = x :=
  D.left_inv_apply x

/-- Pointwise cancellation of the backward and forward maps on the target. -/
@[simp]
theorem forward_comp_backward_apply
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) (x : D.target) :
    D.forward (D.backward x) = x :=
  D.right_inv_apply x

/-- The equivalence projection is definitionally the pinned forward map. -/
@[simp]
theorem equiv_toAlgHom
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    D.equiv.toAlgHom = D.forward := by
  rfl

/-- The inverse equivalence projection is definitionally the pinned backward map. -/
@[simp]
theorem equiv_symm_toAlgHom
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutPinnedData C) :
    D.equiv.symm.toAlgHom = D.backward := by
  rfl

end TensorProductPushoutPinnedData

/-! ### Compatibility and canonical constructors -/

/-- Convert the original dependent record to the let-free pinned facade. -/
noncomputable def TensorProductPushoutData.toPinned
    {C : TensorProductPushoutCarriers (M := M) (K := K) (A := A)
      (B₁ := B₁) (B₂ := B₂)}
    (D : TensorProductPushoutData C) : TensorProductPushoutPinnedData C := by
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  refine
    { leftInclusion := D.leftInclusion
      rightInclusion := D.rightInclusion
      hom := D.hom
      inv := D.inv
      left_inv := ?_
      right_inv := ?_ }
  · apply DFunLike.ext _ _
    intro x
    rw [D.inv_equiv, D.hom_equiv]
    exact D.equiv.left_inv x
  · apply DFunLike.ext _ _
    intro x
    rw [D.hom_equiv, D.inv_equiv]
    exact D.equiv.right_inv x

/-- The canonical let-free package for the canonical carrier witnesses. -/
noncomputable def tensorProductPushoutPinnedData :
    TensorProductPushoutPinnedData
      (tensorProductPushoutCarriers (M := M) (K := K) (A := A)
        (B₁ := B₁) (B₂ := B₂)) := by
  let C := tensorProductPushoutCarriers (M := M) (K := K) (A := A)
    (B₁ := B₁) (B₂ := B₂)
  letI := C.leftAlgebra
  letI := C.rightAlgebra
  refine
    { leftInclusion := Algebra.TensorProduct.includeLeft
      rightInclusion := Algebra.TensorProduct.includeRight
      hom := ?_
      inv := ?_
      left_inv := ?_
      right_inv := ?_ }
  · exact (tensorProductPushoutBaseChangeMaps
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).hom
  · exact (tensorProductPushoutBaseChangeMaps
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).inv
  · apply DFunLike.ext _ _
    intro x
    exact (tensorProductPushoutBaseChangeMaps
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).left_inv_apply x
  · apply DFunLike.ext _ _
    intro x
    exact (tensorProductPushoutBaseChangeMaps
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).right_inv_apply x

@[simp]
theorem canonical_hom_tmul (k : K) (b₁ : B₁) (b₂ : B₂) :
    (tensorProductPushoutPinnedData
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).hom
        (k ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂)) =
      tensorProductPushoutBaseChangeTargetTmul
        (tensorProductPushoutBaseChangeLeftAlgebra
          (M := M) (K := K) (A := A) (B₁ := B₁))
        (tensorProductPushoutBaseChangeRightAlgebra
          (M := M) (K := K) (A := A) (B₂ := B₂))
        (k ⊗ₜ[M] b₁) (1 ⊗ₜ[M] b₂) := by
  change (tensorProductPushoutBaseChangeMaps
      (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).hom
      (k ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂)) = _
  exact tensorProductPushoutBaseChangeMaps_hom_tmul k b₁ b₂

/-! ### Pure-tensor adapters -/

/-- The pinned forward map on a pure tensor. -/
@[simp]
theorem tensorProductPushoutBaseChangeHomPinned_tmul (k : K) (b₁ : B₁) (b₂ : B₂) :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutBaseChangeHomPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
        (k ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂)) =
      (k ⊗ₜ[M] b₁) ⊗ₜ[K ⊗[M] A] (1 ⊗ₜ[M] b₂) := by
  dsimp only [tensorProductPushoutBaseChangeHomPinned]
  exact tensorProductPushoutBaseChangeHom_tmul k b₁ b₂

/-- The pinned inverse map on a pure tensor. -/
@[simp]
theorem tensorProductPushoutBaseChangeInvPinned_tmul
    (k₁ k₂ : K) (b₁ : B₁) (b₂ : B₂) :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutBaseChangeInvPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
        ((k₁ ⊗ₜ[M] b₁) ⊗ₜ[K ⊗[M] A] (k₂ ⊗ₜ[M] b₂)) =
      (k₁ * k₂) ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂) := by
  dsimp only [tensorProductPushoutBaseChangeInvPinned]
  exact tensorProductPushoutBaseChangeInvHom_tmul k₁ k₂ b₁ b₂

/-- The pinned equivalence on a pure tensor. -/
@[simp]
theorem tensorProductPushoutBaseChangeEquivPinned_tmul
    (k : K) (b₁ : B₁) (b₂ : B₂) :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)
        (k ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂)) =
      (k ⊗ₜ[M] b₁) ⊗ₜ[K ⊗[M] A] (1 ⊗ₜ[M] b₂) := by
  dsimp only [tensorProductPushoutBaseChangeEquivPinned]
  exact tensorProductPushoutBaseChange_tmul k b₁ b₂

/-- The pinned inverse equivalence on a pure tensor. -/
@[simp]
theorem tensorProductPushoutBaseChangeEquivPinned_symm_tmul
    (k₁ k₂ : K) (b₁ : B₁) (b₂ : B₂) :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    (tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).symm
        ((k₁ ⊗ₜ[M] b₁) ⊗ₜ[K ⊗[M] A] (k₂ ⊗ₜ[M] b₂)) =
      (k₁ * k₂) ⊗ₜ[M] (b₁ ⊗ₜ[A] b₂) := by
  dsimp only [tensorProductPushoutBaseChangeEquivPinned]
  exact tensorProductPushoutBaseChange_symm_tmul k₁ k₂ b₁ b₂

/-- The pinned equivalence followed by its inverse is the identity algebra map. -/
theorem tensorProductPushoutBaseChangeEquivPinned_left_inv :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    (tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).symm.toAlgHom.comp
      (tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).toAlgHom =
      AlgHom.id K (tensorProductPushoutSourceCarrier M K A B₁ B₂) := by
  dsimp only
  apply DFunLike.ext _ _
  intro x
  exact (tensorProductPushoutBaseChangeEquivPinned
    (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).left_inv x

/-- The inverse followed by the pinned equivalence is the identity algebra map. -/
theorem tensorProductPushoutBaseChangeEquivPinned_right_inv :
    let leftAlgebra := tensorProductPushoutLeftAlgebra
      (M := M) (K := K) (A := A) (B₁ := B₁)
    let rightAlgebra := tensorProductPushoutRightAlgebra
      (M := M) (K := K) (A := A) (B₂ := B₂)
    letI := leftAlgebra
    letI := rightAlgebra
    (tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).toAlgHom.comp
      (tensorProductPushoutBaseChangeEquivPinned
        (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).symm.toAlgHom =
      AlgHom.id K (tensorProductPushoutTargetCarrier M K A B₁ B₂
        (tensorProductPushoutLeftAlgebra
          (M := M) (K := K) (A := A) (B₁ := B₁))
        (tensorProductPushoutRightAlgebra
          (M := M) (K := K) (A := A) (B₂ := B₂))) := by
  dsimp only
  apply DFunLike.ext _ _
  intro x
  exact (tensorProductPushoutBaseChangeEquivPinned
    (M := M) (K := K) (A := A) (B₁ := B₁) (B₂ := B₂)).right_inv x

/-! ### Naturality entry points -/

/-- Scalar extension of maps commutes with a scalar tower (pinned forwarding theorem). -/
theorem tensorProductPushoutScalarExtension_tower {F L K A B : Type u}
    [CommRing F] [CommRing L] [CommRing K] [Semiring A] [Semiring B]
    [Algebra F L] [Algebra F K] [Algebra L K] [IsScalarTower F L K]
    [Algebra F A] [Algebra F B]
    (f : A →ₐ[F] B) :
    (Algebra.TensorProduct.map (IsScalarTower.toAlgHom F L K)
        (AlgHom.id F B)).comp
        ((scalarExtensionMapOfAlgHom (R := F) (K := L) f).restrictScalars F) =
      ((scalarExtensionMapOfAlgHom (R := F) (K := K) f).restrictScalars F).comp
        (Algebra.TensorProduct.map (IsScalarTower.toAlgHom F L K)
          (AlgHom.id F A)) := by
  exact @scalarExtensionMapOfAlgHom_tower F L K A B
    _ _ _ _ _ _ _ _ _ _ _ f

/-- Scalar extension preserves composition of algebra maps (pinned forwarding theorem). -/
@[simp]
theorem tensorProductPushoutScalarExtension_comp {R K A B D : Type u}
    [CommRing R] [CommRing K] [Semiring A] [Semiring B] [Semiring D]
    [Algebra R K] [Algebra R A] [Algebra R B] [Algebra R D]
    (f : A →ₐ[R] B) (g : B →ₐ[R] D) :
    (scalarExtensionMapOfAlgHom (R := R) (K := K) g).comp
        (scalarExtensionMapOfAlgHom (R := R) (K := K) f) =
      scalarExtensionMapOfAlgHom (R := R) (K := K) (g.comp f) := by
  exact @scalarExtensionMapOfAlgHom_comp R K A B D
    _ _ _ _ _ _ _ _ _ f g

/-- Scalar extension preserves the identity algebra map (pinned forwarding theorem). -/
@[simp]
theorem tensorProductPushoutScalarExtension_id {R K A : Type u}
    [CommRing R] [CommRing K] [Semiring A]
    [Algebra R K] [Algebra R A] :
    scalarExtensionMapOfAlgHom (R := R) (K := K) (AlgHom.id R A) =
      AlgHom.id K (K ⊗[R] A) := by
  exact @scalarExtensionMapOfAlgHom_id R K A _ _ _ _ _

/-- Cancellation through a scalar tower is natural for commuting map squares.

This is the map-level naturality entry point used by finite-stage transition data. -/
theorem tensorProductPushoutCancelBaseChange_naturality {F L K A B : Type u}
    [CommRing F] [CommRing L] [CommRing K] [CommRing A] [CommRing B]
    [Algebra F L] [Algebra F K] [Algebra L K] [IsScalarTower F L K]
    [Algebra F A] [Algebra F B]
    (phiL : L ⊗[F] A →ₐ[L] L ⊗[F] B)
    (phiK : K ⊗[F] A →ₐ[K] K ⊗[F] B)
    (hphi :
      (Algebra.TensorProduct.map (IsScalarTower.toAlgHom F L K) (AlgHom.id F B)).comp
          (phiL.restrictScalars F) =
        (phiK.restrictScalars F).comp
          (Algebra.TensorProduct.map (IsScalarTower.toAlgHom F L K) (AlgHom.id F A))) :
    (Algebra.TensorProduct.cancelBaseChange F L K K B).toAlgHom.comp
        (scalarExtensionMapOfAlgHom (R := L) (K := K) phiL) =
      phiK.comp (Algebra.TensorProduct.cancelBaseChange F L K K A).toAlgHom := by
  exact @cancelBaseChange_naturality F L K A B
    _ _ _ _ _ _ _ _ _ _ _ phiL phiK hphi

end PinnedMaps

end

end AlgebraicJacobian
