/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.RingTheory.PicardGroup
import Mathlib.RingTheory.Nilpotent.Lemmas

/-!
# Invertible modules over a nilpotent thickening are free once they are free mod the ideal

This file proves the **chart-triviality input** of the Kleiman §5 Thm 5.11 tangent-space
comparison (`Picard/Pic0AbelianVariety.lean`,
`semilinearComparison_cotangentSpaceDual_h1Cok`): *an invertible sheaf on
`C ×_k Spec k[ε]` which is trivial along `ε ↦ 0` is trivial on each base-changed affine
chart.* On an affine chart `V = Spec A` the base change is `Spec A[ε]`, the restriction
`A[ε] → A` has square-zero kernel `(ε)`, and an invertible sheaf on an affine is an
invertible module — so the geometric statement is the algebraic one proved here:

> an invertible `R`-module `M` whose reduction modulo a **nilpotent** ideal `I` is generated
> by the image of a single element is itself generated by that element, hence free.

Nothing here is specific to dual numbers, to curves, or to schemes: the nilpotency of `I`
is the only hypothesis, so the same statement covers any square-zero (indeed any nilpotent)
thickening. It is stated in mathlib generality and is a plausible upstreaming candidate.

## Main results

* `Module.Invertible.free_of_span_singleton_eq_top` — an invertible module generated by one
  element is free. This is the reason the argument works at all: for invertible modules a
  *surjection* from the ring is automatically bijective
  (`Module.Invertible.bijective_of_surjective`), which fails for general modules — a nonzero
  element of an invertible module over a domain spans a copy of the domain that is a proper
  submodule unless the module is free.
* `Submodule.top_le_span_sup_pow_smul_top` — the Nakayama iteration: if
  `N ⊔ I • ⊤ = ⊤` then `N ⊔ Iⁿ • ⊤ = ⊤` for every `n`. Stated without any finiteness
  hypothesis, which is what lets the nilpotent case avoid mathlib's
  `Submodule.le_of_le_smul_of_le_jacobson_bot` (that route needs `(⊤ : Submodule R M).FG`
  *and* `I ≤ jacobson ⊥`; here neither is needed and the induction is three lines).
* `Module.Invertible.free_of_nilpotent_of_span_sup_smul_eq_top` — the main statement, and
* `Module.Invertible.free_of_nilpotent_of_exists_sub_smul_mem` — the same in the form a
  consumer actually has it: *every* element of `M` agrees with some `r • m` modulo `I • M`.

## Why the nilpotent hypothesis is not cosmetic

Without it the statement is false: over a Dedekind domain `R` with a nontrivial ideal class,
a nonprincipal invertible ideal `M` and a maximal ideal `I` give `M = R·m + I·M` for a
suitable `m` (Nakayama over the local ring), while `M` is not free. Nilpotency is what makes
the descending chain `Iⁿ • M` reach `0` and force `span{m} = ⊤` on the nose rather than
locally.
-/

set_option autoImplicit false

universe u v

namespace Module.Invertible

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- **An invertible module generated by a single element is free.**

The point is that for an invertible module surjectivity upgrades to bijectivity:
`Module.Invertible.bijective_of_surjective` (`Mathlib/RingTheory/PicardGroup.lean`) says a
surjection *out of* an invertible module onto an invertible module is injective as well, and
`R` is invertible over itself. So the tautological map `r ↦ r • m`, which is surjective
exactly when `m` generates, is an isomorphism `R ≃ₗ M`.

This is emphatically not true for general modules — `ℤ/2` is generated by one element over
`ℤ` and is not free — and it is the step that makes the whole nilpotent-thickening argument
short. -/
theorem free_of_span_singleton_eq_top [Module.Invertible R M] {m : M}
    (h : Submodule.span R ({m} : Set M) = ⊤) : Module.Free R M := by
  have hsurj : Function.Surjective (LinearMap.toSpanSingleton R M m) := by
    intro x
    have hx : x ∈ Submodule.span R ({m} : Set M) := h ▸ Submodule.mem_top
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨r, hr⟩ := hx
    exact ⟨r, hr⟩
  exact Module.Free.of_equiv
    (LinearEquiv.ofBijective _ (Module.Invertible.bijective_of_surjective hsurj))

end Module.Invertible

namespace Submodule

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- **The Nakayama iteration, with no finiteness hypothesis.** If `N` together with `I • M`
spans `M`, then `N` together with `Iⁿ • M` spans `M`, for every `n`.

Substituting `M = N + I·M` into itself `n` times: `Iⁿ·M = Iⁿ·N + Iⁿ·(I·M)`, the first
summand lies in `N` and the second is `Iⁿ⁺¹·M`.

Mathlib's Nakayama lemmas (`Submodule.le_of_le_smul_of_le_jacobson_bot` and friends,
`Mathlib/RingTheory/Nakayama.lean`) reach a stronger conclusion but require `N'.FG` and
`I ≤ jacobson ⊥`. For a *nilpotent* `I` the iteration below terminates on its own, so
neither hypothesis is needed — which matters here because the modules in the tangent-space
application are sections over an affine chart, where finite generation is exactly the
hypothesis one does not want to have to supply. -/
theorem top_le_span_sup_pow_smul_top {I : Ideal R} {N : Submodule R M}
    (hN : N ⊔ I • (⊤ : Submodule R M) = ⊤) (n : ℕ) :
    (⊤ : Submodule R M) ≤ N ⊔ (I ^ n) • (⊤ : Submodule R M) := by
  induction n with
  | zero => simp
  | succ n ih =>
    have h₁ : (I ^ n) • (⊤ : Submodule R M)
        = (I ^ n) • N ⊔ (I ^ n) • (I • (⊤ : Submodule R M)) := by
      rw [← Submodule.smul_sup, hN]
    have h₂ : (I ^ n) • (I • (⊤ : Submodule R M)) = (I ^ (n + 1)) • (⊤ : Submodule R M) := by
      rw [← Submodule.smul_assoc, Ideal.smul_eq_mul, ← pow_succ]
    calc (⊤ : Submodule R M) ≤ N ⊔ (I ^ n) • (⊤ : Submodule R M) := ih
      _ = N ⊔ ((I ^ n) • N ⊔ (I ^ (n + 1)) • (⊤ : Submodule R M)) := by rw [h₁, h₂]
      _ ≤ N ⊔ (I ^ (n + 1)) • (⊤ : Submodule R M) :=
          sup_le le_sup_left
            (sup_le (le_trans Submodule.smul_le_right le_sup_left) le_sup_right)

end Submodule

namespace Module.Invertible

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- **An invertible module over a nilpotent thickening is free once it is cyclic modulo the
ideal.** If `I` is nilpotent and `span{m} ⊔ I • M = M`, then `span{m} = M` and `M` is free.

Proof: `Iʲ = 0` for some `j`, and `Submodule.top_le_span_sup_pow_smul_top` gives
`span{m} ⊔ Iʲ • M = M`, i.e. `span{m} = M`; then
`Module.Invertible.free_of_span_singleton_eq_top`.

This is the chart-triviality input of the tangent-space comparison: on an affine chart
`Spec A` of the curve, the base change along `k → k[ε]` is `Spec A[ε]`, the ideal `(ε)` is
square-zero hence nilpotent, and an invertible sheaf trivial along `ε ↦ 0` is an invertible
`A[ε]`-module that is cyclic modulo `(ε)`. -/
theorem free_of_nilpotent_of_span_sup_smul_eq_top [Module.Invertible R M] {I : Ideal R}
    (hI : IsNilpotent I) {m : M}
    (hgen : Submodule.span R ({m} : Set M) ⊔ I • (⊤ : Submodule R M) = ⊤) :
    Module.Free R M := by
  obtain ⟨j, hj⟩ := hI
  refine free_of_span_singleton_eq_top (m := m) (le_antisymm le_top ?_)
  have h := Submodule.top_le_span_sup_pow_smul_top hgen j
  rw [hj] at h
  simpa using h

/-- **The same statement in the form a consumer has it.** Instead of a `span ⊔ smul`
equation, the hypothesis is the pointwise one: every element of `M` differs from a multiple
of `m` by an element of `I • M` — i.e. the image of `m` generates the reduction `M ⧸ I • M`
as a module over `R ⧸ I`.

For the geometric application `R = A[ε]`, `I = (ε)` and `M ⧸ (ε) • M` is the restriction of
the invertible sheaf along `ε ↦ 0`, whose triviality is exactly the hypothesis that the
class lies in the kernel of `Pic(C ×_k Spec k[ε]) → Pic(C)`. -/
theorem free_of_nilpotent_of_exists_sub_smul_mem [Module.Invertible R M] {I : Ideal R}
    (hI : IsNilpotent I) {m : M}
    (h : ∀ x : M, ∃ r : R, x - r • m ∈ I • (⊤ : Submodule R M)) :
    Module.Free R M := by
  refine free_of_nilpotent_of_span_sup_smul_eq_top hI (m := m) (le_antisymm le_top ?_)
  intro x _
  obtain ⟨r, hr⟩ := h x
  have hx : x = r • m + (x - r • m) := by abel
  rw [hx]
  exact Submodule.add_mem _
    (Submodule.mem_sup_left (Submodule.mem_span_singleton.mpr ⟨r, rfl⟩))
    (Submodule.mem_sup_right hr)

end Module.Invertible

namespace Ideal

variable {R : Type u} [CommRing R]

/-- A square-zero ideal is nilpotent. Recorded because the dual-number thickening
`k[ε] → k` — and every first-order deformation situation — supplies `I * I = ⊥` rather than
an explicit nilpotency exponent. -/
theorem isNilpotent_of_mul_self_eq_bot {I : Ideal R} (h : I * I = ⊥) : IsNilpotent I :=
  ⟨2, by rw [pow_two]; exact h⟩

end Ideal
