/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.ProjectiveCoordinateChart
import AlgebraicJacobian.Picard.ProjectiveSpaceAffineChartIso
import Mathlib.Data.Fintype.BigOperators

/-!
# Arbitrary standard charts of projective space

For a finite coordinate type `J` and a distinguished coordinate `i : J`, this
file identifies the degree-zero homogeneous localization at `X i` with the
polynomial ring on the remaining coordinates.  This is the reindexed form of
the standard `D_+(X_none)` chart calculation.
-/

set_option autoImplicit false

open MvPolynomial HomogeneousLocalization

noncomputable section

universe u

namespace AlgebraicGeometry.ProjectiveSpace.AffineChartAtRing

local instance (J R : Type u) [CommRing R] :
    GradedRing (homogeneousSubmodule J R) :=
  MvPolynomial.gradedAlgebra

variable (R : Type u) [CommRing R]
variable (J : Type u)

/-- Every homogeneous coordinate has degree one. -/
theorem X_mem_deg_one (i : J) :
    (X i : MvPolynomial J R) ∈ homogeneousSubmodule J R 1 :=
  isHomogeneous_X _ _

/-- The normalized coordinate `X_j / X_i` on `D_+(X_i)`. -/
def chartCoord (i : J) (j : {j : J // j ≠ i}) :
    Away (homogeneousSubmodule J R) (X i) :=
  Away.mk (homogeneousSubmodule J R) (X_mem_deg_one R J i) 1 (X j.1)
    (by simpa using X_mem_deg_one R J j.1)

/-- Dehomogenization at `X_i`: send `X_i` to one and the other variables to
the corresponding variables of the complementary polynomial ring. -/
def dehomogenize (i : J) :
    MvPolynomial J R →ₐ[R] MvPolynomial {j : J // j ≠ i} R := by
  classical
  exact MvPolynomial.aeval fun j ↦ if h : j = i then 1 else X ⟨j, h⟩

@[simp]
theorem dehomogenize_X_self (i : J) : dehomogenize R J i (X i) = 1 := by
  classical
  simp [dehomogenize]

@[simp]
theorem dehomogenize_X_ne (i : J) (j : {j : J // j ≠ i}) :
    dehomogenize R J i (X j.1) = X j := by
  classical
  simp [dehomogenize, j.2]

private theorem isUnit_dehomogenize_X_self (i : J) :
    IsUnit ((dehomogenize R J i).toRingHom (X i)) := by
  rw [show (dehomogenize R J i).toRingHom (X i) = 1 by
    exact dehomogenize_X_self R J i]
  exact isUnit_one

/-- The polynomial algebra map generated by the normalized coordinates. -/
def polyToAway (i : J) : MvPolynomial {j : J // j ≠ i} R →ₐ[R]
    Away (homogeneousSubmodule J R) (X i) :=
  MvPolynomial.aeval (chartCoord R J i)

@[simp]
theorem polyToAway_X (i : J) (j : {j : J // j ≠ i}) :
    polyToAway R J i (X j) = chartCoord R J i j :=
  MvPolynomial.aeval_X _ _

/-- Dehomogenization descends to the degree-zero homogeneous localization. -/
def awayToPoly (i : J) : Away (homogeneousSubmodule J R) (X i) →ₐ[R]
    MvPolynomial {j : J // j ≠ i} R where
  toRingHom :=
    (Localization.awayLift (dehomogenize R J i).toRingHom (X i)
      (isUnit_dehomogenize_X_self R J i)).comp
      (algebraMap (Away (homogeneousSubmodule J R) (X i))
        (Localization.Away (X i : MvPolynomial J R)))
  commutes' r := by
    change (Localization.awayLift (dehomogenize R J i).toRingHom (X i)
        (isUnit_dehomogenize_X_self R J i))
        ((algebraMap R (Away (homogeneousSubmodule J R) (X i)) r).val) =
      algebraMap R (MvPolynomial {j : J // j ≠ i} R) r
    rw [HomogeneousLocalization.algebraMap_val, IsLocalization.Away.lift_eq]
    exact (dehomogenize R J i).commutes r

/-- Evaluation of dehomogenization on a homogeneous fraction. -/
theorem awayToPoly_mk (i : J) (a : ℕ) (p : MvPolynomial J R)
    (hp : p ∈ homogeneousSubmodule J R (a • 1)) :
    awayToPoly R J i
        (Away.mk (homogeneousSubmodule J R) (X_mem_deg_one R J i) a p hp) =
      dehomogenize R J i p := by
  have h1 : (dehomogenize R J i).toRingHom (X i) * 1 = 1 := by
    rw [mul_one]
    exact dehomogenize_X_self R J i
  have h := Localization.awayLift_mk
    (A := MvPolynomial {j : J // j ≠ i} R)
    (dehomogenize R J i).toRingHom (X i) p 1 h1 a
  exact h.trans (by rw [one_pow, mul_one]; rfl)

@[simp]
theorem awayToPoly_chartCoord (i : J) (j : {j : J // j ≠ i}) :
    awayToPoly R J i (chartCoord R J i j) = X j :=
  (awayToPoly_mk R J i 1 (X j.1)
    (by simpa using X_mem_deg_one R J j.1)).trans
      (dehomogenize_X_ne R J i j)

/-- Dehomogenization is a left inverse to the normalized-coordinate map. -/
theorem awayToPoly_comp_polyToAway (i : J) :
    (awayToPoly R J i).comp (polyToAway R J i) =
      AlgHom.id R (MvPolynomial {j : J // j ≠ i} R) := by
  apply MvPolynomial.algHom_ext
  intro j
  rw [AlgHom.comp_apply, polyToAway_X, awayToPoly_chartCoord, AlgHom.id_apply]

/-! ### Surjectivity of the normalized-coordinate map -/

/-- Every degree-zero homogeneous polynomial is a constant. -/
theorem exists_algebraMap_eq_gradeZero
    (c : homogeneousSubmodule J R 0) :
    ∃ r : R, algebraMap R (homogeneousSubmodule J R 0) r = c := by
  have hc : (c : MvPolynomial J R) ∈
      (1 : Submodule R (MvPolynomial J R)) := by
    rw [← homogeneousSubmodule_zero (σ := J) (R := R)]
    exact c.2
  obtain ⟨r, hr⟩ := Submodule.mem_one.mp hc
  exact ⟨r, Subtype.ext (by simpa using hr)⟩

/-- The homogeneous coordinate ring is generated over its degree-zero part by
its variables. -/
theorem adjoin_gradeZero_range_X :
    Algebra.adjoin (homogeneousSubmodule J R 0)
      (Set.range (X : J → MvPolynomial J R)) = ⊤ := by
  rw [eq_top_iff]
  rintro p -
  have hp : p ∈ Algebra.adjoin R
      (Set.range (X : J → MvPolynomial J R)) := by
    rw [MvPolynomial.adjoin_range_X]
    trivial
  induction hp using Algebra.adjoin_induction with
  | mem q hq => exact Algebra.subset_adjoin hq
  | algebraMap r =>
      exact Subalgebra.algebraMap_mem _
        (⟨algebraMap R (MvPolynomial J R) r, by
          rw [MvPolynomial.algebraMap_eq]
          exact isHomogeneous_C _ r⟩ : homogeneousSubmodule J R 0)
  | add q₁ q₂ _ _ h₁ h₂ => exact add_mem h₁ h₂
  | mul q₁ q₂ _ _ h₁ h₂ => exact mul_mem h₁ h₂

section Finite

variable [Finite J]
local instance : Fintype J := Fintype.ofFinite J
local instance : DecidableEq J := Classical.decEq J

/-- Split the total degree into the distinguished coordinate and all remaining
coordinates. -/
private theorem degree_eq (i : J) {e : J → ℕ} {a : ℕ}
    (hae : ∑ l, e l • (1 : ℕ) = a • (1 : ℕ)) :
    e i + ∑ j : {j : J // j ≠ i}, e j = a := by
  rw [← (Equiv.optionSubtypeNe i).sum_comp, Fintype.sum_option] at hae
  simpa using hae

/-- A homogeneous monomial divided by the appropriate power of `X_i` is the
corresponding monomial in the normalized coordinates. -/
private theorem away_mk_prod_eq (i : J) (a : ℕ) (e : J → ℕ)
    (hae : e i + ∑ j : {j : J // j ≠ i}, e j = a)
    (H : (∏ l, (X l : MvPolynomial J R) ^ e l) ∈
      homogeneousSubmodule J R (a • 1)) :
    Away.mk (homogeneousSubmodule J R) (X_mem_deg_one R J i) a
        (∏ l, X l ^ e l) H =
      ∏ j : {j : J // j ≠ i}, chartCoord R J i j ^ e j := by
  apply (show Function.Injective (algebraMap
      (Away (homogeneousSubmodule J R) (X i))
      (Localization.Away (X i : MvPolynomial J R))) from
    HomogeneousLocalization.val_injective _)
  simp only [map_prod, map_pow, HomogeneousLocalization.algebraMap_apply,
    Away.val_mk, chartCoord, Localization.mk_pow, Localization.mk_prod]
  rw [← (Equiv.optionSubtypeNe i).prod_comp, Fintype.prod_option]
  simp only [Equiv.optionSubtypeNe_none, Equiv.optionSubtypeNe_some]
  rw [Localization.mk_eq_mk_iff, Localization.r_iff_exists]
  refine ⟨1, ?_⟩
  push_cast
  rw [Finset.prod_pow_eq_pow_sum, ← hae, pow_add]
  ring

/-- Every element of the arbitrary standard chart ring is a polynomial in the
normalized coordinates. -/
theorem polyToAway_surjective (i : J) :
    Function.Surjective (polyToAway R J i) := by
  intro z
  have hz : z ∈
      (⊤ : Submodule (homogeneousSubmodule J R 0)
        (Away (homogeneousSubmodule J R) (X i))) := trivial
  rw [← Away.span_mk_prod_pow_eq_top (X_mem_deg_one R J i) X
    (adjoin_gradeZero_range_X R J) (fun _ ↦ 1)
    (fun l ↦ X_mem_deg_one R J l)] at hz
  induction hz using Submodule.span_induction with
  | mem w hw =>
      obtain ⟨a, e, hae, rfl⟩ := hw
      refine ⟨∏ j : {j : J // j ≠ i}, X j ^ e j, ?_⟩
      rw [map_prod]
      simp_rw [map_pow, polyToAway_X]
      exact (away_mk_prod_eq R J i a e (degree_eq J i hae) _).symm
  | zero => exact ⟨0, map_zero _⟩
  | add p q _ _ hp hq =>
      obtain ⟨p, rfl⟩ := hp
      obtain ⟨q, rfl⟩ := hq
      exact ⟨p + q, map_add _ _ _⟩
  | smul c p _ hp =>
      obtain ⟨p, rfl⟩ := hp
      obtain ⟨r, rfl⟩ := exists_algebraMap_eq_gradeZero R J c
      exact ⟨r • p, by rw [map_smul, IsScalarTower.algebraMap_smul]⟩

omit [Finite J] in
theorem awayToPoly_polyToAway_apply (i : J)
    (p : MvPolynomial {j : J // j ≠ i} R) :
    awayToPoly R J i (polyToAway R J i p) = p :=
  AlgHom.congr_fun (awayToPoly_comp_polyToAway R J i) p

/-- The normalized-coordinate map is a left inverse to dehomogenization. -/
theorem polyToAway_comp_awayToPoly (i : J) :
    (polyToAway R J i).comp (awayToPoly R J i) =
      AlgHom.id R (Away (homogeneousSubmodule J R) (X i)) := by
  refine AlgHom.ext fun z ↦ ?_
  obtain ⟨p, rfl⟩ := polyToAway_surjective R J i z
  rw [AlgHom.comp_apply, AlgHom.id_apply, awayToPoly_polyToAway_apply]

/-- The `i`-th projective chart ring is the polynomial ring on all coordinates
other than `i`. -/
def awayAlgEquiv (i : J) :
    Away (homogeneousSubmodule J R) (X i) ≃ₐ[R]
      MvPolynomial {j : J // j ≠ i} R :=
  AlgEquiv.ofAlgHom (awayToPoly R J i) (polyToAway R J i)
    (awayToPoly_comp_polyToAway R J i) (polyToAway_comp_awayToPoly R J i)

@[simp]
theorem awayAlgEquiv_chartCoord (i : J) (j : {j : J // j ≠ i}) :
    awayAlgEquiv R J i (chartCoord R J i j) = X j :=
  awayToPoly_chartCoord R J i j

@[simp]
theorem awayAlgEquiv_symm_X (i : J) (j : {j : J // j ≠ i}) :
    (awayAlgEquiv R J i).symm (X j) = chartCoord R J i j :=
  (awayAlgEquiv R J i).symm_apply_eq.mpr
    (awayAlgEquiv_chartCoord R J i j).symm

omit [Finite J] in
/-- The normalized coordinate used by the arbitrary chart calculation is the
same element as the coordinate used by the projective-coordinate API. -/
theorem chartCoord_eq_coordinates (i : J) (j : {j : J // j ≠ i}) :
    chartCoord (ULift.{u} ℤ) J i j =
      Coordinates.chartCoord i j.1 := by
  apply HomogeneousLocalization.val_injective
  rfl

/-- Under the arbitrary chart equivalence, the existing normalized projective
coordinate `X_j / X_i` is the corresponding affine variable. -/
@[simp]
theorem awayAlgEquiv_coordinates_chartCoord (i j : J) (hji : j ≠ i) :
    awayAlgEquiv (ULift.{u} ℤ) J i (Coordinates.chartCoord i j) =
      X (⟨j, hji⟩ : {j : J // j ≠ i}) := by
  rw [← chartCoord_eq_coordinates J i ⟨j, hji⟩]
  exact awayAlgEquiv_chartCoord (ULift.{u} ℤ) J i ⟨j, hji⟩

/-- The inverse arbitrary chart equivalence sends an affine variable to the
existing normalized projective coordinate. -/
@[simp]
theorem awayAlgEquiv_symm_X_eq_coordinates (i j : J) (hji : j ≠ i) :
    (awayAlgEquiv (ULift.{u} ℤ) J i).symm
        (X (⟨j, hji⟩ : {j : J // j ≠ i})) =
      Coordinates.chartCoord i j := by
  rw [awayAlgEquiv_symm_X, chartCoord_eq_coordinates]

end Finite

end AlgebraicGeometry.ProjectiveSpace.AffineChartAtRing

open CategoryTheory Limits

namespace AlgebraicGeometry.ProjectiveSpace

variable (J : Type u) (i : J) (S : Scheme.{u})

local notation3 "P[" J "]" =>
  homogeneousSubmodule J (ULift ℤ)

/-- The coordinate `X_i` has degree one in the integral homogeneous
coordinate ring. -/
private theorem X_i_mem_deg_one :
    (X i : MvPolynomial J (ULift.{u} ℤ)) ∈ P[J] 1 :=
  isHomogeneous_X _ _

/-- The relative standard chart `D_+(X_i)` in projective space. -/
def affineChartAt : Scheme.{u} :=
  pullback (toProjInt J S)
    (Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one)

namespace affineChartAt

/-- Inclusion of the arbitrary standard chart into relative projective
space. -/
def incl : affineChartAt J i S ⟶ ℙ(J; S) :=
  pullback.fst (toProjInt J S)
    (Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one)

/-- Projection from the relative chart to the affine integral chart. -/
def toSpecAway : affineChartAt J i S ⟶ Spec (.of (Away P[J] (X i))) :=
  pullback.snd (toProjInt J S)
    (Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one)

instance : IsOpenImmersion (incl J i S) := by
  dsimp [incl]
  exact MorphismProperty.pullback_fst _ _
    (Proj.instIsOpenImmersionAwayι P[J] (X i)
      (X_i_mem_deg_one J i) Nat.zero_lt_one)

/-- The chart inclusion followed by the integral projection is the other
pullback projection followed by the integral chart inclusion. -/
@[reassoc]
theorem incl_toProjInt :
    incl J i S ≫ toProjInt J S =
      pullback.snd (toProjInt J S)
          (Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one) ≫
        Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one :=
  pullback.condition

instance : (affineChartAt J i S).CanonicallyOver S where
  hom := incl J i S ≫ (ℙ(J; S) ↘ S)

@[simp]
theorem over_eq : affineChartAt J i S ↘ S = incl J i S ≫ (ℙ(J; S) ↘ S) :=
  rfl

/-- The arbitrary chart is the inverse image of `D_+(X_i)` under the integral
projection. -/
theorem opensRange_incl :
    (incl J i S).opensRange =
      toProjInt J S ⁻¹ᵁ Proj.basicOpen P[J] (X i) := by
  change (pullback.fst (toProjInt J S)
      (Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one)).opensRange = _
  rw [Scheme.Hom.opensRange_pullbackFst, Proj.opensRange_awayι]

section IsoAffineSpace

variable [Finite J]

/-- On integral models, the spectrum of the arbitrary chart ring is affine
space on the complementary coordinates. -/
def specAwayIso :
    Spec (.of (Away P[J] (X i))) ≅
      Spec (.of (MvPolynomial {j : J // j ≠ i} (ULift.{u} ℤ))) :=
  (Scheme.Spec.mapIso
    (((AffineChartAtRing.awayAlgEquiv (ULift.{u} ℤ) J i).toRingEquiv.toCommRingCatIso).op)).symm

private def integralChartIncl :
    Spec (.of (Away P[J] (X i))) ⟶ Proj P[J] :=
  Proj.awayι P[J] (X i) (X_i_mem_deg_one J i) Nat.zero_lt_one

private def flattenIso :
    affineChartAt J i S ≅
      pullback (terminal.from S)
        (integralChartIncl J i ≫ terminal.from (Proj P[J])) :=
  pullbackLeftPullbackSndIso
    (terminal.from S) (terminal.from (Proj P[J])) (integralChartIncl J i)

private def changeChartHom :
    pullback (terminal.from S)
        (integralChartIncl J i ≫ terminal.from (Proj P[J])) ⟶
      𝔸({j : J // j ≠ i}; S) :=
  pullback.map
    (terminal.from S)
    (integralChartIncl J i ≫ terminal.from (Proj P[J]))
    (terminal.from S)
    (terminal.from
      (Spec (.of (MvPolynomial {j : J // j ≠ i} (ULift.{u} ℤ)))))
    (𝟙 S) (specAwayIso J i).hom (𝟙 (⊤_ Scheme)) (by simp) (by simp)

private instance : IsIso (changeChartHom J i S) := by
  dsimp [changeChartHom]
  apply pullback.map_isIso

@[reassoc]
private theorem changeChartHom_over :
    changeChartHom J i S ≫ (𝔸({j : J // j ≠ i}; S) ↘ S) =
      pullback.fst (terminal.from S)
        (integralChartIncl J i ≫ terminal.from (Proj P[J])) := by
  change pullback.lift _ _ _ ≫ pullback.fst _ _ = _
  rw [pullback.lift_fst, Category.comp_id]

omit [Finite J] in
@[reassoc]
private theorem flattenIso_hom_over :
    (flattenIso J i S).hom ≫
        pullback.fst (terminal.from S)
          (integralChartIncl J i ≫ terminal.from (Proj P[J])) =
      pullback.fst (ProjectiveSpace.toProjInt J S) (integralChartIncl J i) ≫
        (ℙ(J; S) ↘ S) :=
  pullbackLeftPullbackSndIso_hom_fst _ _ _

/-- The relative standard chart `D_+(X_i)` is affine space on all coordinates
other than `i`. -/
def isoAffineSpace :
    affineChartAt J i S ≅ 𝔸({j : J // j ≠ i}; S) :=
  flattenIso J i S ≪≫ asIso (changeChartHom J i S)

@[reassoc]
theorem isoAffineSpace_hom_over :
    (isoAffineSpace J i S).hom ≫ (𝔸({j : J // j ≠ i}; S) ↘ S) =
      affineChartAt J i S ↘ S := by
  change ((flattenIso J i S ≪≫ asIso (changeChartHom J i S)).hom) ≫
      (𝔸({j : J // j ≠ i}; S) ↘ S) = affineChartAt J i S ↘ S
  rw [Iso.trans_hom, Category.assoc, asIso_hom, changeChartHom_over,
    flattenIso_hom_over]
  rfl

/-- Under the affine-space identification, the integral polynomial-space
projection is the chart projection followed by the chart-ring equivalence. -/
@[reassoc]
theorem isoAffineSpace_hom_toSpecMvPoly :
    (isoAffineSpace J i S).hom ≫
        AffineSpace.toSpecMvPoly {j : J // j ≠ i} S =
      toSpecAway J i S ≫ (specAwayIso J i).hom := by
  change ((flattenIso J i S).hom ≫ changeChartHom J i S) ≫
      pullback.snd _ _ = _
  rw [Category.assoc]
  change (flattenIso J i S).hom ≫
      (pullback.lift _ _ _ ≫ pullback.snd _ _) = _
  rw [pullback.lift_snd]
  change (flattenIso J i S).hom ≫
      pullback.snd (terminal.from S)
        (integralChartIncl J i ≫ terminal.from (Proj P[J])) ≫
        (specAwayIso J i).hom =
    pullback.snd (ProjectiveSpace.toProjInt J S) (integralChartIncl J i) ≫
      (specAwayIso J i).hom
  exact pullbackLeftPullbackSndIso_hom_snd_assoc _ _ _ _

end IsoAffineSpace

end affineChartAt

end AlgebraicGeometry.ProjectiveSpace
