/-
Copyright (c) 2026 Frenzymath. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Frenzymath
-/
module

public import Mathlib.LinearAlgebra.FreeModule.Basic
public import Mathlib.RingTheory.PicardGroup

/-!
# Invertible modules over nilpotent thickenings

This file records the module-theoretic argument used in the two
`Algebraic-Jacobian` source candidates
`MainProjects/AlgebraicJacobian/MilneKollar/AlgebraicJacobian/Picard/`
`NilpotentThickeningFree.lean` and
`MainProjects/AlgebraicJacobian/PicardAlbanese/AlgebraicJacobian/Tangent/`
`NilpotentThickeningFree.lean`.  If an invertible module is generated by one
element after quotienting by a nilpotent ideal, the element already generates
the module, so the module is free.

The MilneKollar source candidate supplies the cyclic-invertible step directly
from Mathlib and permits separate universes for the ring and module; that is
the proof route extracted here.  The PicardAlbanese candidate reuses a
route-local cyclic lemma and consequently restricts the two types to one
universe, so it is provenance and consumer evidence rather than a dependency.

The iteration is deliberately independent of finite-generation and Jacobson
hypotheses.  Mathlib's Nakayama API (`Submodule.le_of_le_smul_of_le_jacobson_bot`)
is useful in its setting, but its hypotheses are not available or needed here:
nilpotency makes the powers of the ideal reach zero directly.  Nilpotency is
the hypothesis in the generator form of Nakayama's lemma recorded in the
Stacks Project, Tag 00DV, Lemma 10.20.1 (12) (bibliography key
`stacks-project-00DV`).  It is essential: if a Dedekind domain has nontrivial
class group and `L` is a nonprincipal invertible ideal, then `L / mL` is
one-dimensional over `R / m`, hence cyclic, for every maximal ideal `m`, while
`L` is not free.

## Main results

* `Module.Invertible.free_of_span_singleton_eq_top` turns cyclicity of an
  invertible module into freeness.
* `Submodule.top_le_span_sup_pow_smul_top` iterates generation modulo an ideal
  without a finiteness assumption.
* `Module.Invertible.free_of_nilpotent_of_span_sup_smul_eq_top` and
  `Module.Invertible.free_of_nilpotent_of_exists_sub_smul_mem` are the two
  nilpotent-thickening forms used by consumers.
* `Ideal.isNilpotent_of_mul_self_eq_bot` packages the square-zero case.
-/

set_option autoImplicit false

@[expose] public section

universe u v

namespace Module.Invertible

variable {R : Type u} [CommSemiring R] {M : Type v} [AddCommMonoid M] [Module R M]

/-- An invertible module generated by one element is free.

The map `r ↦ r • m` is surjective when `m` spans `M`.  For an invertible
module, `Module.Invertible.bijective_of_surjective` upgrades this map to a
linear equivalence, and `Module.Free.of_equiv` then gives freeness.  The
invertibility assumption is essential: a cyclic torsion module over a ring
need not be free. -/
theorem free_of_span_singleton_eq_top [Module.Invertible R M] {m : M}
    (h : Submodule.span R ({m} : Set M) = ⊤) : Module.Free R M := by
  have hsurj : Function.Surjective (LinearMap.toSpanSingleton R M m) := by
    exact LinearMap.range_eq_top.mp <| (LinearMap.range_toSpanSingleton m).trans h
  exact Module.Free.of_equiv
    (LinearEquiv.ofBijective _ (Module.Invertible.bijective_of_surjective hsurj))

end Module.Invertible

namespace Submodule

variable {R : Type u} [CommSemiring R] {M : Type v} [AddCommMonoid M] [Module R M]

/-- If `N ⊔ I • ⊤` is the top submodule, then so is `N ⊔ I ^ n • ⊤` for every `n`.

This is the finite iteration behind the nilpotent argument.  Multiplying the
equality `M = N + I M` by `I ^ n` gives
`I ^ n M = I ^ n N + I ^ (n + 1) M`; the first summand is already contained in
`N`.  No finite-generation or Jacobson-radical hypothesis is used. -/
theorem top_le_span_sup_pow_smul_top {I : Ideal R} {N : Submodule R M}
    (hN : N ⊔ I • (⊤ : Submodule R M) = ⊤) (n : ℕ) :
    (⊤ : Submodule R M) ≤ N ⊔ (I ^ n) • (⊤ : Submodule R M) := by
  induction n with
  | zero => simp
  | succ n ih =>
    have h₁ : (I ^ n) • (⊤ : Submodule R M)
        = (I ^ n) • N ⊔ (I ^ n) • (I • (⊤ : Submodule R M)) := by
      rw [← Submodule.smul_sup, hN]
    have h₂ : (I ^ n) • (I • (⊤ : Submodule R M)) = (I ^ (n + 1)) • (⊤ : Submodule R M) := by
      rw [← Submodule.smul_assoc, Ideal.smul_eq_mul, ← pow_succ]
    calc
      (⊤ : Submodule R M) ≤ N ⊔ (I ^ n) • (⊤ : Submodule R M) := ih
      _ = N ⊔ ((I ^ n) • N ⊔ (I ^ (n + 1)) • (⊤ : Submodule R M)) := by rw [h₁, h₂]
      _ ≤ N ⊔ (I ^ (n + 1)) • (⊤ : Submodule R M) :=
        sup_le le_sup_left
          (sup_le (le_trans Submodule.smul_le_right le_sup_left) le_sup_right)

end Submodule

namespace Module.Invertible

variable {R : Type u} [CommSemiring R] {M : Type v} [AddCommMonoid M] [Module R M]

/-- If an invertible module is generated modulo a nilpotent ideal by one element,
then it is free.

The hypothesis says `span {m} ⊔ I • ⊤ = ⊤`.  Applying
`Submodule.top_le_span_sup_pow_smul_top` at an exponent killing `I` removes the
second summand, and `free_of_span_singleton_eq_top` finishes.  The proof has no
finite-generation, locality, domain, or field assumptions. -/
theorem free_of_nilpotent_of_span_sup_smul_eq_top [Module.Invertible R M] {I : Ideal R}
    (hI : IsNilpotent I) {m : M}
    (hgen : Submodule.span R ({m} : Set M) ⊔ I • (⊤ : Submodule R M) = ⊤) :
    Module.Free R M := by
  obtain ⟨j, hj⟩ := hI
  refine free_of_span_singleton_eq_top (m := m) (le_antisymm le_top ?_)
  have h := Submodule.top_le_span_sup_pow_smul_top hgen j
  rw [hj] at h
  simpa using h

end Module.Invertible

namespace Module.Invertible

variable {R : Type u} [CommSemiring R] {M : Type v} [AddCommGroup M] [Module R M]

/-- The pointwise form of freeness modulo a nilpotent ideal.

For every `x`, the hypothesis supplies a scalar `r` such that
`x - r • m ∈ I • ⊤`, meaning that the image of `m` generates the quotient by
`I • M`.  The conclusion is free generation before quotienting.  No
finite-generation or Jacobson hypothesis is hidden in this statement. -/
theorem free_of_nilpotent_of_exists_sub_smul_mem [Module.Invertible R M] {I : Ideal R}
    (hI : IsNilpotent I) {m : M}
    (h : ∀ x : M, ∃ r : R, x - r • m ∈ I • (⊤ : Submodule R M)) :
    Module.Free R M := by
  refine free_of_nilpotent_of_span_sup_smul_eq_top hI (m := m) (le_antisymm le_top ?_)
  intro x _
  obtain ⟨r, hr⟩ := h x
  have hx : x = r • m + (x - r • m) := by abel
  rw [hx]
  exact Submodule.add_mem _
    (Submodule.mem_sup_left (Submodule.mem_span_singleton.mpr ⟨r, rfl⟩))
    (Submodule.mem_sup_right hr)

end Module.Invertible

namespace Ideal

variable {R : Type u} [CommSemiring R]

/-- An ideal whose square is zero is nilpotent.

This small helper is useful for first-order thickenings, which naturally
provide `I * I = ⊥` rather than a chosen nilpotency exponent. -/
theorem isNilpotent_of_mul_self_eq_bot {I : Ideal R} (h : I * I = ⊥) : IsNilpotent I :=
  ⟨2, by rw [pow_two]; exact h⟩

end Ideal

end
