/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivisorFamilyAffThetaDescent

/-!
# The intrinsic theta kernel on widened affine pieces

This file supplies the local division statement needed by the kernel of
`AffAdaptation.intrinsicThetaEvalRel`.  Although the theta line is not trivial on an
arbitrary widened piece, its cocycle-glued presentation is componentwise a structure-sheaf
section.  A section lies in the equation-generated theta submodule exactly when every
component germ lies in the divisor's stalk ideal.
-/

set_option autoImplicit false

universe u

open CategoryTheory Opposite TopologicalSpace

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {π : C.left ⟶ P1 k} [IsFinite π]
variable {D : AffCoverData C R} {d : (relCurve C R).LocalEquations}

namespace AffAdaptation

/-! ## Division by a widened equation -/

/-- Cancellation by the restriction of a widened adaptation equation. -/
lemma eqn_res_cancel (A : AffAdaptation D d) (j : D.index)
    {W : (relCurve C R).Opens} (hW : W ≤ D.pieces j)
    {x y : Γ(relCurve C R, W)}
    (h : (relCurve C R).resHom hW (A.eqn j) * x =
      (relCurve C R).resHom hW (A.eqn j) * y) :
    x = y :=
  (mul_cancel_left_mem_nonZeroDivisors
    (Scheme.restriction_mem_nonZeroDivisors
      (fun z hz => A.eqn_regular j z hz) hW)).mp h

/-- A section vanishing along `d` on an open below a widened piece is uniquely divisible
by that piece's equation. -/
theorem existsUnique_eqn_mul_eq (A : AffAdaptation D d) (j : D.index)
    {W : (relCurve C R).Opens} (hW : W ≤ D.pieces j) {s : Γ(relCurve C R, W)}
    (hs : ∀ (z : relCurve C R) (hz : z ∈ W),
      ((relCurve C R).presheaf.germ W z hz).hom s ∈ d.stalkIdeal z) :
    ∃! c : Γ(relCurve C R, W), (relCurve C R).resHom hW (A.eqn j) * c = s := by
  have hb : ∀ (z : relCurve C R) (hz : z ∈ W),
      ((relCurve C R).presheaf.germ W z hz).hom
        ((relCurve C R).resHom hW (A.eqn j)) ∈
          nonZeroDivisors ((relCurve C R).presheaf.stalk z) := by
    intro z hz
    have hswap : ((relCurve C R).presheaf.germ W z hz).hom
        ((relCurve C R).resHom hW (A.eqn j)) =
          ((relCurve C R).presheaf.germ (D.pieces j) z (hW hz)).hom (A.eqn j) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    rw [hswap]
    exact A.eqn_regular j z (hW hz)
  have hmem : s ∈ Ideal.span {(relCurve C R).resHom hW (A.eqn j)} := by
    refine Scheme.mem_span_singleton_of_forall_germ hb (fun z hz => ?_)
    have hswap : ((relCurve C R).presheaf.germ W z hz).hom
        ((relCurve C R).resHom hW (A.eqn j)) =
          ((relCurve C R).presheaf.germ (D.pieces j) z (hW hz)).hom (A.eqn j) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    rw [hswap, A.germ_eqn_span_eq_stalkIdeal j (hW hz)]
    exact hs z hz
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hmem
  rw [mul_comm] at hc
  exact ⟨c, hc, fun y hy => A.eqn_res_cancel j hW (hy.trans hc.symm)⟩

/-- The cofactor of a section vanishing along `d` over a widened piece equation. -/
noncomputable def eqnDiv (A : AffAdaptation D d) (j : D.index)
    {W : (relCurve C R).Opens} (hW : W ≤ D.pieces j) (s : Γ(relCurve C R, W))
    (hs : ∀ (z : relCurve C R) (hz : z ∈ W),
      ((relCurve C R).presheaf.germ W z hz).hom s ∈ d.stalkIdeal z) :
    Γ(relCurve C R, W) :=
  (A.existsUnique_eqn_mul_eq j hW hs).choose

/-- Multiplying the cofactor by the restricted widened equation returns the section. -/
lemma eqn_mul_eqnDiv (A : AffAdaptation D d) (j : D.index)
    {W : (relCurve C R).Opens} (hW : W ≤ D.pieces j) (s : Γ(relCurve C R, W))
    (hs : ∀ (z : relCurve C R) (hz : z ∈ W),
      ((relCurve C R).presheaf.germ W z hz).hom s ∈ d.stalkIdeal z) :
    (relCurve C R).resHom hW (A.eqn j) * A.eqnDiv j hW s hs = s :=
  (A.existsUnique_eqn_mul_eq j hW hs).choose_spec.1

/-! ## Stalkwise membership in the theta vanishing submodule -/

/-- A theta section on one widened piece is generated by the piece equation if and only
if every cocycle component has germ in the divisor's stalk ideal.  This is the
module-valued principal-ideal locality needed by the intrinsic theta kernel, proved here
from the structure-sheaf components rather than assumed as an extra Qcoh hypothesis. -/
theorem mem_thetaPieceVanishing_iff_forall_germ (A : AffAdaptation D d) (a : ℕ)
    (j : D.index) (s : A.ThetaPieceSections (π := π) a j) :
    s ∈ A.thetaPieceVanishing (π := π) a j ↔
      ∀ (q : (thetaChartDatum C R π a).index) (z : relCurve C R)
        (hz : z ∈ D.pieces j ⊓ (thetaChartDatum C R π a).pieces q),
        ((relCurve C R).presheaf.germ
          (D.pieces j ⊓ (thetaChartDatum C R π a).pieces q) z hz).hom (s.val q) ∈
            d.stalkIdeal z := by
  let Mj := A.thetaPieceSectionsModel (π := π) a j
  letI : Scheme.QcohOn (thetaChartDatum C R π a).sheaf (D.pieces j) := Mj.qcoh
  letI : Module Γ(relCurve C R, D.pieces j)
      (A.ThetaPieceSections (π := π) a j) :=
    A.thetaPieceSectionsModule (π := π) a j
  constructor
  · intro hs q z hz
    rw [thetaPieceVanishing, Submodule.ideal_span_singleton_smul] at hs
    obtain ⟨t, -, ht⟩ :=
      (Submodule.mem_smul_pointwise_iff_exists s (A.eqn j) ⊤).mp hs
    have hq := congrArg
      (fun y : A.ThetaPieceSections (π := π) a j => y.val q) ht
    change (Scheme.QcohOn.qsmul (F := (thetaChartDatum C R π a).sheaf)
      (le_refl (D.pieces j)) (A.eqn j) t).val q = s.val q at hq
    rw [Mj.qsmul_eq, gluedQsmul_coe] at hq
    have hgerm := congrArg ((relCurve C R).presheaf.germ
      (D.pieces j ⊓ (thetaChartDatum C R π a).pieces q) z hz).hom hq
    rw [map_mul] at hgerm
    have hswap :
        ((relCurve C R).presheaf.germ
          (D.pieces j ⊓ (thetaChartDatum C R π a).pieces q) z hz).hom
            ((relCurve C R).resHom inf_le_left (A.eqn j)) =
          ((relCurve C R).presheaf.germ (D.pieces j) z hz.1).hom (A.eqn j) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    rw [hswap] at hgerm
    rw [← A.germ_eqn_span_eq_stalkIdeal j hz.1, ← hgerm]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
  · intro hs
    let c : ∀ q : (thetaChartDatum C R π a).index,
        Γ(relCurve C R, D.pieces j ⊓ (thetaChartDatum C R π a).pieces q) :=
      fun q => A.eqnDiv j inf_le_left (s.val q) (hs q)
    have hc (q : (thetaChartDatum C R π a).index) :
        (relCurve C R).resHom
            (inf_le_left : D.pieces j ⊓ (thetaChartDatum C R π a).pieces q ≤ D.pieces j)
            (A.eqn j) * c q = s.val q := by
      simpa only [c] using A.eqn_mul_eqnDiv j inf_le_left (s.val q) (hs q)
    have hc_mem : c ∈ AlgebraicGeometry.gluedSubmodule R
        (thetaChartDatum C R π a).pieces
        (thetaChartDatum C R π a).unit (D.pieces j) := by
      intro q r
      refine A.eqn_res_cancel j (inf_le_left.trans inf_le_left) ?_
      have hL := congrArg ((relCurve C R).resHom
        (inf_le_left : D.pieces j ⊓ (thetaChartDatum C R π a).pieces q ⊓
          (thetaChartDatum C R π a).pieces r ≤
            D.pieces j ⊓ (thetaChartDatum C R π a).pieces q)) (hc q)
      have hR := congrArg ((relCurve C R).resHom
        (gluedInclSnd (thetaChartDatum C R π a).pieces (D.pieces j) q r)) (hc r)
      rw [map_mul] at hL hR
      simp only [Scheme.resHom_resHom] at hL hR
      calc
        _ = (relCurve C R).resHom inf_le_left (s.val q) := hL
        _ = (relCurve C R).resHom
              (gluedInclCoc (thetaChartDatum C R π a).pieces (D.pieces j) q r)
              ((thetaChartDatum C R π a).unit q r :
                Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                  (thetaChartDatum C R π a).pieces r)) *
              (relCurve C R).resHom
                (gluedInclSnd (thetaChartDatum C R π a).pieces (D.pieces j) q r)
                (s.val r) := s.property q r
        _ = (relCurve C R).resHom
              (gluedInclCoc (thetaChartDatum C R π a).pieces (D.pieces j) q r)
              ((thetaChartDatum C R π a).unit q r :
                Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                  (thetaChartDatum C R π a).pieces r)) *
              ((relCurve C R).resHom (inf_le_left.trans inf_le_left) (A.eqn j) *
                (relCurve C R).resHom
                  (gluedInclSnd (thetaChartDatum C R π a).pieces (D.pieces j) q r)
                  (c r)) := by rw [hR]
        _ = (relCurve C R).resHom (inf_le_left.trans inf_le_left) (A.eqn j) *
              ((relCurve C R).resHom
                (gluedInclCoc (thetaChartDatum C R π a).pieces (D.pieces j) q r)
                ((thetaChartDatum C R π a).unit q r :
                  Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                    (thetaChartDatum C R π a).pieces r)) *
                (relCurve C R).resHom
                  (gluedInclSnd (thetaChartDatum C R π a).pieces (D.pieces j) q r)
                  (c r)) := by ring
    let t : A.ThetaPieceSections (π := π) a j := ⟨c, hc_mem⟩
    rw [thetaPieceVanishing, Submodule.ideal_span_singleton_smul]
    apply (Submodule.mem_smul_pointwise_iff_exists s (A.eqn j) ⊤).mpr
    refine ⟨t, Submodule.mem_top, ?_⟩
    apply Subtype.ext
    funext q
    change (Scheme.QcohOn.qsmul (F := (thetaChartDatum C R π a).sheaf)
      (le_refl (D.pieces j)) (A.eqn j) t).val q = s.val q
    rw [Mj.qsmul_eq, gluedQsmul_coe]
    exact hc q

/-- A theta section on a widened piece overlap lies in the symmetric equation-generated
submodule if and only if every cocycle component has germ in the divisor's stalk ideal. -/
theorem mem_thetaOverlapVanishing_iff_forall_germ [IsProper C.hom]
    (A : AffAdaptation D d) (a : ℕ)
    (i j : D.index) (s : A.ThetaOverlapSections (π := π) a i j) :
    s ∈ A.thetaOverlapVanishing (π := π) a i j ↔
      ∀ (q : (thetaChartDatum C R π a).index) (z : relCurve C R)
        (hz : z ∈ (D.pieces i ⊓ D.pieces j) ⊓
          (thetaChartDatum C R π a).pieces q),
        ((relCurve C R).presheaf.germ
          ((D.pieces i ⊓ D.pieces j) ⊓ (thetaChartDatum C R π a).pieces q)
          z hz).hom (s.val q) ∈ d.stalkIdeal z := by
  let Mij := A.thetaOverlapSectionsModel (π := π) a i j
  letI : Scheme.QcohOn (thetaChartDatum C R π a).sheaf
      (D.pieces i ⊓ D.pieces j) := Mij.qcoh
  letI : Module Γ(relCurve C R, D.pieces i ⊓ D.pieces j)
      (A.ThetaOverlapSections (π := π) a i j) :=
    A.thetaOverlapSectionsModule (π := π) a i j
  constructor
  · intro hs q z hz
    rw [thetaOverlapVanishing, A.ovlIdeal_eq_span_left i j,
      Submodule.ideal_span_singleton_smul] at hs
    obtain ⟨t, -, ht⟩ :=
      (Submodule.mem_smul_pointwise_iff_exists s
        (relResAlgHom C R
          (inf_le_left : D.pieces i ⊓ D.pieces j ≤ D.pieces i) (A.eqn i)) ⊤).mp hs
    have hq := congrArg
      (fun y : A.ThetaOverlapSections (π := π) a i j => y.val q) ht
    change (Scheme.QcohOn.qsmul (F := (thetaChartDatum C R π a).sheaf)
      (le_refl (D.pieces i ⊓ D.pieces j))
      (relResAlgHom C R inf_le_left (A.eqn i)) t).val q = s.val q at hq
    rw [Mij.qsmul_eq, gluedQsmul_coe] at hq
    have hgerm := congrArg ((relCurve C R).presheaf.germ
      ((D.pieces i ⊓ D.pieces j) ⊓ (thetaChartDatum C R π a).pieces q)
      z hz).hom hq
    rw [map_mul] at hgerm
    have hswapOverlap :
        ((relCurve C R).presheaf.germ
          ((D.pieces i ⊓ D.pieces j) ⊓ (thetaChartDatum C R π a).pieces q)
          z hz).hom
            ((relCurve C R).resHom inf_le_left
              (relResAlgHom C R inf_le_left (A.eqn i))) =
          ((relCurve C R).presheaf.germ (D.pieces i ⊓ D.pieces j) z hz.1).hom
            (relResAlgHom C R inf_le_left (A.eqn i)) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    have hswapPiece :
        ((relCurve C R).presheaf.germ (D.pieces i ⊓ D.pieces j) z hz.1).hom
            (relResAlgHom C R inf_le_left (A.eqn i)) =
          ((relCurve C R).presheaf.germ (D.pieces i) z hz.1.1).hom (A.eqn i) :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    rw [hswapOverlap, hswapPiece] at hgerm
    rw [← A.germ_eqn_span_eq_stalkIdeal i hz.1.1, ← hgerm]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
  · intro hs
    let c : ∀ q : (thetaChartDatum C R π a).index,
        Γ(relCurve C R, (D.pieces i ⊓ D.pieces j) ⊓
          (thetaChartDatum C R π a).pieces q) :=
      fun q => A.eqnDiv i (inf_le_left.trans inf_le_left) (s.val q) (hs q)
    have hc (q : (thetaChartDatum C R π a).index) :
        (relCurve C R).resHom
            (inf_le_left.trans inf_le_left :
              (D.pieces i ⊓ D.pieces j) ⊓
                (thetaChartDatum C R π a).pieces q ≤ D.pieces i)
            (A.eqn i) * c q = s.val q := by
      simpa only [c] using
        A.eqn_mul_eqnDiv i (inf_le_left.trans inf_le_left) (s.val q) (hs q)
    have hc_mem : c ∈ AlgebraicGeometry.gluedSubmodule R
        (thetaChartDatum C R π a).pieces
        (thetaChartDatum C R π a).unit (D.pieces i ⊓ D.pieces j) := by
      intro q r
      refine A.eqn_res_cancel i ((inf_le_left.trans inf_le_left).trans inf_le_left) ?_
      have hL := congrArg ((relCurve C R).resHom
        (inf_le_left : (D.pieces i ⊓ D.pieces j) ⊓
          (thetaChartDatum C R π a).pieces q ⊓
          (thetaChartDatum C R π a).pieces r ≤
            (D.pieces i ⊓ D.pieces j) ⊓
              (thetaChartDatum C R π a).pieces q)) (hc q)
      have hR := congrArg ((relCurve C R).resHom
        (gluedInclSnd (thetaChartDatum C R π a).pieces
          (D.pieces i ⊓ D.pieces j) q r)) (hc r)
      rw [map_mul] at hL hR
      simp only [Scheme.resHom_resHom] at hL hR
      calc
        _ = (relCurve C R).resHom inf_le_left (s.val q) := hL
        _ = (relCurve C R).resHom
              (gluedInclCoc (thetaChartDatum C R π a).pieces
                (D.pieces i ⊓ D.pieces j) q r)
              ((thetaChartDatum C R π a).unit q r :
                Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                  (thetaChartDatum C R π a).pieces r)) *
              (relCurve C R).resHom
                (gluedInclSnd (thetaChartDatum C R π a).pieces
                  (D.pieces i ⊓ D.pieces j) q r)
                (s.val r) := s.property q r
        _ = (relCurve C R).resHom
              (gluedInclCoc (thetaChartDatum C R π a).pieces
                (D.pieces i ⊓ D.pieces j) q r)
              ((thetaChartDatum C R π a).unit q r :
                Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                  (thetaChartDatum C R π a).pieces r)) *
              ((relCurve C R).resHom
                  ((inf_le_left.trans inf_le_left).trans inf_le_left) (A.eqn i) *
                (relCurve C R).resHom
                  (gluedInclSnd (thetaChartDatum C R π a).pieces
                    (D.pieces i ⊓ D.pieces j) q r)
                  (c r)) := by rw [hR]
        _ = (relCurve C R).resHom
              ((inf_le_left.trans inf_le_left).trans inf_le_left) (A.eqn i) *
              ((relCurve C R).resHom
                (gluedInclCoc (thetaChartDatum C R π a).pieces
                  (D.pieces i ⊓ D.pieces j) q r)
                ((thetaChartDatum C R π a).unit q r :
                  Γ(relCurve C R, (thetaChartDatum C R π a).pieces q ⊓
                    (thetaChartDatum C R π a).pieces r)) *
                (relCurve C R).resHom
                  (gluedInclSnd (thetaChartDatum C R π a).pieces
                    (D.pieces i ⊓ D.pieces j) q r)
                  (c r)) := by ring
    let t : A.ThetaOverlapSections (π := π) a i j := ⟨c, hc_mem⟩
    rw [thetaOverlapVanishing, A.ovlIdeal_eq_span_left i j,
      Submodule.ideal_span_singleton_smul]
    apply (Submodule.mem_smul_pointwise_iff_exists s
      (relResAlgHom C R
        (inf_le_left : D.pieces i ⊓ D.pieces j ≤ D.pieces i) (A.eqn i)) ⊤).mpr
    refine ⟨t, Submodule.mem_top, ?_⟩
    apply Subtype.ext
    funext q
    change (Scheme.QcohOn.qsmul (F := (thetaChartDatum C R π a).sheaf)
      (le_refl (D.pieces i ⊓ D.pieces j))
      (relResAlgHom C R inf_le_left (A.eqn i)) t).val q = s.val q
    rw [Mij.qsmul_eq, gluedQsmul_coe]
    have hrel :
        relResAlgHom C R
            (inf_le_left : D.pieces i ⊓ D.pieces j ≤ D.pieces i) (A.eqn i) =
          (relCurve C R).resHom inf_le_left (A.eqn i) := rfl
    rw [hrel, Scheme.resHom_resHom]
    exact hc q

end AffAdaptation

end AlgebraicGeometry
