/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivisorFamilyAffExtraction
import AlgebraicJacobian.Picard.DivisorIdealSheaf

/-!
# The intrinsic ideal sheaf of a local-equation divisor

On a proper relative curve, the germwise section ideals of a local-equation system satisfy
basic-open localization.  They therefore define an ideal sheaf independently of the affine
adaptation used to prove this fact.  The resulting ideal sheaf is invariant under `DivEq` and
agrees with the previously constructed ideal of every widened affine adaptation.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

universe u

open CategoryTheory Opposite TopologicalSpace

namespace AlgebraicGeometry

namespace Scheme.LocalEquations

variable {X : Scheme.{u}}

/-- Restricting sections sends the germwise section ideal into the section ideal on the
smaller open. -/
theorem map_sectionIdeal_le (d : X.LocalEquations) {U V : X.Opens} (h : V ≤ U) :
    Ideal.map (X.presheaf.map (homOfLE h).op).hom (d.sectionIdeal U) ≤
      d.sectionIdeal V := by
  rw [Ideal.map_le_iff_le_comap]
  intro s hs
  rw [Ideal.mem_comap]
  intro z hz
  rw [TopCat.Presheaf.germ_res_apply]
  exact hs z (h hz)

/-- Divisor equality preserves the germwise ideal of sections on every open. -/
theorem sectionIdeal_eq_of_divEq {d₁ d₂ : X.LocalEquations} (h : d₁.DivEq d₂)
    (U : X.Opens) : d₁.sectionIdeal U = d₂.sectionIdeal U := by
  ext s
  simp only [mem_sectionIdeal_iff]
  constructor
  · intro hs z hz
    rw [← stalkIdeal_eq_of_divEq h z]
    exact hs z hz
  · intro hs z hz
    rw [stalkIdeal_eq_of_divEq h z]
    exact hs z hz

end Scheme.LocalEquations

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {D : AffCoverData C R} {d : (relCurve C R).LocalEquations}

namespace AffAdaptation

/-- On every affine subopen of an adapted piece, the intrinsic section ideal is generated by
the restriction of the adapted equation. -/
theorem sectionIdeal_eq_span_restrict_eqn (A : AffAdaptation D d) (j : D.index)
    {U : (relCurve C R).Opens} (hU : U ≤ D.pieces j) :
    d.sectionIdeal U = Ideal.span {
      ((relCurve C R).presheaf.map (homOfLE hU).op).hom (A.eqn j)} := by
  apply d.sectionIdeal_eq_span_of_generator
  · intro z hz
    rw [TopCat.Presheaf.germ_res_apply]
    exact A.eqn_regular j z (hU hz)
  · intro z hz
    rw [TopCat.Presheaf.germ_res_apply]
    exact A.germ_eqn_span_eq_stalkIdeal j (hU hz)

/-- The Cartier ideal of an adaptation agrees with the intrinsic section ideal on every
affine subopen of one adapted piece. -/
theorem cartierIdeal_ideal_eq_sectionIdeal_of_le [IsProper C.hom]
    (A : AffAdaptation D d) (j : D.index) (U : (relCurve C R).affineOpens)
    (hU : U.1 ≤ D.pieces j) :
    A.cartierIdeal.ideal U = d.sectionIdeal U.1 := by
  rw [← A.cartierIdeal.map_ideal (U := U)
    (V := ⟨D.pieces j, D.isAffineOpen j⟩) hU]
  rw [A.cartierIdeal_ideal_eq_span_eqn j, Ideal.map_span, Set.image_singleton]
  exact (A.sectionIdeal_eq_span_restrict_eqn j hU).symm

/-- The Cartier ideal of any widened adaptation is the germwise section ideal on every
affine open of the relative curve. -/
theorem cartierIdeal_ideal_eq_sectionIdeal_affine [IsProper C.hom]
    (A : AffAdaptation D d) (U : (relCurve C R).affineOpens) :
    A.cartierIdeal.ideal U = d.sectionIdeal U.1 := by
  apply le_antisymm
  · intro s hs z hz
    obtain ⟨j, hzj⟩ := D.exists_mem_pieces z
    let W : (relCurve C R).affineOpens :=
      ⟨U.1 ⊓ D.pieces j, Over.isAffineOpen_inf C U.2 (D.isAffineOpen j)⟩
    have hsW :
        ((relCurve C R).presheaf.map
          (homOfLE (inf_le_left : W.1 ≤ U.1)).op).hom s ∈
          A.cartierIdeal.ideal W := by
      rw [← A.cartierIdeal.map_ideal (U := W) (V := U)
        (show W.1 ≤ U.1 from inf_le_left)]
      exact Ideal.mem_map_of_mem _ hs
    rw [A.cartierIdeal_ideal_eq_sectionIdeal_of_le j W inf_le_right] at hsW
    have hzW : z ∈ W.1 := ⟨hz, hzj⟩
    have := hsW z hzW
    rw [TopCat.Presheaf.germ_res_apply] at this
    exact this
  · have hlocal : ∀ x : U.1, ∃ (j : D.index) (r : Γ(relCurve C R, U.1))
        (rj : Γ(relCurve C R, D.pieces j)),
        (relCurve C R).basicOpen r = (relCurve C R).basicOpen rj ∧
          x.1 ∈ (relCurve C R).basicOpen r := by
      intro ⟨x, hxU⟩
      obtain ⟨j, hxj⟩ := D.exists_mem_pieces x
      exact ⟨j, exists_basicOpen_le_affine_inter U.2 (D.isAffineOpen j) x ⟨hxU, hxj⟩⟩
    choose j r rj hr hx using hlocal
    have hspan : Ideal.span (Set.range r) = ⊤ := by
      rw [← U.2.self_le_iSup_basicOpen_iff]
      exact fun x hxU ↦
        Opens.mem_iSup.mpr ⟨⟨_, ⟨x, hxU⟩, rfl⟩, hx ⟨x, hxU⟩⟩
    have inst := U.2.isLocalization_basicOpen
    refine Submodule.le_of_isLocalized_span _ hspan
      (fun q ↦ Γ(relCurve C R, (relCurve C R).basicOpen q.1))
      (fun q ↦ Algebra.linearMap Γ(relCurve C R, U.1)
        Γ(relCurve C R, (relCurve C R).basicOpen q.1)) ?_
    rintro ⟨_, x, rfl⟩
    simp +instances only [← Submodule.restrictScalars_localized'
      Γ(relCurve C R, (relCurve C R).basicOpen (r x)),
      Ideal.localized'_eq_map, RingHom.algebraMap_toAlgebra]
    erw [A.cartierIdeal.map_ideal
      (U := ⟨_, U.2.basicOpen (r x)⟩) ((relCurve C R).basicOpen_le (r x))]
    have hpiece : (relCurve C R).basicOpen (r x) ≤ D.pieces (j x) := by
      rw [hr x]
      exact (relCurve C R).basicOpen_le (rj x)
    rw [A.cartierIdeal_ideal_eq_sectionIdeal_of_le (j x)
      ⟨_, U.2.basicOpen (r x)⟩ hpiece]
    exact d.map_sectionIdeal_le ((relCurve C R).basicOpen_le (r x))

end AffAdaptation

namespace Scheme.LocalEquations

/-- On a proper relative curve, the germwise section ideals commute with localization to
affine basic opens. -/
theorem sectionIdeal_map_ideal_basicOpen [IsProper C.hom]
    (d : (relCurve C R).LocalEquations) (U : (relCurve C R).affineOpens)
    (f : Γ(relCurve C R, U.1)) :
    Ideal.map ((relCurve C R).presheaf.map
      (homOfLE ((relCurve C R).basicOpen_le f)).op).hom (d.sectionIdeal U.1) =
      d.sectionIdeal ((relCurve C R).affineBasicOpen f).1 := by
  obtain ⟨D, ⟨A⟩⟩ := exists_affAdaptation_of_isProper C R d
  rw [← A.cartierIdeal_ideal_eq_sectionIdeal_affine U,
    ← A.cartierIdeal_ideal_eq_sectionIdeal_affine
      ((relCurve C R).affineBasicOpen f)]
  exact A.cartierIdeal.map_ideal_basicOpen U f

/-- The intrinsic Cartier ideal sheaf cut out by a local-equation divisor on a proper
relative curve. -/
noncomputable def cartierIdealData [IsProper C.hom]
    (d : (relCurve C R).LocalEquations) : (relCurve C R).IdealSheafData where
  ideal U := d.sectionIdeal U.1
  map_ideal_basicOpen := d.sectionIdeal_map_ideal_basicOpen

@[simp]
theorem cartierIdealData_ideal [IsProper C.hom]
    (d : (relCurve C R).LocalEquations) (U : (relCurve C R).affineOpens) :
    d.cartierIdealData.ideal U = d.sectionIdeal U.1 :=
  rfl

/-- The intrinsic Cartier ideal sheaf is invariant under divisor equality. -/
theorem cartierIdealData_eq_of_divEq [IsProper C.hom]
    {d₁ d₂ : (relCurve C R).LocalEquations} (h : d₁.DivEq d₂) :
    d₁.cartierIdealData = d₂.cartierIdealData := by
  apply Scheme.IdealSheafData.ext
  funext U
  exact sectionIdeal_eq_of_divEq h U.1

end Scheme.LocalEquations

namespace AffAdaptation

/-- The intrinsic Cartier ideal sheaf agrees with the ideal sheaf constructed from every
widened affine adaptation. -/
theorem cartierIdealData_eq_cartierIdeal [IsProper C.hom]
    (A : AffAdaptation D d) : d.cartierIdealData = A.cartierIdeal := by
  apply Scheme.IdealSheafData.ext_of_iSup_eq_top
    (fun j : D.index ↦ ⟨D.pieces j, D.isAffineOpen j⟩) D.cover
  intro j
  exact (A.cartierIdeal_ideal_eq_sectionIdeal j).symm

end AffAdaptation

end AlgebraicGeometry
