/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivisorFamilyAffTheta

/-!
# The section ideal of a Cartier divisor

This file packages the cover-independent ideal of sections whose germs lie in the stalk
ideal of a local-equation system.  On any open carrying one regular generator, this ideal
is the principal ideal generated by that section.  In particular, every widened adapted
affine piece presents its colength algebra as the quotient by the same intrinsic ideal.

This is the local input for constructing the Cartier divisor subscheme and descending the
intrinsic theta line without a `SwallowedBy` hypothesis or a fixed `P1` chart partition.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

universe u

open CategoryTheory Opposite TopologicalSpace

namespace AlgebraicGeometry

namespace Scheme.LocalEquations

variable {X : Scheme.{u}}

/-- Sections whose germ at every point lies in the intrinsic stalk ideal of `d`. -/
noncomputable def sectionIdeal (d : X.LocalEquations) (U : X.Opens) : Ideal Γ(X, U) where
  carrier := {s | ∀ (z : X) (hz : z ∈ U),
    (X.presheaf.germ U z hz).hom s ∈ d.stalkIdeal z}
  zero_mem' := by
    intro z hz
    rw [map_zero]
    exact Ideal.zero_mem _
  add_mem' := by
    intro s t hs ht z hz
    rw [map_add]
    exact Ideal.add_mem _ (hs z hz) (ht z hz)
  smul_mem' := by
    intro r s hs z hz
    rw [smul_eq_mul, map_mul]
    exact Ideal.mul_mem_left _ _ (hs z hz)

/-- Membership in the section ideal is the defining germwise condition. -/
lemma mem_sectionIdeal_iff {d : X.LocalEquations} {U : X.Opens} {s : Γ(X, U)} :
    s ∈ d.sectionIdeal U ↔ ∀ (z : X) (hz : z ∈ U),
      (X.presheaf.germ U z hz).hom s ∈ d.stalkIdeal z :=
  Iff.rfl

/-- A germwise regular section which generates the intrinsic stalk ideal at every point
generates the section ideal. -/
theorem sectionIdeal_eq_span_of_generator (d : X.LocalEquations) {U : X.Opens}
    (b : Γ(X, U))
    (hreg : ∀ (z : X) (hz : z ∈ U),
      (X.presheaf.germ U z hz).hom b ∈ nonZeroDivisors (X.presheaf.stalk z))
    (hspan : ∀ (z : X) (hz : z ∈ U),
      Ideal.span {(X.presheaf.germ U z hz).hom b} = d.stalkIdeal z) :
    d.sectionIdeal U = Ideal.span {b} := by
  apply le_antisymm
  · intro s hs
    apply Scheme.mem_span_singleton_of_forall_germ hreg
    intro z hz
    rw [hspan z hz]
    exact hs z hz
  · rw [Ideal.span_singleton_le_iff_mem]
    intro z hz
    rw [← hspan z hz]
    exact Ideal.subset_span (Set.mem_singleton _)

/-- On every subopen of a member of the local-equation cover, the section ideal is
generated by the restricted local equation. -/
theorem sectionIdeal_eq_span_restrict (d : X.LocalEquations) (x : X) {U : X.Opens}
    (hU : U ≤ d.cover.opens x) :
    d.sectionIdeal U = Ideal.span {
      (X.presheaf.map (homOfLE hU).op).hom (d.eqn x)} := by
  apply d.sectionIdeal_eq_span_of_generator
  · intro z hz
    rw [TopCat.Presheaf.germ_res_apply]
    exact d.regular x z (hU hz)
  · intro z hz
    rw [TopCat.Presheaf.germ_res_apply]
    exact d.germ_eqn_span_eq x z (hU hz)

end Scheme.LocalEquations

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]

namespace AffAdaptation

variable {D : AffCoverData C R} {d : (relCurve C R).LocalEquations}

/-- Every widened adapted piece presents the intrinsic section ideal by its recorded
equation.  The statement is independent of a chart typing and of the certificate. -/
theorem sectionIdeal_eq_span_eqn (A : AffAdaptation D d) (j : D.index) :
    d.sectionIdeal (D.pieces j) = Ideal.span {A.eqn j} := by
  apply d.sectionIdeal_eq_span_of_generator
  · exact A.eqn_regular j
  · intro z hz
    exact A.germ_eqn_span_eq_stalkIdeal j hz

end AffAdaptation

end AlgebraicGeometry
