/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeHighWindowKoszul

/-!
# Reducing finite multiplication syzygies to a pencil

The first Koszul relation problem for a large multiplier space can be reduced
to two distinguished linear combinations of its basis.  If those two
combinations generate the middle window from the preceding window, and their
two-term multiplication kernel is the usual pencil relation, then every
relation for the full multiplier basis is generated by the finite Koszul
boundary.

This is the linear-algebra half of the basepoint-free pencil argument.  Its
geometric inputs are deliberately hypotheses: the high-window application
will obtain them from the two fibre coordinates and one lower-window `H^1`
vanishing statement.
-/

set_option autoImplicit false

universe u v

open CategoryTheory TopologicalSpace Opposite

namespace AlgebraicGeometry

variable {R L M N : Type u} [CommRing R]
variable [AddCommGroup L] [Module R L]
variable [AddCommGroup M] [Module R M]
variable [AddCommGroup N] [Module R N]
variable {ι : Type v} [Fintype ι]

/-- Two coefficient rows reduce the full finite-component relation problem to
their two-term relation problem.

The first hypothesis says that the two coefficient combinations of `step`
span `M`.  The second is the basepoint-free pencil trick for those same two
combinations.  The conclusion is the reverse inclusion missing from the
generic finite Koszul construction. -/
theorem ker_finiteComponentSum_le_range_finiteKoszulBoundary_of_pencil
    (row : ι → M →ₗ[R] N) (step : ι → L →ₗ[R] M)
    (c : Fin 2 → ι → R)
    (hcomm : ∀ (i j : ι) (z : L),
      row i (step j z) = row j (step i z))
    (hspan : ∀ x : M, ∃ z : Fin 2 → L,
      x = ∑ q, ∑ i, c q i • step i (z q))
    (hpencil : ∀ y : Fin 2 → M,
      (∑ q, ∑ i, c q i • row i (y q)) = 0 →
        ∃ z : L,
          y 0 = ∑ i, c 1 i • step i z ∧
          y 1 = -∑ i, c 0 i • step i z) :
    LinearMap.ker (finiteComponentSum row) ≤
      LinearMap.range (finiteKoszulBoundary step) := by
  classical
  intro x hx
  choose d hd using fun i => hspan (x i)
  let y : Fin 2 → M := fun q => ∑ i, step i (d i q)
  let zMain : ι × ι → L := fun ij => ∑ q, c q ij.2 • d ij.1 q
  have hzMain : ∀ i,
      finiteKoszulBoundary step zMain i = x i - ∑ q, c q i • y q := by
    intro i
    rw [finiteKoszulBoundary_apply]
    simp only [zMain, y, map_sum, map_smul]
    rw [Finset.sum_sub_distrib]
    have hleft : (∑ j, ∑ q, c q j • step j (d i q)) = x i := by
      rw [hd i, Finset.sum_comm]
    rw [hleft]
    congr 1
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro q hq
    rw [Finset.smul_sum]
  have hpairZero : (∑ q, ∑ i, c q i • row i (y q)) = 0 := by
    have hx0 : finiteComponentSum row x = 0 := LinearMap.mem_ker.mp hx
    have hboundary0 : finiteComponentSum row (finiteKoszulBoundary step zMain) = 0 :=
      LinearMap.mem_ker.mp
        (range_finiteKoszulBoundary_le_ker_finiteComponentSum row step hcomm
          (LinearMap.mem_range_self (finiteKoszulBoundary step) zMain))
    have hdiff : x - finiteKoszulBoundary step zMain =
        fun i => ∑ q, c q i • y q := by
      funext i
      simp only [Pi.sub_apply, hzMain i, sub_sub_cancel]
    have hzero : finiteComponentSum row
        (fun i => ∑ q, c q i • y q) = 0 := by
      rw [← hdiff, map_sub, hx0, hboundary0, sub_zero]
    simp only [finiteComponentSum, LinearMap.sum_apply, LinearMap.comp_apply,
      LinearMap.proj_apply, map_sum, map_smul] at hzero
    rw [Finset.sum_comm] at hzero
    exact hzero
  obtain ⟨a, hy0, hy1⟩ := hpencil y hpairZero
  let zPair : ι × ι → L := fun ij => (c 0 ij.1 * c 1 ij.2) • a
  have hzPair : ∀ i,
      finiteKoszulBoundary step zPair i = ∑ q, c q i • y q := by
    intro i
    rw [finiteKoszulBoundary_apply, Finset.sum_sub_distrib]
    simp only [zPair, map_smul]
    calc
      (∑ j, (c 0 i * c 1 j) • step j a) -
          ∑ j, (c 0 j * c 1 i) • step j a =
          c 0 i • (∑ j, c 1 j • step j a) -
            c 1 i • (∑ j, c 0 j • step j a) := by
        rw [Finset.smul_sum, Finset.smul_sum]
        apply congrArg₂ (· - ·)
        · apply Finset.sum_congr rfl
          intro j hj
          rw [smul_smul]
        · apply Finset.sum_congr rfl
          intro j hj
          rw [smul_smul, mul_comm (c 1 i)]
      _ = c 0 i • y 0 + c 1 i • y 1 := by
        rw [hy0, hy1, smul_neg]
        abel
      _ = ∑ q, c q i • y q := by rw [Fin.sum_univ_two]
  refine ⟨zMain + zPair, ?_⟩
  funext i
  simp only [map_add, Pi.add_apply, hzMain i, hzPair i, sub_add_cancel]

/-- Equality form of the pencil reduction, combining the hard reverse
inclusion with the universal rows-minus-columns inclusion. -/
theorem ker_finiteComponentSum_eq_range_finiteKoszulBoundary_of_pencil
    (row : ι → M →ₗ[R] N) (step : ι → L →ₗ[R] M)
    (c : Fin 2 → ι → R)
    (hcomm : ∀ (i j : ι) (z : L),
      row i (step j z) = row j (step i z))
    (hspan : ∀ x : M, ∃ z : Fin 2 → L,
      x = ∑ q, ∑ i, c q i • step i (z q))
    (hpencil : ∀ y : Fin 2 → M,
      (∑ q, ∑ i, c q i • row i (y q)) = 0 →
        ∃ z : L,
          y 0 = ∑ i, c 1 i • step i z ∧
          y 1 = -∑ i, c 0 i • step i z) :
    LinearMap.ker (finiteComponentSum row) =
      LinearMap.range (finiteKoszulBoundary step) := by
  apply le_antisymm
  · exact ker_finiteComponentSum_le_range_finiteKoszulBoundary_of_pencil
      row step c hcomm hspan hpencil
  · exact range_finiteKoszulBoundary_le_ker_finiteComponentSum row step hcomm

/-! ## Multiplication by a basis of function-field subspaces -/

attribute [local instance] Scheme.overModule Scheme.functionFieldOverModule

variable {K : Type u} [Field K]
variable {X : Scheme.{u}} [X.Over (Spec (CommRingCat.of K))] [IsIntegral X]

private theorem Scheme.sum_repr_mul
    (U : Submodule K X.functionField) (b : Module.Basis ι K U)
    (a : U) (z : X.functionField) :
    (∑ i, (b.repr a i) • ((b i : X.functionField) * z)) =
      (a : X.functionField) * z := by
  have hterm : ∀ i,
      (b.repr a i) • ((b i : X.functionField) * z) =
        ((b.repr a i) • (b i : X.functionField)) * z := by
    intro i
    rw [Scheme.functionFieldOverModule_smul_def,
      Scheme.functionFieldOverModule_smul_def]
    ring
  simp_rw [hterm]
  rw [← Finset.sum_mul]
  congr 1
  calc
    (∑ i, (b.repr a i) • (b i : X.functionField)) =
        ((∑ i, (b.repr a i) • b i : U) : X.functionField) := by
      symm
      exact Submodule.coe_sum U (fun i => (b.repr a i) • b i) Finset.univ
    _ = a := by rw [b.sum_repr]

/-- Function-field multiplication form of the pencil reduction.  Two
distinguished sections of `U` are expressed in the arbitrary basis `b`; no
basis replacement is required. -/
theorem Scheme.ker_finiteMulMap_eq_range_finiteMulKoszulBoundary_of_pencil
    (U L T : Submodule K X.functionField) (b : Module.Basis ι K U)
    (hmul : ∀ (i : ι) (z : L),
      (b i : X.functionField) * (z : X.functionField) ∈ T)
    (a : Fin 2 → U)
    (hspan : ∀ x : T, ∃ z : Fin 2 → L,
      (x : X.functionField) =
        ∑ q, (a q : X.functionField) * (z q : X.functionField))
    (hpencil : ∀ y : Fin 2 → T,
      (∑ q, (a q : X.functionField) * (y q : X.functionField)) = 0 →
        ∃ z : L,
          (y 0 : X.functionField) =
              (a 1 : X.functionField) * (z : X.functionField) ∧
          (y 1 : X.functionField) =
              -(a 0 : X.functionField) * (z : X.functionField)) :
    LinearMap.ker (Scheme.finiteMulMap U T b) =
      LinearMap.range (Scheme.finiteMulKoszulBoundary U L T b hmul) := by
  classical
  let row : ι → T →ₗ[K] X.functionField := fun i =>
    (Scheme.mulLinear K (b i : X.functionField)).comp T.subtype
  let step : ι → L →ₗ[K] T := fun i => Scheme.finiteMulStepTo U L T b hmul i
  let c : Fin 2 → ι → K := fun q => b.repr (a q)
  change LinearMap.ker (finiteComponentSum row) =
    LinearMap.range (finiteKoszulBoundary step)
  apply ker_finiteComponentSum_eq_range_finiteKoszulBoundary_of_pencil
    row step c
  · intro i j z
    change
      (b i : X.functionField) * ((b j : X.functionField) * (z : X.functionField)) =
        (b j : X.functionField) * ((b i : X.functionField) * (z : X.functionField))
    ring
  · intro x
    obtain ⟨z, hz⟩ := hspan x
    refine ⟨z, ?_⟩
    apply Subtype.ext
    simp only [step, c, Submodule.coe_sum, Submodule.coe_smul,
      Scheme.finiteMulStepTo_apply]
    rw [hz]
    apply Finset.sum_congr rfl
    intro q hq
    exact (Scheme.sum_repr_mul U b (a q) (z q : X.functionField)).symm
  · intro y hy
    have hy' : (∑ q, (a q : X.functionField) * (y q : X.functionField)) = 0 := by
      rw [← hy]
      apply Finset.sum_congr rfl
      intro q hq
      simpa only [row, c, LinearMap.comp_apply, Submodule.subtype_apply,
        Scheme.mulLinear_apply] using
        (Scheme.sum_repr_mul U b (a q) (y q : X.functionField)).symm
    obtain ⟨z, hz0, hz1⟩ := hpencil y hy'
    refine ⟨z, ?_, ?_⟩
    · apply Subtype.ext
      simpa only [step, c, Submodule.coe_sum, Submodule.coe_smul,
        Scheme.finiteMulStepTo_apply] using
        hz0.trans (Scheme.sum_repr_mul U b (a 1) (z : X.functionField)).symm
    · apply Subtype.ext
      simp only [step, c, Submodule.coe_neg, Submodule.coe_sum, Submodule.coe_smul,
        Scheme.finiteMulStepTo_apply]
      rw [Scheme.sum_repr_mul]
      simpa only [neg_mul] using hz1

end AlgebraicGeometry
