/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeSeedUnivRead
import AlgebraicJacobian.Picard.DivSchemeRedesignCascade
import AlgebraicJacobian.Picard.SectionsToDivisors

/-!
# The generic-fibre branch of the pointwise seed

The relative achiever theorem is intentionally a closed-point theorem on the fibre.  When a
total point specializes to the generic point of its residue-field fibre, no order comparison
is needed: a nonzero fibre reading has a nonzero germ in the function field, hence is a unit.
This file records that elementary but useful branch.

The results are stated for an arbitrary base-change window vector and an arbitrary section of
the pinned chart.  They prove, respectively, that the compared reading germ is a unit, that
its principal ideal is the whole generic stalk, and that it divides every chart germ.  All
claims remain on the fibre curve over a field; no total-stalk flatness or base-change
identification is asserted here.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

open Scheme

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule

section GenericFibre

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
variable (R : Type u) [CommRing R] [Algebra k R]
variable (K : Type u) [Field K] [Algebra k K] [Algebra R K] [IsScalarTower k R K]
variable (π : C.left ⟶ P1 k) [IsFinite π]

noncomputable local instance instOverCleftGenericFibre : C.left.Over (Spec (.of k)) :=
  ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))] [QuasiCompact (C.left ↘ Spec (.of k))]
  [IsDominant π]
variable (a : ℕ)
variable (hH1 : Subsingleton (relTwistPair C k π (relThetaCocycle C k π a)).H1)
variable [IsIntegral (relCurve C K)]
  [SmoothOfRelativeDimension 1 (relCurve C K ↘ Spec (CommRingCat.of K))]
  [QuasiCompact (relCurve C K ↘ Spec (CommRingCat.of K))]

set_option maxHeartbeats 1000000 in
-- The nonzero bridge and generic-stalk injectivity elaborate through the mixed curve/product
-- spellings and the residue-field tower.
set_option synthInstance.maxHeartbeats 500000 in
set_option maxRecDepth 8000 in
/-- A nonzero compared window vector gives a **unit** generic germ of the corresponding
relative reading on any pinned chart containing the fibre generic point.

The compared-side bridge first gives a nonzero chart section.  Injectivity of germs on the
integral fibre makes its generic germ nonzero, and the generic stalk is the function field.
-/
theorem isUnit_germ_genericPoint_of_windowCompare_ne_zero
    (b : Bool)
    (hη : genericPoint (relCurve C K) ∈ relPinnedChart C K π b)
    {x : R ⊗[k] ↥(Scheme.divisorSections k (a • fiberWeilDivisor π) ⊤)}
    (hx : windowCompare R K x ≠ 0) :
    IsUnit (((relCurve C K).presheaf.germ (relPinnedChart C K π b)
      (genericPoint (relCurve C K)) hη).hom
      (relPinnedSectionsMap C R K π b
        (relThetaResSide a b le_rfl (relThetaWindowEquiv C R π a hH1 x)))) := by
  have hb : relPinnedChart C K π b ≠ ⊥ := by
    intro hbot
    rw [hbot] at hη
    exact hη
  have hs := relPinnedSectionsMap_relThetaResSide_ne_zero C R K π a hH1 b hx hb
  have hg : ((relCurve C K).presheaf.germ (relPinnedChart C K π b)
      (genericPoint (relCurve C K)) hη).hom
      (relPinnedSectionsMap C R K π b
        (relThetaResSide a b le_rfl (relThetaWindowEquiv C R π a hH1 x))) ≠ 0 := by
    intro h0
    apply hs
    apply germ_injective_of_isIntegral (relCurve C K) (genericPoint (relCurve C K)) hη
    rw [h0, map_zero]
  exact isUnit_iff_ne_zero.mpr hg

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 500000 in
set_option maxRecDepth 8000 in
/-- The generic-point principal ideal generated by a nonzero compared reading is the whole
generic stalk.  This is the precise fibre-generic replacement for the closed-point achiever
divisibility statement.
-/
theorem span_germ_genericPoint_eq_top_of_windowCompare_ne_zero
    (b : Bool)
    (hη : genericPoint (relCurve C K) ∈ relPinnedChart C K π b)
    {x : R ⊗[k] ↥(Scheme.divisorSections k (a • fiberWeilDivisor π) ⊤)}
    (hx : windowCompare R K x ≠ 0) :
    Ideal.span {((relCurve C K).presheaf.germ (relPinnedChart C K π b)
      (genericPoint (relCurve C K)) hη).hom
      (relPinnedSectionsMap C R K π b
        (relThetaResSide a b le_rfl (relThetaWindowEquiv C R π a hH1 x)))} = ⊤ :=
  Ideal.span_singleton_eq_top.mpr
    (isUnit_germ_genericPoint_of_windowCompare_ne_zero C R K π a hH1 b hη hx)

set_option maxHeartbeats 1000000 in
set_option synthInstance.maxHeartbeats 500000 in
set_option maxRecDepth 8000 in
/-- At the generic point, the nonzero compared reading divides every section of the pinned
chart.  In particular this applies to every fibre reading coming from the universal window.
-/
theorem germ_genericPoint_dvd_of_windowCompare_ne_zero
    (b : Bool)
    (hη : genericPoint (relCurve C K) ∈ relPinnedChart C K π b)
    {x : R ⊗[k] ↥(Scheme.divisorSections k (a • fiberWeilDivisor π) ⊤)}
    (hx : windowCompare R K x ≠ 0)
    (t : Γ(relCurve C K, relPinnedChart C K π b)) :
    ((relCurve C K).presheaf.germ (relPinnedChart C K π b)
      (genericPoint (relCurve C K)) hη).hom
      (relPinnedSectionsMap C R K π b
        (relThetaResSide a b le_rfl (relThetaWindowEquiv C R π a hH1 x))) ∣
      ((relCurve C K).presheaf.germ (relPinnedChart C K π b)
        (genericPoint (relCurve C K)) hη).hom t :=
  (isUnit_germ_genericPoint_of_windowCompare_ne_zero C R K π a hH1 b hη hx).dvd

end GenericFibre

end AlgebraicGeometry
