/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeHighWindowDirectLimit
import AlgebraicJacobian.Picard.DivSchemeHighWindowMulCompatibility
import AlgebraicJacobian.Picard.DivSchemeMulIdealFinite
import AlgebraicJacobian.Picard.DivisorFamilyWindowUnitGeneration
import AlgebraicJacobian.Picard.DivSchemeSeedUnivMulIdeal

/-!
# Chart readings of successor relation modules

The recursive high-window relation at a successor is generated by multiplying the
preceding relation by the finite multiplier window.  This file records the chart
reading formula behind that construction and its immediate ideal containment.
The multiplier-window readings generate `1` on each pinned chart, so the finite
unit-generation bridge upgrades the containment to equality.  Consequently all
recursive relation stages from index one onward have the same genuine reading ideal.
-/

set_option autoImplicit false
set_option quotPrecheck false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 8
set_option maxRecDepth 8000
set_option linter.unusedSectionVars false

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

open Scheme Grassmannian

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule
attribute [local instance 10000] relCurve.instOver

section HighWindowRelationRead

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
  [SmoothOfRelativeDimension 1 C.hom] [IsProper C.hom]
  [GeometricallyIrreducible C.hom]
variable {pi : C.left ⟶ P1 k} [IsFinite pi] [IsDominant pi]

noncomputable local instance instOverCleftHighWindowRelationRead :
    C.left.Over (Spec (.of k)) := ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))]
  [QuasiCompact (C.left ↘ Spec (.of k))]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hpi : pi ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))
variable (g r1 r2 : Nat)
variable (b1 : Module.Basis (Fin r1) k
  ↥(Scheme.divisorSections k (windowM_choice pi hpi g • fiberWeilDivisor pi) ⊤))
variable (b2 : Module.Basis (Fin r2) k
  ↥(Scheme.divisorSections k ((windowS_choice pi hpi g • fiberWeilDivisor pi)
    + (windowM_choice pi hpi g • fiberWeilDivisor pi)) ⊤))
variable (i : (glueData k g r1).J) (j : (glueData k g r2).J)

local notation "RZ" => DivCarveChartRing k
  (windowS_choice pi hpi g • fiberWeilDivisor pi)
  (windowM_choice pi hpi g • fiberWeilDivisor pi) g r1 r2 b1 b2 i j
local notation "HS" => ↥(Scheme.divisorSections k
  (windowS_choice pi hpi g • fiberWeilDivisor pi) ⊤)

/-! ## Range transport along ambient reindexings -/

private theorem span_range_comp_surjective
    {R B M N : Type*} [CommRing R] [CommRing B] [Algebra R B]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (f : M →ₗ[R] B) (e : N →ₗ[R] M) (he : Function.Surjective e) :
    Ideal.span (Set.range (f.comp e)) = Ideal.span (Set.range f) := by
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨x, rfl⟩
    exact Ideal.subset_span ⟨e x, rfl⟩
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨x, rfl⟩
    obtain ⟨y, rfl⟩ := he x
    exact Ideal.subset_span ⟨y, rfl⟩

private theorem span_range_read_map_submodule_map
    {R A A' B : Type*} [CommRing R] [CommRing B] [Algebra R B]
    [AddCommGroup A] [Module R A] [AddCommGroup A'] [Module R A']
    (f : A' →ₗ[R] B) (e : A →ₗ[R] A') (N : Submodule R A) :
    Ideal.span (Set.range (f.comp (Submodule.map e N).subtype)) =
      Ideal.span (Set.range ((f.comp e).comp N.subtype)) := by
  let em := e.submoduleMap N
  calc
    Ideal.span (Set.range (f.comp (Submodule.map e N).subtype)) =
        Ideal.span (Set.range ((f.comp (Submodule.map e N).subtype).comp em)) := by
      symm
      exact span_range_comp_surjective
        (f := f.comp (Submodule.map e N).subtype) (e := em)
          (LinearMap.submoduleMap_surjective e N)
    _ = Ideal.span (Set.range ((f.comp e).comp N.subtype)) := by
      have hmaps :
          (f.comp (Submodule.map e N).subtype).comp em =
            (f.comp e).comp N.subtype := by
        apply LinearMap.ext
        intro x
        rfl
      rw [hmaps]

private theorem relThetaResSide_relThetaWindowEquiv_baseChange_ofEq_seed
    {p q : Nat} (h : p = q)
    (hp : Subsingleton
      (relTwistPair C k pi (relThetaCocycle C k pi p)).H1)
    (hq : Subsingleton
      (relTwistPair C k pi (relThetaCocycle C k pi q)).H1)
    (R : Type u) [CommRing R] [Algebra k R] (side : Bool)
    (x : R ⊗[k] ↥(divisorSections k (p • fiberWeilDivisor pi) ⊤)) :
    relThetaResSide q side le_rfl
        (relThetaWindowEquiv C R pi q hq
          (LinearMap.baseChange R
            (divisorWindowExponentEquiv (C := C) (pi := pi) h).toLinearMap x)) =
      relThetaResSide p side le_rfl
        (relThetaWindowEquiv C R pi p hp x) := by
  subst q
  have heq :
      (divisorWindowExponentEquiv (C := C) (pi := pi) (rfl : p = p)).toLinearMap =
        LinearMap.id := by
    apply LinearMap.ext
    intro y
    rfl
  rw [heq, LinearMap.baseChange_id, LinearMap.id_apply]

/-! The submodule spelling is placed before the seed anchors because the anchor
lemmas compare the public relation-reading ideal with transported seed ranges. -/

/-- The ideal generated by readings of an arbitrary submodule in one high window. -/
noncomputable def divUniversalHighWindowSubmoduleReadIdeal (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n))
    (side : Bool) : Ideal Γ(relCurve C RZ, relPinnedChart C RZ pi side) :=
  Ideal.span (Set.range
    ((divUniversalHighWindowChartRead (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j n side).comp K.subtype))

@[simp]
theorem divUniversalHighWindowRelationReadIdeal_eq_submodule (n : Nat) (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n side =
      divUniversalHighWindowSubmoduleReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n
        (divUniversalHighWindowRelation (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j n) side :=
  rfl

/-! ## The two seed anchors -/

set_option maxHeartbeats 2400000 in
-- The zero-window bridge unfolds the Grassmannian ambient transport and seed restriction.
set_option synthInstance.maxHeartbeats 800000 in
-- The chart-ring tensor instances are shared by both universal window presentations.
theorem divUniversalHighWindowChartRead_zero_comp_zeroEquiv_eq_fstWindowChartRead
    (side : Bool) :
    ((divUniversalHighWindowChartRead (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 0 side).comp
      (LinearMap.baseChange RZ
        (divUniversalHighWindowZeroEquiv (C := C) (pi := pi) hpi g).toLinearMap)).comp
        (divUniversalFstWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule.subtype =
      divUniversalFstWindowChartRead C hpi g r1 r2 b1 b2 i j side := by
  ext x
  change relThetaResSide
      (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 0)
      side le_rfl
      (relThetaWindowEquiv C RZ pi
        (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 0)
        (relThetaPairH1_windowM_add_mulS C pi hpi g 0)
        (LinearMap.baseChange RZ
          (divUniversalHighWindowZeroEquiv (C := C) (pi := pi) hpi g).toLinearMap
          x)) =
    relThetaResSide (windowM_choice pi hpi g) side le_rfl
      (relThetaWindowEquiv C RZ pi (windowM_choice pi hpi g)
        (relThetaPairH1_windowM C pi hpi g) x)
  have hzero : windowM_choice pi hpi g =
      divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 0 := by
    simp [divUniversalHighWindowExponent]
  have hmap :
      (divUniversalHighWindowZeroEquiv (C := C) (pi := pi) hpi g).toLinearMap =
        (divisorWindowExponentEquiv (C := C) (pi := pi) hzero).toLinearMap := by
    apply LinearMap.ext
    intro y
    rfl
  rw [hmap]
  exact relThetaResSide_relThetaWindowEquiv_baseChange_ofEq_seed
    (C := C) (pi := pi) hzero
    (relThetaPairH1_windowM C pi hpi g)
    (relThetaPairH1_windowM_add_mulS C pi hpi g 0)
    RZ side x

set_option maxHeartbeats 2400000 in
-- The one-window bridge unfolds the shifted Grassmannian ambient and seed restriction.
set_option synthInstance.maxHeartbeats 800000 in
-- The shifted chart-ring tensor instances are shared by both second-window presentations.
theorem divUniversalHighWindowChartRead_one_comp_oneEquiv_eq_sndWindowChartRead
    (side : Bool) :
    ((divUniversalHighWindowChartRead (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 1 side).comp
      (LinearMap.baseChange RZ
        (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap)).comp
        (divUniversalSndWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule.subtype =
      divUniversalSndWindowChartRead C hpi g r1 r2 b1 b2 i j side := by
  ext x
  change relThetaResSide
      (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 1)
      side le_rfl
      (relThetaWindowEquiv C RZ pi
        (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 1)
        (relThetaPairH1_windowM_add_mulS C pi hpi g 1)
        (LinearMap.baseChange RZ
          (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap
          x)) =
    relThetaResSide
      (windowM_choice pi hpi g + windowS_choice pi hpi g) side le_rfl
      (relThetaWindowEquiv C RZ pi
        (windowM_choice pi hpi g + windowS_choice pi hpi g)
        (relThetaPairH1_windowMS C pi hpi g) x)
  have hone : windowM_choice pi hpi g + windowS_choice pi hpi g =
      divUniversalHighWindowExponent (C := C) (pi := pi) hpi g 1 := by
    simp [divUniversalHighWindowExponent]
  have hmap :
      (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap =
        (divisorWindowExponentEquiv (C := C) (pi := pi) hone).toLinearMap := by
    apply LinearMap.ext
    intro y
    rfl
  rw [hmap]
  exact relThetaResSide_relThetaWindowEquiv_baseChange_ofEq_seed
    (C := C) (pi := pi) hone
    (relThetaPairH1_windowMS C pi hpi g)
    (relThetaPairH1_windowM_add_mulS C pi hpi g 1)
    RZ side x

set_option maxHeartbeats 2400000 in
-- The zero-stage ideal comparison repeats the mapped-submodule range reduction.
set_option synthInstance.maxHeartbeats 800000 in
-- The first-window seed equivalence carries the chart-ring dependent subtype.
theorem divUniversalHighWindowRelationReadIdeal_zero_eq_fstWindowChartReadIdeal
    (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 0 side =
      Ideal.span (Set.range
        (divUniversalFstWindowChartRead C hpi g r1 r2 b1 b2 i j side)) := by
  rw [divUniversalHighWindowRelationReadIdeal_eq_submodule]
  change Ideal.span (Set.range
    ((divUniversalHighWindowChartRead (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 0 side).comp
      (divUniversalHighWindowStageZero (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j).toSubmodule.subtype)) = _
  rw [divUniversalHighWindowStageZero_toSubmodule]
  calc
    _ = Ideal.span (Set.range
        (((divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 0 side).comp
          (LinearMap.baseChange RZ
            (divUniversalHighWindowZeroEquiv (C := C) (pi := pi)
              hpi g).toLinearMap)).comp
          (divUniversalFstWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule.subtype)) :=
      span_range_read_map_submodule_map
        (f := divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 0 side)
        (e := LinearMap.baseChange RZ
          (divUniversalHighWindowZeroEquiv (C := C) (pi := pi) hpi g).toLinearMap)
        ((divUniversalFstWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule)
    _ = _ := by
      rw [divUniversalHighWindowChartRead_zero_comp_zeroEquiv_eq_fstWindowChartRead]

set_option maxHeartbeats 2400000 in
-- The seed equivalence is a surjective reparametrization of the first-window readings.
set_option synthInstance.maxHeartbeats 800000 in
-- The chart-reading map retains the concrete carve-chart section ring.
/-- Stage zero generates exactly the genuine chart-reading ideal of the universal seed. -/
theorem divUniversalHighWindowRelationReadIdeal_zero_eq_chartReadIdeal
    (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 0 side =
      ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side := by
  rw [divUniversalHighWindowRelationReadIdeal_zero_eq_fstWindowChartReadIdeal
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side]
  unfold divUniversalFstWindowChartRead ThetaGeneratorSeed.chartReadIdeal
  exact span_range_comp_surjective
    (f := ThetaGeneratorSeed.chartReadMap
      (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side)
    (e := (divUniversalSeedKEquiv C pi hpi g r1 r2 b1 b2 i j).toLinearMap)
    (divUniversalSeedKEquiv C pi hpi g r1 r2 b1 b2 i j).surjective

set_option maxHeartbeats 2400000 in
-- The stage-one ideal comparison repeats the mapped-submodule range reduction.
set_option synthInstance.maxHeartbeats 800000 in
-- The second-window seed equivalence carries the shifted chart-ring subtype.
theorem divUniversalHighWindowRelationReadIdeal_one_eq_sndWindowChartReadIdeal
    (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : Int))
    (hb : 0 < windowBound pi hpi) (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      Ideal.span (Set.range
        (divUniversalSndWindowChartRead C hpi g r1 r2 b1 b2 i j side)) := by
  rw [divUniversalHighWindowRelationReadIdeal_eq_submodule,
    divUniversalHighWindowRelation_one_eq_secondWindow
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb,
    divUniversalHighWindowStageOne_toSubmodule]
  calc
    _ = Ideal.span (Set.range
        (((divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 1 side).comp
          (LinearMap.baseChange RZ
            (divUniversalHighWindowOneEquiv (C := C) (pi := pi)
              hpi g).toLinearMap)).comp
          (divUniversalSndWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule.subtype)) :=
      span_range_read_map_submodule_map
        (f := divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 1 side)
        (e := LinearMap.baseChange RZ
          (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap)
        ((divUniversalSndWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule)
    _ = _ := by
      rw [divUniversalHighWindowChartRead_one_comp_oneEquiv_eq_sndWindowChartRead]

set_option maxHeartbeats 2400000 in
-- The stage-one ideal comparison repeats the mapped-submodule range reduction.
set_option synthInstance.maxHeartbeats 800000 in
-- The second-window seed equivalence carries the shifted chart-ring subtype.
/-- At independent Euler parameter `gamma ≤ g`, stage one generates the
degree-`g` second-window chart-reading span. -/
theorem divUniversalHighWindowRelationReadIdeal_one_eq_sndWindowChartReadIdeal_at
    {gamma : ℕ}
    (hgamma : gamma ≤ g)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ))
    (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      Ideal.span (Set.range
        (divUniversalSndWindowChartRead C hpi g r1 r2 b1 b2 i j side)) := by
  rw [divUniversalHighWindowRelationReadIdeal_eq_submodule,
    divUniversalHighWindowRelation_one_eq_secondWindow_at
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchi,
    divUniversalHighWindowStageOne_toSubmodule]
  calc
    _ = Ideal.span (Set.range
        (((divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 1 side).comp
          (LinearMap.baseChange RZ
            (divUniversalHighWindowOneEquiv (C := C) (pi := pi)
              hpi g).toLinearMap)).comp
          (divUniversalSndWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule.subtype)) :=
      span_range_read_map_submodule_map
        (f := divUniversalHighWindowChartRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j 1 side)
        (e := LinearMap.baseChange RZ
          (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap)
        ((divUniversalSndWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule)
    _ = _ := by
      rw [divUniversalHighWindowChartRead_one_comp_oneEquiv_eq_sndWindowChartRead]

set_option maxHeartbeats 2400000 in
-- The shifted seed equivalence is a surjective reparametrization of second-window readings.
set_option synthInstance.maxHeartbeats 800000 in
-- The shifted chart-reading map retains the concrete carve-chart section ring.
/-- Stage one generates exactly the genuine chart-reading ideal of the shifted seed. -/
theorem divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal
    (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : Int))
    (hb : 0 < windowBound pi hpi) (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side := by
  rw [divUniversalHighWindowRelationReadIdeal_one_eq_sndWindowChartReadIdeal
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb side]
  unfold divUniversalSndWindowChartRead ThetaGeneratorSeed.chartReadIdeal
  exact span_range_comp_surjective
    (f := ThetaGeneratorSeed.chartReadMap
      (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side)
    (e := (divUniversalSeedK'Equiv C pi hpi g r1 r2 b1 b2 i j).toLinearMap)
    (divUniversalSeedK'Equiv C pi hpi g r1 r2 b1 b2 i j).surjective

set_option maxHeartbeats 2400000 in
-- The shifted seed equivalence is a surjective reparametrization of second-window readings.
set_option synthInstance.maxHeartbeats 800000 in
-- The shifted chart-reading map retains the concrete carve-chart section ring.
/-- At independent Euler parameter `gamma ≤ g`, stage one generates exactly the
genuine chart-reading ideal of the shifted degree-`g` seed. -/
theorem divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal_at {gamma : ℕ}
    (hgamma : gamma ≤ g)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ))
    (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side := by
  rw [divUniversalHighWindowRelationReadIdeal_one_eq_sndWindowChartReadIdeal_at
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchi side]
  unfold divUniversalSndWindowChartRead ThetaGeneratorSeed.chartReadIdeal
  exact span_range_comp_surjective
    (f := ThetaGeneratorSeed.chartReadMap
      (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side)
    (e := (divUniversalSeedK'Equiv C pi hpi g r1 r2 b1 b2 i j).toLinearMap)
    (divUniversalSeedK'Equiv C pi hpi g r1 r2 b1 b2 i j).surjective

set_option maxHeartbeats 2400000 in
-- The seed-anchor equality combines the two window ideal transports and persistence.
set_option synthInstance.maxHeartbeats 800000 in
-- The final comparison keeps both chart-ring seed ideals at the same dependent type.
theorem divUniversalHighWindowRelationReadIdeal_one_eq_zero
    (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : Int))
    (hb : 0 < windowBound pi hpi) (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 0 side := by
  calc
    _ = ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side := by
      exact divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb side
    _ = ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side :=
      chartReadIdeal_divUniversalSeedK'_eq_divUniversalSeedK
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb side
    _ = _ :=
      (divUniversalHighWindowRelationReadIdeal_zero_eq_chartReadIdeal
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side).symm

set_option maxHeartbeats 2400000 in
-- The seed-anchor equality combines the two window ideal transports and persistence.
set_option synthInstance.maxHeartbeats 800000 in
-- The final comparison keeps both chart-ring seed ideals at the same dependent type.
/-- At independent Euler parameter `gamma ≤ g`, the stage-one and stage-zero
degree-`g` relation-reading ideals agree. -/
theorem divUniversalHighWindowRelationReadIdeal_one_eq_zero_at {gamma : ℕ}
    (hgamma : gamma ≤ g)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ))
    (side : Bool) :
    divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side =
      divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 0 side := by
  calc
    _ = ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK' C pi hpi g r1 r2 b1 b2 i j) side := by
      exact divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal_at
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchi side
    _ = ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side :=
      chartReadIdeal_divUniversalSeedK'_eq_divUniversalSeedK_at
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchi side
    _ = _ :=
      (divUniversalHighWindowRelationReadIdeal_zero_eq_chartReadIdeal
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side).symm

end HighWindowRelationRead

end AlgebraicGeometry
