/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeRedesignIdealPurity

/-!
# A multiplication presentation of a reading ideal

The second-window route produces a finite multiplication presentation
`S ⊗ K → K'`.  This file records the small algebraic step needed before any
geometric specialization: if the readings of `K'` are the products of the
readings of `S` and `K`, and the product map is onto, then the ideal generated
by the `K'` readings is the ideal generated by the `K` readings, provided the
multiplier window contains a section reading `1`.

The statement is intentionally map-shaped.  It does not identify a concrete
theta multiplication map, and it does not infer purity from an `R`-linear
range.  A separate hypothesis that the quotient by the *second-window* ideal
is `R`-flat can then be transported to the first-window ideal and fed to the
genuine ideal-purity consumer.
-/

set_option autoImplicit false

universe u

open scoped TensorProduct

namespace AlgebraicGeometry

namespace IdealPurity

variable {R B S K K' : Type u}
variable [CommRing R] [CommRing B] [Algebra R B]
variable [AddCommGroup S] [Module R S]
variable [AddCommGroup K] [Module R K]
variable [AddCommGroup K'] [Module R K']

/-! ## The product reading map -/

/-- The `R`-linear product of two `B`-valued reading maps. -/
noncomputable def productReadMap
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) :
    S ⊗[R] K →ₗ[R] B :=
  (LinearMap.mul' R B).comp (TensorProduct.map m r)

@[simp]
theorem productReadMap_tmul
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (s : S) (k : K) :
    productReadMap (R := R) m r (s ⊗ₜ[R] k) = m s * r k := by
  rfl

private theorem productReadMap_mem_span_range
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (x : S ⊗[R] K) :
    productReadMap (R := R) m r x ∈ Ideal.span (Set.range r) := by
  induction x using TensorProduct.induction_on with
  | zero => exact Ideal.zero_mem _
  | add x y hx hy =>
      simpa only [map_add] using Ideal.add_mem _ hx hy
  | tmul s k =>
      rw [productReadMap_tmul]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨k, rfl⟩)

/-! ## Equality of the first- and second-window reading ideals -/

/-- A surjective multiplication presentation gives the inclusion of the
second-window reading ideal in the first-window reading ideal. -/
theorem span_range_read_le_of_surjective_mul
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (r' : K' →ₗ[R] B)
    (μ : S ⊗[R] K →ₗ[R] K')
    (hsurj : Function.Surjective μ)
    (hread : ∀ x, r' (μ x) = productReadMap (R := R) m r x) :
    Ideal.span (Set.range r') ≤ Ideal.span (Set.range r) := by
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨k', rfl⟩
  obtain ⟨x, hx⟩ := hsurj k'
  rw [← hx, hread]
  exact productReadMap_mem_span_range (R := R) m r x

/-- If the multiplier window contains a unit reading and its product with `K`
is represented in `K'`, the two generated reading ideals are equal.

The section `ι k` is explicit because the relative theta multiplication map may
carry an ambient reindexing or a coherence unit; callers can provide the exact
map-level equality they have proved instead of relying on definitional equality.
-/
theorem span_range_read_eq_of_surjective_mul_of_unit
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (r' : K' →ₗ[R] B)
    (μ : S ⊗[R] K →ₗ[R] K')
    (hsurj : Function.Surjective μ)
    (hread : ∀ x, r' (μ x) = productReadMap (R := R) m r x)
    (s₁ : S) (hmunit : IsUnit (m s₁))
    (ι : K → K')
    (hι : ∀ k, μ (s₁ ⊗ₜ[R] k) = ι k) :
    Ideal.span (Set.range r') = Ideal.span (Set.range r) := by
  apply le_antisymm
  · exact span_range_read_le_of_surjective_mul (R := R) m r r' μ hsurj hread
  · refine Ideal.span_le.mpr ?_
    rintro _ ⟨k, rfl⟩
    have hprod : r' (ι k) = m s₁ * r k := by
      rw [← hι k, hread, productReadMap_tmul]
    have hmem : m s₁ * r k ∈ Ideal.span (Set.range r') := by
      rw [← hprod]
      exact Ideal.subset_span ⟨ι k, rfl⟩
    obtain ⟨u, hu⟩ := hmunit
    rw [← hu] at hmem
    have hinv := Ideal.mul_mem_left (Ideal.span (Set.range r')) ((u⁻¹ : Bˣ) : B) hmem
    change r k ∈ Ideal.span (Set.range r')
    simpa only [← mul_assoc, Units.inv_mul, Units.val_one, one_mul] using hinv

/-! ## Flatness and purity after the equality -/

/-- Flatness of the quotient by the second-window reading ideal transfers to
the quotient by the first-window reading ideal. -/
theorem flat_quotient_span_range_read_of_surjective_mul_of_unit
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (r' : K' →ₗ[R] B)
    (μ : S ⊗[R] K →ₗ[R] K')
    (hsurj : Function.Surjective μ)
    (hread : ∀ x, r' (μ x) = productReadMap (R := R) m r x)
    (s₁ : S) (hmunit : IsUnit (m s₁))
    (ι : K → K')
    (hι : ∀ k, μ (s₁ ⊗ₜ[R] k) = ι k)
    [Module.Flat R (B ⧸ Ideal.span (Set.range r'))] :
    Module.Flat R (B ⧸ Ideal.span (Set.range r)) := by
  have hJ := span_range_read_eq_of_surjective_mul_of_unit
    (R := R) m r r' μ hsurj hread s₁ hmunit ι hι
  rw [← hJ]
  infer_instance

/-- The corresponding universal injectivity statement for the first-window
ideal.  This is the direct consumer for a residue-field `hspan` argument. -/
theorem subtype_rTensor_injective_span_range_read_of_surjective_mul_of_unit
    (m : S →ₗ[R] B) (r : K →ₗ[R] B) (r' : K' →ₗ[R] B)
    (μ : S ⊗[R] K →ₗ[R] K')
    (hsurj : Function.Surjective μ)
    (hread : ∀ x, r' (μ x) = productReadMap (R := R) m r x)
    (s₁ : S) (hmunit : IsUnit (m s₁))
    (ι : K → K')
    (hι : ∀ k, μ (s₁ ⊗ₜ[R] k) = ι k)
    [Module.Flat R (B ⧸ Ideal.span (Set.range r'))]
    (A : Type u) [AddCommGroup A] [Module R A] :
    Function.Injective
      (LinearMap.rTensor (R := R) A
        ((Ideal.span (Set.range r)).restrictScalars R).subtype) := by
  haveI : Module.Flat R (B ⧸ Ideal.span (Set.range r)) := by
    exact flat_quotient_span_range_read_of_surjective_mul_of_unit
      (R := R) m r r' μ hsurj hread s₁ hmunit ι hι
  exact subtype_rTensor_injective_of_flat_quotient
    (R := R) (B := B) (Ideal.span (Set.range r)) A

end IdealPurity

end AlgebraicGeometry
