/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import Mathlib.RingTheory.Smooth.Quotient
import AlgebraicJacobian.Picard.FlatCokernel

/-!
# DD-4 redesign: purity of the genuine chart ideal

The reading map has an `R`-linear range, while the divisor is cut out by the
`B`-ideal generated by that range.  This file records the elementary purity
bridge for the latter.  Flatness of `B / J` over `R` makes the inclusion
`J ↪ B` universally injective; in particular, after tensoring with a residue
field, a principal subideal of `J` can be compared inside the ambient fibre.

No geometric generation statement is asserted here.  Callers still have to
provide the appropriate fibrewise (usually single-point) generation input.
-/

set_option autoImplicit false

universe u

open scoped TensorProduct

namespace AlgebraicGeometry

namespace IdealPurity

variable {R B : Type u} [CommRing R] [CommRing B] [Algebra R B]

/-! ## The ideal as the kernel of its quotient -/

@[simp]
theorem restrictScalars_ker_quotient
    (J : Ideal B) :
    LinearMap.ker (Ideal.Quotient.mkₐ R J).toLinearMap = J.restrictScalars R := by
  ext x
  simp [Ideal.Quotient.eq_zero_iff_mem]

/-! ## Universal injectivity of a flat ideal inclusion -/

/-- If `B / J` is `R`-flat, the inclusion of the genuine ideal `J` into `B`
remains injective after tensoring with any `R`-module. -/
theorem subtype_lTensor_injective_of_flat_quotient
    (J : Ideal B) [Module.Flat R (B ⧸ J)]
    (A : Type u) [AddCommGroup A] [Module R A] :
    Function.Injective ((J.restrictScalars R).subtype.lTensor A) := by
  apply LinearMap.lTensor_injective_of_exact_of_flat
    (Ideal.Quotient.mkₐ R J).toLinearMap
    Ideal.Quotient.mk_surjective
    (J.restrictScalars R).subtype
    (Submodule.injective_subtype _)
  rw [LinearMap.exact_iff, restrictScalars_ker_quotient]
  exact (Submodule.range_subtype _).symm

/-- The same purity statement in the right-tensor orientation. -/
theorem subtype_rTensor_injective_of_flat_quotient
    (J : Ideal B) [Module.Flat R (B ⧸ J)]
    (A : Type u) [AddCommGroup A] [Module R A] :
    Function.Injective ((J.restrictScalars R).subtype.rTensor A) := by
  exact ((J.restrictScalars R).subtype.lTensor_inj_iff_rTensor_inj A).mp
    (subtype_lTensor_injective_of_flat_quotient (R := R) (B := B) J A)

end IdealPurity

end AlgebraicGeometry
