/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeMono
import AlgebraicJacobian.Picard.FlatCokernel
import AlgebraicJacobian.Picard.DivisorFamilyPullbackMap
import AlgebraicJacobian.RiemannRoch.StalkColength

/-!
# DDR-8 — the window→stalk-ideal bridge (the `hbridge` seam, window-recovery route)

This file discharges the *upgrade machinery* of the `hbridge` seam of
`Picard/DivSchemeMono.lean`: equal `ε`-windows over the test ring `R` force equal stalk
ideals at every point of `relCurve C R`, hence `DivEq` (`divFam_divEq_of_eps_eq'`).

## Route correction (binding for the follow-up lane)

The route sketched in the `DivSchemeMono` header — *fibrewise stalk-ideal equality (the
field mono at every `κ(p)`) upgraded to relative stalk-ideal equality by the colon-Tor
pair* — is **mathematically incomplete**: fibrewise stalk-ideal equality does NOT imply
relative equality.  Witness (`R = k[ε]`, affine chart of a curve): the divisors cut by
`t` and `t + ε` have *equal stalk ideals in every residue-field fibre* (both cut `(t)`
over `κ((ε)) = k`), both colengths are free `R`-modules of rank one, yet
`(t) ≠ (t + ε)` in `k[ε][t]_{(t,ε)}` — because `t + ε = c·t` forces `ε ∈ t·k[ε][t]`
locally, which fails.  The relative information that separates them is exactly the
`ε`-window over `R` (their vanishing submodules in `R ⊗ H_M` differ).  Any honest
discharge must therefore consume the window equality at the `R`-level, not only
fibrewise.

## The window-recovery route (this file)

Per certified family the stalk ideal is *recovered from the window*: at every point `z`
the germs of the window sections generate the stalk ideal.  Since the window is shared
(`heps`), the two stalk ideals coincide — the field mono at `κ(p)` is not needed at all.

* **§1** `Scheme.twistGermSet` — the germs at `z` of the chart components of a set of
  twisted pairs; `span_twistGermSet_le_stalkIdeal` — germs of vanishing sections lie in
  the stalk ideal (the easy inclusion).
* **§2** the local upgrade (pure algebra, no scheme, no Noetherian hypothesis):
  - `mul_mem_smul_top_of_flat_coker_of_mem_smul_top` — over a flat colength `B ⧸ (f)`
    the regular element `f` cancels from `s`-multiples (`f·x ∈ s•B ⟹ x ∈ s•B`); the
    `R' = R⧸s` instance of the Kleiman `lm:ctn` (i)⟹(iii) discharge
    (`includeRight_mem_nonZeroDivisors_of_flat_coker`).
  - `span_singleton_algebraMap_eq_of_le_sup_map` — **the unit trick** at a localization
    `L` of `B` at a prime: if `(f) ⊆ E + s·L` with `E ⊆ (f)` and `s` mapping into the
    maximal ideal, then `(f) = E` — write `f = e + c·f`, cancel `f` from `c·f ∈ s·L`
    through the flat colength (clearing denominators), so `c ∈ s·L ⊆ m_L` and `1 − c`
    is a unit.
* **§3** the geometric instantiation on a certified adaptation:
  `DivisorAdaptation.stalkIdeal_eq_span_germ_eqn` (piece equations generate, over any
  test ring — the `R`-generic port of the field-level lemma) and
  `DivisorAdaptation.stalkIdeal_eq_of_le_sup_map` — the certificate clause (c1)
  `projective_colength` is exactly the flat-colength input, and the stalk is the
  localization of the piece ring (`IsAffineOpen.isLocalization_stalk`).
* **§4** the family keystones: `divFamEpsWindowGermSet` (the germ set of the
  `ε`-window), `CertifiedDivisorFamily.stalkIdeal_eq_span_windowGerm` (the per-family
  recovery), `divFam_stalkIdeal_eq_of_eps_eq` (the discharged `hbridge` shape), and the
  pinned `divFam_divEq_of_eps_eq'`.

## The one named seam (`hwin`)

What remains gated is the **window generation input** `hwin`: at every `z` (with base
ideal `s` mapping into `m_z`), the stalk ideal is generated by window germs *modulo*
`s` — `I_d(z) ≤ ⟨window germs⟩ ⊔ s·𝒪_z`.  This is fibre-level content: at the residue
field `κ(s)` it is base-point-freeness of the window `H⁰(𝒪(N − D))` (the achiever
`exists_coeffAt_eq_baseDivisorAt` + `baseDivisorAt_window_normalization` through the
G-3 dictionary `divFamPhi`), transported to `𝒪_z ⧸ s𝒪_z` through the sections base
change and the fibre-window surjectivity (the G-2 `divFamEps_mapAlg` naturality, or the
flat-cokernel rank count).  Over a field `hwin` holds with `s = ⊥`.  The discharge is
the follow-up brick; everything downstream of `hwin` is fully proven here, axiom-clean,
with **no Noetherian hypothesis**.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.stalkOverAlgebra
attribute [local instance 10000] relCurve.instOver

/-! ## §1 The germ set of a set of twisted pairs -/

section GermSet

variable {A : Type u} [CommRing A] {X : Scheme.{u}} [X.Over (Spec (.of A))]
variable {V₀ V₁ : X.Opens} {gc : Γ(X, V₀ ⊓ V₁)ˣ}

/-- **The germ set of a set of twisted pairs at a point**: the germs at `z` of the chart
components of the members of `T`, on whichever pinned chart(s) contain `z`.  For
`T = ` (the image of) a divisor-family window this is the set whose span the DDR-8
bridge shows to be the full stalk ideal. -/
def Scheme.twistGermSet (T : Set ↥(twistSubmodule A V₀ V₁ gc ⊤)) (z : X) :
    Set (X.presheaf.stalk z) :=
  {a | ∃ (x : ↥(twistSubmodule A V₀ V₁ gc ⊤)) (_ : x ∈ T) (hz₀ : z ∈ ⊤ ⊓ V₀),
      a = (X.presheaf.germ (⊤ ⊓ V₀) z hz₀).hom x.val.1} ∪
  {a | ∃ (x : ↥(twistSubmodule A V₀ V₁ gc ⊤)) (_ : x ∈ T) (hz₁ : z ∈ ⊤ ⊓ V₁),
      a = (X.presheaf.germ (⊤ ⊓ V₁) z hz₁).hom x.val.2}

/-- **The easy inclusion**: germs of vanishing sections lie in the stalk ideal — the
membership clauses of `vanishingSubmodule` verbatim. -/
lemma span_twistGermSet_le_stalkIdeal (d : X.LocalEquations)
    {T : Set ↥(twistSubmodule A V₀ V₁ gc ⊤)}
    (hT : T ⊆ ↑(d.vanishingSubmodule A V₀ V₁ gc)) (z : X) :
    Ideal.span (Scheme.twistGermSet T z) ≤ d.stalkIdeal z := by
  rw [Ideal.span_le]
  rintro a (⟨x, hx, hz₀, rfl⟩ | ⟨x, hx, hz₁, rfl⟩)
  · exact ((Scheme.LocalEquations.mem_vanishingSubmodule_iff A).mp (hT hx)).1 z hz₀
  · exact ((Scheme.LocalEquations.mem_vanishingSubmodule_iff A).mp (hT hx)).2 z hz₁

end GermSet

/-! ## §2 The local upgrade: cancelling a flat-colength regular element -/

section LocalBridge

variable {R B : Type u} [CommRing R] [CommRing B] [Algebra R B]

/-- **Cancelling a regular element with flat colength from `s`-multiples**
(the `R⧸s`-instance of the Kleiman `lm:ctn` (i)⟹(iii) discharge
`includeRight_mem_nonZeroDivisors_of_flat_coker`): if `f` is a nonzerodivisor of the
`R`-algebra `B` whose colength `B ⧸ (f)` is `R`-flat, then for every ideal `s` of `R`,
`f · x ∈ s • B` forces `x ∈ s • B`.  No Noetherian hypothesis. -/
theorem mul_mem_smul_top_of_flat_coker_of_mem_smul_top
    {f : B} (hf : f ∈ nonZeroDivisors B) [Module.Flat R (B ⧸ Ideal.span {f})]
    (s : Ideal R) {x : B} (h : f * x ∈ s • (⊤ : Submodule R B)) :
    x ∈ s • (⊤ : Submodule R B) := by
  have hreg := Algebra.TensorProduct.includeRight_mem_nonZeroDivisors_of_flat_coker
    (R := R) (R' := R ⧸ s) f hf
  -- the tensor image of `f * x` vanishes
  have hz : ((1 : R ⧸ s) ⊗ₜ[R] (f * x) : (R ⧸ s) ⊗[R] B) = 0 := by
    apply (TensorProduct.quotTensorEquivQuotSMul B s).injective
    rw [map_zero, TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul,
      Submodule.Quotient.mk_eq_zero]
    exact h
  -- split off the regular factor
  have hsplit : ((1 : R ⧸ s) ⊗ₜ[R] (f * x) : (R ⧸ s) ⊗[R] B)
      = Algebra.TensorProduct.includeRight f * ((1 : R ⧸ s) ⊗ₜ[R] x) := by
    rw [Algebra.TensorProduct.includeRight_apply, Algebra.TensorProduct.tmul_mul_tmul,
      one_mul]
  have hx0 : ((1 : R ⧸ s) ⊗ₜ[R] x : (R ⧸ s) ⊗[R] B) = 0 :=
    (mul_left_mem_nonZeroDivisors_eq_zero_iff hreg).mp (by rw [← hsplit]; exact hz)
  have hmk : (TensorProduct.quotTensorEquivQuotSMul B s) ((1 : R ⧸ s) ⊗ₜ[R] x)
      = (TensorProduct.quotTensorEquivQuotSMul B s) 0 := by rw [hx0]
  rwa [TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul, map_zero,
    Submodule.Quotient.mk_eq_zero] at hmk

variable {L : Type u} [CommRing L] [Algebra B L] [Algebra R L] [IsScalarTower R B L]

/-- **The unit trick at a localization** (the heart of the DDR-8 window→stalk-ideal
bridge): let `L` be the localization of the `R`-algebra `B` at a prime `q`, `f ∈ B` a
nonzerodivisor with `R`-flat colength `B ⧸ (f)`, and `s` an ideal of `R` mapping into
the maximal ideal of `L`.  If an ideal `E ⊆ (f)` of `L` covers `(f)` modulo `s` —
`(f) ⊆ E ⊔ s·L` — then `E` is all of `(f)`: writing `f = e + c·f`, the cofactor `c`
lies in `s·L` (clear denominators and cancel `f` through the flat colength), hence in
the maximal ideal, so `1 − c` is a unit and `f = (1−c)⁻¹·e ∈ E`. -/
theorem span_singleton_algebraMap_eq_of_le_sup_map [IsLocalRing L]
    (q : Ideal B) [q.IsPrime] [IsLocalization.AtPrime L q]
    {f : B} (hf : f ∈ nonZeroDivisors B) [Module.Flat R (B ⧸ Ideal.span {f})]
    {s : Ideal R} (hs : ∀ r ∈ s, algebraMap R L r ∈ IsLocalRing.maximalIdeal L)
    {E : Ideal L} (hE : E ≤ Ideal.span {algebraMap B L f})
    (hcov : Ideal.span {algebraMap B L f} ≤ E ⊔ Ideal.map (algebraMap R L) s) :
    Ideal.span {algebraMap B L f} = E := by
  refine le_antisymm ?_ hE
  -- decompose the generator: `f = e + w` with `w ∈ s·L ∩ (f)`, so `w = c·f`
  obtain ⟨e, he, w, hw, hew⟩ := Submodule.mem_sup.mp
    (hcov (Ideal.mem_span_singleton_self _))
  have hwa : w ∈ Ideal.span {algebraMap B L f} := by
    have hsub : w = algebraMap B L f - e := by rw [← hew]; ring
    rw [hsub]
    exact Submodule.sub_mem _ (Ideal.mem_span_singleton_self _) (hE he)
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hwa
  -- the map ideal through the tower
  have hsB : Ideal.map (algebraMap R L) s
      = Ideal.map (algebraMap B L) (Ideal.map (algebraMap R B) s) := by
    rw [Ideal.map_map, ← IsScalarTower.algebraMap_eq]
  -- clear denominators: `f · (c₀·u·v) = t·σ·v ∈ s·B`
  have hcw : c * algebraMap B L f
      ∈ Ideal.map (algebraMap B L) (Ideal.map (algebraMap R B) s) := by
    rw [← hsB, hc]
    exact hw
  obtain ⟨⟨⟨σ, hσ⟩, u⟩, hσu⟩ :=
    (IsLocalization.mem_map_algebraMap_iff q.primeCompl L).mp hcw
  obtain ⟨⟨c₀, t⟩, hct⟩ := IsLocalization.surj q.primeCompl c
  have hkey : algebraMap B L (c₀ * f * ↑u) = algebraMap B L (↑t * σ) := by
    simp only [map_mul]
    rw [← hct, ← hσu]
    ring
  obtain ⟨v, hv⟩ := (IsLocalization.eq_iff_exists q.primeCompl L).mp hkey
  have hfmul : f * (c₀ * ↑u * ↑v) ∈ Ideal.map (algebraMap R B) s := by
    have hre : f * (c₀ * ↑u * ↑v) = ↑v * (c₀ * f * ↑u) := by ring
    rw [hre, hv]
    exact Ideal.mul_mem_left _ _ (Ideal.mul_mem_left _ _ hσ)
  -- cancel `f` through the flat colength
  have hcuv : c₀ * ↑u * ↑v ∈ Ideal.map (algebraMap R B) s := by
    have h1 : f * (c₀ * ↑u * ↑v) ∈ s • (⊤ : Submodule R B) := by
      rw [Ideal.smul_top_eq_map]
      exact hfmul
    have h2 := mul_mem_smul_top_of_flat_coker_of_mem_smul_top hf s h1
    rwa [Ideal.smul_top_eq_map] at h2
  -- descend: `c ∈ s·L`
  have hcmem : c ∈ Ideal.map (algebraMap R L) s := by
    have h3 : c * algebraMap B L (↑t * ↑u * ↑v) = algebraMap B L (c₀ * ↑u * ↑v) := by
      simp only [map_mul]
      rw [← hct]
      ring
    have hunit : IsUnit (algebraMap B L (↑t * ↑u * ↑v : B)) := by
      have hco : (↑t * ↑u * ↑v : B) = ((t * u * v : q.primeCompl) : B) := by
        push_cast; ring
      rw [hco]
      exact IsLocalization.map_units L (t * u * v)
    obtain ⟨ω, hω⟩ := hunit
    have hcval : c = algebraMap B L (c₀ * ↑u * ↑v) * ↑ω⁻¹ := by
      rw [← h3, ← hω, mul_assoc, Units.mul_inv, mul_one]
    rw [hcval, hsB]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ hcuv)
  have hcmax : c ∈ IsLocalRing.maximalIdeal L :=
    (Ideal.map_le_iff_le_comap.mpr fun r hr => Ideal.mem_comap.mpr (hs r hr)) hcmem
  -- the unit trick
  have hunit1c : IsUnit (1 - c) :=
    IsLocalRing.isUnit_one_sub_self_of_mem_nonunits c hcmax
  obtain ⟨ω, hω⟩ := hunit1c
  have hae : ↑ω * algebraMap B L f = e := by
    have hfe : algebraMap B L f - c * algebraMap B L f = e := by
      rw [hc, ← hew]
      ring
    rw [hω, sub_mul, one_mul]
    exact hfe
  rw [Ideal.span_singleton_le_iff_mem]
  have hfval : algebraMap B L f = ↑ω⁻¹ * e := by
    rw [← hae, ← mul_assoc, Units.inv_mul, one_mul]
  rw [hfval]
  exact Ideal.mul_mem_left _ _ he

end LocalBridge

/-! ## §3 The geometric instantiation on a certified adaptation -/

section StalkUpgrade

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {π : C.left ⟶ P1 k} [IsAffineHom π]

namespace DivisorAdaptation

variable {d : (relCurve C R).LocalEquations} (A : DivisorAdaptation C R π d)

/-- Two elements differing by a unit factor span the same ideal (file-local copy of the
`DivisorStalkIdeal` private lemma). -/
private lemma span_eq_of_unit_mul {S : Type u} [CommRing S] {a b c : S} (hc : IsUnit c)
    (h : a = c * b) : Ideal.span {a} = Ideal.span {b} := by
  obtain ⟨u, rfl⟩ := hc
  refine le_antisymm
    (Ideal.span_singleton_le_span_singleton.mpr ⟨u, by rw [h, mul_comm]⟩)
    (Ideal.span_singleton_le_span_singleton.mpr ⟨(↑u⁻¹ : S), ?_⟩)
  rw [h, mul_comm (u : S) b, mul_assoc, Units.mul_inv, mul_one]

/-- **A piece equation generates the stalk ideal at each of its points, over any test
ring** (the `R`-generic port of the field-level
`DivisorAdaptation.span_germ_eqn_eq_stalkIdeal`): the pointwise clause `eqn_rel j z`
presents the germ of `f_j` as a unit germ times the germ of `d`'s equation at the
member of `z` itself, whose span is the stalk ideal. -/
lemma stalkIdeal_eq_span_germ_eqn (j : A.index) {z : relCurve C R}
    (hz : z ∈ A.pieces j) :
    d.stalkIdeal z
      = Ideal.span {((relCurve C R).presheaf.germ (A.pieces j) z hz).hom (A.eqn j)} := by
  obtain ⟨u, hu⟩ := A.eqn_rel j z
  have hzW : z ∈ A.pieces j ⊓ d.cover.opens z := ⟨hz, d.cover.mem_opens z⟩
  have hgerm := congrArg ((relCurve C R).presheaf.germ
    (A.pieces j ⊓ d.cover.opens z) z hzW).hom hu
  rw [map_mul, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply] at hgerm
  exact (span_eq_of_unit_mul (u.isUnit.map ((relCurve C R).presheaf.germ
    (A.pieces j ⊓ d.cover.opens z) z hzW).hom) hgerm).symm

/-- **The stalk upgrade on a certified adaptation** (the geometric §2): if an ideal
`E ⊆ I_d(z)` of the stalk covers the stalk ideal modulo an ideal `s` of `R` mapping
into the maximal ideal, then `E` is the full stalk ideal.  The flat-colength input is
the certificate clause (c1) `projective_colength` on the piece through `z`; the stalk
is the localization of the piece ring at the point's prime
(`IsAffineOpen.isLocalization_stalk`). -/
theorem stalkIdeal_eq_of_le_sup_map
    (hproj : ∀ j, Module.Projective R (A.colength j)) {z : relCurve C R}
    {s : Ideal R}
    (hs : ∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
      ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z))
    {E : Ideal ((relCurve C R).presheaf.stalk z)} (hE : E ≤ d.stalkIdeal z)
    (hcov : d.stalkIdeal z
      ≤ E ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s) :
    d.stalkIdeal z = E := by
  obtain ⟨j, hz⟩ := A.toFinCoverData.exists_mem_pieces z
  letI : Algebra Γ(relCurve C R, A.pieces j) ((relCurve C R).presheaf.stalk z) :=
    (relCurve C R).presheaf.algebra_section_stalk ⟨z, hz⟩
  haveI hloc := (A.toFinCoverData.isAffineOpen_pieces j).isLocalization_stalk ⟨z, hz⟩
  haveI htower : IsScalarTower R Γ(relCurve C R, A.pieces j)
      ((relCurve C R).presheaf.stalk z) :=
    Scheme.stalkOverAlgebra_isScalarTower R hz
  haveI : Module.Projective R (A.colength j) := hproj j
  haveI hflat : Module.Flat R
      (Γ(relCurve C R, A.pieces j) ⧸ Ideal.span {A.eqn j}) :=
    Module.Flat.of_projective
  have hspan := A.stalkIdeal_eq_span_germ_eqn j hz
  have halg : ((relCurve C R).presheaf.germ (A.pieces j) z hz).hom (A.eqn j)
      = algebraMap Γ(relCurve C R, A.pieces j) ((relCurve C R).presheaf.stalk z)
          (A.eqn j) := rfl
  rw [hspan, halg] at hE hcov ⊢
  exact span_singleton_algebraMap_eq_of_le_sup_map
    ((A.toFinCoverData.isAffineOpen_pieces j).primeIdealOf ⟨z, hz⟩).asIdeal
    (A.eqn_mem_nonZeroDivisors j) hs hE hcov

end DivisorAdaptation

end StalkUpgrade

/-! ## §4 The family keystones: window recovery and the relative mono -/

section FamilyBridge

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {π : C.left ⟶ P1 k} [IsFinite π]

noncomputable local instance instOverCleftBridge : C.left.Over (Spec (.of k)) := ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))] [QuasiCompact (C.left ↘ Spec (.of k))]
  [IsDominant π]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hπ : π ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))

/-- **The germ set of the `ε`-window of a divisor family at a point**: the germs at `z`
of the chart components of the global theta sections in the family's embedding window
`ε₁ = K_M(d)` (read through the window identification `relThetaWindowEquiv`).  Depends
only on the functor value `F : DivFam C R π g` — in particular two families with equal
`ε`-pairs have the SAME germ sets. -/
noncomputable def divFamEpsWindowGermSet (g : ℕ) (F : DivFam C R π g)
    (z : relCurve C R) : Set ((relCurve C R).presheaf.stalk z) :=
  Scheme.twistGermSet
    ((↑(Submodule.map (relThetaWindowEquiv C R π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g)).toLinearMap ((divFamEps hπ g F).1)) :
      Set (relThetaSections C R π (windowM_choice π hπ g)))) z

/-- **The easy inclusion at the family level**: window germs lie in the stalk ideal —
the window is the preimage of the vanishing submodule, whose membership clauses are the
germ conditions. -/
lemma span_divFamEpsWindowGermSet_le (g : ℕ) (G : CertifiedDivisorFamily C R π g)
    (z : relCurve C R) :
    Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z)
      ≤ G.eqns.stalkIdeal z := by
  refine span_twistGermSet_le_stalkIdeal G.eqns ?_ z
  have h0 : (divFamEps hπ g (DivFam.mk G)).1
      = divisorWindow G.eqns (relThetaPairH1_windowM C π hπ g) := rfl
  have h1 : Submodule.map (relThetaWindowEquiv C R π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g)).toLinearMap ((divFamEps hπ g (DivFam.mk G)).1)
      = G.eqns.vanishingSubmodule R (relCover C R (fiberTwoCover π)).V₀
          (relCover C R (fiberTwoCover π)).V₁
          (relThetaCocycle C R π (windowM_choice π hπ g)) := by
    rw [h0, divisorWindow]
    exact Submodule.map_comap_eq_of_surjective
      (relThetaWindowEquiv C R π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g)).surjective _
  rw [h1]

/-- **The per-family window recovery** (the keystone of the DDR-8 bridge): under the
window generation input `hwin` — at every point the stalk ideal is generated by window
germs modulo an ideal of `R` mapping into the maximal ideal (the one named seam; over a
field it holds with `s = ⊥`) — the stalk ideal at EVERY point of the relative curve is
exactly the span of the window germs.  The stalk ideal is thereby a function of the
`ε`-window alone. -/
theorem CertifiedDivisorFamily.stalkIdeal_eq_span_windowGerm (g : ℕ)
    (G : CertifiedDivisorFamily C R π g)
    (hwin : ∀ z : relCurve C R, ∃ s : Ideal R,
      (∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z)) ∧
      G.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z)
          ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s)
    (z : relCurve C R) :
    G.eqns.stalkIdeal z
      = Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z) := by
  obtain ⟨s, hs, hcov⟩ := hwin z
  exact G.adaptation.stalkIdeal_eq_of_le_sup_map
    (fun j => G.certified.projective_colength j) hs
    (span_divFamEpsWindowGermSet_le hπ g G z) hcov

/-- **The discharged `hbridge` shape**: two certified families with equal `ε`-pairs and
window generation have equal stalk ideals at every point — both stalk ideals are the
span of the SAME window germ set (`heps` transports the germ sets). -/
theorem divFam_stalkIdeal_eq_of_eps_eq (g : ℕ)
    (G G' : CertifiedDivisorFamily C R π g)
    (heps : divFamEps hπ g (DivFam.mk G) = divFamEps hπ g (DivFam.mk G'))
    (hwin : ∀ z : relCurve C R, ∃ s : Ideal R,
      (∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z)) ∧
      G.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z)
          ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s)
    (hwin' : ∀ z : relCurve C R, ∃ s : Ideal R,
      (∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z)) ∧
      G'.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G') z)
          ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s)
    (z : relCurve C R) :
    G.eqns.stalkIdeal z = G'.eqns.stalkIdeal z := by
  have hset : divFamEpsWindowGermSet hπ g (DivFam.mk G) z
      = divFamEpsWindowGermSet hπ g (DivFam.mk G') z := by
    unfold divFamEpsWindowGermSet
    rw [heps]
  rw [CertifiedDivisorFamily.stalkIdeal_eq_span_windowGerm hπ g G hwin z,
    CertifiedDivisorFamily.stalkIdeal_eq_span_windowGerm hπ g G' hwin' z, hset]

/-- **The relative mono / Law-1 core, window-recovery form** (DDR-8, the `hbridge`
composition of `Picard/DivSchemeMono.lean` discharged up to the window generation seam
`hwin`): two certified divisor families of degree `g` over the test ring `R` — ANY
commutative test ring, no Noetherian hypothesis — with equal `ε`-pairs and window
generation are equal in `DivFam`.

`hwin`/`hwin'` is the ONE remaining named seam (see the file header): the stalk ideal
is generated by window germs modulo the base maximal-ideal directions — fibre-level
base-point-freeness of the window, transported along the fibre presentation.  Over a
field it holds with `s = ⊥`.  Everything else — the unit trick, the flat-colength
cancellation, the setoid descent — is fully proven. -/
theorem divFam_divEq_of_eps_eq' (g : ℕ) (G G' : CertifiedDivisorFamily C R π g)
    (heps : divFamEps hπ g (DivFam.mk G) = divFamEps hπ g (DivFam.mk G'))
    (hwin : ∀ z : relCurve C R, ∃ s : Ideal R,
      (∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z)) ∧
      G.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z)
          ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s)
    (hwin' : ∀ z : relCurve C R, ∃ s : Ideal R,
      (∀ r ∈ s, algebraMap R ((relCurve C R).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C R).presheaf.stalk z)) ∧
      G'.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G') z)
          ⊔ Ideal.map (algebraMap R ((relCurve C R).presheaf.stalk z)) s) :
    DivFam.mk G = DivFam.mk G' :=
  divFam_divEq_of_stalkIdeal_eq g G G'
    (divFam_stalkIdeal_eq_of_eps_eq hπ g G G' heps hwin hwin')

end FamilyBridge

end AlgebraicGeometry
