/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeMonoBridge
import AlgebraicJacobian.Picard.DivisorFamilyFieldDictionary
import AlgebraicJacobian.Picard.DivisorFamilyFieldCRT
import AlgebraicJacobian.Picard.DivisorFamilyEpsMono

/-!
# DDR-8 — the window generation input over a field (`hwin` at `s = ⊥`)

The field-level discharge of the `hwin` seam of `Picard/DivSchemeMonoBridge.lean`:
over a FIELD `K` the stalk ideal of a certified divisor family is generated by its
window germs outright, so the relative mono `divFam_divEq_of_eps_eq'` is
**unconditional over fields** (`divFam_divEq_of_eps_eq_of_field`) — an independent
second proof of the DD-4 Task 6 field mono consuming neither the carve `hcarve` nor
`divFamPhi_injective` nor `hsurj`.

The mechanism is base-point-freeness in valuative form: at a closed point `z` the
achiever of the base divisor (`Scheme.exists_coeffAt_eq_baseDivisorAt`) provides
`f ∈ Φ(K_M(d)) = H⁰(𝒪(N − D))` with `(N + div f)_z = bd_z = D_z`
(`baseDivisorAt_window_normalization`; the degree input is the unconditional
`deg_divFamDivisor`, I-0230).  Unwinding `f = w·read(s)` through the shift unit
(`divOf_thetaFieldShiftUnit`), the reading of the underlying theta section has order
EXACTLY the bound `N₀(M) − D` at `z`; the generation dictionary
`stalkIdeal_le_span_germ_iff_le_ord` (the ≥-mirror of `ord_thetaFieldRead_le_iff`)
then makes the germ of its chart component a GENERATOR of the stalk ideal
(`span_germ_thetaFieldGluedEquiv_eq_stalkIdeal`).  At the generic point any nonzero
window element generates the whole field stalk.  The threaded `hO/hχ` at both fields
are the standard genus normalizations (at residue fields of a test ring they are
`chi_relCurve_of_chi`-style transports).
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule Scheme.stalkOverAlgebra
attribute [local instance 10000] relCurve.instOver

/-! ## §1 The generation dictionary: order domination ⟺ the germ generates -/

section ExactOrder

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
variable (K : Type u) [Field K] [Algebra k K]
variable (π : C.left ⟶ P1 k) [IsFinite π]
variable (a : ℕ)
variable [IsIntegral (relCurve C K)]
  [SmoothOfRelativeDimension 1 (relCurve C K ↘ Spec (CommRingCat.of K))]
  [QuasiCompact (relCurve C K ↘ Spec (CommRingCat.of K))]

/-- **The generation dictionary at a closed point** (the ≥-mirror of the landed
`ord_thetaFieldRead_le_iff`): the order of the reading of a global theta section
dominating the divisor bound `N₀(a) − div d` at `z` is equivalent to the germ of its
glued component generating the stalk ideal — total divisibility of the DVR stalk read
through the trivializing elements. -/
lemma stalkIdeal_le_span_germ_iff_le_ord (d : (relCurve C K).LocalEquations)
    (s : relThetaSections C K π a) {z : relCurve C K}
    (hzg : z ≠ genericPoint (relCurve C K)) :
    Scheme.divisorBound
        (thetaFieldDivisor C K π a - Scheme.presentationDivisor K d.presentation) hzg
      ≤ Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hzg
          (thetaFieldRead C K π a s)
    ↔ d.stalkIdeal z ≤ Ideal.span
        {((relCurve C K).presheaf.germ (⊤ ⊓ (thetaFieldPointedCover C K π).opens z) z
            ⟨trivial, (thetaFieldPointedCover C K π).mem_opens z⟩).hom
          ((thetaFieldGluedEquiv C K π a s).val z)} := by
  have hsplit : Scheme.divisorBound
      (thetaFieldDivisor C K π a - Scheme.presentationDivisor K d.presentation) hzg
      = Scheme.divisorBound
          (Scheme.presentationDivisor K (thetaFieldPresentation C K π a)) hzg
        * Scheme.divisorBound (-Scheme.presentationDivisor K d.presentation) hzg := by
    rw [sub_eq_add_neg]
    exact Scheme.divisorBound_add _ _ hzg
  have hpos : (0 : WithZero (Multiplicative ℤ))
      < Scheme.divisorBound
          (Scheme.presentationDivisor K (thetaFieldPresentation C K π a)) hzg := by
    rw [show Scheme.divisorBound
        (Scheme.presentationDivisor K (thetaFieldPresentation C K π a)) hzg
        = ((Multiplicative.ofAdd (coeffAt hzg
            (Scheme.presentationDivisor K (thetaFieldPresentation C K π a))) :
          Multiplicative ℤ) : WithZero (Multiplicative ℤ)) from rfl]
    exact zero_lt_iff.mpr WithZero.coe_ne_zero
  have helem : (d.presentation.elem z : (relCurve C K).functionField)
      = algebraMap ((relCurve C K).presheaf.stalk z) (relCurve C K).functionField
          (((relCurve C K).presheaf.germ (d.cover.opens z) z
            (d.cover.mem_opens z)).hom (d.eqn z)) := by
    rw [Scheme.LocalEquations.presentation_elem_val]
    exact Scheme.germ_generic_eq_algebraMap_germ (d.cover.genericPoint_mem_opens z)
      (d.cover.mem_opens z) (d.eqn z)
  have hβ : ((relCurve C K).presheaf.germ
        (⊤ ⊓ (thetaFieldPresentation C K π a).cover.opens z)
        (genericPoint (relCurve C K))
        ⟨trivial, (thetaFieldPresentation C K π a).cover.genericPoint_mem_opens z⟩).hom
        ((thetaFieldGluedEquiv C K π a s).val z)
      = algebraMap ((relCurve C K).presheaf.stalk z) (relCurve C K).functionField
          (((relCurve C K).presheaf.germ
            (⊤ ⊓ (thetaFieldPointedCover C K π).opens z) z
            ⟨trivial, (thetaFieldPointedCover C K π).mem_opens z⟩).hom
            ((thetaFieldGluedEquiv C K π a s).val z)) :=
    Scheme.germ_generic_eq_algebraMap_germ
      (⟨trivial, (thetaFieldPresentation C K π a).cover.genericPoint_mem_opens z⟩ :
        genericPoint (relCurve C K)
          ∈ ⊤ ⊓ (thetaFieldPresentation C K π a).cover.opens z)
      (⟨trivial, (thetaFieldPresentation C K π a).cover.mem_opens z⟩ :
        z ∈ ⊤ ⊓ (thetaFieldPresentation C K π a).cover.opens z)
      ((thetaFieldGluedEquiv C K π a s).val z)
  rw [thetaFieldRead_apply,
    Scheme.MeromorphicPresentation.gluedVal_eq_elem_inv_mul K
      (thetaFieldPresentation C K π a) z (W := ⊤) trivial
      (thetaFieldGluedEquiv C K π a s),
    map_mul, hsplit,
    Scheme.MeromorphicPresentation.ord_elem_inv K (thetaFieldPresentation C K π a) z hzg,
    mul_le_mul_iff_right₀ hpos,
    ← Scheme.LocalEquations.ord_presentation_elem K d hzg,
    hβ, helem, Scheme.LocalEquations.stalkIdeal, Ideal.span_singleton_le_iff_mem,
    Ideal.mem_span_singleton, Scheme.dvd_iff_ord_le K hzg]

/-- **Exact order makes the germ a generator**: if the reading's order both respects
(`hle`) and dominates (`hge`) the bound `N₀(a) − div d` at the closed point `z`, then
the germ of the glued component spans the stalk ideal exactly. -/
lemma span_germ_thetaFieldGluedEquiv_eq_stalkIdeal (d : (relCurve C K).LocalEquations)
    (s : relThetaSections C K π a) {z : relCurve C K}
    (hzg : z ≠ genericPoint (relCurve C K))
    (hle : Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hzg
        (thetaFieldRead C K π a s)
      ≤ Scheme.divisorBound
          (thetaFieldDivisor C K π a - Scheme.presentationDivisor K d.presentation) hzg)
    (hge : Scheme.divisorBound
          (thetaFieldDivisor C K π a - Scheme.presentationDivisor K d.presentation) hzg
      ≤ Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hzg
          (thetaFieldRead C K π a s)) :
    Ideal.span
        {((relCurve C K).presheaf.germ (⊤ ⊓ (thetaFieldPointedCover C K π).opens z) z
            ⟨trivial, (thetaFieldPointedCover C K π).mem_opens z⟩).hom
          ((thetaFieldGluedEquiv C K π a s).val z)}
      = d.stalkIdeal z := by
  refine le_antisymm ?_
    ((stalkIdeal_le_span_germ_iff_le_ord C K π a d s hzg).mp hge)
  rw [Ideal.span_singleton_le_iff_mem]
  exact (ord_thetaFieldRead_le_iff C K π a d s hzg).mp hle

end ExactOrder

/-! ## §2 The field-level `hwin` and the unconditional field mono -/

section FieldWindow

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {K : Type u} [Field K] [Algebra k K]
variable {π : C.left ⟶ P1 k} [IsFinite π]

noncomputable local instance instOverCleftBridgeField : C.left.Over (Spec (.of k)) :=
  ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 C.hom] [IsProper C.hom]
  [GeometricallyIrreducible C.hom]
variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))] [QuasiCompact (C.left ↘ Spec (.of k))]
  [IsDominant π]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hπ : π ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))
variable [IsIntegral (relCurve C K)]
  [SmoothOfRelativeDimension 1 (relCurve C K ↘ Spec (CommRingCat.of K))]
  [LocallyOfFiniteType (relCurve C K ↘ Spec (CommRingCat.of K))]
  [QuasiCompact (relCurve C K ↘ Spec (CommRingCat.of K))]
  [Module.Finite K (Sheaf.HModule ((relCurve C K).moduleKSheaf K) 0)]
  [Module.Finite K (Sheaf.HModule ((relCurve C K).moduleKSheaf K) 1)]

set_option maxRecDepth 8000 in
set_option maxHeartbeats 800000 in
-- The two-field instance towers and the window-submodule defeqs exceed the default
-- limits; the I-0198 escape hatch, as in `RiemannRoch/WindowFieldTransport.lean`.
set_option synthInstance.maxHeartbeats 800000 in
/-- **The decoupled window generation input over a field** (`hwin` at `s = ⊥`; the field-level
discharge of the DivSchemeMonoBridge seam): at every point of the fibre curve the stalk
ideal of a certified divisor family is contained in — hence by the easy inclusion equal
to — the span of its `ε`-window germs.  Closed points are the achiever of the base
divisor read through the generation dictionary; the generic point is generated by any
nonzero window element.  The family degree is `g`, while the Euler-characteristic
normalization is indexed independently by `gamma ≤ g`. -/
theorem CertifiedDivisorFamily.stalkIdeal_le_span_windowGerm_of_field_at
    (g : ℕ) {gamma : ℕ} (hgamma : gamma ≤ g)
    (G : CertifiedDivisorFamily C K π g)
    (_hOk : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (_hχk : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ))
    (hOK : Sheaf.h0 ((relCurve C K).moduleKSheaf K) = 1)
    (hχK : Sheaf.chi ((relCurve C K).moduleKSheaf K) = 1 - (gamma : ℤ))
    (z : relCurve C K) :
    G.eqns.stalkIdeal z
      ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z) := by
  -- the shared window data
  have hT : Submodule.map
        (divFamPhi C K π (windowM_choice π hπ g) (relThetaPairH1_windowM C π hπ g))
        ((divFamEps hπ g (DivFam.mk G)).1)
      = Scheme.divisorSections K
          (windowN C K hπ g - divFamDivisor (DivFam.mk G)) ⊤ :=
    map_divFamPhi_eps_fst K hπ g G
  have hdeg : Scheme.CurveDivisor.deg K (divFamDivisor (DivFam.mk G)) = (g : ℤ) :=
    deg_divFamDivisor (DivFam.mk G)
  have hD0 : 0 ≤ divFamDivisor (DivFam.mk G) := zero_le_divFamDivisor _
  have hNnorm : ∀ D' : (relCurve C K).CurveDivisor,
      Scheme.CurveDivisor.deg K D' ≤ 2 * (g : ℤ) →
      Subsingleton (Sheaf.HModule
        ((relCurve C K).divisorSheaf K (windowN C K hπ g - D')) 1) :=
    fun D' hD' => subsingleton_h1_windowN_sub_at C K hπ g hχK D' hD' hgamma
  have hNdeg : 2 * (g : ℤ) ≤ Scheme.CurveDivisor.deg K (windowN C K hπ g) :=
    two_mul_degree_le_deg_windowN C K hπ g
  have hne : ∃ f ∈ Submodule.map
      (divFamPhi C K π (windowM_choice π hπ g) (relThetaPairH1_windowM C π hπ g))
      ((divFamEps hπ g (DivFam.mk G)).1), f ≠ 0 :=
    exists_mem_ne_zero_of_window_normalization_at g hgamma hχK
      (windowN C K hπ g) hNnorm hNdeg (divFamDivisor (DivFam.mk G)) hdeg hT
  -- the window membership of a window element's reading, in ord form
  have hread_le : ∀ (x : K ⊗[k] ↥(Scheme.divisorSections k
        (windowM_choice π hπ g • fiberWeilDivisor π) ⊤))
      (_ : x ∈ (divFamEps hπ g (DivFam.mk G)).1)
      {w : relCurve C K} (hwg : w ≠ genericPoint (relCurve C K)),
      Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hwg
          (thetaFieldRead C K π (windowM_choice π hπ g)
            (relThetaWindowEquiv C K π (windowM_choice π hπ g)
              (relThetaPairH1_windowM C π hπ g) x))
        ≤ Scheme.divisorBound (thetaFieldDivisor C K π (windowM_choice π hπ g)
            - Scheme.presentationDivisor K G.eqns.presentation) hwg := by
    intro x hx w hwg
    have hvan : relThetaWindowEquiv C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x
        ∈ G.eqns.vanishingSubmodule K (relCover C K (fiberTwoCover π)).V₀
            (relCover C K (fiberTwoCover π)).V₁
            (relThetaCocycle C K π (windowM_choice π hπ g)) := hx
    have hmem := (mem_vanishingSubmodule_iff_thetaFieldRead_mem C K π
      (windowM_choice π hπ g) G.eqns _).mp hvan
    rw [Scheme.mem_divisorSections_of_nonempty K
      (top_opens_nonempty (X := relCurve C K))] at hmem
    exact hmem w hwg trivial
  by_cases hzg : z = genericPoint (relCurve C K)
  · -- the generic point: any nonzero window element generates the field stalk
    subst hzg
    rw [Scheme.LocalEquations.stalkIdeal_genericPoint]
    obtain ⟨f, hfT, hf⟩ := hne
    obtain ⟨x, hx, rfl⟩ := Submodule.mem_map.mp hfT
    have hΦval : divFamPhi C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x
        = ((thetaFieldShiftUnit C K π (windowM_choice π hπ g) :
            (relCurve C K).functionFieldˣ) : (relCurve C K).functionField)
          * thetaFieldRead C K π (windowM_choice π hπ g)
              (relThetaWindowEquiv C K π (windowM_choice π hπ g)
                (relThetaPairH1_windowM C π hπ g) x) := by
      simp only [divFamPhi, LinearMap.coe_comp, Function.comp_apply,
        LinearEquiv.coe_coe, Scheme.mulLinear_apply]
    have hs_ne : relThetaWindowEquiv C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x ≠ 0 := by
      intro h0
      apply hf
      rw [hΦval, h0, map_zero, mul_zero]
    have hcomp : (relThetaWindowEquiv C K π (windowM_choice π hπ g)
          (relThetaPairH1_windowM C π hπ g) x).val.1 ≠ 0
        ∨ (relThetaWindowEquiv C K π (windowM_choice π hπ g)
          (relThetaPairH1_windowM C π hπ g) x).val.2 ≠ 0 := by
      rcases eq_or_ne (relThetaWindowEquiv C K π (windowM_choice π hπ g)
          (relThetaPairH1_windowM C π hπ g) x).val.1 0 with h1 | h1
      · refine Or.inr fun h2 => hs_ne (Subtype.ext (Prod.ext h1 h2))
      · exact Or.inl h1
    have hsmem : relThetaWindowEquiv C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x
        ∈ Submodule.map (relThetaWindowEquiv C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g)).toLinearMap
          ((divFamEps hπ g (DivFam.mk G)).1) :=
      Submodule.mem_map_of_mem hx
    rcases hcomp with h1 | h2
    · -- chart 0 carries a nonzero component
      have hnonempty : ((⊤ ⊓ (relCover C K (fiberTwoCover π)).V₀ :
          (relCurve C K).Opens) : Set (relCurve C K)).Nonempty := by
        by_contra hemp
        have hbot : (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₀ :
            (relCurve C K).Opens) ≤ ⊥ := fun w hw => absurd ⟨w, hw⟩ hemp
        haveI := (relCurve C K).subsingleton_sections_of_le_bot hbot
        exact h1 (Subsingleton.elim _ _)
      have hη₀ : genericPoint (relCurve C K)
          ∈ ⊤ ⊓ (relCover C K (fiberTwoCover π)).V₀ :=
        Scheme.genericPoint_mem_of_nonempty hnonempty
      have hγne : ((relCurve C K).presheaf.germ
          (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₀) (genericPoint (relCurve C K))
          hη₀).hom (relThetaWindowEquiv C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g) x).val.1 ≠ 0 := fun h0 =>
        h1 (germ_injective_of_isIntegral (relCurve C K) (genericPoint (relCurve C K))
          hη₀ (by rw [h0, map_zero]))
      have hγmem : ((relCurve C K).presheaf.germ
            (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₀) (genericPoint (relCurve C K))
            hη₀).hom (relThetaWindowEquiv C K π (windowM_choice π hπ g)
              (relThetaPairH1_windowM C π hπ g) x).val.1
          ∈ divFamEpsWindowGermSet hπ g (DivFam.mk G) (genericPoint (relCurve C K)) :=
        Set.mem_union_left _ ⟨_, hsmem, hη₀, rfl⟩
      exact (Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span hγmem)
        (Units.mk0 (G₀ := (relCurve C K).functionField) _ hγne).isUnit).ge
    · -- chart 1 carries a nonzero component
      have hnonempty : ((⊤ ⊓ (relCover C K (fiberTwoCover π)).V₁ :
          (relCurve C K).Opens) : Set (relCurve C K)).Nonempty := by
        by_contra hemp
        have hbot : (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₁ :
            (relCurve C K).Opens) ≤ ⊥ := fun w hw => absurd ⟨w, hw⟩ hemp
        haveI := (relCurve C K).subsingleton_sections_of_le_bot hbot
        exact h2 (Subsingleton.elim _ _)
      have hη₁ : genericPoint (relCurve C K)
          ∈ ⊤ ⊓ (relCover C K (fiberTwoCover π)).V₁ :=
        Scheme.genericPoint_mem_of_nonempty hnonempty
      have hγne : ((relCurve C K).presheaf.germ
          (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₁) (genericPoint (relCurve C K))
          hη₁).hom (relThetaWindowEquiv C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g) x).val.2 ≠ 0 := fun h0 =>
        h2 (germ_injective_of_isIntegral (relCurve C K) (genericPoint (relCurve C K))
          hη₁ (by rw [h0, map_zero]))
      have hγmem : ((relCurve C K).presheaf.germ
            (⊤ ⊓ (relCover C K (fiberTwoCover π)).V₁) (genericPoint (relCurve C K))
            hη₁).hom (relThetaWindowEquiv C K π (windowM_choice π hπ g)
              (relThetaPairH1_windowM C π hπ g) x).val.2
          ∈ divFamEpsWindowGermSet hπ g (DivFam.mk G) (genericPoint (relCurve C K)) :=
        Set.mem_union_right _ ⟨_, hsmem, hη₁, rfl⟩
      exact (Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span hγmem)
        (Units.mk0 (G₀ := (relCurve C K).functionField) _ hγne).isUnit).ge
  · -- a closed point: the achiever generates
    have hTA : Submodule.map
        (divFamPhi C K π (windowM_choice π hπ g) (relThetaPairH1_windowM C π hπ g))
        ((divFamEps hπ g (DivFam.mk G)).1)
        ≤ Scheme.divisorSections K (windowN C K hπ g) ⊤ := by
      have hle : windowN C K hπ g - divFamDivisor (DivFam.mk G) ≤ windowN C K hπ g := by
        refine Scheme.CurveDivisor.le_iff_coeffAt.mpr fun x hx => ?_
        rw [Scheme.CurveDivisor.coeffAt_sub]
        have h0 := Scheme.CurveDivisor.le_iff_coeffAt.mp hD0 x hx
        rw [Scheme.CurveDivisor.coeffAt_zero] at h0
        omega
      rw [hT, Scheme.divisorSections_of_nonempty K
          (top_opens_nonempty (X := relCurve C K)),
        Scheme.divisorSections_of_nonempty K (top_opens_nonempty (X := relCurve C K))]
      exact Scheme.boundedSections_mono K hle ⊤
    obtain ⟨f, hfT, hf, hach0⟩ :=
      Scheme.exists_coeffAt_eq_baseDivisorAt K hTA hne hzg
    have hbd : (Scheme.baseDivisorAt K (Submodule.map
          (divFamPhi C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g)) ((divFamEps hπ g (DivFam.mk G)).1))
          (windowN C K hπ g) ⟨z, hzg⟩ : ℤ)
        = coeffAt hzg (divFamDivisor (DivFam.mk G)) := by
      rw [hT]
      exact baseDivisorAt_window_normalization g hOK hχK (windowN C K hπ g) hNnorm
        hNdeg (divFamDivisor (DivFam.mk G)) hD0 hdeg hzg hgamma
    rw [hbd] at hach0
    obtain ⟨x, hx, rfl⟩ := Submodule.mem_map.mp hfT
    have hΦval : divFamPhi C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x
        = ((thetaFieldShiftUnit C K π (windowM_choice π hπ g) :
            (relCurve C K).functionFieldˣ) : (relCurve C K).functionField)
          * thetaFieldRead C K π (windowM_choice π hπ g)
              (relThetaWindowEquiv C K π (windowM_choice π hπ g)
                (relThetaPairH1_windowM C π hπ g) x) := by
      simp only [divFamPhi, LinearMap.coe_comp, Function.comp_apply,
        LinearEquiv.coe_coe, Scheme.mulLinear_apply]
    have hread_ne : thetaFieldRead C K π (windowM_choice π hπ g)
        (relThetaWindowEquiv C K π (windowM_choice π hπ g)
          (relThetaPairH1_windowM C π hπ g) x) ≠ 0 := by
      intro h0
      apply hf
      rw [hΦval, h0, mul_zero]
    -- the unit decomposition `f = w · read s` and its divisor
    have hfU : Units.mk0 (divFamPhi C K π (windowM_choice π hπ g)
          (relThetaPairH1_windowM C π hπ g) x) hf
        = thetaFieldShiftUnit C K π (windowM_choice π hπ g)
          * Units.mk0 _ hread_ne := by
      refine Units.ext ?_
      rw [Units.val_mul]
      exact hΦval
    have hdiv : coeffAt hzg (Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
          (Units.mk0 (divFamPhi C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g) x) hf))
        = coeffAt hzg (Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
            (thetaFieldShiftUnit C K π (windowM_choice π hπ g)))
          + coeffAt hzg (Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
            (Units.mk0 _ hread_ne)) := by
      rw [hfU, Scheme.divOf_mul, Scheme.CurveDivisor.coeffAt_add]
    have hshift : coeffAt hzg (thetaFieldDivisor C K π (windowM_choice π hπ g))
        - coeffAt hzg (windowN C K hπ g)
        = coeffAt hzg (Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
            (thetaFieldShiftUnit C K π (windowM_choice π hπ g))) := by
      have h := congrArg (coeffAt hzg)
        (divOf_thetaFieldShiftUnit C K π (windowM_choice π hπ g))
      rwa [Scheme.CurveDivisor.coeffAt_sub] at h
    have hach1 : coeffAt hzg (windowN C K hπ g)
        + coeffAt hzg (Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
            (Units.mk0 (divFamPhi C K π (windowM_choice π hπ g)
              (relThetaPairH1_windowM C π hπ g) x) hf))
        = coeffAt hzg (divFamDivisor (DivFam.mk G)) := by
      rw [← Scheme.CurveDivisor.coeffAt_add]
      exact hach0
    -- the generation-side bound
    have hge : Scheme.divisorBound
          (thetaFieldDivisor C K π (windowM_choice π hπ g)
            - Scheme.presentationDivisor K G.eqns.presentation) hzg
        ≤ Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hzg
            (thetaFieldRead C K π (windowM_choice π hπ g)
              (relThetaWindowEquiv C K π (windowM_choice π hπ g)
                (relThetaPairH1_windowM C π hπ g) x)) := by
      have hval : Scheme.ord (relCurve C K ↘ Spec (CommRingCat.of K)) hzg
          (thetaFieldRead C K π (windowM_choice π hπ g)
            (relThetaWindowEquiv C K π (windowM_choice π hπ g)
              (relThetaPairH1_windowM C π hπ g) x))
          = Scheme.divisorBound
              (-Scheme.divOf (relCurve C K ↘ Spec (CommRingCat.of K))
                (Units.mk0 _ hread_ne)) hzg :=
        Scheme.ord_val_eq K (Units.mk0 _ hread_ne) hzg
      rw [hval, divisorBound_le_divisorBound_iff hzg,
        Scheme.CurveDivisor.coeffAt_sub, Scheme.CurveDivisor.coeffAt_neg]
      have hDpres : coeffAt hzg (divFamDivisor (DivFam.mk G))
          = coeffAt hzg (Scheme.presentationDivisor K G.eqns.presentation) := by
        rw [divFamDivisor_mk]
      omega
    -- the membership-side bound
    have hle := hread_le x hx hzg
    -- assemble: the germ generates and lies in the window germ set
    have hspan := span_germ_thetaFieldGluedEquiv_eq_stalkIdeal C K π
      (windowM_choice π hπ g) G.eqns
      (relThetaWindowEquiv C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x) hzg hle hge
    have hsmem : relThetaWindowEquiv C K π (windowM_choice π hπ g)
        (relThetaPairH1_windowM C π hπ g) x
        ∈ Submodule.map (relThetaWindowEquiv C K π (windowM_choice π hπ g)
            (relThetaPairH1_windowM C π hπ g)).toLinearMap
          ((divFamEps hπ g (DivFam.mk G)).1) :=
      Submodule.mem_map_of_mem hx
    rw [← hspan]
    refine Ideal.span_mono (Set.singleton_subset_iff.mpr ?_)
    by_cases hz₀ : z ∈ (relCover C K (fiberTwoCover π)).V₀
    · refine Set.mem_union_left _ ⟨_, hsmem, ⟨trivial, hz₀⟩, ?_⟩
      exact germ_thetaFieldGluedEquiv_fst C K π (windowM_choice π hπ g) _ hz₀
        ⟨trivial, (thetaFieldPointedCover C K π).mem_opens z⟩ ⟨trivial, hz₀⟩
    · refine Set.mem_union_right _
        ⟨_, hsmem, ⟨trivial, mem_V₁_of_notMem_V₀ C K π hz₀⟩, ?_⟩
      exact germ_thetaFieldGluedEquiv_snd C K π (windowM_choice π hπ g) _ hz₀
        ⟨trivial, (thetaFieldPointedCover C K π).mem_opens z⟩
        ⟨trivial, mem_V₁_of_notMem_V₀ C K π hz₀⟩

set_option maxRecDepth 8000 in
set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 800000 in
/-- The diagonal specialization of
`CertifiedDivisorFamily.stalkIdeal_le_span_windowGerm_of_field_at`. -/
theorem CertifiedDivisorFamily.stalkIdeal_le_span_windowGerm_of_field (g : ℕ)
    (G : CertifiedDivisorFamily C K π g)
    (hOk : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hχk : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : ℤ))
    (hOK : Sheaf.h0 ((relCurve C K).moduleKSheaf K) = 1)
    (hχK : Sheaf.chi ((relCurve C K).moduleKSheaf K) = 1 - (g : ℤ))
    (z : relCurve C K) :
    G.eqns.stalkIdeal z
      ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z) :=
  CertifiedDivisorFamily.stalkIdeal_le_span_windowGerm_of_field_at
    (gamma := g) hπ g le_rfl G hOk hχk hOK hχK z

/-- **`hwin` over a field**, in the threaded shape of `divFam_divEq_of_eps_eq'`. -/
theorem CertifiedDivisorFamily.windowGen_of_field (g : ℕ)
    (G : CertifiedDivisorFamily C K π g)
    (hOk : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hχk : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : ℤ))
    (hOK : Sheaf.h0 ((relCurve C K).moduleKSheaf K) = 1)
    (hχK : Sheaf.chi ((relCurve C K).moduleKSheaf K) = 1 - (g : ℤ)) :
    ∀ z : relCurve C K, ∃ s : Ideal K,
      (∀ r ∈ s, algebraMap K ((relCurve C K).presheaf.stalk z) r
        ∈ IsLocalRing.maximalIdeal ((relCurve C K).presheaf.stalk z)) ∧
      G.eqns.stalkIdeal z
        ≤ Ideal.span (divFamEpsWindowGermSet hπ g (DivFam.mk G) z)
          ⊔ Ideal.map (algebraMap K ((relCurve C K).presheaf.stalk z)) s := by
  intro z
  refine ⟨⊥, fun r hr => ?_, le_trans
    (CertifiedDivisorFamily.stalkIdeal_le_span_windowGerm_of_field hπ g G
      hOk hχk hOK hχK z) le_sup_left⟩
  rw [Ideal.mem_bot] at hr
  subst hr
  rw [map_zero]
  exact Ideal.zero_mem _

/-- **The relative mono over a field, unconditional**: two certified divisor families
of degree `g` over the field `K` with equal `ε`-pairs are equal in `DivFam` — the
window-recovery second proof of DD-4 Task 6's field mono. -/
theorem divFam_divEq_of_eps_eq_of_field (g : ℕ)
    (G G' : CertifiedDivisorFamily C K π g)
    (heps : divFamEps hπ g (DivFam.mk G) = divFamEps hπ g (DivFam.mk G'))
    (hOk : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hχk : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : ℤ))
    (hOK : Sheaf.h0 ((relCurve C K).moduleKSheaf K) = 1)
    (hχK : Sheaf.chi ((relCurve C K).moduleKSheaf K) = 1 - (g : ℤ)) :
    DivFam.mk G = DivFam.mk G' :=
  divFam_divEq_of_eps_eq' hπ g G G' heps
    (CertifiedDivisorFamily.windowGen_of_field hπ g G hOk hχk hOK hχK)
    (CertifiedDivisorFamily.windowGen_of_field hπ g G' hOk hχk hOK hχK)

end FieldWindow

end AlgebraicGeometry
