/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeHighWindowTransitionSaturationCoefficient
import AlgebraicJacobian.Picard.DivSchemeHighWindowTransitionKernelKill
import AlgebraicJacobian.Picard.DivSchemeHighWindowTransitionQuotient

/-!
# Saturation of the shifted high-window relation system

The two-coordinate recurrence makes the pure windows
`S + q*S` normally generated by the multiplier window `S`.  Cofinal theta
exhaustion therefore realizes multiplication of a relation reading by every
coefficient of a pinned-chart ring at a later recursive relation stage.

The stage-one reading ideal is generated by relation readings.  Ideal-span
induction, with transport to a common later stage in the additive case, gives a
relation witness for every element of this ideal.  Subtracting such a witness
from an arbitrary section with the same reading reduces eventual saturation to
the high-window zero-read kernel-killing theorem.
-/

set_option autoImplicit false
set_option quotPrecheck false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 8
set_option maxRecDepth 8000
set_option linter.unusedSectionVars false

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

open Scheme Grassmannian

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule
attribute [local instance 10000] relCurve.instOver

section HighWindowTransitionSaturation

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
  [SmoothOfRelativeDimension 1 C.hom] [IsProper C.hom]
  [GeometricallyIrreducible C.hom]
variable {pi : C.left ⟶ P1 k} [IsFinite pi] [IsDominant pi]

noncomputable local instance instOverCleftHighWindowTransitionSaturation :
    C.left.Over (Spec (.of k)) := ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))]
  [QuasiCompact (C.left ↘ Spec (.of k))]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hpi : pi ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))
variable (g r1 r2 : Nat)
variable (b1 : Module.Basis (Fin r1) k
  ↥(Scheme.divisorSections k (windowM_choice pi hpi g • fiberWeilDivisor pi) ⊤))
variable (b2 : Module.Basis (Fin r2) k
  ↥(Scheme.divisorSections k ((windowS_choice pi hpi g • fiberWeilDivisor pi)
    + (windowM_choice pi hpi g • fiberWeilDivisor pi)) ⊤))
variable (i : (glueData k g r1).J) (j : (glueData k g r2).J)
variable (side : Bool)

local notation "RZ" => DivCarveChartRing k
  (windowS_choice pi hpi g • fiberWeilDivisor pi)
  (windowM_choice pi hpi g • fiberWeilDivisor pi) g r1 r2 b1 b2 i j
local notation "S" => windowS_choice pi hpi g
local notation "F" => fiberWeilDivisor pi
local notation "HS" => ↥(Scheme.divisorSections k (S • F) ⊤)
local notation "HP" q => ↥(Scheme.divisorSections k ((S + q * S) • F) ⊤)
local notation "G" n => divUniversalHighWindowAmbient (C := C) (pi := pi)
  (hpi := hpi) (g := g) (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2)
  (i := i) (j := j) n
local notation "K" n => divUniversalHighWindowRelation (C := C) (pi := pi)
  hpi g r1 r2 b1 b2 i j n
local notation "B" => Γ(relCurve C RZ, relPinnedChart C RZ pi side)
local notation "CR" => divUniversalHighWindowChartRead (C := C)
  (pi := pi) hpi g r1 r2 b1 b2 i j

/-! ## Eventual multiples of relation readings -/
/-- A coefficient `c` eventually multiplies the selected reading of `x` at a
later recursive relation stage. -/
private def RelationReadMultipleWitness (n : Nat) (x : G(n + 1)) (c : B) : Prop :=
  ∃ m : Nat, ∃ _h : n ≤ m, ∃ y : G(m + 1),
    y ∈ (K(m + 1)) ∧ (CR (m + 1) side) y = c * (CR (n + 1) side) x

set_option maxHeartbeats 1600000 in
-- The zero witness still elaborates the dependent stage-one chart module.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadMultipleWitness_zero (n : Nat) (x : G(n + 1)) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x 0 := by
  refine ⟨n, le_rfl, 0, Submodule.zero_mem _, ?_⟩
  change (CR (n + 1) side) (0 : G(n + 1)) =
    0 * (CR (n + 1) side) x
  simp only [LinearMap.map_zero, zero_mul]

set_option maxHeartbeats 2400000 in
-- Common-stage transport synthesizes both shifted ambient module structures.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadMultipleWitness_add (n : Nat) (x : G(n + 1))
    {c d : B}
    (hc : RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x c)
    (hd : RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x d) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x (c + d) := by
  obtain ⟨m, hnm, y, hy, hry⟩ := hc
  obtain ⟨r, hnr, z, hz, hrz⟩ := hd
  let l := max m r
  let hml : m ≤ l := le_max_left m r
  let hrl : r ≤ l := le_max_right m r
  let y' := divUniversalHighWindowShiftedRelationTransitionOfLE
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side m l hml y
  let z' := divUniversalHighWindowShiftedRelationTransitionOfLE
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r l hrl z
  have hy' : y' ∈ (K(l + 1)) :=
    map_divUniversalHighWindowShiftedRelationTransitionOfLE_relation_le
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side m l hml ⟨y, hy, rfl⟩
  have hz' : z' ∈ (K(l + 1)) :=
    map_divUniversalHighWindowShiftedRelationTransitionOfLE_relation_le
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r l hrl ⟨z, hz, rfl⟩
  refine ⟨l, hnm.trans hml, y' + z', Submodule.add_mem _ hy' hz', ?_⟩
  rw [map_add, divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead,
    divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead, hry, hrz]
  ring

set_option maxHeartbeats 2400000 in
-- Scalar closure unfolds the carve-chart action on the dependent ambient.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadMultipleWitness_smul (n : Nat) (x : G(n + 1))
    (r : RZ) {c : B}
    (hc : RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x c) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x (r • c) := by
  obtain ⟨m, hnm, y, hy, hry⟩ := hc
  let y' : G(m + 1) := r • y
  refine ⟨m, hnm, y', (K(m + 1)).smul_mem r hy, ?_⟩
  change (CR (m + 1) side) (r • y) = _
  rw [map_smul, hry, Scheme.overModule_smul_def,
    Scheme.overModule_smul_def]
  ring

set_option maxHeartbeats 2400000 in
-- The pure multiplier step combines recursive membership and theta reading.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadMultipleWitness_mul_pureS (n : Nat) (x : G(n + 1))
    (a : HS) {c : B}
    (hc : RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x c) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x
        (divUniversalPureWindowCoefficientRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j side 0
            (divUniversalPureWindowZeroTensor (C := C) (pi := pi)
              hpi g r1 r2 b1 b2 i j a) * c) := by
  obtain ⟨m, hnm, y, hy, hry⟩ := hc
  let y' := divUniversalHighWindowTensorMultiplierTransition
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j (m + 1) (1 ⊗ₜ a) y
  have hy' : y' ∈ (K(m + 2)) :=
    map_divUniversalHighWindowTensorMultiplierTransition_relation_succ_le
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j m (1 ⊗ₜ a) ⟨y, hy, rfl⟩
  refine ⟨m + 1, Nat.le.step hnm, y', ?_, ?_⟩
  · simpa only [Nat.add_assoc, Nat.reduceAdd] using hy'
  · rw [divUniversalHighWindowTensorMultiplierTransition_chartRead, hry]
    rw [divUniversalPureWindowCoefficientRead_zeroTensor]
    ring

set_option maxHeartbeats 4800000 in
-- Tensor and span induction repeatedly synthesizes changing relation stages.
set_option synthInstance.maxHeartbeats 1200000 in
/-- Every pure arithmetic-progression coefficient eventually multiplies a
recursive relation reading. -/
private theorem exists_relationReadMultipleWitness_pureWindow (q n : Nat)
    (z : RZ ⊗[k] HP(q)) (x : G(n + 1)) (hx : x ∈ (K(n + 1))) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x
        (divUniversalPureWindowCoefficientRead (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j side q z) := by
  induction q with
  | zero =>
      let z0 : RZ ⊗[k] HS := by
        exact LinearMap.baseChange RZ
          (divisorWindowExponentEquiv (C := C) (pi := pi)
            (by simp : S + 0 * S = S)).toLinearMap z
      let y := divUniversalHighWindowTensorMultiplierTransition
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j (n + 1) z0 x
      have hy : y ∈ (K(n + 2)) :=
        map_divUniversalHighWindowTensorMultiplierTransition_relation_succ_le
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j n z0 ⟨x, hx, rfl⟩
      refine ⟨n + 1, Nat.le_succ n, y, ?_, ?_⟩
      · simpa only [Nat.add_assoc, Nat.reduceAdd] using hy
      · rw [divUniversalHighWindowTensorMultiplierTransition_chartRead]
        rw [divUniversalPureWindowCoefficientRead_zero]
  | succ q ih =>
      induction z with
      | zero =>
          simpa only [map_zero] using
            relationReadMultipleWitness_zero (C := C) (pi := pi)
              hpi g r1 r2 b1 b2 i j side n x
      | add z w hz hw =>
          simpa only [map_add] using
            relationReadMultipleWitness_add (C := C) (pi := pi)
              hpi g r1 r2 b1 b2 i j side n x hz hw
      | tmul r a =>
          let T := Scheme.divisorSections k ((S + (q + 1) * S) • F) ⊤
          let P : C.left.functionField → Prop := fun w =>
            ∀ hw : w ∈ T,
              RelationReadMultipleWitness (C := C) (pi := pi)
                hpi g r1 r2 b1 b2 i j side n x
                  (divUniversalPureWindowCoefficientRead (C := C) (pi := pi)
                    hpi g r1 r2 b1 b2 i j side (q + 1) (1 ⊗ₜ ⟨w, hw⟩))
          have hspan := thetaCoordinate_windowS_mulSpan_eq
            (C := C) pi hpi g q
          have ha : (a : C.left.functionField) ∈
              Scheme.mulSpan k
                (Scheme.divisorSections k (S • F) ⊤)
                (Scheme.divisorSections k ((S + q * S) • F) ⊤) := by
            rw [hspan]
            exact a.property
          have hpa : ∀ (w : C.left.functionField),
              w ∈ Scheme.mulSpan k
                (Scheme.divisorSections k (S • F) ⊤)
                (Scheme.divisorSections k ((S + q * S) • F) ⊤) → P w := by
            intro w hwspan
            induction hwspan using Submodule.span_induction with
            | mem w hw =>
                obtain ⟨a, ha, b, hb, rfl⟩ := hw
                intro hab
                let a' : HS := ⟨a, ha⟩
                let b' : HP(q) := ⟨b, hb⟩
                have hpure := ih (1 ⊗ₜ b')
                have hmul := relationReadMultipleWitness_mul_pureS
                  (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side n x a' hpure
                have hprod : (⟨a * b, hab⟩ : HP(q + 1)) =
                    divUniversalPureWindowProduct (C := C) (pi := pi)
                      hpi g q a' b' := by
                  apply Subtype.ext
                  simp only [coe_divUniversalPureWindowProduct, a', b']
                rw [hprod, divUniversalPureWindowCoefficientRead_product]
                exact hmul
            | zero =>
                intro hzero
                have hzero' : (⟨0, hzero⟩ : HP(q + 1)) = 0 := by
                  apply Subtype.ext
                  rfl
                rw [hzero', TensorProduct.tmul_zero, map_zero]
                exact relationReadMultipleWitness_zero (C := C) (pi := pi)
                  hpi g r1 r2 b1 b2 i j side n x
            | add v w hv hw hvw hww =>
                intro hvaddw
                have hvT : v ∈ T := by
                  change v ∈ Scheme.divisorSections k
                    ((S + (q + 1) * S) • F) ⊤
                  rw [← hspan]
                  exact hv
                have hwT : w ∈ T := by
                  change w ∈ Scheme.divisorSections k
                    ((S + (q + 1) * S) • F) ⊤
                  rw [← hspan]
                  exact hw
                change RelationReadMultipleWitness (C := C) (pi := pi)
                  hpi g r1 r2 b1 b2 i j side n x
                    (divUniversalPureWindowCoefficientRead (C := C) (pi := pi)
                      hpi g r1 r2 b1 b2 i j side (q + 1)
                        (1 ⊗ₜ ⟨v + w, hvaddw⟩))
                have hadd : (⟨v + w, hvaddw⟩ : HP(q + 1)) =
                    ⟨v, hvT⟩ + ⟨w, hwT⟩ := by
                  apply Subtype.ext
                  rfl
                rw [hadd, TensorProduct.tmul_add, map_add]
                exact relationReadMultipleWitness_add (C := C) (pi := pi)
                  hpi g r1 r2 b1 b2 i j side n x (hvw hvT) (hww hwT)
            | smul c v hv hvw =>
                intro hcv
                have hvT : v ∈ T := by
                  change v ∈ Scheme.divisorSections k
                    ((S + (q + 1) * S) • F) ⊤
                  rw [← hspan]
                  exact hv
                have hsmul : (⟨c • v, hcv⟩ : HP(q + 1)) =
                    c • (⟨v, hvT⟩ : HP(q + 1)) := by
                  apply Subtype.ext
                  rfl
                have htensor :
                    (1 ⊗ₜ (⟨c • v, hcv⟩ : HP(q + 1)) : RZ ⊗[k] HP(q + 1)) =
                      algebraMap k RZ c • (1 ⊗ₜ (⟨v, hvT⟩ : HP(q + 1))) := by
                  rw [hsmul, TensorProduct.tmul_smul]
                  exact (IsScalarTower.algebraMap_smul RZ c _).symm
                rw [htensor, map_smul]
                exact relationReadMultipleWitness_smul (C := C) (pi := pi)
                  hpi g r1 r2 b1 b2 i j side n x (algebraMap k RZ c) (hvw hvT)
          have hpure := hpa (a : C.left.functionField) ha a.property
          have htmul : (r ⊗ₜ a : RZ ⊗[k] HP(q + 1)) =
              r • (1 ⊗ₜ a) := by
            rw [TensorProduct.smul_tmul', smul_eq_mul, mul_one]
          rw [htmul, map_smul]
          exact relationReadMultipleWitness_smul (C := C) (pi := pi)
            hpi g r1 r2 b1 b2 i j side n x r hpure

/-! ## From coefficient exhaustion to ideal-span witnesses -/
set_option maxHeartbeats 2400000 in
-- Cofinal exhaustion re-elaborates the inverse relative-theta equivalence.
set_option synthInstance.maxHeartbeats 1200000 in
/-- Every pinned-chart coefficient eventually acts on a recursive relation
reading inside the recursive relation tower. -/
private theorem relationReadMultipleWitness_chartCoefficient
    (hb : 0 < windowBound pi hpi) (n : Nat) (x : G(n + 1))
    (hx : x ∈ (K(n + 1))) (c : B) :
    RelationReadMultipleWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side n x c := by
  have hS : 0 < S := windowS_choice_pos_of_windowBound_pos pi hpi g hb
  obtain ⟨q, s, hs⟩ := exists_arithmeticProgression_relThetaResSide_eq
    C RZ pi S S hS side c
  let z : RZ ⊗[k] HP(q) :=
    (relThetaWindowEquiv C RZ pi (S + q * S)
      (relThetaPairH1_windowS_add_mulS C pi hpi g q)).symm s
  have hz := exists_relationReadMultipleWitness_pureWindow
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side q n z x hx
  have hread : divUniversalPureWindowCoefficientRead (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side q z = c := by
    change relThetaResSide (S + q * S) side le_rfl
      (relThetaWindowEquiv C RZ pi (S + q * S)
        (relThetaPairH1_windowS_add_mulS C pi hpi g q) z) = c
    simpa [z] using hs
  rwa [hread] at hz

/-- A chart section is read by some recursive relation stage. -/
private def RelationReadWitness (c : B) : Prop :=
  ∃ n : Nat, ∃ x : G(n + 1), x ∈ (K(n + 1)) ∧ (CR (n + 1) side) x = c

private theorem relationReadWitness_zero :
    RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side 0 := by
  refine ⟨0, 0, Submodule.zero_mem _, ?_⟩
  change (CR 1 side) (0 : G 1) = 0
  simp only [LinearMap.map_zero]

set_option maxHeartbeats 2400000 in
-- Adding witnesses transports two recursive stages to their common maximum.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadWitness_add {c d : B}
    (hc : RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side c)
    (hd : RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side d) :
    RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side (c + d) := by
  obtain ⟨m, y, hy, hry⟩ := hc
  obtain ⟨r, z, hz, hrz⟩ := hd
  let l := max m r
  let hml : m ≤ l := le_max_left m r
  let hrl : r ≤ l := le_max_right m r
  refine ⟨l,
    divUniversalHighWindowShiftedRelationTransitionOfLE
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side m l hml y +
    divUniversalHighWindowShiftedRelationTransitionOfLE
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r l hrl z, ?_, ?_⟩
  · exact Submodule.add_mem _
      (map_divUniversalHighWindowShiftedRelationTransitionOfLE_relation_le
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side m l hml ⟨y, hy, rfl⟩)
      (map_divUniversalHighWindowShiftedRelationTransitionOfLE_relation_le
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r l hrl ⟨z, hz, rfl⟩)
  · rw [map_add, divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead,
      divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead, hry, hrz]

set_option maxHeartbeats 2400000 in
-- Coefficient closure invokes the full eventual pure-window construction.
set_option synthInstance.maxHeartbeats 1200000 in
private theorem relationReadWitness_mul
    (hb : 0 < windowBound pi hpi) (c : B) {d : B}
    (hd : RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side d) :
    RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side (c * d) := by
  obtain ⟨n, x, hx, hrx⟩ := hd
  obtain ⟨m, _, y, hy, hry⟩ := relationReadMultipleWitness_chartCoefficient
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side hb n x hx c
  refine ⟨m, y, hy, ?_⟩
  rw [hry, hrx]

set_option maxHeartbeats 4800000 in
-- Ideal-span induction traverses the full dependent chart-ring module graph.
set_option synthInstance.maxHeartbeats 1200000 in
/-- Every element of the fixed stage-one reading ideal has a same-reading
relation witness at some shifted stage. -/
private theorem exists_divUniversalHighWindowRelation_chartRead_eq_of_mem_stageOneIdeal
    (hb : 0 < windowBound pi hpi) (c : B)
    (hc : c ∈ divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 1 side) :
    RelationReadWitness (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j side c := by
  rw [divUniversalHighWindowRelationReadIdeal_eq_submodule] at hc
  unfold divUniversalHighWindowSubmoduleReadIdeal at hc
  induction hc using Submodule.span_induction with
  | mem c hc =>
      obtain ⟨x, rfl⟩ := hc
      exact ⟨0, x, x.property, rfl⟩
  | zero =>
      exact relationReadWitness_zero (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j side
  | add c d _ _ hc hd =>
      exact relationReadWitness_add (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j side hc hd
  | smul c d _ hd =>
      exact relationReadWitness_mul (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j side hb c hd

/-! ## Eventual read-kernel saturation -/
set_option maxHeartbeats 4800000 in
-- The final common-stage subtraction re-elaborates two dependent transitions.
set_option synthInstance.maxHeartbeats 1200000 in
/-- The shifted recursive high-window relation system is saturated with respect
to its fixed stage-one pinned-chart reading ideal. -/
theorem exists_divUniversalHighWindowShiftedRelationTransitionOfLE_mem_relation_of_mem_readIdeal
    (hb : 0 < windowBound pi hpi) (n : Nat) (x : G(n + 1))
    (hx : (CR (n + 1) side) x ∈
      divUniversalHighWindowRelationReadIdeal (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j 1 side) :
    ∃ m : Nat, ∃ h : n ≤ m,
      divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side n m h x ∈
        (K(m + 1)) := by
  obtain ⟨r, y, hy, hry⟩ :=
    exists_divUniversalHighWindowRelation_chartRead_eq_of_mem_stageOneIdeal
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side hb
        ((CR (n + 1) side) x) hx
  let l := max n r
  let hnl : n ≤ l := le_max_left n r
  let hrl : r ≤ l := le_max_right n r
  let x' := divUniversalHighWindowShiftedRelationTransitionOfLE
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side n l hnl x
  let y' := divUniversalHighWindowShiftedRelationTransitionOfLE
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r l hrl y
  have hzero : (CR (l + 1) side) (x' - y') = 0 := by
    rw [map_sub, divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead,
      divUniversalHighWindowShiftedRelationTransitionOfLE_chartRead, hry, sub_self]
  obtain ⟨m, hlm, hkill⟩ :=
    exists_divUniversalHighWindowShiftedRelationTransitionOfLE_mem_relation_of_chartRead_eq_zero
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hb side l (x' - y') hzero
  let hnm : n ≤ m := hnl.trans hlm
  let hrm : r ≤ m := hrl.trans hlm
  have hym :
      divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r m hrm y ∈
        (K(m + 1)) :=
    map_divUniversalHighWindowShiftedRelationTransitionOfLE_relation_le
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r m hrm ⟨y, hy, rfl⟩
  have hmapx :
      divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side l m hlm x' =
        divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side n m hnm x := by
    simpa only [x', hnm, divUniversalHighWindowShiftedRelationTransitionOfLE] using
      HighWindowTransitionKit.transitionOfLE_map_map
        (fun q => G(q + 1))
        (fun q => divUniversalHighWindowRelationTransition (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j side (q + 1)) n l m hnl hlm x
  have hmapy :
      divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side l m hlm y' =
        divUniversalHighWindowShiftedRelationTransitionOfLE
          (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side r m hrm y := by
    simpa only [y', hrm, divUniversalHighWindowShiftedRelationTransitionOfLE] using
      HighWindowTransitionKit.transitionOfLE_map_map
        (fun q => G(q + 1))
        (fun q => divUniversalHighWindowRelationTransition (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j side (q + 1)) r l m hrl hlm y
  have hsum := (K(m + 1)).add_mem hkill hym
  rw [map_sub, hmapx, hmapy, sub_add_cancel] at hsum
  exact ⟨m, hnm, hsum⟩

/-! ## The genuine chart-ideal flatness consumer -/

set_option maxHeartbeats 2400000 in
-- The wrapper only specializes the already-proved direct-limit criterion and
-- rewrites the stabilized stage-one ideal to the original seed ideal.
set_option synthInstance.maxHeartbeats 800000 in
/-- Once every finite high-window quotient is flat, the shifted colimit is flat
over the actual chart-reading ideal of the first universal seed.

This is deliberately conditional on finite-stage flatness.  In particular, it
does not identify the linear range of the reading map with the algebra ideal,
and it does not use Nakayama to manufacture flatness. -/
theorem flat_chartReadIdeal_divUniversalSeedK_of_all_stage
    (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : Int))
    (hb : 0 < windowBound pi hpi)
    [hflat : ∀ n, Module.Flat RZ
      ((G(n + 1)) ⧸ K(n + 1))] :
    Module.Flat RZ
      (B ⧸ ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side) := by
  have hcolim := flat_shifted_highWindow_chart_quotient_of_saturation
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hb side
    (fun n x hx =>
      exists_divUniversalHighWindowShiftedRelationTransitionOfLE_mem_relation_of_mem_readIdeal
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side hb n x hx)
  rw [divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb side,
    chartReadIdeal_divUniversalSeedK'_eq_divUniversalSeedK
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb side] at hcolim
  exact hcolim

set_option maxHeartbeats 2400000 in
-- Transporting colimit flatness through both off-diagonal seed ideals is elaboration-heavy.
set_option synthInstance.maxHeartbeats 800000 in
/-- Once every finite degree-`g` high-window quotient is flat, the shifted
colimit is flat over the first seed ideal at independent curve parameter
`gamma ≤ g`. -/
theorem flat_chartReadIdeal_divUniversalSeedK_of_all_stage_at {gamma : Nat}
    (hgamma : gamma ≤ g)
    (hchiGamma : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ))
    [hflat : ∀ n, Module.Flat RZ ((G(n + 1)) ⧸ K(n + 1))] :
    Module.Flat RZ
      (B ⧸ ThetaGeneratorSeed.chartReadIdeal
        (divUniversalSeedK C pi hpi g r1 r2 b1 b2 i j) side) := by
  have hcolim := flat_shifted_highWindow_chart_quotient_of_saturation
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j
      (windowBound_pos pi hpi) side
    (fun n x hx =>
      exists_divUniversalHighWindowShiftedRelationTransitionOfLE_mem_relation_of_mem_readIdeal
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j side
          (windowBound_pos pi hpi) n x hx)
  rw [divUniversalHighWindowRelationReadIdeal_one_eq_chartReadIdeal_at
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchiGamma side,
    chartReadIdeal_divUniversalSeedK'_eq_divUniversalSeedK_at
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchiGamma side] at hcolim
  exact hcolim

end HighWindowTransitionSaturation
end AlgebraicGeometry
