/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeHighWindowStage
import AlgebraicJacobian.Picard.DivSchemeHighWindowPersistence
import AlgebraicJacobian.Picard.DivSchemeSeedUnivSecondWindowBaseChange

/-!
# Recursive relation modules in every high divisor-scheme window

This file constructs the relative relation tower generated by the multiplier window.
The initial relation module is the universal first carve window.  Its first successor
reuses the already-landed finite universal multiplication span, transported to high-window
index one.  Every later successor is the range of the analogous finite basis-indexed
multiplication map.

Only finite generation is asserted.  In particular, no high relation module is assumed
to be a Grassmannian point, projective, pure, or to have flat quotient; those are the
scheme-theoretic persistence obligations which remain after this formal recursion.
-/

set_option autoImplicit false
set_option quotPrecheck false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 8
set_option maxRecDepth 8000
-- Recurrence declarations deliberately retain the standing curve pack through their ambients.
set_option linter.unusedSectionVars false

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

open Scheme Grassmannian

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule
attribute [local instance 10000] relCurve.instOver

section HighWindowRelations

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
  [hSmoothC : SmoothOfRelativeDimension 1 C.hom] [hProperC : IsProper C.hom]
  [hGeometricallyIrreducibleC : GeometricallyIrreducible C.hom]
variable {pi : C.left ⟶ P1 k} [IsFinite pi] [IsDominant pi]

noncomputable local instance instOverCleftHighWindowRelations :
    C.left.Over (Spec (.of k)) := ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))]
  [QuasiCompact (C.left ↘ Spec (.of k))]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hpi : pi ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))
variable (g r1 r2 : Nat)
variable (b1 : Module.Basis (Fin r1) k
  ↥(Scheme.divisorSections k (windowM_choice pi hpi g • fiberWeilDivisor pi) ⊤))
variable (b2 : Module.Basis (Fin r2) k
  ↥(Scheme.divisorSections k ((windowS_choice pi hpi g • fiberWeilDivisor pi)
    + (windowM_choice pi hpi g • fiberWeilDivisor pi)) ⊤))
variable (i : (glueData k g r1).J) (j : (glueData k g r2).J)

local notation "RZ" => DivCarveChartRing k
  (windowS_choice pi hpi g • fiberWeilDivisor pi)
  (windowM_choice pi hpi g • fiberWeilDivisor pi) g r1 r2 b1 b2 i j
local notation "HS" => ↥(Scheme.divisorSections k
  (windowS_choice pi hpi g • fiberWeilDivisor pi) ⊤)

/-! ## The arbitrary successor multiplication map -/

/-- Reindex the product divisor `sF + (M + n*s)F` as the next high window. -/
noncomputable def divUniversalHighWindowSuccEquiv (n : Nat) :
    ↥(Scheme.divisorSections k
        ((windowS_choice pi hpi g • fiberWeilDivisor pi) +
          (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g n •
            fiberWeilDivisor pi)) ⊤) ≃ₗ[k]
      divUniversalHighWindowSections (C := C) (pi := pi) hpi g (n + 1) :=
  LinearEquiv.ofEq _ _ (congrArg (fun D => Scheme.divisorSections k D ⊤) (by
    rw [← add_nsmul]
    apply congrArg (fun m : Nat => m • fiberWeilDivisor pi)
    simp only [divUniversalHighWindowExponent, Nat.succ_mul]
    omega))

/-- Multiplication by one multiplier-basis section from high window `n` to `n+1`. -/
noncomputable def divUniversalHighWindowShiftMul (n : Nat) (a : HS) :
    divUniversalHighWindowSections (C := C) (pi := pi) hpi g n →ₗ[k]
      divUniversalHighWindowSections (C := C) (pi := pi) hpi g (n + 1) :=
  (divUniversalHighWindowSuccEquiv (C := C) (pi := pi) hpi g n).toLinearMap.comp
    (sectionMulBilin k
      (windowS_choice pi hpi g • fiberWeilDivisor pi)
      (divUniversalHighWindowExponent (C := C) (pi := pi) hpi g n •
        fiberWeilDivisor pi) a)

/-- The finite tuple source used to span the successor of a relation module `K`. -/
noncomputable abbrev DivUniversalHighWindowMulSource (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n)) :
    Type u :=
  Fin (Module.finrank k HS) → ↥K

set_option maxHeartbeats 1600000 in
-- Elaborating the nested base change and dependent high-window ambient exceeds the default budget.
/-- The finite basis-indexed multiplication map carrying `K_n` into window `n+1`. -/
noncomputable def divUniversalHighWindowMulMap (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n)) :
    DivUniversalHighWindowMulSource (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n K →ₗ[RZ]
      divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) (n + 1) :=
  ∑ t : Fin (Module.finrank k HS),
    (LinearMap.baseChange RZ
      (divUniversalHighWindowShiftMul (C := C) (pi := pi) hpi g n
        ((Module.finBasis k HS) t))).comp
      (K.subtype.comp (LinearMap.proj t))

/-- The successor relation module: the finite `RZ`-linear multiplication span of `K`. -/
noncomputable def divUniversalHighWindowMulSpan (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n)) :
    Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) (n + 1)) :=
  LinearMap.range
    (divUniversalHighWindowMulMap (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j n K)

set_option synthInstance.maxHeartbeats 400000 in
-- Finiteness inference unfolds the dependent finite tuple source.
/-- A successor multiplication source is finite when its input relation module is finite. -/
theorem finite_divUniversalHighWindowMulSource (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n))
    [Module.Finite RZ ↥K] :
    Module.Finite RZ
      (DivUniversalHighWindowMulSource (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n K) := by
  infer_instance

set_option maxHeartbeats 1600000 in
-- Reducing the dependent range and its base-changed map exceeds the default budget.
set_option synthInstance.maxHeartbeats 400000 in
-- The range instance combines source finiteness with the dependent multiplication map.
/-- The finite multiplication span of a finite relation module is finite. -/
theorem finite_divUniversalHighWindowMulSpan (n : Nat)
    (K : Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n))
    [Module.Finite RZ ↥K] :
    Module.Finite RZ
      ↥(divUniversalHighWindowMulSpan (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n K) := by
  letI := finite_divUniversalHighWindowMulSource
    (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j n K
  infer_instance

/-! ## The recursive relation tower -/

set_option maxHeartbeats 1600000 in
-- The recursive ambient changes with the index and requires extended definitional reduction.
/-- The recursive high-window relation modules.

Stage zero is the universal first window.  Stage one is the already-landed universal
multiplication span transported to the high-window ambient.  From stage one onward the
successor is formed by `divUniversalHighWindowMulSpan`. -/
noncomputable def divUniversalHighWindowRelation :
    (n : Nat) → Submodule RZ
      (divUniversalHighWindowAmbient (C := C) (pi := pi) (hpi := hpi) (g := g)
        (r1 := r1) (r2 := r2) (b1 := b1) (b2 := b2) (i := i) (j := j) n)
  | 0 => (divUniversalHighWindowStageZero (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j).toSubmodule
  | 1 => Submodule.map
      (LinearMap.baseChange RZ
        (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap)
      (universalMulSpan (C := C) (π := pi) hpi g r1 r2 b1 b2 i j)
  | n + 2 => divUniversalHighWindowMulSpan (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j (n + 1)
      (divUniversalHighWindowRelation (n + 1))

set_option maxHeartbeats 1600000 in
-- Reducing the stage-zero dependent ambient exceeds the default definitional-equality budget.
@[simp]
theorem divUniversalHighWindowRelation_zero :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 0 =
      (divUniversalHighWindowStageZero (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j).toSubmodule :=
  rfl

set_option maxHeartbeats 1600000 in
-- Reducing the transported stage-one ambient exceeds the default definitional-equality budget.
@[simp]
theorem divUniversalHighWindowRelation_one_transport :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 1 =
      Submodule.map
        (LinearMap.baseChange RZ
          (divUniversalHighWindowOneEquiv (C := C) (pi := pi) hpi g).toLinearMap)
        (universalMulSpan (C := C) (π := pi) hpi g r1 r2 b1 b2 i j) :=
  rfl

@[simp]
theorem divUniversalHighWindowRelation_succ_succ (n : Nat) :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j (n + 2) =
      divUniversalHighWindowMulSpan (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j (n + 1)
        (divUniversalHighWindowRelation (C := C) (pi := pi)
          hpi g r1 r2 b1 b2 i j (n + 1)) :=
  rfl

set_option maxHeartbeats 1600000 in
-- The recursive ambient changes with the index and requires extended definitional reduction.
set_option synthInstance.maxHeartbeats 400000 in
-- Successor finiteness repeatedly unfolds the dependent range instance.
/-- Every recursively generated relation module is finite over `RZ`. -/
theorem finite_divUniversalHighWindowRelation :
    ∀ n : Nat, Module.Finite RZ
      ↥(divUniversalHighWindowRelation (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j n)
  | 0 => by
      let x := divUniversalHighWindowStageZero (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j
      letI := finite_divUniversalHighWindowQuotient
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j 0 x
      letI := projective_divUniversalHighWindowQuotient
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j 0 x
      exact finite_submodule_of_projective_quotient x.toSubmodule
  | 1 => by
      letI := finite_universalMulSpan (C := C) (π := pi)
        hpi g r1 r2 b1 b2 i j
      infer_instance
  | n + 2 => by
      letI := finite_divUniversalHighWindowRelation (n + 1)
      exact finite_divUniversalHighWindowMulSpan
        (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j (n + 1)
          (divUniversalHighWindowRelation (C := C) (pi := pi)
            hpi g r1 r2 b1 b2 i j (n + 1))

/-! ## Agreement with the two landed universal windows -/

set_option maxHeartbeats 1600000 in
-- Expanding stage zero compares two dependent tensor-product ambients.
/-- Stage zero, expanded all the way to the transported universal first window. -/
theorem divUniversalHighWindowRelation_zero_eq_firstWindow :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 0 =
      Submodule.map
        (LinearMap.baseChange RZ
          (divUniversalHighWindowZeroEquiv (C := C) (pi := pi) hpi g).toLinearMap)
        (divUniversalFstWindow C pi hpi g r1 r2 b1 b2 i j).toSubmodule := by
  rw [divUniversalHighWindowRelation_zero,
    divUniversalHighWindowStageZero_toSubmodule]

set_option maxHeartbeats 1600000 in
-- Comparing the two transported second-window ambients is definitionally expensive.
/-- Under the landed relative persistence hypotheses, stage one is exactly the
transported universal second window. -/
theorem divUniversalHighWindowRelation_one_eq_secondWindow
    (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : Int))
    (hb : 0 < windowBound pi hpi) :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 1 =
      (divUniversalHighWindowStageOne (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j).toSubmodule := by
  rw [divUniversalHighWindowRelation_one_transport,
    universalMulSpan_eq_divUniversalSndWindow
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hO hchi hb,
    divUniversalHighWindowStageOne_toSubmodule]

set_option maxHeartbeats 1600000 in
-- Comparing the two transported second-window ambients is definitionally expensive.
/-- At independent Euler parameter `gamma ≤ g`, stage one is exactly the transported
universal second window of divisor degree `g`. -/
theorem divUniversalHighWindowRelation_one_eq_secondWindow_at {gamma : ℕ}
    (hgamma : gamma ≤ g)
    (hchi : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (gamma : ℤ)) :
    divUniversalHighWindowRelation (C := C) (pi := pi)
      hpi g r1 r2 b1 b2 i j 1 =
      (divUniversalHighWindowStageOne (C := C) (pi := pi)
        hpi g r1 r2 b1 b2 i j).toSubmodule := by
  rw [divUniversalHighWindowRelation_one_transport,
    universalMulSpan_eq_divUniversalSndWindow_at
      (C := C) (pi := pi) hpi g r1 r2 b1 b2 i j hgamma hchi,
    divUniversalHighWindowStageOne_toSubmodule]

end HighWindowRelations

end AlgebraicGeometry
