/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import AlgebraicJacobian.Picard.DivCarveKit

/-!
# Base change of a submodule with projective quotient

The inclusion of a submodule with projective quotient is split.  Consequently its
scalar extension is injective over an arbitrary algebra, without a flatness
hypothesis on that algebra.  This packages the resulting identification with
`Submodule.baseChange`.
-/

set_option autoImplicit false

universe u

open scoped TensorProduct

namespace AlgebraicGeometry.Grassmannian

variable {R S M : Type u} [CommRing R] [CommRing S] [Algebra R S]
variable [AddCommGroup M] [Module R M]

/-- Scalar extension of a submodule with projective quotient, identified with the
submodule generated by its image after base change. -/
noncomputable def projectiveQuotientBaseChangeEquiv (N : Submodule R M)
    [Module.Projective R (M ⧸ N)] :
    S ⊗[R] N ≃ₗ[S] N.baseChange S := by
  have hsplit : quotRetract N ∘ₗ N.subtype = LinearMap.id :=
    LinearMap.ext fun x => quotRetract_apply_of_mem N x.2
  have hinj : Function.Injective (LinearMap.baseChange S N.subtype) := by
    have hleft : LinearMap.baseChange S (quotRetract N) ∘ₗ
        LinearMap.baseChange S N.subtype = LinearMap.id := by
      rw [← LinearMap.baseChange_comp, hsplit, LinearMap.baseChange_id]
    exact Function.LeftInverse.injective
      (g := LinearMap.baseChange S (quotRetract N))
      fun x => by rw [← LinearMap.comp_apply, hleft, LinearMap.id_apply]
  refine LinearEquiv.ofBijective (N.toBaseChange S) ⟨?_, N.toBaseChange_surjective S⟩
  intro x y hxy
  apply hinj
  exact congrArg Subtype.val hxy

@[simp]
theorem projectiveQuotientBaseChangeEquiv_apply (N : Submodule R M)
    [Module.Projective R (M ⧸ N)] (x : S ⊗[R] N) :
    projectiveQuotientBaseChangeEquiv (S := S) N x = N.toBaseChange S x :=
  rfl

section Window

variable {k K H : Type u} [Field k] [CommRing K]
variable [Algebra k R] [Algebra k K] [Algebra R K] [IsScalarTower k R K]
variable [AddCommGroup H] [Module k H]

/-- A projective-quotient window after scalar extension, identified with the kernel
of its base-changed quotient map in the cancelled tensor-product ambient. -/
noncomputable def projectiveQuotientWindowFibreEquiv
    (N : Submodule R (TensorProduct k R H))
    [Module.Projective R (TensorProduct k R H ⧸ N)] :
    K ⊗[R] N ≃ₗ[K]
      LinearMap.ker (Module.Grassmannian.baseChangeMkQ K N) :=
  (projectiveQuotientBaseChangeEquiv (S := K) N).trans
    ((Submodule.equivMapOfInjective
      (TensorProduct.AlgebraTensorModule.cancelBaseChange k R K K H).toLinearMap
      (TensorProduct.AlgebraTensorModule.cancelBaseChange k R K K H).injective
      (N.baseChange K)).trans
        (LinearEquiv.ofEq _ _
          (ker_baseChangeMkQ_eq_map_baseChange K N).symm))

end Window

end AlgebraicGeometry.Grassmannian
