/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeRedesignRankOneFibre
import AlgebraicJacobian.Picard.DivSchemeRedesignChartReadIdeal

/-!
# Rank-one fibre reduction for the chart colength

This is the geometric wrapper around `RankOneFibre`: the genuine chart-reading ideal is mapped
to `B/(read s)`, and that image is definitionally `chartIdealColengthModule`.  Thus a pointwise
span statement for the fibre of the ideal immediately gives the desired vanishing of the
colength fibre.  The span statement is allowed to include the zero-fibre case.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false

universe u

open CategoryTheory TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {π : C.left ⟶ P1 k} [IsFinite π] {a : ℕ}

namespace ThetaGeneratorSeed

/-- **Pointwise chart-colength fibre vanishing from ideal-fibre span.**  Let `B` be the
pinned-chart section ring, `J` the genuine `B`-ideal generated by the readings of `K`, and
`I = (read s)` for `s ∈ K`.  If every vector of
`κ(p) ⊗[B] J` is a scalar multiple of `1 ⊗ read(s)`, then the image of `J` in `B/I` has
zero `κ(p)`-fibre.  This is the exact single-point input consumed by the `κ(z)` RD-N bridge;
it uses no global base-fibre or flatness inference. -/
theorem subsingleton_chartIdealColengthModule_tensor_residueField_of_ideal_span
    (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a) (hsK : s ∈ K)
    (p : PrimeSpectrum Γ(relCurve C R, relPinnedChart C R π b))
    (hspan : ∀ v : p.asIdeal.ResidueField ⊗[
        Γ(relCurve C R, relPinnedChart C R π b)]
        (chartReadIdeal K b), ∃ c : p.asIdeal.ResidueField,
          c • ((1 : p.asIdeal.ResidueField) ⊗ₜ[
            Γ(relCurve C R, relPinnedChart C R π b)]
            (⟨relThetaResSide a b (le_rfl) s,
              by
                exact Ideal.subset_span ⟨⟨s, hsK⟩, rfl⟩⟩ :
              chartReadIdeal K b)) = v) :
    Subsingleton ((chartIdealColengthModule K b s) ⊗[
      Γ(relCurve C R, relPinnedChart C R π b)] p.asIdeal.ResidueField) := by
  let B : Type u := Γ(relCurve C R, relPinnedChart C R π b)
  let I : Ideal B := Ideal.span {relThetaResSide a b le_rfl s}
  let P : Submodule B B := chartReadIdeal K b
  let f : B →ₗ[B] (B ⧸ I) := (Ideal.Quotient.mkₐ B I).toLinearMap
  have hsP : relThetaResSide a b le_rfl s ∈ P := by
    exact Ideal.subset_span ⟨⟨s, hsK⟩, rfl⟩
  have hfs : f (relThetaResSide a b le_rfl s) = 0 := by
    change Ideal.Quotient.mk I (relThetaResSide a b le_rfl s) = 0
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (by simp))
  have hzero := RankOneFibre.subsingleton_map_tensor_of_span_singleton
    P f (relThetaResSide a b le_rfl s) hsP (by
      · intro v
        exact hspan v) (by
      · exact hfs)
  change Subsingleton ((P.map f) ⊗[B] p.asIdeal.ResidueField) at hzero
  exact hzero

end ThetaGeneratorSeed

end AlgebraicGeometry
