/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeRedesignIdealPurity
import Mathlib.RingTheory.Finiteness.Ideal
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Nakayama

/-!
# Lifting fibre-local principal generation to the total stalk

Let `R → B`, let `q ∈ Spec B`, and put `p = q ∩ R`.  If `J ⊆ B` is
finitely generated and `B / J` is flat over `R`, then principal generation
of `J` near `q` in the fibre over `p` lifts to principal generation in the
total local ring `B_q`.

The fibre input below is deliberately stated in denominator-cleared form:
for every `x ∈ J`, there is `r ∉ q` such that

`r * x ∈ (e) + pB`.

This is exactly the elementwise form of the localized fibre containment

`J_q ⊆ (e) + p B_q`.

Flatness of `B / J` gives the purity identity `J ∩ pB = pJ`.  Consequently,
after localizing and quotienting `J_q` by `(e)`, the displayed containment
becomes `J_q / (e) = p (J_q / (e))`.  Since `p B_q` lies in the maximal ideal
and `J_q` is finite, Nakayama gives `J_q = (e)`.  The final statement clears
the localization denominator again.
-/

set_option autoImplicit false

universe u

namespace AlgebraicGeometry

namespace FibreToStalkFlat

open scoped TensorProduct

variable {R B : Type u} [CommRing R] [CommRing B] [Algebra R B]

/-! ## The flat-quotient intersection identity -/

/-- If `B / J` is flat over `R`, an element of `J` which lies in the extension
of an `R`-ideal `p` already lies in `pJ` (viewed first as the `R`-submodule
`p • J`).  This is the elementwise content of `J ∩ pB = pJ`. -/
theorem mem_smul_top_of_mem_map_of_flat_quotient
    (J : Ideal B) [Module.Flat R (B ⧸ J)] (p : Ideal R) (x : J)
    (hx : (x : B) ∈ Ideal.map (algebraMap R B) p) :
    x ∈ p • (⊤ : Submodule R J) := by
  have hzeroAmbient :
      ((J.restrictScalars R).subtype.lTensor (R ⧸ p))
          ((1 : R ⧸ p) ⊗ₜ[R] x) = 0 := by
    rw [LinearMap.lTensor_tmul]
    apply (TensorProduct.quotTensorEquivQuotSMul B p).injective
    rw [map_zero, TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul,
      Submodule.Quotient.mk_eq_zero, Ideal.smul_top_eq_map]
    exact hx
  have hzero : ((1 : R ⧸ p) ⊗ₜ[R] x) = 0 :=
    (IdealPurity.subtype_lTensor_injective_of_flat_quotient
      (R := R) (B := B) J (R ⧸ p)) hzeroAmbient
  have hmk :
      (Submodule.Quotient.mk x : J ⧸ (p • (⊤ : Submodule R J))) = 0 := by
    rw [← TensorProduct.quotTensorEquivQuotSMul_mk_one_tmul]
    rw [hzero, map_zero]
  rw [Submodule.Quotient.mk_eq_zero] at hmk
  exact hmk

/-- Ideal-valued form of
`mem_smul_top_of_mem_map_of_flat_quotient`: `J ∩ pB ⊆ (pB)J`. -/
theorem mem_map_mul_of_mem_map_of_flat_quotient
    (J : Ideal B) [Module.Flat R (B ⧸ J)] (p : Ideal R) (x : J)
    (hx : (x : B) ∈ Ideal.map (algebraMap R B) p) :
    (x : B) ∈ Ideal.map (algebraMap R B) p * J := by
  have hp := mem_smul_top_of_mem_map_of_flat_quotient
    (R := R) (B := B) J p x hx
  refine Submodule.smul_induction_on hp (fun r hr y _ ↦ ?_) (fun y z hy hz ↦ ?_)
  · simpa [Algebra.smul_def] using
      Ideal.mul_mem_mul (Ideal.mem_map_of_mem (algebraMap R B) hr) y.2
  · exact (Ideal.map (algebraMap R B) p * J).add_mem hy hz

/-! ## Fibre-to-stalk lifting -/

variable {L : Type u} [CommRing L] [Algebra B L] [Algebra R L]
variable [IsScalarTower R B L]

/-- **Fibre-to-total-stalk lift.**

The hypothesis `hfibre` is the denominator-cleared version of fibre-local
generation at `q`: every `x ∈ J` becomes a sum of a multiple of `e` and an
element from the contracted base prime after multiplication by some element
outside `q`.  Flatness of `B / J` converts the base-prime summand into `pJ`,
and local Nakayama removes it.

The conclusion is likewise denominator-cleared: it says precisely that the
image of every `x ∈ J` in `B_q` belongs to the principal ideal generated by
the image of `e`. -/
theorem exists_notMem_mul_mem_span_singleton_of_fibre_of_flat_quotient_of_isLocalization
    (q : PrimeSpectrum B) [IsLocalization.AtPrime L q.asIdeal]
    (J : Ideal B) (hJfg : J.FG) [Module.Flat R (B ⧸ J)]
    (e : B) (he : e ∈ J)
    (hfibre : ∀ x : J, ∃ r : B, r ∉ q.asIdeal ∧
      r * (x : B) ∈
        Ideal.span ({e} : Set B) ⊔
          Ideal.map (algebraMap R B)
            (Ideal.comap (algebraMap R B) q.asIdeal)) :
    ∀ x : J, ∃ r : B, r ∉ q.asIdeal ∧
      r * (x : B) ∈ Ideal.span ({e} : Set B) := by
  letI : IsLocalRing L :=
    IsLocalization.AtPrime.isLocalRing L q.asIdeal
  let p : Ideal R := Ideal.comap (algebraMap R B) q.asIdeal
  let JL : Ideal L := Ideal.map (algebraMap B L) J
  let E : Ideal L := Ideal.span ({algebraMap B L e} : Set L)
  let I : Ideal L := Ideal.map (algebraMap R L) p
  have hImax : I ≤ IsLocalRing.maximalIdeal L := by
    change Ideal.map (algebraMap R L) p ≤ IsLocalRing.maximalIdeal L
    rw [Ideal.map_le_iff_le_comap]
    intro r hr
    change algebraMap R L r ∈ IsLocalRing.maximalIdeal L
    rw [IsScalarTower.algebraMap_apply R B L]
    exact (IsLocalization.AtPrime.to_map_mem_maximal_iff
      L q.asIdeal (algebraMap R B r)).2 hr
  have hIjac : I ≤ (⊥ : Ideal L).jacobson :=
    hImax.trans (IsLocalRing.maximalIdeal_le_jacobson ⊥)
  have hlocal : JL ≤ E ⊔ I * JL := by
    change Ideal.map (algebraMap B L) J ≤ E ⊔ I * JL
    rw [Ideal.map_le_iff_le_comap]
    intro x hx
    obtain ⟨r, hr, hrx⟩ := hfibre ⟨x, hx⟩
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp hrx
    have haJ : a ∈ J :=
      (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr he)) ha
    have hbJ : b ∈ J := by
      have hbeq : b = r * x - a := by rw [← hab]; ring
      rw [hbeq]
      exact J.sub_mem (J.mul_mem_left r hx) haJ
    have hbMul : b ∈ Ideal.map (algebraMap R B) p * J :=
      mem_map_mul_of_mem_map_of_flat_quotient
        (R := R) (B := B) J p ⟨b, hbJ⟩ hb
    have hma : algebraMap B L a ∈ E := by
      have := Ideal.mem_map_of_mem (algebraMap B L) ha
      simpa [E, Ideal.map_span] using this
    have hmb : algebraMap B L b ∈ I * JL := by
      have := Ideal.mem_map_of_mem (algebraMap B L) hbMul
      simpa [I, JL, p, Ideal.map_mul, Ideal.map_map,
        IsScalarTower.algebraMap_eq R B L] using this
    have hrxLocal :
        algebraMap B L r * algebraMap B L x ∈ E ⊔ I * JL := by
      have habLocal := congrArg (algebraMap B L) hab
      rw [map_add, map_mul] at habLocal
      rw [← habLocal]
      exact Submodule.add_mem _
        (Submodule.mem_sup_left hma) (Submodule.mem_sup_right hmb)
    have hrUnit : IsUnit (algebraMap B L r) :=
      IsLocalization.map_units L (⟨r, hr⟩ : q.asIdeal.primeCompl)
    exact (Ideal.unit_mul_mem_iff_mem (E ⊔ I * JL) hrUnit).mp hrxLocal
  have hNak : (JL : Submodule L L) ≤ (E : Submodule L L) := by
    apply Submodule.le_of_le_smul_of_le_jacobson_bot
      (hJfg.map (algebraMap B L)) hIjac
    simpa only [Ideal.smul_eq_mul] using hlocal
  intro x
  have hxLocal :
      algebraMap B L (x : B) ∈
        Ideal.map (algebraMap B L) (Ideal.span ({e} : Set B)) := by
    have hxJL : algebraMap B L (x : B) ∈ JL := by
      exact Ideal.mem_map_of_mem (algebraMap B L) x.2
    have hxE : algebraMap B L (x : B) ∈ E := hNak hxJL
    simpa [E, Ideal.map_span] using hxE
  obtain ⟨r, hr, hrx⟩ :=
    (IsLocalization.algebraMap_mem_map_algebraMap_iff
      q.asIdeal.primeCompl L (Ideal.span ({e} : Set B)) (x : B)).mp hxLocal
  exact ⟨r, hr, hrx⟩

/-- The specialization of
`exists_notMem_mul_mem_span_singleton_of_fibre_of_flat_quotient_of_isLocalization`
to mathlib's canonical localization `B_q`.  This is the convenient form for
callers: no choice of a localization model occurs in its statement. -/
theorem exists_notMem_mul_mem_span_singleton_of_fibre_of_flat_quotient
    (q : PrimeSpectrum B) (J : Ideal B) (hJfg : J.FG)
    [Module.Flat R (B ⧸ J)] (e : B) (he : e ∈ J)
    (hfibre : ∀ x : J, ∃ r : B, r ∉ q.asIdeal ∧
      r * (x : B) ∈
        Ideal.span ({e} : Set B) ⊔
          Ideal.map (algebraMap R B)
            (Ideal.comap (algebraMap R B) q.asIdeal)) :
    ∀ x : J, ∃ r : B, r ∉ q.asIdeal ∧
      r * (x : B) ∈ Ideal.span ({e} : Set B) := by
  let L := Localization.AtPrime q.asIdeal
  exact
    exists_notMem_mul_mem_span_singleton_of_fibre_of_flat_quotient_of_isLocalization
      (R := R) (B := B) (L := L) q J hJfg e he hfibre

end FibreToStalkFlat

end AlgebraicGeometry
