/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.DivSchemeCertZarConn

/-!
# The coarse adaptation: one piece per pinned chart

`DivSchemeCertZarConn.lean` decides which divisors the assembler route can reach at all: a
connected one must lie inside a single pinned chart.  This file supplies the adaptation to use
once that holds, and it is the coarsest one possible — **one piece per chart, the chart
itself**.

`FinCoverData` asks for a partition of unity on each pinned chart; taking a single generator
`h = 1` with coefficient `a = 1` satisfies it trivially, and `Scheme.basicOpen_one` identifies
the resulting piece with the chart.  Feeding that cover data to the landed anchored
constructor `DivisorAdaptation.ofAnchors` turns a *chart-principality* datum — one member of
`d`'s cover containing each pinned chart, with a comparison unit — into an adaptation whose
two pieces are `V₀` and `V₁`.

For that adaptation the certificate's per-piece obligations are as small as they can be:

* if `supportLocus ⊆ V₀ ⊓ V₁` then **both** pieces swallow the support, so `hnoLeak` and
  clause (c1)-finite hold at every piece (`DivSchemeCertZarSwallow.lean`), with no fibre
  analysis and no packet idempotent;
* none of the landed no-gos touches this configuration.  `not_exists_unique_support_piece`
  refutes *one* support-meeting piece and this adaptation has *two*;
  `supportLocus_disjoint_chart_inter_of_separated` refutes *separation* and this adaptation is
  as unseparated as possible — its two pieces share the whole overlap.

The residual hypothesis, chart principality, is the honest one: it says the divisor is cut by
a single equation on each pinned chart, i.e. it is the statement that the DD-R window's local
generators can be taken globally on a chart.  The pointwise gate
(`isLocallyCertified_of_forall_prime_exists_certified_adaptation`) licenses shrinking the base
before asking for it.

## Main declarations

* `AlgebraicGeometry.chartPairCoverData` — the two-piece cover data, one piece per pinned
  chart, with `pieces_inl`/`pieces_inr` identifying the pieces with `V₀` and `V₁`.
* `AlgebraicGeometry.DivisorAdaptation.ofChartPair` — the adaptation from a chart-principality
  datum.
* `AlgebraicGeometry.DivisorAdaptation.ofChartPair_pieces_eq_chart` — its pieces are the
  pinned charts.
* `AlgebraicGeometry.DivisorAdaptation.forall_subset_or_disjoint_of_pieces_eq_chart` — a
  divisor inside the chart overlap is swallowed by every chart-shaped piece.
* `AlgebraicGeometry.DivisorAdaptation.forall_noLeak_of_pieces_eq_chart` and
  `forall_finite_colength_of_pieces_eq_chart` — the assembler's `hnoLeak` and clause
  (c1)-finite for a chart-shaped adaptation of a chart-overlap divisor.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
/- `lake env lean` drops the lakefile's `[leanOptions]` (I-0161); pin in-file. -/
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory Limits TopologicalSpace Opposite

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
variable (R : Type u) [CommRing R] [Algebra k R]
variable (π : C.left ⟶ P1 k) [IsFinite π]

/-! ## The coarse cover data -/

/-- **The two-piece cover data**: one piece per pinned chart, generated by `1`.  The partition
of unity is `1 * 1 = 1` over `Fin 1`, so no geometry is consumed. -/
noncomputable def chartPairCoverData : FinCoverData C R π where
  m₀ := 1
  m₁ := 1
  h₀ := fun _ => 1
  h₁ := fun _ => 1
  a₀ := fun _ => 1
  a₁ := fun _ => 1
  partition₀ := by simp
  partition₁ := by simp

@[simp]
lemma chartPairCoverData_pieces_inl (j : Fin (chartPairCoverData C R π).m₀) :
    (chartPairCoverData C R π).pieces (Sum.inl j)
      = (relCover C R (fiberTwoCover π)).V₀ := by
  rw [FinCoverData.pieces_inl]
  exact (relCurve C R).basicOpen_one

@[simp]
lemma chartPairCoverData_pieces_inr (j : Fin (chartPairCoverData C R π).m₁) :
    (chartPairCoverData C R π).pieces (Sum.inr j)
      = (relCover C R (fiberTwoCover π)).V₁ := by
  rw [FinCoverData.pieces_inr]
  exact (relCurve C R).basicOpen_one

/-- Every piece of the coarse cover data is one of the two pinned charts. -/
lemma chartPairCoverData_pieces_eq (j : (chartPairCoverData C R π).index) :
    (chartPairCoverData C R π).pieces j = (relCover C R (fiberTwoCover π)).V₀
      ∨ (chartPairCoverData C R π).pieces j = (relCover C R (fiberTwoCover π)).V₁ := by
  cases j with
  | inl j => exact Or.inl (chartPairCoverData_pieces_inl C R π j)
  | inr j => exact Or.inr (chartPairCoverData_pieces_inr C R π j)

namespace DivisorAdaptation

variable {C R π} {d : (relCurve C R).LocalEquations}

/-- **The coarse adaptation from a chart-principality datum.** `pt` names, for each pinned
chart, a member of `d`'s cover containing that whole chart; `eqn` is the chart equation and
`unit` the comparison unit against `d`'s equation there.  The result is an adaptation whose
two pieces are the pinned charts themselves. -/
noncomputable def ofChartPair
    (eqn : ∀ j : (chartPairCoverData C R π).index,
      Γ(relCurve C R, (chartPairCoverData C R π).pieces j))
    (pt : (chartPairCoverData C R π).index → relCurve C R)
    (piece_le : ∀ j, (chartPairCoverData C R π).pieces j ≤ d.cover.opens (pt j))
    (unit : ∀ j, Γ(relCurve C R, (chartPairCoverData C R π).pieces j)ˣ)
    (eqn_eq : ∀ j, eqn j
      = (unit j : Γ(relCurve C R, (chartPairCoverData C R π).pieces j))
        * ((relCurve C R).presheaf.map (homOfLE (piece_le j)).op).hom (d.eqn (pt j))) :
    DivisorAdaptation C R π d :=
  DivisorAdaptation.ofAnchors (chartPairCoverData C R π) eqn pt piece_le unit eqn_eq

/-- **The pieces of `ofChartPair` are the pinned charts.** The anchored constructor keeps the
supplied cover data, so this is definitional plus `Scheme.basicOpen_one`. -/
lemma ofChartPair_pieces_eq_chart
    (eqn : ∀ j : (chartPairCoverData C R π).index,
      Γ(relCurve C R, (chartPairCoverData C R π).pieces j))
    (pt : (chartPairCoverData C R π).index → relCurve C R)
    (piece_le : ∀ j, (chartPairCoverData C R π).pieces j ≤ d.cover.opens (pt j))
    (unit : ∀ j, Γ(relCurve C R, (chartPairCoverData C R π).pieces j)ˣ)
    (eqn_eq : ∀ j, eqn j
      = (unit j : Γ(relCurve C R, (chartPairCoverData C R π).pieces j))
        * ((relCurve C R).presheaf.map (homOfLE (piece_le j)).op).hom (d.eqn (pt j)))
    (j : (ofChartPair eqn pt piece_le unit eqn_eq).index) :
    (ofChartPair eqn pt piece_le unit eqn_eq).pieces j
        = (relCover C R (fiberTwoCover π)).V₀
      ∨ (ofChartPair eqn pt piece_le unit eqn_eq).pieces j
        = (relCover C R (fiberTwoCover π)).V₁ :=
  chartPairCoverData_pieces_eq C R π j

/-! ## The certificate obligations for a chart-shaped adaptation

Stated against the *shape* of the pieces rather than against `ofChartPair` itself, so that any
adaptation whose pieces are the two pinned charts — however it was built — qualifies. -/

variable (A : DivisorAdaptation C R π d)

/-- **A divisor inside the chart overlap is swallowed by every chart-shaped piece.** -/
theorem forall_subset_or_disjoint_of_pieces_eq_chart
    (hpieces : ∀ j : A.index, A.pieces j = (relCover C R (fiberTwoCover π)).V₀
      ∨ A.pieces j = (relCover C R (fiberTwoCover π)).V₁)
    (hsub : d.supportLocus ⊆ (((relCover C R (fiberTwoCover π)).V₀
      ⊓ (relCover C R (fiberTwoCover π)).V₁ : (relCurve C R).Opens) : Set (relCurve C R))) :
    ∀ j : A.index, d.supportLocus ⊆ (A.pieces j : Set (relCurve C R))
      ∨ Disjoint d.supportLocus (A.pieces j : Set (relCurve C R)) := by
  intro j
  refine Or.inl fun x hx => ?_
  have hx' := hsub hx
  rcases hpieces j with h | h <;> rw [h]
  · exact hx'.1
  · exact hx'.2

/-- **The assembler's `hnoLeak` for a chart-shaped adaptation of a chart-overlap divisor.** No
fibre, no tube, no packet idempotent. -/
theorem forall_noLeak_of_pieces_eq_chart
    (hpieces : ∀ j : A.index, A.pieces j = (relCover C R (fiberTwoCover π)).V₀
      ∨ A.pieces j = (relCover C R (fiberTwoCover π)).V₁)
    (hsub : d.supportLocus ⊆ (((relCover C R (fiberTwoCover π)).V₀
      ⊓ (relCover C R (fiberTwoCover π)).V₁ : (relCurve C R).Opens) : Set (relCurve C R))) :
    ∀ (j : A.index) (s : Spec (.of R)),
      ((relCurve C R) ↘ Spec (.of R)).base ⁻¹' {s}
          ∩ closure (d.supportLocus ∩ (A.pieces j : Set (relCurve C R))) ⊆
        (A.pieces j : Set (relCurve C R)) :=
  A.forall_noLeak_of_forall_subset_or_disjoint
    (A.forall_subset_or_disjoint_of_pieces_eq_chart hpieces hsub)

section Finite

variable [IsProper C.hom]

/-- **Clause (c1)-finite for a chart-shaped adaptation of a chart-overlap divisor.** -/
theorem forall_finite_colength_of_pieces_eq_chart
    (hpieces : ∀ j : A.index, A.pieces j = (relCover C R (fiberTwoCover π)).V₀
      ∨ A.pieces j = (relCover C R (fiberTwoCover π)).V₁)
    (hsub : d.supportLocus ⊆ (((relCover C R (fiberTwoCover π)).V₀
      ⊓ (relCover C R (fiberTwoCover π)).V₁ : (relCurve C R).Opens) : Set (relCurve C R))) :
    ∀ j : A.index, Module.Finite R (A.colength j) :=
  A.forall_finite_colength_of_forall_subset_or_disjoint
    (A.forall_subset_or_disjoint_of_pieces_eq_chart hpieces hsub)

end Finite

end DivisorAdaptation

end AlgebraicGeometry
