/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeRedesignFibreCut
import AlgebraicJacobian.Picard.DivSchemeRedesignHinjChart

/-!
# DD-4 redesign — RD-N step 2a: the concrete chart-level colength `N z` and the ann→hdvd bridge

The ann-based fibre-cutter engine `IsAffineOpen.exists_mem_basicOpen_forall_smul_eq_zero`
(`Picard/DivSchemeRedesignFibreCut.lean`, I-0292) consumes a *finite* `Γ(V)`-module `N z`
and the support-avoidance `primeIdealOf z ∉ Module.support Γ(V) (N z)` (= **RD-N proper**),
and produces the seed's cutter `h z ∈ Γ(V)` with `z ∈ D(h z)` and `h z · N z = 0`.  This file
lands the *concrete* `N z` (I-0302 §residual 2a) and the routine glue that turns the engine's
`h z · N z = 0` into the seed's DIRECT `hdvd` clause `hann` (the ann containment the redesigned
`isGenerator_of_ann_cutter` consumes).

* `Module.Finite.span_range_of_finite_isScalarTower` — **reusable pure-algebra finiteness**:
  the `S`-span of the range of an `R`-linear map out of a finite `R`-module is a finite
  `S`-module (`R → S` an algebra, the codomain a scalar tower).  The finiteness route for `N z`.

* `ThetaGeneratorSeed.chartColengthModule K b s` — **the concrete chart-level `N z`**: the
  `Γ(V)`-submodule of the colength `Γ(V) ⧸ ⟨read s⟩` generated by the chart readings of `K`,
  where `V = relPinnedChart C R π b` (`le_rfl`, `h z`-free) and `read = relThetaResSide a b le_rfl`.
  Its annihilation by `h` is exactly `h · (read ψ) ∈ ⟨read s⟩` for every `ψ ∈ K`.

* `chartColengthModule_finite` — `N z` is a finite `Γ(V)`-module (from the reusable finiteness,
  `K` finite over `R`).

* `forall_mul_read_mem_span_of_forall_smul_eq_zero` — **the ann→hdvd bridge**: `h · N z = 0`
  ⟹ `h · (read ψ) ∈ ⟨read s⟩` for `ψ ∈ K` (the `hann` shape of `isGenerator_of_ann_cutter`).

* `exists_h_mem_basicOpen_forall_mul_read_mem_span` — **the ann-cutter, seed-shaped**: from
  RD-N (`primeIdealOf z ∉ supp (N z)`) at a point `z` in the chart, a section `h ∈ Γ(V)` with
  `z ∈ D(h)` and `h · (read ψ) ∈ ⟨read s⟩` for all `ψ ∈ K` — exactly the seed's `h z` +
  `mem_basicOpen` + `hann` data, packaged for the concrete `seedUniv'` assembly.

The support-avoidance premise `primeIdealOf z ∉ supp (N z)` is **RD-N proper**; discharging it
(the achiever fibre-generation + the landed chart flat, via the `κ(p)→𝒪_z` transport) is the
remaining geometric content (I-0302 §residual 2b/2c).  This file is certificate-free,
`IsGenerator`-free, and consumes only the landed ann-cutter engine + `chartReadMap`.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 3

universe u v

open CategoryTheory TopologicalSpace Opposite
open scoped TensorProduct

/-! ## The reusable finiteness core -/

/-- **The `S`-span of the range of an `R`-linear map out of a finite `R`-module is `S`-finite.**
For an `R`-algebra `S`, a finite `R`-module `M`, and a scalar-tower `S`-module `N`, the
`S`-submodule `Submodule.span S (Set.range f)` generated by the image of `f : M →ₗ[R] N` is a
finite `S`-module: a finite `R`-generating set `T` of `M` yields the finite `S`-generating set
`f '' T` (every `f m` is an `R`-combination of the `f tᵢ`, hence an `S`-combination).  Pure
algebra; the finiteness route for the concrete colength `N z`. -/
theorem Module.Finite.span_range_of_finite_isScalarTower
    {R S M N : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module S N] [IsScalarTower R S N]
    (f : M →ₗ[R] N) :
    Module.Finite S (Submodule.span S (Set.range f)) := by
  obtain ⟨T, hT⟩ := (Module.Finite.fg_top (R := R) (M := M))
  have hspan : Submodule.span S (Set.range f) = Submodule.span S (f '' T) := by
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨m, rfl⟩
      have hm : m ∈ Submodule.span R (T : Set M) := by rw [hT]; trivial
      have hfm : f m ∈ Submodule.span R (f '' T) := by
        rw [← Submodule.map_span]
        exact Submodule.mem_map_of_mem hm
      exact (Submodule.span_le_restrictScalars R S (f '' T)) hfm
    · exact Submodule.span_mono (Set.image_subset_range f T)
  rw [hspan]
  exact Module.Finite.iff_fg.mpr (Submodule.fg_span (T.finite_toSet.image f))

namespace AlgebraicGeometry

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable {R : Type u} [CommRing R] [Algebra k R]
variable {π : C.left ⟶ P1 k} [IsFinite π] {a : ℕ}

namespace ThetaGeneratorSeed

/-! ## The concrete chart-level colength `N z` -/

/-- **The concrete chart-level colength `N z`** (I-0302 §residual 2a): the `Γ(V)`-submodule of
the colength ring `Γ(V) ⧸ ⟨read s⟩` generated by the chart readings `read ψ` of the submodule
`K`, where `V = relPinnedChart C R π b` and `read = relThetaResSide a b le_rfl` (`le_rfl`,
`h z`-free).  A section `h ∈ Γ(V)` annihilates `N z` exactly when `h · (read ψ) ∈ ⟨read s⟩` for
every `ψ ∈ K` — the ann containment the redesigned `hdvd` consumes. -/
noncomputable def chartColengthModule (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a) :
    Submodule Γ(relCurve C R, relPinnedChart C R π b)
      (Γ(relCurve C R, relPinnedChart C R π b) ⧸
        Ideal.span {relThetaResSide a b (le_rfl) s}) :=
  Submodule.span _ (Set.range
    ((Ideal.Quotient.mkₐ R (Ideal.span {relThetaResSide a b (le_rfl) s})).toLinearMap.comp
      (chartReadMap K b)))

/-- The class of a chart reading of a `K`-element lies in `N z`. -/
theorem mk_relThetaResSide_mem_chartColengthModule
    (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a) {ψ : relThetaSections C R π a} (hψ : ψ ∈ K) :
    Ideal.Quotient.mk (Ideal.span {relThetaResSide a b (le_rfl) s})
        (relThetaResSide a b (le_rfl) ψ) ∈ chartColengthModule K b s :=
  Submodule.subset_span ⟨⟨ψ, hψ⟩, rfl⟩

/-- **`N z` is a finite `Γ(V)`-module**: from the reusable finiteness core, since `K` is a
finite `R`-module (the chart readings of a finite generating set of `K` span `N z`). -/
theorem chartColengthModule_finite (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a) [Module.Finite R ↥K] :
    Module.Finite Γ(relCurve C R, relPinnedChart C R π b) ↥(chartColengthModule K b s) :=
  Module.Finite.span_range_of_finite_isScalarTower _

/-! ## The ann→hdvd bridge -/

/-- **The ann→hdvd bridge** (I-0302 §residual 2a): if `h ∈ Γ(V)` annihilates the colength
`N z = chartColengthModule K b s`, then `h · (read ψ) ∈ ⟨read s⟩` for every `ψ ∈ K` — the ann
containment (`hann` shape) the redesigned `isGenerator_of_ann_cutter` consumes.  The class of
`read ψ` lies in `N z`, so `h • [read ψ] = 0`, i.e. `[h · read ψ] = 0`, i.e.
`h · read ψ ∈ ⟨read s⟩`. -/
theorem forall_mul_read_mem_span_of_forall_smul_eq_zero
    (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a)
    {h : Γ(relCurve C R, relPinnedChart C R π b)}
    (hann : ∀ n : ↥(chartColengthModule K b s), h • n = 0) :
    ∀ ⦃ψ : relThetaSections C R π a⦄, ψ ∈ K →
      h * relThetaResSide a b (le_rfl) ψ
        ∈ Ideal.span {relThetaResSide a b (le_rfl) s} := by
  intro ψ hψ
  set I := Ideal.span {relThetaResSide a b (le_rfl) s} with hI
  have hmem := mk_relThetaResSide_mem_chartColengthModule K b s hψ
  have hz := hann ⟨_, hmem⟩
  have hz' : h • Ideal.Quotient.mk I (relThetaResSide a b (le_rfl) ψ) = 0 := by
    have h2 := congrArg (Subtype.val) hz
    rw [SetLike.val_smul, ZeroMemClass.coe_zero] at h2
    exact h2
  rw [show h • Ideal.Quotient.mk I (relThetaResSide a b (le_rfl) ψ)
        = Ideal.Quotient.mk I (h * relThetaResSide a b (le_rfl) ψ) by
      rw [Algebra.smul_def, Ideal.Quotient.algebraMap_eq, ← map_mul]] at hz'
  exact (Ideal.Quotient.eq_zero_iff_mem).mp hz'

/-! ## The ann-cutter, seed-shaped (RD-N ⟹ the cutter `h z`) -/

set_option synthInstance.maxHeartbeats 400000 in
-- the ann-cutter application over the heavy `relCurve` chart section ring re-synthesizes the
-- finite-module / support instances past the default synthesis budget
/-- **The ann-based fibre-cutter, seed-shaped** (I-0302 §residual 2a→ann-cutter): from **RD-N
proper** — the support-avoidance `primeIdealOf z ∉ Module.support Γ(V) (N z)` for the concrete
colength `N z = chartColengthModule K b s` at a point `z` in the chart `V = relPinnedChart C R π b`
— there is a section `h ∈ Γ(V)` with `z ∈ D(h)` and `h · (read ψ) ∈ ⟨read s⟩` for every `ψ ∈ K`.

This packages the landed ann-cutter engine `IsAffineOpen.exists_mem_basicOpen_forall_smul_eq_zero`
with the ann→hdvd bridge: the engine gives `h` annihilating `N z` with `z ∈ D(h)`, and the bridge
turns `h · N z = 0` into the seed's `hann` containment.  Exactly the seed's `h z` +
`mem_basicOpen` + `hann` data for the concrete `seedUniv'`; the RD-N premise is the honest
remaining wall (I-0302 §residual 2b/2c). -/
theorem exists_h_mem_basicOpen_forall_mul_read_mem_span
    (K : Submodule R (relThetaSections C R π a)) (b : Bool)
    (s : relThetaSections C R π a) [Module.Finite R ↥K]
    {z : relCurve C R} (hz : z ∈ relPinnedChart C R π b)
    (hsupp : (isAffineOpen_relPinnedChart C R π b).primeIdealOf ⟨z, hz⟩ ∉
      Module.support Γ(relCurve C R, relPinnedChart C R π b) ↥(chartColengthModule K b s)) :
    ∃ h : Γ(relCurve C R, relPinnedChart C R π b),
      z ∈ (relCurve C R).basicOpen h ∧
      ∀ ⦃ψ : relThetaSections C R π a⦄, ψ ∈ K →
        h * relThetaResSide a b (le_rfl) ψ
          ∈ Ideal.span {relThetaResSide a b (le_rfl) s} := by
  haveI := chartColengthModule_finite K b s
  obtain ⟨h, hmem, hann⟩ :=
    (isAffineOpen_relPinnedChart C R π b).exists_mem_basicOpen_forall_smul_eq_zero
      (↥(chartColengthModule K b s)) hz hsupp
  exact ⟨h, hmem, forall_mul_read_mem_span_of_forall_smul_eq_zero K b s hann⟩

end ThetaGeneratorSeed

end AlgebraicGeometry
