/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.DivSchemeRedesignSeedUniv
import AlgebraicJacobian.Picard.DivSchemeRedesignKappaZ

/-!
# DD-4 redesign — `SeedUnivRDN` from seed-level germ divisibility (I-0305 §route, assembly)

The universal seed's RD-N (`SeedUnivRDN`, `DivSchemeRedesignSeedUniv.lean`) is the threaded
hypothesis of `seedUniv'` / `isGenerator_seedUniv'`: at every point `z`, the seed colength
`seedUnivColength z = chartColengthModule K_univ (side z) (sec z)` avoids the module-stalk prime
of `z`.

This file packages the κ(z) reduction chain (`DivSchemeRedesignKappaZ.lean`) at the seed level:
`SeedUnivRDN` follows from the **single honest input** — seed-level germ divisibility

  `∀ z, ∀ ψ ∈ K_univ, germ_z (read ψ) ∈ ⟨germ_z (read (sec z))⟩`   (in the stalk `𝒪_z`),

i.e. the achiever's `read sec z` (which attains the base multiplicity at `z`, I-0291, hence has
minimal order in the fibre DVR at `z`) locally generates the readings at `z`.  This is exactly
the achiever's per-point local-generation, base-changed to the total-space germ — the remaining
geometric content (I-0305 §route step 2 (ii), the fibre-DVR → germ transport) isolated to one
seed-level germ-divisibility premise.

`seedUnivRDN_of_forall_germ_mem_span` discharges `SeedUnivRDN` from that premise via the
per-point germ reduction `notMem_support_chartColengthModule_of_forall_germ_mem_span` and the
window finiteness `finite_divUniversalSeedK`.  Single-point throughout — the degree obstruction
(I-0305 §2, which kills the *global* κ(p) base-fibre) never fires.  Certificate-free,
`IsGenerator`-free.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory Limits TopologicalSpace Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

open Scheme Grassmannian ThetaGeneratorSeed

attribute [local instance] Scheme.overModule Scheme.overSectionsAlgebra
  Scheme.functionFieldOverModule
attribute [local instance 10000] relCurve.instOver

namespace ThetaGeneratorSeed

section SeedUnivRDNAssembly

variable {k : Type u} [Field k] (C : Over (Spec (.of k)))
  [SmoothOfRelativeDimension 1 C.hom] [IsProper C.hom] [GeometricallyIrreducible C.hom]
variable {π : C.left ⟶ P1 k} [IsFinite π] [IsDominant π]

noncomputable local instance instOverCleftSeedUnivRDNAssembly : C.left.Over (Spec (.of k)) :=
  ⟨C.hom⟩

variable [SmoothOfRelativeDimension 1 (C.left ↘ Spec (.of k))] [IsIntegral C.left]
  [LocallyOfFiniteType (C.left ↘ Spec (.of k))] [QuasiCompact (C.left ↘ Spec (.of k))]
variable [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 0)]
  [Module.Finite k (Sheaf.HModule (C.left.moduleKSheaf k) 1)]
variable (hπ : π ≫ P1.structureMap k = C.left ↘ Spec (CommRingCat.of k))
variable (g r₁ r₂ : ℕ)
variable (b₁ : Module.Basis (Fin r₁) k
  ↥(Scheme.divisorSections k (windowM_choice π hπ g • fiberWeilDivisor π) ⊤))
variable (b₂ : Module.Basis (Fin r₂) k
  ↥(Scheme.divisorSections k ((windowS_choice π hπ g • fiberWeilDivisor π)
    + (windowM_choice π hπ g • fiberWeilDivisor π)) ⊤))
variable (i : (glueData k g r₁).J) (j : (glueData k g r₂).J)
variable (hO : Sheaf.h0 (C.left.moduleKSheaf k) = 1)
  (hχ : Sheaf.chi (C.left.moduleKSheaf k) = 1 - (g : ℤ))

set_option maxHeartbeats 2400000 in
-- the full seed context (`seedChartRing`/`seedUniv`/`seedUnivColength` over the heavy
-- `DivCarveChartRing`/`relCurve` types) re-elaborates the finite-module/support instances
set_option synthInstance.maxHeartbeats 800000 in
set_option maxSynthPendingDepth 8 in
set_option maxRecDepth 8000 in
/-- **`SeedUnivRDN` from seed-level germ divisibility** (I-0305 §route, the assembly): the
universal seed's RD-N holds provided that, at every point `z`, every window reading `read ψ`
(`ψ ∈ K_univ`) has its germ at `z` in the principal ideal generated by the germ of the
achiever section's reading `read (sec z)` in the stalk `𝒪_z`.

This is the achiever's single-point local generation at `z` (`read sec z` attains the base
multiplicity, I-0291) transported to the total-space germ.  The proof instantiates the
per-point germ reduction `notMem_support_chartColengthModule_of_forall_germ_mem_span` at the
seed's colength (`K := divUniversalSeedK`, finite over `R_Z` by `finite_divUniversalSeedK`),
whose support-avoidance is exactly `SeedUnivRDN z`.  Single-point throughout, so the degree
obstruction (I-0305 §2) never fires; the sole remaining wall is the germ-divisibility premise
(the fibre-DVR → germ base change). -/
theorem seedUnivRDN_of_forall_germ_mem_span
    (hgerm : ∀ (z : relCurve C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j)),
      ∀ ⦃ψ : relThetaSections C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j) π
          (windowM_choice π hπ g)⦄, ψ ∈ divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j →
        ((relCurve C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j)).presheaf.germ
            (relPinnedChart C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j) π
              ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)) z
            (seedUniv_mem_chart C hπ g r₁ r₂ b₁ b₂ i j hO hχ z)).hom
          (relThetaResSide (windowM_choice π hπ g)
            ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z) (le_rfl) ψ)
        ∈ Ideal.span {((relCurve C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j)).presheaf.germ
            (relPinnedChart C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j) π
              ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)) z
            (seedUniv_mem_chart C hπ g r₁ r₂ b₁ b₂ i j hO hχ z)).hom
          (relThetaResSide (windowM_choice π hπ g)
            ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z) (le_rfl)
            ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).sec z))}) :
    SeedUnivRDN C hπ g r₁ r₂ b₁ b₂ i j hO hχ := by
  intro z
  haveI := finite_divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j
  exact notMem_support_chartColengthModule_of_forall_germ_mem_span
    (divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j)
    ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)
    ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).sec z)
    (seedUniv_mem_chart C hπ g r₁ r₂ b₁ b₂ i j hO hχ z)
    (hgerm z)

set_option maxHeartbeats 2400000 in
set_option synthInstance.maxHeartbeats 800000 in
set_option maxSynthPendingDepth 8 in
set_option maxRecDepth 8000 in
/-- **`SeedUnivRDN` from the sharp point fibre.**  The support criterion can also be fed
directly by the single-point tensor
`chartColengthModule K_univ ... ⊗_{Γ(V)} κ(z)`.  This is deliberately independent of the
fibre-to-total germ transport: it records the exact module-theoretic insertion point for a
future residue-field proof, with `κ(z)` taken from the chart point prime itself (never from
the comapped base prime). -/
theorem seedUnivRDN_of_forall_kappaZ_tensor_subsingleton
    (hfib : ∀ (z : relCurve C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j)),
      Subsingleton (↥(chartColengthModule
          (divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j)
          ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)
          ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).sec z)) ⊗[
            Γ(relCurve C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j),
              relPinnedChart C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j) π
                ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z))]
          ((isAffineOpen_relPinnedChart C (seedChartRing C hπ g r₁ r₂ b₁ b₂ i j) π
              ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)).primeIdealOf
            ⟨z, seedUniv_mem_chart C hπ g r₁ r₂ b₁ b₂ i j hO hχ z⟩).asIdeal.ResidueField)) :
    SeedUnivRDN C hπ g r₁ r₂ b₁ b₂ i j hO hχ := by
  intro z
  haveI := finite_divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j
  exact notMem_support_chartColengthModule_of_subsingleton_tmul_residueField_kappaZ
    (divUniversalSeedK C π hπ g r₁ r₂ b₁ b₂ i j)
    ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).side z)
    ((seedUniv C hπ g r₁ r₂ b₁ b₂ i j hO hχ).sec z)
    (seedUniv_mem_chart C hπ g r₁ r₂ b₁ b₂ i j hO hχ z)
    (hfib z)

end SeedUnivRDNAssembly

end ThetaGeneratorSeed

end AlgebraicGeometry
