/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Mathlib

/-!
# Entry ideals of matrix presentations (Nitsure §4, `n = 0` substrate)

This file is the commutative-algebra substrate for the *universal* `n = 0`
flattening stratification (`flatLocusStratification_universal` in
`AlgebraicJacobian.Picard.GenericFlatnessGeometric`), following the special
case `n = 0` of the proof of the flattening-stratification theorem in
[Nitsure, §4].  Mathlib v4.31 has no Fitting-ideal vocabulary; for a module
presented by `e` generators the *entry ideal* of the relation matrix — the
ideal generated by all matrix entries, i.e. the ideal of `1 × 1` minors,
which for an `e`-generator presentation is the Fitting ideal
`Fitt_{e-1}` — substitutes for it.

## Main definitions

* `Module.MatrixPresentation R M e m`: a presentation of the `R`-module `M`
  by `e` generators and `m` relations, recorded as a relation matrix
  `ψ : Matrix (Fin e) (Fin m) R` together with a surjection
  `π : R^e → M` with `ker π = range ψ`.
* `Module.MatrixPresentation.entryIdeal`: the ideal generated by the entries
  of the relation matrix.
* `Ideal.fiberRank`: the dimension `dim_{κ(p)} (κ(p) ⊗[R] M)` of the fiber
  of `M` at a prime `p`.

## Main results

* `Module.MatrixPresentation.baseChange`: a presentation base-changes along
  any `R`-algebra `A` (right-exactness of the tensor product), with
  `entryIdeal_baseChange`: the entry ideal of the base change is the image
  ideal.
* `Module.MatrixPresentation.projEquiv`: if the relation matrix vanishes,
  the presentation exhibits `M` as free of rank `e`
  (`rankAtStalk_eq_of_relMatrix_eq_zero`).
* `Module.MatrixPresentation.relMatrix_eq_zero_of_flat`: **the hard
  direction of Nitsure's local universal property** — if `M` is flat with
  `rankAtStalk M ≡ e`, the relation matrix of *any* `e`-generator
  presentation vanishes.  (The surjection `R^e ↠ M` between finite
  projectives of the same everywhere-rank is bijective.)
* `Module.MatrixPresentation.entryIdeal_eq`: presentation-independence of
  the entry ideal (the Fitting-ideal miracle for `1 × 1` minors), by
  base-changing each presentation to `R ⧸ entryIdeal` of the other.
* `Module.MatrixPresentation.entryIdeal_le_prime_iff`: for a prime `p`,
  `entryIdeal ≤ p ↔ fiberRank p M = e` — the point-set description of the
  rank-`e` stratum.
* `Module.FinitePresentation.exists_matrixPresentation_of_isLocalizedModule`:
  **Nakayama prolongation** — for `M` finitely presented and a prime `p`,
  there is `g ∉ p` such that every localization of `M` away from `g`
  admits a presentation with exactly `fiberRank p M` generators.

Blueprint chapter: `Picard_FlatteningStratification.tex`, §entry-ideal.
Source: [Nitsure], §4, proof of the flattening-stratification theorem,
special case `n = 0` (`references/nitsure-hilbert-quot-src/`
`nitsure-hilbert-quot.tex`, L1849–L1885).
-/

universe u v u' v'

open TensorProduct

namespace Module

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- A **matrix presentation** of the `R`-module `M` by `e` generators and
`m` relations: a relation matrix `ψ : Matrix (Fin e) (Fin m) R` and a
surjection `π : R^e → M` whose kernel is the column span of `ψ`, i.e.
`R^m —ψ→ R^e —π→ M → 0` is exact.  [Nitsure §4, n = 0 case: the local
presentation `𝒪_V^{⊕m} →ψ 𝒪_V^{⊕e} → F|_V → 0`.] -/
structure MatrixPresentation (R : Type u) [CommRing R]
    (M : Type v) [AddCommGroup M] [Module R M] (e m : ℕ) where
  /-- The relation matrix `ψ`. -/
  relMatrix : Matrix (Fin e) (Fin m) R
  /-- The projection `R^e → M` picking out the `e` generators. -/
  proj : (Fin e → R) →ₗ[R] M
  surjective_proj : Function.Surjective proj
  exact_mulVecLin_proj : Function.Exact relMatrix.mulVecLin proj

namespace MatrixPresentation

variable {e m m' : ℕ}

lemma ker_proj (P : MatrixPresentation R M e m) :
    LinearMap.ker P.proj = LinearMap.range P.relMatrix.mulVecLin :=
  LinearMap.exact_iff.mp P.exact_mulVecLin_proj

/-- A module admitting a matrix presentation is finitely presented. -/
lemma finitePresentation (P : MatrixPresentation R M e m) :
    Module.FinitePresentation R M := by
  refine Module.finitePresentation_of_surjective P.proj P.surjective_proj ?_
  rw [P.ker_proj, LinearMap.range_eq_map]
  exact Module.Finite.fg_top.map _

/-- The **entry ideal** of a matrix presentation: the ideal generated by all
entries of the relation matrix (the ideal of `1 × 1` minors; for an
`e`-generator presentation this is the Fitting ideal `Fitt_{e-1} M`).
[Nitsure §4: "the ideal sheaf generated by the entries `ψ_{i,j}`".] -/
def entryIdeal (P : MatrixPresentation R M e m) : Ideal R :=
  Ideal.span (Set.range fun ij : Fin e × Fin m ↦ P.relMatrix ij.1 ij.2)

lemma entryIdeal_le_iff {P : MatrixPresentation R M e m} {I : Ideal R} :
    P.entryIdeal ≤ I ↔ ∀ i j, P.relMatrix i j ∈ I := by
  rw [entryIdeal, Ideal.span_le]
  constructor
  · intro h i j
    exact h ⟨(i, j), rfl⟩
  · rintro h _ ⟨⟨i, j⟩, rfl⟩
    exact h i j

lemma relMatrix_mem_entryIdeal (P : MatrixPresentation R M e m)
    (i : Fin e) (j : Fin m) : P.relMatrix i j ∈ P.entryIdeal :=
  entryIdeal_le_iff.mp le_rfl i j

section BaseChange

variable (A : Type u') [CommRing A] [Algebra R A]

/-- Vanishing of the base-changed relation matrix is containment of the
entry ideal in the kernel: `ψ ⊗ A = 0 ↔ I(ψ) ⊆ ker (R → A)`. -/
lemma relMatrix_map_eq_zero_iff {P : MatrixPresentation R M e m} :
    P.relMatrix.map (algebraMap R A) = 0 ↔
      P.entryIdeal ≤ RingHom.ker (algebraMap R A) := by
  rw [entryIdeal_le_iff, ← Matrix.ext_iff]
  simp [RingHom.mem_ker]

/-- Base change intertwines `mulVecLin` of the mapped matrix with the
base-changed `mulVecLin`, through the scalar-extension isomorphisms
`A ⊗[R] (ι → R) ≃ (ι → A)`. -/
lemma mulVecLin_map_algebraMap (ψ : Matrix (Fin e) (Fin m) R) :
    (ψ.map (algebraMap R A)).mulVecLin =
      (TensorProduct.piScalarRight R A A (Fin e)).toLinearMap
        ∘ₗ ψ.mulVecLin.baseChange A
        ∘ₗ (TensorProduct.piScalarRight R A A (Fin m)).symm.toLinearMap := by
  refine LinearMap.pi_ext' fun j ↦ LinearMap.ext_ring ?_
  ext i
  simp only [LinearMap.comp_apply, LinearMap.coe_single, LinearEquiv.coe_toLinearMap,
    TensorProduct.piScalarRight_symm_single, LinearMap.baseChange_tmul,
    TensorProduct.piScalarRight_apply, TensorProduct.piScalarRightHom_tmul,
    Matrix.mulVecLin_apply, Matrix.mulVec, Matrix.map_apply]
  rw [dotProduct_single, dotProduct_single]
  simp [Algebra.smul_def]

/-- The base change of a matrix presentation along an `R`-algebra `A`:
`A^m —ψ⊗A→ A^e —π⊗A→ A ⊗[R] M → 0` (right-exactness of the tensor
product).  [Nitsure §4: "the pulled-back sequence is exact by
right-exactness of tensor products".] -/
noncomputable def baseChange (P : MatrixPresentation R M e m) :
    MatrixPresentation A (A ⊗[R] M) e m where
  relMatrix := P.relMatrix.map (algebraMap R A)
  proj := P.proj.baseChange A ∘ₗ
    (TensorProduct.piScalarRight R A A (Fin e)).symm.toLinearMap
  surjective_proj := by
    have h1 : Function.Surjective (P.proj.baseChange A) := by
      rw [LinearMap.baseChange_eq_ltensor]
      exact LinearMap.lTensor_surjective A P.surjective_proj
    exact h1.comp (TensorProduct.piScalarRight R A A (Fin e)).symm.surjective
  exact_mulVecLin_proj := by
    rw [mulVecLin_map_algebraMap]
    have hex : Function.Exact (P.relMatrix.mulVecLin.baseChange A)
        (P.proj.baseChange A) := by
      simp only [LinearMap.baseChange_eq_ltensor]
      exact lTensor_exact A P.exact_mulVecLin_proj P.surjective_proj
    intro y
    simp only [LinearMap.comp_apply, LinearEquiv.coe_toLinearMap]
    rw [hex ((TensorProduct.piScalarRight R A A (Fin e)).symm y)]
    constructor
    · rintro ⟨x, hx⟩
      refine ⟨TensorProduct.piScalarRight R A A (Fin m) x, ?_⟩
      simp only [LinearMap.comp_apply, LinearEquiv.coe_toLinearMap]
      rw [LinearEquiv.symm_apply_apply, hx, LinearEquiv.apply_symm_apply]
    · rintro ⟨x, hx⟩
      simp only [LinearMap.comp_apply, LinearEquiv.coe_toLinearMap] at hx
      refine ⟨(TensorProduct.piScalarRight R A A (Fin m)).symm x, ?_⟩
      rw [← hx, LinearEquiv.symm_apply_apply]

@[simp]
lemma baseChange_relMatrix (P : MatrixPresentation R M e m) :
    (P.baseChange A).relMatrix = P.relMatrix.map (algebraMap R A) := rfl

/-- The entry ideal of the base-changed presentation is the image of the
entry ideal. -/
lemma entryIdeal_baseChange (P : MatrixPresentation R M e m) :
    (P.baseChange A).entryIdeal = P.entryIdeal.map (algebraMap R A) := by
  rw [entryIdeal, entryIdeal, Ideal.map_span]
  congr 1
  ext x
  simp [Matrix.map_apply, eq_comm]

end BaseChange

section Vanishing

/-- If the relation matrix vanishes, the projection of the presentation is
an isomorphism `R^e ≃ M`. -/
noncomputable def projEquiv (P : MatrixPresentation R M e m)
    (h : P.relMatrix = 0) : (Fin e → R) ≃ₗ[R] M :=
  LinearEquiv.ofBijective P.proj
    ⟨by
      rw [← LinearMap.ker_eq_bot, P.ker_proj, h]
      simp, P.surjective_proj⟩

@[simp]
lemma projEquiv_apply (P : MatrixPresentation R M e m) (h : P.relMatrix = 0)
    (x : Fin e → R) : P.projEquiv h x = P.proj x := rfl

/-- If the relation matrix vanishes, `M` is free (of rank `e`). -/
lemma free_of_relMatrix_eq_zero (P : MatrixPresentation R M e m)
    (h : P.relMatrix = 0) : Module.Free R M :=
  Module.Free.of_equiv (P.projEquiv h)

/-- A ring with a prime ideal is nontrivial. -/
private lemma nontrivial_of_primeSpectrum (p : PrimeSpectrum R) : Nontrivial R :=
  ⟨0, 1, fun h01 ↦ p.isPrime.ne_top
    ((Ideal.eq_top_iff_one _).mpr (h01 ▸ p.asIdeal.zero_mem))⟩

/-- If the relation matrix vanishes, `M` has rank `e` at every prime. -/
lemma rankAtStalk_eq_of_relMatrix_eq_zero (P : MatrixPresentation R M e m)
    (h : P.relMatrix = 0) (p : PrimeSpectrum R) :
    Module.rankAtStalk M p = e := by
  haveI : Nontrivial R := nontrivial_of_primeSpectrum p
  calc Module.rankAtStalk M p
      = Module.rankAtStalk (R := R) (Fin e → R) p :=
        (congrFun (Module.rankAtStalk_eq_of_equiv (P.projEquiv h)) p).symm
    _ = e := by simp

end Vanishing

section HardDirection

/-- **The hard direction of Nitsure's local universal property** (the step
left implicit in [Nitsure §4]): if `M` is flat and has rank `e` at every
prime, then the relation matrix of *any* presentation of `M` by `e`
generators vanishes.

The surjection `π : R^e ↠ M` between finite projectives of the same
everywhere-rank splits, the complement `K = ker π` is a finite projective
of everywhere-rank `0`, hence zero, so `ker π = range ψ = 0` and all
entries of `ψ` vanish. -/
theorem relMatrix_eq_zero_of_flat (P : MatrixPresentation R M e m)
    [Module.Flat R M]
    (h : ∀ p : PrimeSpectrum R, Module.rankAtStalk M p = e) :
    P.relMatrix = 0 := by
  haveI := P.finitePresentation
  haveI : Module.Projective R M := Module.Flat.projective_of_finitePresentation
  -- split the projection
  obtain ⟨s, hs⟩ := Module.projective_lifting_property P.proj LinearMap.id
    P.surjective_proj
  have hs' : ∀ x : M, P.proj (s x) = x := fun x ↦ congr($hs x)
  -- `R^e ≃ M × ker` via the splitting
  let E : (Fin e → R) ≃ₗ[R] M × LinearMap.ker P.proj :=
    { toFun := fun x ↦ (P.proj x, ⟨x - s (P.proj x), by simp [hs']⟩)
      map_add' := fun x y ↦ by
        ext <;> simp [add_sub_add_comm]
      map_smul' := fun r x ↦ by
        ext <;> simp [smul_sub]
      invFun := fun nk ↦ s nk.1 + nk.2.1
      left_inv := fun x ↦ by simp
      right_inv := fun nk ↦ by
        have hk : P.proj nk.2.1 = 0 := nk.2.2
        ext <;> simp [hs', hk] }
  -- the kernel is finite projective (a direct summand of `R^e`)
  haveI : Module.Projective R (LinearMap.ker P.proj) := by
    refine Module.Projective.of_split (LinearMap.ker P.proj).subtype
      ((LinearMap.snd R M (LinearMap.ker P.proj)) ∘ₗ E.toLinearMap) ?_
    refine LinearMap.ext fun ⟨x, hx⟩ ↦ Subtype.ext ?_
    have hx0 : P.proj x = 0 := hx
    simp [E, hx0]
  haveI : Module.Finite R (LinearMap.ker P.proj) := by
    have hsurj : Function.Surjective
        ((LinearMap.snd R M (LinearMap.ker P.proj)) ∘ₗ E.toLinearMap) := fun k ↦
      ⟨E.symm (0, k), by simp⟩
    exact Module.Finite.of_surjective _ hsurj
  -- rank bookkeeping: `e = e + rankAtStalk (ker) p` at every prime
  have hrank : ∀ p : PrimeSpectrum R,
      Module.rankAtStalk (R := R) (LinearMap.ker P.proj) p = 0 := by
    intro p
    haveI : Nontrivial R := nontrivial_of_primeSpectrum p
    have h1 : Module.rankAtStalk (R := R) (Fin e → R) p = e := by
      simp
    have h2 : Module.rankAtStalk (R := R) (Fin e → R) p
        = Module.rankAtStalk M p + Module.rankAtStalk (LinearMap.ker P.proj) p := by
      rw [congrFun (Module.rankAtStalk_eq_of_equiv E) p,
        congrFun (Module.rankAtStalk_prod (R := R) (M := M) (LinearMap.ker P.proj)) p,
        Pi.add_apply]
    have h3 := h p
    omega
  -- everywhere-rank-zero finite flat module is zero
  haveI : Subsingleton (LinearMap.ker P.proj) :=
    Module.rankAtStalk_eq_zero_iff_subsingleton.mp (funext hrank)
  -- hence the kernel is trivial and the relation matrix vanishes
  have hker : LinearMap.ker P.proj = ⊥ := by
    rw [Submodule.eq_bot_iff]
    intro x hx
    simpa using congrArg Subtype.val (Subsingleton.elim
      (⟨x, hx⟩ : LinearMap.ker P.proj) ⟨0, (LinearMap.ker P.proj).zero_mem⟩)
  have hrange : LinearMap.range P.relMatrix.mulVecLin = ⊥ := by
    rw [← P.ker_proj]
    exact hker
  rw [LinearMap.range_eq_bot] at hrange
  ext i j
  have := congr($hrange (Pi.single j 1) i)
  simpa [Matrix.mulVecLin_apply, Matrix.mulVec_single_one] using this

end HardDirection

section Independence

/-- Auxiliary half of presentation-independence: the entry ideal of one
`e`-generator presentation is contained in that of another. -/
theorem entryIdeal_le_entryIdeal (P : MatrixPresentation R M e m)
    (Q : MatrixPresentation R M e m') :
    Q.entryIdeal ≤ P.entryIdeal := by
  -- base change both to `A := R ⧸ P.entryIdeal`
  set A := R ⧸ P.entryIdeal
  -- the base change of `P` has vanishing relation matrix
  have hP : (P.baseChange A).relMatrix = 0 := by
    rw [baseChange_relMatrix, relMatrix_map_eq_zero_iff]
    intro x hx
    rw [RingHom.mem_ker, Ideal.Quotient.algebraMap_eq, Ideal.Quotient.eq_zero_iff_mem]
    exact hx
  -- hence `A ⊗ M` is free of everywhere-rank `e`
  haveI : Module.Free A (A ⊗[R] M) := (P.baseChange A).free_of_relMatrix_eq_zero hP
  -- apply the hard direction to the base change of `Q`
  have hQ : (Q.baseChange A).relMatrix = 0 :=
    (Q.baseChange A).relMatrix_eq_zero_of_flat
      ((P.baseChange A).rankAtStalk_eq_of_relMatrix_eq_zero hP)
  rw [baseChange_relMatrix, relMatrix_map_eq_zero_iff] at hQ
  refine hQ.trans ?_
  intro x hx
  rwa [RingHom.mem_ker, Ideal.Quotient.algebraMap_eq,
    Ideal.Quotient.eq_zero_iff_mem] at hx

/-- **Presentation-independence of the entry ideal** (the Fitting-ideal
miracle for `1 × 1` minors of an `e`-generator presentation): any two
presentations of `M` by `e` generators have the same entry ideal.
[Nitsure §4: implicit in "the resulting strata glue together by their
universal property".] -/
theorem entryIdeal_eq (P : MatrixPresentation R M e m)
    (Q : MatrixPresentation R M e m') :
    P.entryIdeal = Q.entryIdeal :=
  le_antisymm (entryIdeal_le_entryIdeal Q P) (entryIdeal_le_entryIdeal P Q)

end Independence

end MatrixPresentation

end Module

/-! ## The fiber rank and the point-set description of the strata -/

namespace Ideal

variable {R : Type u} [CommRing R]

/-- The **fiber rank** of a module `M` at a prime `p`: the dimension of the
fiber `κ(p) ⊗[R] M` over the residue field `κ(p)`.  [Nitsure §4:
`e = dim_{κ(s)} F|_s`.] -/
noncomputable def fiberRank (p : Ideal R) [p.IsPrime]
    (M : Type v) [AddCommGroup M] [Module R M] : ℕ :=
  Module.finrank p.ResidueField (p.Fiber M)

end Ideal

namespace Module.MatrixPresentation

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]
variable {e m : ℕ}

/-- **Point-set description of the rank-`e` stratum** [Nitsure §4, part (i)
of the theorem, `n = 0` case]: a prime `p` contains the entry ideal of an
`e`-generator presentation iff the fiber of `M` at `p` has dimension
exactly `e`. -/
theorem entryIdeal_le_prime_iff (P : MatrixPresentation R M e m)
    (p : Ideal R) [p.IsPrime] :
    P.entryIdeal ≤ p ↔ p.fiberRank M = e := by
  have hker : RingHom.ker (algebraMap R p.ResidueField) = p :=
    Ideal.ker_algebraMap_residueField p
  constructor
  · -- entries in `p` ⟹ the fiber presentation has zero relation matrix
    intro hle
    have h0 : (P.baseChange p.ResidueField).relMatrix = 0 := by
      rw [baseChange_relMatrix, relMatrix_map_eq_zero_iff, hker]
      exact hle
    rw [Ideal.fiberRank, ← LinearEquiv.finrank_eq
      ((P.baseChange p.ResidueField).projEquiv h0)]
    simp
  · -- fiber dimension `e` ⟹ the fiber relation matrix vanishes (hard
    -- direction over the residue field), so the entries lie in `p`
    intro hrank
    have h0 : (P.baseChange p.ResidueField).relMatrix = 0 := by
      refine (P.baseChange p.ResidueField).relMatrix_eq_zero_of_flat ?_
      intro q
      rw [Module.rankAtStalk_eq_finrank_of_free]
      exact hrank
    rw [baseChange_relMatrix, relMatrix_map_eq_zero_iff, hker] at h0
    exact h0

end Module.MatrixPresentation

/-! ## Nakayama prolongation

For `M` finitely presented over `R` and a prime `p`, there is `g ∉ p` such
that every localization of `M` away from `g` admits a matrix presentation
with exactly `fiberRank p M` generators.  This is the "prolongation of a
fiber basis" step of [Nitsure §4] (Nakayama applied twice: once to lift a
fiber basis to local generators, once to finitely present the kernel). -/

namespace Module.FinitePresentation

open Module

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- Every element of the fiber `κ(p) ⊗[R] M` is, up to a unit (an `r ∉ p`),
a pure tensor `1 ⊗ s`.  (The module version of
`Ideal.Fiber.exists_smul_eq_one_tmul`, which Mathlib states only for
algebras.) -/
private lemma exists_smul_eq_one_tmul (p : Ideal R) [p.IsPrime]
    (x : p.ResidueField ⊗[R] M) :
    ∃ r ∉ p, ∃ s : M, r • x = (1 : p.ResidueField) ⊗ₜ[R] s := by
  induction x using TensorProduct.induction_on with
  | zero =>
    exact ⟨1, fun h ↦ ‹p.IsPrime›.ne_top ((Ideal.eq_top_iff_one _).mpr h), 0, by simp⟩
  | tmul c m =>
    obtain ⟨y, rfl⟩ := IsLocalRing.residue_surjective c
    obtain ⟨⟨a, t⟩, rfl⟩ := IsLocalization.mk'_surjective p.primeCompl y
    refine ⟨t, t.2, a • m, ?_⟩
    have ht : (t : R) • (IsLocalRing.residue (Localization.AtPrime p)
          (IsLocalization.mk' (Localization.AtPrime p) a t))
        = algebraMap R p.ResidueField a := by
      rw [Algebra.smul_def,
        IsScalarTower.algebraMap_apply R (Localization.AtPrime p) p.ResidueField,
        IsLocalRing.ResidueField.algebraMap_eq, ← map_mul, IsLocalization.mk'_spec',
        ← IsLocalRing.ResidueField.algebraMap_eq, ← IsScalarTower.algebraMap_apply]
    calc (t : R) • (IsLocalRing.residue (Localization.AtPrime p)
          (IsLocalization.mk' (Localization.AtPrime p) a t) ⊗ₜ[R] m)
        = ((t : R) • IsLocalRing.residue (Localization.AtPrime p)
            (IsLocalization.mk' (Localization.AtPrime p) a t)) ⊗ₜ[R] m := by
          rw [TensorProduct.smul_tmul']
      _ = (algebraMap R p.ResidueField a) ⊗ₜ[R] m := by rw [ht]
      _ = (a • (1 : p.ResidueField)) ⊗ₜ[R] m := by
          rw [Algebra.algebraMap_eq_smul_one]
      _ = (1 : p.ResidueField) ⊗ₜ[R] (a • m) := TensorProduct.smul_tmul a 1 m
  | add x y hx hy =>
    obtain ⟨rx, hrx, sx, hsx⟩ := hx
    obtain ⟨ry, hry, sy, hsy⟩ := hy
    refine ⟨rx * ry, fun hmem ↦ ?_, ry • sx + rx • sy, ?_⟩
    · rcases ‹p.IsPrime›.mem_or_mem hmem with h | h
      · exact hrx h
      · exact hry h
    · rw [TensorProduct.tmul_add, smul_add]
      congr 1
      · rw [mul_comm, mul_smul, hsx, TensorProduct.tmul_smul]
      · rw [mul_smul, hsy, TensorProduct.tmul_smul]

/-- **Nakayama prolongation of a fiber basis** [Nitsure §4, `n = 0` case,
first step]: for `M` finitely presented over `R` and `p` a prime, there is
`g ∉ p` such that every localization `(R', N)` of `(R, M)` away from `g`
admits a matrix presentation with exactly `e = fiberRank p M` generators.

The statement quantifies over abstract localizations (`IsLocalization.Away`
/ `IsLocalizedModule`) so that geometric section rings `Γ(S, D(g))` and
section modules `Γ(F, D(g))` can be consumed directly. -/
theorem exists_matrixPresentation_of_isLocalizedModule
    [Module.FinitePresentation R M] (p : Ideal R) [p.IsPrime] :
    ∃ g : R, g ∉ p ∧
      ∀ (R' : Type u') [CommRing R'] [Algebra R R'] [IsLocalization.Away g R']
        (N : Type v') [AddCommGroup N] [Module R N] [Module R' N]
        [IsScalarTower R R' N] (l : M →ₗ[R] N)
        [IsLocalizedModule (Submonoid.powers g) l],
      ∃ mm : ℕ, Nonempty (MatrixPresentation R' N (p.fiberRank M) mm) := by
  classical
  -- a basis of the fiber, rescaled to consist of pure tensors `1 ⊗ mᵢ`
  let b : Basis (Fin (p.fiberRank M)) p.ResidueField (p.Fiber M) :=
    Module.finBasis p.ResidueField (p.Fiber M)
  have hb : ∀ i, ∃ r ∉ p, ∃ s : M, r • b i = (1 : p.ResidueField) ⊗ₜ[R] s := fun i ↦
    exists_smul_eq_one_tmul p (b i)
  choose r hr mvec hm using hb
  -- the images `1 ⊗ mᵢ` span the fiber
  have hunit : ∀ i, IsUnit (algebraMap R p.ResidueField (r i)) := by
    intro i
    rw [isUnit_iff_ne_zero, Ne, Ideal.algebraMap_residueField_eq_zero]
    exact hr i
  have hspan : Submodule.span p.ResidueField
      (Set.range fun i ↦ (1 : p.ResidueField) ⊗ₜ[R] mvec i) = ⊤ := by
    have hsm : Set.range (fun i ↦ (1 : p.ResidueField) ⊗ₜ[R] mvec i) =
        Set.range ⇑(b.unitsSMul fun i ↦ (hunit i).unit) := by
      apply congrArg
      funext i
      rw [← hm i, ← algebraMap_smul p.ResidueField (r i) (b i),
        Basis.unitsSMul_apply, Units.smul_def, IsUnit.unit_spec]
    rw [hsm]
    exact (b.unitsSMul fun i ↦ (hunit i).unit).span_eq
  -- the `mᵢ` generate `M` modulo Nakayama: the quotient has vanishing fiber
  have hQfiber : Subsingleton (p.ResidueField ⊗[R]
      (M ⧸ LinearMap.range (Fintype.linearCombination R mvec))) := by
    have hsurj : Function.Surjective
        ((LinearMap.range (Fintype.linearCombination R mvec)).mkQ.baseChange
          p.ResidueField) := by
      rw [LinearMap.baseChange_eq_ltensor]
      exact LinearMap.lTensor_surjective _ (Submodule.mkQ_surjective _)
    have hcomp : ((LinearMap.range (Fintype.linearCombination R mvec)).mkQ.baseChange
        p.ResidueField) ∘ₗ
        ((Fintype.linearCombination R mvec).baseChange p.ResidueField) = 0 := by
      rw [← LinearMap.baseChange_comp]
      have h0 : (LinearMap.range (Fintype.linearCombination R mvec)).mkQ ∘ₗ
          Fintype.linearCombination R mvec = 0 := by
        ext x
        simp only [LinearMap.comp_apply, Submodule.mkQ_apply, LinearMap.zero_apply,
          Submodule.Quotient.mk_eq_zero]
        exact ⟨_, rfl⟩
      rw [h0, LinearMap.baseChange_zero]
    have hrange : LinearMap.range
        ((Fintype.linearCombination R mvec).baseChange p.ResidueField) = ⊤ := by
      rw [← top_le_iff, ← hspan, Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      exact ⟨(1 : p.ResidueField) ⊗ₜ Pi.single i 1, by
        simp [LinearMap.baseChange_tmul, Fintype.linearCombination_apply_single]⟩
    apply subsingleton_of_forall_eq 0
    intro x
    obtain ⟨y, rfl⟩ := hsurj x
    have hy : y ∈ LinearMap.range
        ((Fintype.linearCombination R mvec).baseChange p.ResidueField) :=
      hrange ▸ Submodule.mem_top
    obtain ⟨a, rfl⟩ := hy
    exact congr($hcomp a)
  -- Nakayama at `p`: the finite quotient localizes to zero at `p`
  haveI : Module.Finite R (M ⧸ LinearMap.range (Fintype.linearCombination R mvec)) :=
    Module.Finite.of_surjective _ (Submodule.mkQ_surjective _)
  have e2 : Localization.AtPrime p ⊗[R]
      (M ⧸ LinearMap.range (Fintype.linearCombination R mvec))
      ≃ₗ[Localization.AtPrime p] LocalizedModule p.primeCompl
        (M ⧸ LinearMap.range (Fintype.linearCombination R mvec)) :=
    (IsLocalizedModule.isBaseChange p.primeCompl (Localization.AtPrime p)
      (LocalizedModule.mkLinearMap p.primeCompl _)).equiv
  haveI : Module.Finite (Localization.AtPrime p) (LocalizedModule p.primeCompl
      (M ⧸ LinearMap.range (Fintype.linearCombination R mvec))) :=
    Module.Finite.equiv e2
  have hQpsub : Subsingleton (LocalizedModule p.primeCompl
      (M ⧸ LinearMap.range (Fintype.linearCombination R mvec))) := by
    haveI := hQfiber
    haveI : Subsingleton (p.ResidueField ⊗[Localization.AtPrime p]
        (LocalizedModule p.primeCompl
          (M ⧸ LinearMap.range (Fintype.linearCombination R mvec)))) :=
      Equiv.subsingleton (((TensorProduct.congr
        (LinearEquiv.refl (Localization.AtPrime p) p.ResidueField) e2.symm).toEquiv).trans
        (AlgebraTensorModule.cancelBaseChange R (Localization.AtPrime p) p.ResidueField
          p.ResidueField _).toEquiv)
    exact (IsLocalRing.subsingleton_tensorProduct (R := Localization.AtPrime p)).mp ‹_›
  -- extract `g ∉ p` annihilating the quotient
  obtain ⟨g, hgann, hgp⟩ : ∃ g ∈ Module.annihilator R
      (M ⧸ LinearMap.range (Fintype.linearCombination R mvec)), g ∉ p := by
    have hnmem : (⟨p, ‹_›⟩ : PrimeSpectrum R) ∉ Module.support R
        (M ⧸ LinearMap.range (Fintype.linearCombination R mvec)) :=
      Module.notMem_support_iff.mpr hQpsub
    rw [Module.mem_support_iff_of_finite] at hnmem
    exact SetLike.not_le_iff_exists.mp hnmem
  have hg : ∀ x : M, g • x ∈ LinearMap.range (Fintype.linearCombination R mvec) := by
    intro x
    have hx := Module.mem_annihilator.mp hgann (Submodule.Quotient.mk
      (p := LinearMap.range (Fintype.linearCombination R mvec)) x)
    rwa [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero] at hx
  refine ⟨g, hgp, ?_⟩
  intro R' _ _ _ N _ _ _ _ l _
  -- `N` is finitely presented over `R'`
  haveI : Module.FinitePresentation R' N :=
    _root_.FinitePresentation.of_isBaseChange l
      (IsLocalizedModule.isBaseChange (Submonoid.powers g) R' l)
  -- the images `l mᵢ` generate `N` over `R'`
  have hgen : Function.Surjective (Fintype.linearCombination R' fun i ↦ l (mvec i)) := by
    rw [← LinearMap.range_eq_top, Fintype.range_linearCombination, ← top_le_iff]
    intro n _
    obtain ⟨⟨x, s⟩, hxs⟩ := IsLocalizedModule.surj (Submonoid.powers g) l n
    have hs : IsUnit (algebraMap R R' (s : R)) := IsLocalization.map_units R' s
    have hgu : IsUnit (algebraMap R R' g) :=
      IsLocalization.map_units R' ⟨g, Submonoid.mem_powers g⟩
    -- `l (g • x)` lies in the `R'`-span of the `l mᵢ`
    have hmem : l (g • x) ∈ Submodule.span R' (Set.range fun i ↦ l (mvec i)) := by
      obtain ⟨c, hc⟩ := hg x
      have hsum : l (g • x) = ∑ i, c i • l (mvec i) := by
        rw [← hc]
        simp [Fintype.linearCombination_apply, map_sum]
      rw [hsum]
      exact Submodule.sum_mem _ fun i _ ↦ Submodule.smul_of_tower_mem _ (c i)
        (Submodule.subset_span ⟨i, rfl⟩)
    -- clear the units `s` and `g`
    have hxs' : (s : R) • n = l x := hxs
    have hn : algebraMap R R' ((s : R) * g) • n = l (g • x) := by
      rw [map_mul, mul_smul, algebraMap_smul, algebraMap_smul, smul_comm, hxs',
        ← map_smul]
    have hu : IsUnit (algebraMap R R' ((s : R) * g)) := by
      rw [map_mul]
      exact hs.mul hgu
    have hnn : n = hu.unit⁻¹ • l (g • x) := by
      rw [eq_inv_smul_iff, Units.smul_def, IsUnit.unit_spec]
      exact hn
    rw [hnn]
    exact Submodule.smul_mem _ _ hmem
  -- the kernel is finitely generated; its generators are the relation matrix
  obtain ⟨T, hT⟩ := Module.FinitePresentation.fg_ker
    (Fintype.linearCombination R' fun i ↦ l (mvec i)) hgen
  refine ⟨T.card, ⟨{
    relMatrix := Matrix.of fun i j ↦ (T.equivFin.symm j : Fin (p.fiberRank M) → R') i
    proj := Fintype.linearCombination R' fun i ↦ l (mvec i)
    surjective_proj := hgen
    exact_mulVecLin_proj := ?_ }⟩⟩
  rw [LinearMap.exact_iff, ← hT]
  apply le_antisymm
  · -- each generator is a column of the matrix
    rw [Submodule.span_le]
    intro t ht
    obtain ⟨j, hj⟩ := T.equivFin.symm.surjective ⟨t, ht⟩
    refine ⟨Pi.single j 1, ?_⟩
    funext i
    simp only [Matrix.mulVecLin_apply, Matrix.mulVec, Matrix.of_apply]
    rw [dotProduct_single, mul_one, hj]
  · -- every matrix-vector product is a combination of the columns
    rintro _ ⟨x, rfl⟩
    have hcol : (Matrix.of fun i j ↦
          (T.equivFin.symm j : Fin (p.fiberRank M) → R') i).mulVecLin x =
        ∑ j, x j • ((T.equivFin.symm j : Fin (p.fiberRank M) → R')) := by
      funext i
      simp [Matrix.mulVec, dotProduct, Finset.sum_apply, mul_comm]
    rw [hcol]
    exact Submodule.sum_mem _ fun j _ ↦ Submodule.smul_mem _ _
      (Submodule.subset_span (T.equivFin.symm j).2)

end Module.FinitePresentation
