/-
Copyright (c) 2026 The AlgebraicJacobian Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/

import AlgebraicJacobian.Picard.FinitePresentationAlgebraFiniteStage
import AlgebraicJacobian.Picard.FinitePresentationAlgebraMapFiniteStage

/-!
# Stable finite-stage data

The first finite-stage files in this project expose several nested existential
packages.  That shape is convenient for proving existence, but it loses the
stage inclusion and makes every consumer reconstruct the same comparison
square.  This module provides small records for the data that is actually
used by consumers.  The records are additive: the original existential
theorems remain available, and the adapters below turn their output into the
records without introducing new hypotheses.
-/

set_option autoImplicit false

universe u

open TensorProduct

namespace AlgebraicGeometry.DatG0

/-! ## A finite stage and its canonical inclusion -/

/-- A finite intermediate stage of an algebraic field extension.

The finite-dimensionality witness is stored as a field instead of being
reconstructed by typeclass search at every use site.  The map to the ambient
field is canonical (`IntermediateField.val`), so tensor maps built from this
record have a stable type.
-/
structure FiniteStageData (F K : Type u) [Field F] [Field K] [Algebra F K] where
  stage : IntermediateField F K
  finiteWitness : FiniteDimensional F stage

namespace FiniteStageData

/-- Regard the packaged stage as an element of the old `FinSubext` index. -/
def toFinSubext {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) : FinSubext F K :=
  ⟨S.stage, S.finiteWitness⟩

/-- The canonical inclusion of a finite stage into the ambient field. -/
abbrev inclusion {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) : S.stage →ₐ[F] K := S.stage.val

@[simp]
theorem inclusion_apply {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) (x : S.stage) : S.inclusion x = (x : K) := rfl

theorem inclusion_injective {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) : Function.Injective S.inclusion := by
  intro x y h
  exact Subtype.ext h

/-- Package an existing finite-subextension witness. -/
def ofFinSubext {F K : Type u} [Field F] [Field K] [Algebra F K]
    (L : FinSubext F K) : FiniteStageData F K :=
  { stage := L.1
    finiteWitness := L.2 }

@[simp]
theorem ofFinSubext_toFinSubext {F K : Type u} [Field F] [Field K] [Algebra F K]
    (L : FinSubext F K) : (ofFinSubext L).toFinSubext = L := by
  rfl

@[simp]
theorem toFinSubext_stage {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) : S.toFinSubext.1 = S.stage := rfl

/-! ## Tensor maps attached to a stage -/

/-- The canonical scalar-extension map from a finite-stage tensor product to
the ambient tensor product. -/
noncomputable def tensorMap {F K A : Type u}
    [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A]
    (S : FiniteStageData F K) :
    S.stage ⊗[F] A →ₐ[F] K ⊗[F] A :=
  Algebra.TensorProduct.map S.inclusion (AlgHom.id F A)

@[simp]
theorem tensorMap_apply_tmul {F K A : Type u}
    [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A]
  (S : FiniteStageData F K) (x : S.stage) (a : A) :
    S.tensorMap (A := A) (x ⊗ₜ[F] a) = (x : K) ⊗ₜ[F] a := by
  rfl

/-- The target algebra generated by the canonical finite-stage tensor map.

Keeping this witness next to `tensorMap` makes the scalar-extension carrier
independent of whichever local `Algebra` instance happens to be in scope at a
consumer. -/
@[reducible] noncomputable def tensorAlgebra {F K A : Type u}
    [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A]
    (S : FiniteStageData F K) :
    Algebra (S.stage ⊗[F] A) (K ⊗[F] A) :=
  (S.tensorMap (A := A)).toRingHom.toAlgebra

/-- The scalar tower attached to `tensorAlgebra`.

The proof is stored once with the generated algebra map, so downstream
base-change APIs can install exactly this tower rather than reconstructing it
from a dependent tensor expression. -/
@[reducible] noncomputable def tensorTower {F K A : Type u}
    [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A]
    (S : FiniteStageData F K) :
    letI : Algebra (S.stage ⊗[F] A) (K ⊗[F] A) := S.tensorAlgebra (A := A)
    IsScalarTower F (S.stage ⊗[F] A) (K ⊗[F] A) := by
  letI : Algebra (S.stage ⊗[F] A) (K ⊗[F] A) := S.tensorAlgebra (A := A)
  exact @IsScalarTower.of_algebraMap_eq F (S.stage ⊗[F] A) (K ⊗[F] A)
    inferInstance inferInstance inferInstance inferInstance inferInstance inferInstance
    (fun x => (S.tensorMap (A := A)).commutes x)

/-! The legacy `tensorTower` keeps its local algebra in the result type for compatibility.
    New code should use this explicitly pinned form: its three scalar actions are determined by
    the named tensor algebras, so changing the ambient instance environment cannot change the
    proposition being transported. -/

theorem tensorTower_pinned {F K A : Type u}
    [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A]
    (S : FiniteStageData F K) :
    @IsScalarTower F (S.stage ⊗[F] A) (K ⊗[F] A)
      (Algebra.toSMul
        (self := Algebra.TensorProduct.instAlgebra (R := F) (A := S.stage) (B := A)))
      (Algebra.toSMul (self := S.tensorAlgebra (A := A)))
      (Algebra.toSMul
        (self := Algebra.TensorProduct.instAlgebra (R := F) (A := K) (B := A))) := by
  exact @IsScalarTower.of_algebraMap_eq F (S.stage ⊗[F] A) (K ⊗[F] A)
    (inferInstance : CommSemiring F)
    (inferInstance : CommSemiring (S.stage ⊗[F] A))
    (inferInstance : Semiring (K ⊗[F] A))
    (Algebra.TensorProduct.instAlgebra (R := F) (A := S.stage) (B := A))
    (S.tensorAlgebra (A := A))
    (Algebra.TensorProduct.instAlgebra (R := F) (A := K) (B := A))
    (fun x => (S.tensorMap (A := A)).commutes x)

end FiniteStageData

/-! ## Tensor-element presentations -/

/-- A tensor element together with the finite stage and preimage chosen for it.

The older `exists_finSubext_tensorProduct_preimage` theorem returns the stage as a
`FinSubext` and the map as a raw `LinearMap.rTensor` expression.  This package keeps
the stage and its canonical algebra map together, so a consumer does not have to
reconstruct either witness (or the equality between the linear and algebra maps).
-/
structure FiniteStageTensorPreimageData
    (F K B : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B] (x : K ⊗[F] B) where
  stage : FiniteStageData F K
  preimage : stage.stage ⊗[F] B
  map_eq : stage.tensorMap (A := B) preimage = x

namespace FiniteStageTensorPreimageData

/-- Package the raw finite-subextension preimage theorem. -/
theorem of_raw
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] [CommRing B] [Algebra F B]
    (x : K ⊗[F] B) :
    Nonempty (FiniteStageTensorPreimageData F K B x) := by
  obtain ⟨L, xL, hx⟩ := exists_finSubext_tensorProduct_preimage x
  let S : FiniteStageData F K := FiniteStageData.ofFinSubext L
  have hx' : S.tensorMap (A := B) xL = x := by
    change LinearMap.rTensor B L.1.val.toLinearMap xL = x
    exact hx
  exact ⟨⟨S, xL, hx'⟩⟩

/-- Select one finite-stage tensor preimage from `of_raw`.

This pins the classical choice at the producer boundary, so consumers can pass a
single presentation without reopening the existential certificate. -/
noncomputable def choose
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] [CommRing B] [Algebra F B]
    (x : K ⊗[F] B) : FiniteStageTensorPreimageData F K B x :=
  Classical.choice (of_raw x)

end FiniteStageTensorPreimageData

/-- A finite family of tensor elements presented over one common finite stage. -/
structure FiniteStageTensorPreimageFamilyData
    (F K B : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B] {ι : Type*} (x : ι → K ⊗[F] B) where
  stage : FiniteStageData F K
  preimage : ι → stage.stage ⊗[F] B
  map_eq : ∀ i, stage.tensorMap (A := B) (preimage i) = x i

namespace FiniteStageTensorPreimageFamilyData

/-- Package the common-stage finite-family preimage theorem. -/
theorem of_raw
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] [CommRing B] [Algebra F B]
    {ι : Type*} [Finite ι] (x : ι → K ⊗[F] B) :
    Nonempty (FiniteStageTensorPreimageFamilyData F K B x) := by
  obtain ⟨L, xL, hx⟩ :=
    exists_finSubext_tensorProduct_preimage_finite (x := x)
  let S : FiniteStageData F K := FiniteStageData.ofFinSubext L
  have hx' : ∀ i, S.tensorMap (A := B) (xL i) = x i := by
    intro i
    change LinearMap.rTensor B L.1.val.toLinearMap (xL i) = x i
    exact hx i
  exact ⟨⟨S, xL, hx'⟩⟩

/-- Select one common finite stage and family of tensor preimages from `of_raw`.

The choice is made once here and can then be reused by all family consumers. -/
noncomputable def choose
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] [CommRing B] [Algebra F B]
    {ι : Type*} [Finite ι] (x : ι → K ⊗[F] B) :
    FiniteStageTensorPreimageFamilyData F K B x :=
  Classical.choice (of_raw x)

end FiniteStageTensorPreimageFamilyData

/-! ## Explicit inclusions between stages -/

/-- A pinned map between two finite stages, together with its ambient
compatibility equation. -/
structure FiniteStageInclusion {F K : Type u}
    [Field F] [Field K] [Algebra F K]
    (S T : FiniteStageData F K) where
  le : S.stage ≤ T.stage
  map : S.stage →ₐ[F] T.stage
  map_spec : ∀ x, T.inclusion (map x) = S.inclusion x

namespace FiniteStageInclusion

/-- The canonical inclusion associated to an order relation. -/
def ofLE {F K : Type u} [Field F] [Field K] [Algebra F K]
    {S T : FiniteStageData F K} (h : S.stage ≤ T.stage) :
    FiniteStageInclusion S T :=
  { le := h
    map := IntermediateField.inclusion h
    map_spec := by
      intro x
      rfl }

@[simp]
theorem ofLE_map {F K : Type u} [Field F] [Field K] [Algebra F K]
    {S T : FiniteStageData F K} (h : S.stage ≤ T.stage) :
    (ofLE h).map = IntermediateField.inclusion h := rfl

theorem map_eq_canonical {F K : Type u} [Field F] [Field K] [Algebra F K]
    {S T : FiniteStageData F K} (i : FiniteStageInclusion S T) :
    i.map = IntermediateField.inclusion i.le := by
  apply DFunLike.ext _ _
  intro x
  apply T.inclusion_injective
  rw [i.map_spec]
  rfl

/-- Composition of pinned stage inclusions. -/
def comp {F K : Type u} [Field F] [Field K] [Algebra F K]
    {S T U : FiniteStageData F K}
    (i : FiniteStageInclusion S T) (j : FiniteStageInclusion T U) :
    FiniteStageInclusion S U :=
  { le := i.le.trans j.le
    map := j.map.comp i.map
    map_spec := by
      intro x
      calc
        U.inclusion ((j.map.comp i.map) x) = U.inclusion (j.map (i.map x)) := rfl
        _ = T.inclusion (i.map x) := j.map_spec _
        _ = S.inclusion x := i.map_spec _ }

/-- Identity inclusion at a stage. -/
def refl {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) : FiniteStageInclusion S S :=
  ofLE le_rfl

@[simp]
theorem refl_map {F K : Type u} [Field F] [Field K] [Algebra F K]
    (S : FiniteStageData F K) :
    (refl S).map = AlgHom.id F S.stage := by
  apply DFunLike.ext _ _
  intro x
  rfl

end FiniteStageInclusion

/-! ## A stable tensor-equality context -/

/-- The context shared by finite-stage tensor comparisons.

The old finite-subextension equality theorem exposes a raw `LinearMap.rTensor` and
leaves each consumer to recreate the stage inclusion and its tensor algebra map.  This
record pins those two maps together.  In particular, a consumer can carry one
`FiniteStageTensorEqualityContext` through several comparison records without asking
typeclass search to choose a new tensor carrier.
-/
structure FiniteStageTensorEqualityContext
    (F K B : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B]
    (S T : FiniteStageData F K) where
  inclusion : FiniteStageInclusion S T
  tensorMap : S.stage ⊗[F] B →ₐ[F] T.stage ⊗[F] B
  tensorMap_spec :
    tensorMap = Algebra.TensorProduct.map inclusion.map (AlgHom.id F B)
  ambientMap : T.stage ⊗[F] B →ₐ[F] K ⊗[F] B
  ambientMap_spec :
    ambientMap = Algebra.TensorProduct.map T.inclusion (AlgHom.id F B)

namespace FiniteStageTensorEqualityContext

@[simp]
theorem tensorMap_apply_tmul
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B]
    {S T : FiniteStageData F K}
    (D : FiniteStageTensorEqualityContext F K B S T)
    (x : S.stage) (b : B) :
    D.tensorMap (x ⊗ₜ[F] b) = D.inclusion.map x ⊗ₜ[F] b := by
  rw [D.tensorMap_spec]
  rfl

@[simp]
theorem ambientMap_apply_tmul
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B]
    {S T : FiniteStageData F K}
    (D : FiniteStageTensorEqualityContext F K B S T)
    (x : T.stage) (b : B) :
    D.ambientMap (x ⊗ₜ[F] b) = (x : K) ⊗ₜ[F] b := by
  rw [D.ambientMap_spec]
  rfl

end FiniteStageTensorEqualityContext

namespace FiniteStageTensorEqualityFamilyData

/-- Convert a raw finite-subextension equality family to the stable stage context. -/
noncomputable def toContext
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B] {ι : Type*}
    {L : FinSubext F K} {x y : ι → L.1 ⊗[F] B}
    (D : FiniteStageTensorEqualityFamilyData F K B L x y) :
    FiniteStageTensorEqualityContext F K B
      (FiniteStageData.ofFinSubext L)
      (FiniteStageData.ofFinSubext D.stage) := by
  let source : FiniteStageData F K := FiniteStageData.ofFinSubext L
  let target : FiniteStageData F K := FiniteStageData.ofFinSubext D.stage
  let inclusion : FiniteStageInclusion source target :=
    by
      refine { le := D.inclusion, map := D.map, map_spec := ?_ }
      intro z
      change (D.map z : K) = (z : K)
      rw [D.map_spec]
      rfl
  exact
    { inclusion := inclusion
      tensorMap := Algebra.TensorProduct.map D.map (AlgHom.id F B)
      tensorMap_spec := by rfl
      ambientMap := Algebra.TensorProduct.map target.inclusion (AlgHom.id F B)
      ambientMap_spec := by rfl }

@[simp]
theorem toContext_inclusion_le
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B] {ι : Type*}
    {L : FinSubext F K} {x y : ι → L.1 ⊗[F] B}
    (D : FiniteStageTensorEqualityFamilyData F K B L x y) :
    D.toContext.inclusion.le = D.inclusion :=
  rfl

theorem equality_via_context
    {F K B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing B] [Algebra F B] {ι : Type*}
    {L : FinSubext F K} {x y : ι → L.1 ⊗[F] B}
    (D : FiniteStageTensorEqualityFamilyData F K B L x y) (i : ι) :
    D.toContext.tensorMap.toLinearMap (x i) =
      D.toContext.tensorMap.toLinearMap (y i) := by
  change
    (Algebra.TensorProduct.map D.map (AlgHom.id F B)).toLinearMap (x i) =
      (Algebra.TensorProduct.map D.map (AlgHom.id F B)).toLinearMap (y i)
  rw [Algebra.TensorProduct.toLinearMap_map,
    TensorProduct.AlgebraTensorModule.map_eq]
  exact D.equality i

end FiniteStageTensorEqualityFamilyData

/-! ## Presented models at one stage -/

set_option synthInstance.maxHeartbeats 100000 in
-- The dependent quotient in the model type needs one larger local synthesis budget.
/-- A finite-presentation model of a `K`-algebra at one finite stage. -/
structure FiniteStageModelData
    (F K A : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra K A] where
  stage : FiniteStageData F K
  generators : Nat
  relationCount : Nat
  relation : Fin relationCount →
    MvPolynomial (Fin generators) stage.stage
  comparison :
    K ⊗[stage.stage] FiniteRelationAlgebra stage.stage generators
      relationCount relation ≃ₐ[K] A

namespace FiniteStageModelData

/-- The finite algebra represented by a model package. -/
abbrev model {F K A : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra K A]
    (D : FiniteStageModelData F K A) : Type u :=
  FiniteRelationAlgebra D.stage.stage D.generators D.relationCount D.relation

/-- Adapter from the raw single-algebra finite-presentation existential. -/
theorem exists_of_raw
    {F K A : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K]
    [CommRing A] [Algebra K A]
    [Algebra.FinitePresentation K A] :
    Nonempty (FiniteStageModelData F K A) := by
  obtain ⟨L, n, m, relation, ⟨e⟩⟩ :=
    exists_finSubext_finitePresentation_algebra_model (F := F) (K := K) (A := A)
  exact ⟨{
    stage := FiniteStageData.ofFinSubext L
    generators := n
    relationCount := m
    relation := relation
    comparison := e }⟩

/-- Select one finite-presentation model from `exists_of_raw`.

The selected stage, relations, and comparison are bundled so downstream code
does not make independent choices from the same existence theorem. -/
noncomputable def choose
    {F K A : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K]
    [CommRing A] [Algebra K A]
    [Algebra.FinitePresentation K A] :
    FiniteStageModelData F K A :=
  Classical.choice (exists_of_raw (F := F) (K := K) (A := A))

end FiniteStageModelData

set_option synthInstance.maxHeartbeats 100000 in
-- A family-indexed quotient otherwise makes synthesis revisit the same carrier parents.
/-- A simultaneous family of finite-presentation models at one common stage. -/
structure FiniteStageModelFamilyData
    (F K : Type u) [Field F] [Field K] [Algebra F K]
    {ι : Type*} (A : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra K (A i)] where
  stage : FiniteStageData F K
  generators : ι → Nat
  relationCount : ι → Nat
  relation : ∀ i, Fin (relationCount i) →
    MvPolynomial (Fin (generators i)) stage.stage
  comparison : ∀ i,
    K ⊗[stage.stage] FiniteRelationAlgebra stage.stage
      (generators i) (relationCount i) (relation i) ≃ₐ[K] A i

namespace FiniteStageModelFamilyData

set_option synthInstance.maxHeartbeats 200000 in
-- The raw family existential carries a dependent quotient for each index.
/-- Adapter from the raw simultaneous finite-presentation existential. -/
theorem exists_of_raw
    {F K : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] {ι : Type*} [Finite ι]
    (A : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra K (A i)]
    [∀ i, Algebra.FinitePresentation K (A i)] :
    Nonempty (FiniteStageModelFamilyData F K A) := by
  obtain ⟨L, hL⟩ :=
    exists_finSubext_finitePresentation_algebra_model_finite (F := F) (K := K) A
  choose n m relation he using hL
  let e : ∀ i,
      K ⊗[L.1] FiniteRelationAlgebra L.1 (n i) (m i) (relation i) ≃ₐ[K] A i :=
    fun i => Classical.choice (he i)
  exact ⟨{
    stage := FiniteStageData.ofFinSubext L
    generators := n
    relationCount := m
    relation := relation
    comparison := e }⟩

/-- Select one common finite-presentation model family from `exists_of_raw`.

The common finite stage is chosen once, rather than separately for each index. -/
noncomputable def choose
    {F K : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] {ι : Type*} [Finite ι]
    (A : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra K (A i)]
    [∀ i, Algebra.FinitePresentation K (A i)] :
    FiniteStageModelFamilyData F K A :=
  Classical.choice (exists_of_raw (F := F) (K := K) A)

end FiniteStageModelFamilyData

/-! ## Comparison maps and map families -/

/-- One finite-stage map together with its ambient comparison square.  The
square is stored explicitly, so downstream code never has to re-infer the
restriction/tensor instances. -/
structure FiniteStageComparisonData
    (F K A B : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A] [CommRing B] [Algebra F B] where
  stage : FiniteStageData F K
  ambientMap : K ⊗[F] A →ₐ[K] K ⊗[F] B
  stageMap : stage.stage ⊗[F] A →ₐ[stage.stage] stage.stage ⊗[F] B
  compatibility :
    (stage.tensorMap (A := B)).comp (stageMap.restrictScalars F) =
      (ambientMap.restrictScalars F).comp (stage.tensorMap (A := A))

namespace FiniteStageComparisonData

/-- Build a comparison package from an already chosen finite subextension and stage map. -/
def ofFinSubextData
    {F K A B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A] [CommRing B] [Algebra F B]
    (L : FinSubext F K) (ambientMap : K ⊗[F] A →ₐ[K] K ⊗[F] B)
    (stageMap : L.1 ⊗[F] A →ₐ[L.1] L.1 ⊗[F] B)
    (compatibility :
      (Algebra.TensorProduct.map L.1.val (AlgHom.id F B)).comp
          (stageMap.restrictScalars F) =
        (ambientMap.restrictScalars F).comp
          (Algebra.TensorProduct.map L.1.val (AlgHom.id F A))) :
    FiniteStageComparisonData F K A B :=
  { stage := FiniteStageData.ofFinSubext L
    ambientMap := ambientMap
    stageMap := stageMap
    compatibility := compatibility }

@[simp]
theorem compatibility_apply
    {F K A B : Type u} [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A] [CommRing B] [Algebra F B]
    (D : FiniteStageComparisonData F K A B) (x : D.stage.stage ⊗[F] A) :
    D.stage.tensorMap (A := B) (D.stageMap.restrictScalars F x) =
      D.ambientMap.restrictScalars F (D.stage.tensorMap (A := A) x) := by
  exact DFunLike.congr_fun D.compatibility x

/-- Adapter from the raw single-map finite-stage existential. -/
theorem exists_of_raw
    {F K A B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K]
    [CommRing A] [Algebra F A] [Algebra.FiniteType F A]
    [CommRing B] [Algebra F B]
    (phi : K ⊗[F] A →ₐ[K] K ⊗[F] B) :
    Nonempty (FiniteStageComparisonData F K A B) := by
  obtain ⟨L, phiL, hphi⟩ :=
    exists_finSubext_tensorProduct_algHom (F := F) (K := K) (A := A) (B := B) phi
  exact ⟨FiniteStageComparisonData.ofFinSubextData L phi phiL hphi⟩

/-- Select one finite-stage comparison from `exists_of_raw`.

The ambient map, stage map, and compatibility square are kept together in the
resulting package. -/
noncomputable def choose
    {F K A B : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K]
    [CommRing A] [Algebra F A] [Algebra.FiniteType F A]
    [CommRing B] [Algebra F B]
    (phi : K ⊗[F] A →ₐ[K] K ⊗[F] B) :
    FiniteStageComparisonData F K A B :=
  Classical.choice (exists_of_raw (F := F) (K := K) (A := A) (B := B) phi)

end FiniteStageComparisonData

/-- A finite family of map comparisons sharing one stage. -/
structure FiniteStageMapFamily
    (F K : Type u) [Field F] [Field K] [Algebra F K]
    {ι : Type*} (A B : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra F (A i)]
    [∀ i, CommRing (B i)] [∀ i, Algebra F (B i)] where
  stage : FiniteStageData F K
  ambientMap : ∀ i, K ⊗[F] A i →ₐ[K] K ⊗[F] B i
  stageMap : ∀ i, stage.stage ⊗[F] A i →ₐ[stage.stage] stage.stage ⊗[F] B i
  compatibility : ∀ i,
    (stage.tensorMap (A := B i)).comp ((stageMap i).restrictScalars F) =
      ((ambientMap i).restrictScalars F).comp (stage.tensorMap (A := A i))

namespace FiniteStageMapFamily

/-- Convert the lower-level finite-subextension family into the canonical stage package.

The lower package pins the actual descended maps and their comparison equations.  This
adapter installs the same stage as `FiniteStageData`, so consumers can use the stable
`tensorMap` API without reopening the raw existential. -/
def ofFinSubextData
    {F K : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] {ι : Type*}
    {A B : ι → Type u}
    [∀ i, CommRing (A i)] [∀ i, Algebra F (A i)]
    [∀ i, CommRing (B i)] [∀ i, Algebra F (B i)]
    (phi : ∀ i, K ⊗[F] A i →ₐ[K] K ⊗[F] B i)
    (D : FinSubextTensorAlgHomFamilyData A B phi) :
    FiniteStageMapFamily F K A B :=
  { stage := FiniteStageData.ofFinSubext D.stage
    ambientMap := phi
    stageMap := D.map
    compatibility := D.commutes }

/-- Each family member is a first-class comparison package. -/
def comparison {F K : Type u} [Field F] [Field K] [Algebra F K]
    {ι : Type*} {A B : ι → Type u}
    [∀ i, CommRing (A i)] [∀ i, Algebra F (A i)]
    [∀ i, CommRing (B i)] [∀ i, Algebra F (B i)]
    (P : FiniteStageMapFamily F K A B) (i : ι) :
    FiniteStageComparisonData F K (A i) (B i) :=
  { stage := P.stage
    ambientMap := P.ambientMap i
    stageMap := P.stageMap i
    compatibility := P.compatibility i }

/-- Adapter from the raw simultaneous map-family existential. -/
theorem exists_of_raw
    {F K : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] {ι : Type*} [Finite ι]
    (A B : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra F (A i)]
    [∀ i, Algebra.FiniteType F (A i)]
    [∀ i, CommRing (B i)] [∀ i, Algebra F (B i)]
    (phi : ∀ i, K ⊗[F] A i →ₐ[K] K ⊗[F] B i) :
    Nonempty (FiniteStageMapFamily F K A B) := by
  obtain ⟨D⟩ := FinSubextTensorAlgHomFamilyData.of_exists A B phi
  exact ⟨FiniteStageMapFamily.ofFinSubextData phi D⟩

/-- Select one common finite stage and map family from `exists_of_raw`.

All descended maps and their compatibility equations are therefore obtained
from one stable producer choice. -/
noncomputable def choose
    {F K : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K] {ι : Type*} [Finite ι]
    (A B : ι → Type u)
    [∀ i, CommRing (A i)] [∀ i, Algebra F (A i)]
    [∀ i, Algebra.FiniteType F (A i)]
    [∀ i, CommRing (B i)] [∀ i, Algebra F (B i)]
    (phi : ∀ i, K ⊗[F] A i →ₐ[K] K ⊗[F] B i) :
    FiniteStageMapFamily F K A B :=
  Classical.choice (exists_of_raw (F := F) (K := K) A B phi)

end FiniteStageMapFamily

/-! ## Composition coherence -/

/-- A packaged three-map comparison used to reflect a composition identity
from the ambient extension back to a finite stage. -/
structure FiniteStageCompositionData
    (F K A B D : Type u) [Field F] [Field K] [Algebra F K]
    [CommRing A] [Algebra F A] [CommRing B] [Algebra F B]
    [CommRing D] [Algebra F D] where
  stage : FiniteStageData F K
  phiStage : stage.stage ⊗[F] A →ₐ[stage.stage] stage.stage ⊗[F] B
  psiStage : stage.stage ⊗[F] B →ₐ[stage.stage] stage.stage ⊗[F] D
  chiStage : stage.stage ⊗[F] A →ₐ[stage.stage] stage.stage ⊗[F] D
  phiAmbient : K ⊗[F] A →ₐ[K] K ⊗[F] B
  psiAmbient : K ⊗[F] B →ₐ[K] K ⊗[F] D
  chiAmbient : K ⊗[F] A →ₐ[K] K ⊗[F] D
  phi_compatibility :
    (stage.tensorMap (A := B)).comp (phiStage.restrictScalars F) =
      (phiAmbient.restrictScalars F).comp (stage.tensorMap (A := A))
  psi_compatibility :
    (stage.tensorMap (A := D)).comp (psiStage.restrictScalars F) =
      (psiAmbient.restrictScalars F).comp (stage.tensorMap (A := B))
  chi_compatibility :
    (stage.tensorMap (A := D)).comp (chiStage.restrictScalars F) =
      (chiAmbient.restrictScalars F).comp (stage.tensorMap (A := A))
  ambient_composition : psiAmbient.comp phiAmbient = chiAmbient

namespace FiniteStageCompositionData

/-- Reflect the ambient composition equation using the pinned comparison
fields. -/
theorem stage_composition
    {F K A B D : Type u} [Field F] [Field K] [Algebra F K]
    [Algebra.IsAlgebraic F K]
    [CommRing A] [Algebra F A] [CommRing B] [Algebra F B]
    [CommRing D] [Algebra F D]
    (P : FiniteStageCompositionData F K A B D) :
    P.psiStage.comp P.phiStage = P.chiStage := by
  apply tensorProduct_algHom_comp_eq_of_baseChange
    P.stage.toFinSubext P.phiStage P.psiStage P.chiStage
    P.phiAmbient P.psiAmbient P.chiAmbient
  · exact P.phi_compatibility
  · exact P.psi_compatibility
  · exact P.chi_compatibility
  · exact P.ambient_composition

end FiniteStageCompositionData

end AlgebraicGeometry.DatG0
