/-
Copyright (c) 2026 The AlgebraicJacobian Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.Pic0AffineEtaleDescent
import AlgebraicJacobian.Picard.Pic0SigmaSheaf
import Mathlib.AlgebraicGeometry.Sites.Fpqc

/-!
# Big-etale descent for the Pic0 Sigma functor

The big etale topology agrees with the quasi-compact topology generated by etale
morphisms.  Its sheaf condition therefore reduces to Zariski descent and singleton
surjective etale maps between affine schemes.  The latter is supplied by the affine
Pic0 descent theorem.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits Opposite
open scoped TensorProduct

namespace AlgebraicGeometry

noncomputable section

/-- The ordinary and quasi-compact presentations generate the same big etale topology. -/
theorem Scheme.etaleTopology_eq_propQCTopology :
    Scheme.etaleTopology.{u} = Scheme.propQCTopology (@Etale) := by
  apply le_antisymm
  · apply Precoverage.toGrothendieck_mono
    rw [Scheme.propQCPrecoverage, le_inf_iff]
    exact ⟨Scheme.precoverage_le_qcPrecoverage_of_isOpenMap
      (fun _ _ f _ => f.isOpenMap), le_rfl⟩
  · exact Precoverage.toGrothendieck_mono
      Scheme.propQCPrecoverage_le_precoverage

private theorem etaleCover_doubleProjection_comp_base
    {k A : Type u} [Field k] [CommRing A] [Algebra k A]
    (E : Algebra.EtaleCover A) :
    let d₀ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
      Over.overSpecMap (doubleInl (k := k) E)
    let d₁ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
      Over.overSpecMap (doubleInr (k := k) E)
    let g : Spec (.of E.Carrier) ⟶ Spec (.of A) :=
      Spec.map (CommRingCat.ofHom (algebraMap A E.Carrier))
    d₀.left ≫ g = d₁.left ≫ g := by
  dsimp only
  let f : A →ₐ[k] E.Carrier :=
    (Algebra.ofId A E.Carrier).restrictScalars k
  let d : overSpec k E.Carrier ⟶ overSpec k A := Over.overSpecMap f
  let d₀ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
    Over.overSpecMap (doubleInl (k := k) E)
  let d₁ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
    Over.overSpecMap (doubleInr (k := k) E)
  have hcomp :
      (doubleInl (k := k) E).comp f =
        (doubleInr (k := k) E).comp f := by
    ext r
    simp [f, doubleInl, doubleInr]
  have hover : d₀ ≫ d = d₁ ≫ d := by
    dsimp only [d₀, d₁, d]
    rw [← Over.overSpecMap_comp, ← Over.overSpecMap_comp, hcomp]
  have hleft := congrArg Over.Hom.left hover
  have hf : f.toRingHom = algebraMap A E.Carrier := rfl
  simpa only [Over.comp_left, d₀, d₁, d, Over.overSpecMap_left, hf,
    overSpec_left] using hleft

set_option maxHeartbeats 400000 in
/-- The Pic0 Sigma functor satisfies descent for the singleton scheme cover attached to a
presented etale algebra cover. -/
theorem pic0SigmaFunctor_isSheafFor_etaleCover
    {k A : Type u} [Field k] [CommRing A]
    (C : Over (Spec (.of k))) [SmoothOfRelativeDimension 1 C.hom]
    [IsProper C.hom] [GeometricallyIrreducible C.hom]
    [GeometricallyReduced C.hom]
    (E : Algebra.EtaleCover A) :
    Presieve.IsSheafFor (pic0SigmaFunctor C)
      (.singleton (Spec.map
        (CommRingCat.ofHom (algebraMap A E.Carrier)))) := by
  rw [Presieve.isSheafFor_singleton]
  rintro ⟨b, x⟩ hx
  let g : Spec (.of E.Carrier) ⟶ Spec (.of A) :=
    Spec.map (CommRingCat.ofHom (algebraMap A E.Carrier))
  letI : Surjective g :=
    ⟨E.comap_surjective⟩
  haveI : Etale g := by
    dsimp [g]
    rw [HasRingHomProperty.Spec_iff (P := @Etale)]
    exact RingHom.etale_algebraMap.mpr inferInstance
  have hbase : ∀ {Z : Scheme.{u}} (p₁ p₂ : Z ⟶ Spec (.of E.Carrier)),
      p₁ ≫ g = p₂ ≫ g → p₁ ≫ b = p₂ ≫ b := by
    intro Z p₁ p₂ hp
    exact congrArg Sigma.fst (hx p₁ p₂ hp)
  let a : Spec (.of A) ⟶ Spec (.of k) :=
    EffectiveEpi.desc g b hbase
  have ha : g ≫ a = b := EffectiveEpi.fac g b hbase
  obtain ⟨φ, hφ⟩ := Spec.map_surjective a
  algebraize [φ.hom]
  have haφ : g ≫ Spec.map φ = b := by
    rw [hφ]
    exact ha
  have hE : (overSpec k E.Carrier).hom = b := by
    change Spec.map (CommRingCat.ofHom (algebraMap k E.Carrier)) = b
    rw [IsScalarTower.algebraMap_eq k A E.Carrier]
    change Spec.map (φ ≫ CommRingCat.ofHom (algebraMap A E.Carrier)) = b
    rw [Spec.map_comp]
    exact haφ
  let eIso : overSpec k E.Carrier ≅ Over.mk b :=
    Over.isoMk (Iso.refl _) hE.symm
  let e : overSpec k E.Carrier ⟶ Over.mk b := eIso.hom
  let xE : pic0Subgroup C (overSpec k E.Carrier) := pic0Map C e x
  let d₀ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
    Over.overSpecMap (doubleInl (k := k) E)
  let d₁ : overSpec k (E.Carrier ⊗[A] E.Carrier) ⟶ overSpec k E.Carrier :=
    Over.overSpecMap (doubleInr (k := k) E)
  have hlegs : d₀.left ≫ g = d₁.left ≫ g := by
    exact etaleCover_doubleProjection_comp_base E
  have hd₀e : (d₀ ≫ e).left = d₀.left := by
    simp only [Over.comp_left, e, eIso, Over.isoMk_hom_left, Iso.refl_hom]
    exact Category.comp_id _
  have hd₁e : (d₁ ≫ e).left = d₁.left := by
    simp only [Over.comp_left, e, eIso, Over.isoMk_hom_left, Iso.refl_hom]
    exact Category.comp_id _
  have hSigma :
      (pic0SigmaFunctor C).map (d₀ ≫ e).left.op ⟨b, x⟩ =
        (pic0SigmaFunctor C).map (d₁ ≫ e).left.op ⟨b, x⟩ := by
    rw [hd₀e, hd₁e]
    exact hx d₀.left d₁.left hlegs
  have hFib := Over.map_eq_of_sigmaExtension_map_eq
    (F := pic0TypeFunctor C) (d₀ ≫ e) (d₁ ≫ e) hSigma
  have hdouble :
      pic0Map C d₀ xE = pic0Map C d₁ xE := by
    change (pic0TypeFunctor C).map d₀.op
        ((pic0TypeFunctor C).map e.op x) =
      (pic0TypeFunctor C).map d₁.op
        ((pic0TypeFunctor C).map e.op x)
    rw [← FunctorToTypes.map_comp_apply, ← FunctorToTypes.map_comp_apply]
    exact hFib
  obtain ⟨z, hz, hzu⟩ :=
    pic0Subgroup_existsUnique_of_etaleCover C E xE hdouble
  let d : overSpec k E.Carrier ⟶ overSpec k A :=
    Over.overSpecMap ((Algebra.ofId A E.Carrier).restrictScalars k)
  let q : Over.mk b ⟶ overSpec k A := Over.homMk g haφ
  have heq : e ≫ q = d := by
    apply Over.OverMorphism.ext
    rfl
  have hrestrict (t : pic0Subgroup C (overSpec k A)) :
      pic0Map C e (pic0Map C q t) = pic0Map C d t := by
    change (pic0TypeFunctor C).map e.op
        ((pic0TypeFunctor C).map q.op t) =
      (pic0TypeFunctor C).map d.op t
    rw [← FunctorToTypes.map_comp_apply, ← op_comp, heq]
  have hq : pic0Map C q z = x := by
    apply (ConcreteCategory.bijective_of_isIso
      ((pic0TypeFunctor C).map e.op)).1
    change (pic0TypeFunctor C).map e.op
        ((pic0TypeFunctor C).map q.op z) =
      (pic0TypeFunctor C).map e.op x
    rw [← FunctorToTypes.map_comp_apply, ← op_comp, heq]
    change pic0Map C d z = xE
    exact hz
  refine ⟨⟨Spec.map φ, z⟩, ?_, ?_⟩
  · refine (Over.sigmaExtension_map_mk_eq_iff
      (F := pic0TypeFunctor C) g haφ z x).mpr ?_
    rw [pic0TypeFunctor_map_apply]
    exact hq
  · rintro ⟨a', z'⟩ hz'
    have ha' : a' = Spec.map φ := by
      exact (EffectiveEpi.uniq g b hbase a'
        (congrArg Sigma.fst hz')).trans hφ.symm
    subst a'
    change pic0Subgroup C (overSpec k A) at z'
    refine congrArg (Sigma.mk (Spec.map φ)) (hzu z' ?_)
    have hq' : pic0Map C q z' = x := by
      have hmem := (Over.sigmaExtension_map_mk_eq_iff
        (F := pic0TypeFunctor C) g haφ z' x).mp hz'
      rw [pic0TypeFunctor_map_apply] at hmem
      exact hmem
    calc
      pic0Map C d z' = pic0Map C e (pic0Map C q z') := (hrestrict z').symm
      _ = pic0Map C e x := congrArg (pic0Map C e) hq'
      _ = xE := rfl

/-- Singleton descent for the Pic0 Sigma functor along an arbitrary surjective etale map
between affine schemes.  The base-field algebra structures and a small presented cover are
chosen internally. -/
theorem pic0SigmaFunctor_isSheafFor_etaleSingleton
    {k : Type u} [Field k]
    (C : Over (Spec (.of k))) [SmoothOfRelativeDimension 1 C.hom]
    [IsProper C.hom] [GeometricallyIrreducible C.hom]
    [GeometricallyReduced C.hom]
    {R S : CommRingCat.{u}} (f : R ⟶ S)
    (hf : Etale (Spec.map f)) (hs : Surjective (Spec.map f)) :
    Presieve.IsSheafFor (pic0SigmaFunctor C)
      (.singleton (Spec.map f)) := by
  algebraize [f.hom]
  haveI : Algebra.Etale R S :=
    RingHom.etale_algebraMap.mp
      ((HasRingHomProperty.Spec_iff (P := @Etale)).mp hf)
  have hcomap :
      Function.Surjective (PrimeSpectrum.comap (algebraMap R S)) := by
    exact (surjective_iff (Spec.map f)).mp hs
  let E : Algebra.EtaleCover R := Algebra.EtaleCover.of S hcomap
  let e : Spec S ≅ Spec (.of E.Carrier) :=
    Scheme.Spec.mapIso
      (Algebra.EtaleCover.ofEquiv S hcomap).toRingEquiv.toCommRingCatIso.op
  have he : e.hom ≫
      Spec.map (CommRingCat.ofHom (algebraMap R E.Carrier)) =
      Spec.map f := by
    change Spec.map (CommRingCat.ofHom
        (Algebra.EtaleCover.ofEquiv S hcomap).toRingEquiv.toRingHom) ≫
      Spec.map (CommRingCat.ofHom
        (algebraMap R (Algebra.EtaleCover.of S hcomap).Carrier)) =
      Spec.map f
    rw [← Spec.map_comp]
    congr 1
    ext r
    exact (Algebra.EtaleCover.ofEquiv S hcomap).commutes r
  exact (Presieve.isSheafFor_singleton_iff_of_iso
    (Spec.map f)
    (Spec.map (CommRingCat.ofHom (algebraMap R E.Carrier))) e he).mpr
      (pic0SigmaFunctor_isSheafFor_etaleCover C E)

/-- The raw Pic0 Sigma functor is a sheaf for the big etale topology. -/
theorem pic0SigmaFunctor_isSheaf_etale
    {k : Type u} [Field k]
    (C : Over (Spec (.of k))) [SmoothOfRelativeDimension 1 C.hom]
    [IsProper C.hom] [GeometricallyIrreducible C.hom]
    [GeometricallyReduced C.hom] :
    Presieve.IsSheaf Scheme.etaleTopology (pic0SigmaFunctor C) := by
  rw [Scheme.etaleTopology_eq_propQCTopology,
    isSheaf_type_propQCTopology_iff]
  exact ⟨pic0SigmaFunctor_isSheaf C,
    fun f hf hs =>
      pic0SigmaFunctor_isSheafFor_etaleSingleton C f hf hs⟩

/-- The categorical sheaf certificate associated to raw big-etale Pic0 Sigma descent. -/
theorem pic0SigmaFunctor_presheafIsSheaf_etale
    {k : Type u} [Field k]
    (C : Over (Spec (.of k))) [SmoothOfRelativeDimension 1 C.hom]
    [IsProper C.hom] [GeometricallyIrreducible C.hom]
    [GeometricallyReduced C.hom] :
    Presheaf.IsSheaf Scheme.etaleTopology (pic0SigmaFunctor C) :=
  (isSheaf_iff_isSheaf_of_type _ _).mpr
    (pic0SigmaFunctor_isSheaf_etale C)

end

end AlgebraicGeometry
