/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.Pic0ChartLocalSurjectivity

/-!
# DAT-B B-5: from pointwise coverage to the sieve condition

`Picard/Pic0ChartLocalSurjectivity.lean` reduced B-6 to `ChartsCoverLocally`, whose statement
is *sieve-theoretic*: for every test `T` and every degree-zero class `s` on it, the supremum
of the per-chart image sieves is a Zariski covering sieve.  The dat-b row calls that "B-5
verbatim" and says a producer discharges it "by exhibiting one open neighbourhood and one
index per point of `T`".

**That last sentence was a claim about a bridge nobody had written.**  What B-5's geometry
produces is pointwise: for each point `t` of the test, an open `W ∋ t`, an index `i`, and a
chart point over `W` whose class restricts to `s`.  What `ChartsCoverLocally` asks for is
membership of a Grothendieck topology.  The two are connected by a *cover construction* —
`Scheme.Cover.mkOfCovers` at the family `{W t}` indexed by the points of `T` — and the
connection is what this file supplies.

## Why the bridge is not bookkeeping the producer can inline

Three things have to line up, and each is a place a lane would stall:

* the cover must be indexed by a type in the right universe.  Indexing by the points of `T`
  works (`↥T : Type u` for `T : Scheme.{u}`) and is the *only* index available before any
  geometry is known — a producer that tries to index by a chosen finite subcover needs
  quasi-compactness, which no row assumes;
* `mem_grothendieckTopology_iff` asks for `Presieve.ofArrows 𝒰.X 𝒰.f ≤ S.arrows`, i.e. a
  statement about the *presieve generated by the cover maps*, so the per-point witness has to
  be produced after destructing `ofArrows` — which binds the point, not an arbitrary map into
  `T`.  This is where the pointwise data is consumed;
* the per-point index makes the target sieve a *supremum*, and `le_iSup` is what turns "some
  chart works at `t`" into "the supremum contains `W t`".  Nothing forces one index to work
  at every point, which is the chart-parameter heterogeneity the dat-b row records — here it
  costs literally nothing, because `iSup` is what the statement already had.

## Main declarations

* `AlgebraicGeometry.mem_zariskiTopology_iSup_of_pointwise` — **the bridge**, stated for an
  arbitrary family of sieves: pointwise opens with a per-point index give the supremum sieve
  covering status.  No presheaf, no chart, no `pic⁰`.
* `AlgebraicGeometry.chartsCoverLocally_of_pointwise` — `ChartsCoverLocally` from exactly the
  data B-5 produces: per test point, an open neighbourhood, an index, and a chart point over
  that open with the right class.  **This is what a coverage lane owes, and nothing more.**
* `AlgebraicGeometry.isLocallySurjective_sigmaDesc_of_pointwise` — the composite: pointwise
  coverage gives the local-surjectivity instance `pic0RepresentableByOfCharts` consumes, i.e.
  B-5 ⟹ B-6 in one step.
* `AlgebraicGeometry.pointwise_of_chartsCoverLocally` — the **converse**, and the reason this
  is a reduction rather than a restatement: the sieve condition gives back an open cover of
  the test on each of whose members some chart hits `s`.  So the pointwise form is not a
  strengthening chosen to be provable.
-/

set_option autoImplicit false
set_option maxSynthPendingDepth 3

universe u

open CategoryTheory Limits Opposite MonoidalCategory CartesianMonoidalCategory

namespace AlgebraicGeometry

variable {k : Type u} [Field k] {C : Over (Spec (.of k))}
variable [SmoothOfRelativeDimension 1 C.hom] [IsProper C.hom]
variable [GeometricallyIrreducible C.hom]

noncomputable section

/-! ## The bridge, with no chart content

Stated for an arbitrary family of sieves on an arbitrary scheme, because that is all it uses:
the coverage half of B-5 is a statement about the *site*, and mixing it with the presheaf
statement is what made it look gated. -/

/-- **Pointwise data gives a covering supremum sieve.**

If every point `t` of `T` has an open neighbourhood `W t` and an index `idx t` such that the
inclusion `(W t).ι` lies in the `idx t`-th sieve, then the supremum of the family is a
Zariski covering sieve of `T`.

The proof is the cover `{W t}_{t : ↥T}` — jointly surjective because `t ∈ W t`, open
immersions because they are opens inclusions — fed to `mem_grothendieckTopology_iff`, and
then `le_iSup` at the index of the destructed point.

Note there is **no compatibility condition between different points**: `idx` is an arbitrary
function.  That is why chart-parameter heterogeneity (dat-b row, `Pic0ChartAtlasParamFree`)
costs nothing here — a supremum sieve never asks its members to agree. -/
theorem mem_zariskiTopology_iSup_of_pointwise {ι : Type u} {T : Scheme.{u}}
    (Sv : ι → Sieve T) (W : ↥T → T.Opens) (hW : ∀ t, t ∈ W t) (idx : ↥T → ι)
    (hmem : ∀ t, (Sv (idx t)).arrows (W t).ι) :
    (⨆ i, Sv i) ∈ Scheme.zariskiTopology T := by
  refine Scheme.mem_grothendieckTopology_iff.mpr
    ⟨Scheme.Cover.mkOfCovers (↥T) (fun t => (W t : Scheme.{u})) (fun t => (W t).ι)
      (fun t => ⟨t, ⟨t, hW t⟩, rfl⟩) (fun t => inferInstance), ?_⟩
  rintro V g ⟨t⟩
  exact le_iSup Sv (idx t) _ (hmem t)

/-! ## `ChartsCoverLocally` from what B-5 actually produces -/

variable (C) in
/-- **THE B-5 PACKAGING**: `ChartsCoverLocally` from pointwise coverage.

The hypothesis is exactly the shape the coverage geometry delivers, and is worth reading
field by field against `w4-datb` §1.2.  For every test `T`, every degree-zero class `s` on
it, and every point `t` of `T`:

* `W` — an open neighbourhood of `t`.  In the intended instantiation this is
  `chartLocusOpens` (`Pic0ChartUnivReduce.lean`), whose openness is CHART-U(b) and is
  unconditional since `IsSplitWitnessIsoInvariant` was discharged;
* `i` — the chart index, chosen *at `t`*.  Per-point by construction, which is what the
  I-0204 non-uniformity of the twist exponent `m` requires;
* `x` — a point of the `i`-th chart scheme over `W`, i.e. the divisor family the coverage
  argument produces at the splitting field of `κ(t)`;
* `hx` — that its class is `s` restricted to `W`.

Given that, the sieve condition holds.  So a coverage lane never has to mention `Sigma.desc`,
a coproduct of yoneda presheaves, a covering sieve, or a Grothendieck topology: it produces
four things at a point and this lemma does the rest.

**What this does not do.**  It does not produce the pointwise data — that is B-5's geometry
and its residue (the chart-parameter/threshold reconciliation) is recorded on the dat-b row.
It removes the site-theoretic layer between that geometry and B-6, which had never been
written down and which the row described as though it were already there. -/
theorem chartsCoverLocally_of_pointwise {ι : Type u} {X : ι → Scheme.{u}}
    (f : ∀ i, yoneda.obj (X i) ⟶ (pic0SigmaSheaf C).1)
    (h : ∀ (T : Scheme.{u}) (s : (pic0SigmaSheaf C).1.obj (op T)) (t : ↥T),
      ∃ (W : T.Opens) (_ : t ∈ W) (i : ι) (x : (W : Scheme.{u}) ⟶ X i),
        (f i).app (op (W : Scheme.{u})) x = (pic0SigmaSheaf C).1.map (W.ι).op s) :
    ChartsCoverLocally C f := by
  intro T s
  choose W hW i x hx using h T s
  exact mem_zariskiTopology_iSup_of_pointwise _ W hW i fun t => ⟨x t, hx t⟩

variable (C) in
/-- **B-5 ⟹ B-6 in one step**: pointwise coverage gives the local-surjectivity instance.

The composite of `chartsCoverLocally_of_pointwise` with `isLocallySurjective_sigmaDesc`.
Recorded because it is the statement a lane closing coverage wants to cite: the *only*
remaining input to the `[Presheaf.IsLocallySurjective Scheme.zariskiTopology (Sigma.desc f)]`
instance that three files carry as an unproduced `variable` is the pointwise data above. -/
theorem isLocallySurjective_sigmaDesc_of_pointwise {ι : Type u} {X : ι → Scheme.{u}}
    (f : ∀ i, yoneda.obj (X i) ⟶ (pic0SigmaSheaf C).1)
    (h : ∀ (T : Scheme.{u}) (s : (pic0SigmaSheaf C).1.obj (op T)) (t : ↥T),
      ∃ (W : T.Opens) (_ : t ∈ W) (i : ι) (x : (W : Scheme.{u}) ⟶ X i),
        (f i).app (op (W : Scheme.{u})) x = (pic0SigmaSheaf C).1.map (W.ι).op s) :
    Presheaf.IsLocallySurjective Scheme.zariskiTopology (Sigma.desc f) :=
  isLocallySurjective_sigmaDesc f (chartsCoverLocally_of_pointwise C f h)

/-! ## The converse: the pointwise form is not a strengthening

A reduction whose hypothesis is strictly stronger than its conclusion is a weakening in
disguise, and the memory `reduction-needs-its-converse` is about exactly this failure.  Here
the converse holds — modulo the one difference that is genuinely there and is named. -/

variable (C) in
/-- **`ChartsCoverLocally` gives back an open cover on whose members a chart hits `s`.**

The converse direction, and the check that the pointwise hypothesis above is the right one.
From the sieve condition one extracts a Zariski cover of `T` by `mem_grothendieckTopology_iff`
and reads the supremum membership at each cover map.

**The one honest difference**, and it is why this is stated with a general `Y ⟶ T` rather than
an open of `T`: `mem_grothendieckTopology_iff` returns a cover by *arbitrary* schemes with
open-immersion maps, not by opens of `T`.  Those are the same up to isomorphism
(`Scheme.Hom.isoOpensRange`) but not on the nose, so the converse produces a cover map where
the hypothesis consumed an opens inclusion.  For the purpose this serves — showing the
pointwise data is *available*, hence not a hypothesis chosen for provability — a cover map is
exactly as good, and pretending otherwise would need a transport that adds nothing. -/
theorem pointwise_of_chartsCoverLocally {ι : Type u} {X : ι → Scheme.{u}}
    (f : ∀ i, yoneda.obj (X i) ⟶ (pic0SigmaSheaf C).1)
    (h : ChartsCoverLocally C f) (T : Scheme.{u})
    (s : (pic0SigmaSheaf C).1.obj (op T)) :
    ∃ (𝒰 : T.Cover.{u} (Scheme.precoverage @IsOpenImmersion)),
      ∀ j : 𝒰.I₀, ∃ (i : ι) (x : 𝒰.X j ⟶ X i),
        (f i).app (op (𝒰.X j)) x = (pic0SigmaSheaf C).1.map (𝒰.f j).op s := by
  obtain ⟨𝒰, hle⟩ := Scheme.mem_grothendieckTopology_iff.mp (h T s)
  refine ⟨𝒰, fun j => ?_⟩
  have hj := hle (𝒰.X j) (𝒰.f j) (Presieve.ofArrows.mk j)
  rw [iSup, Sieve.sSup_apply] at hj
  obtain ⟨S, ⟨i, rfl⟩, x, hx⟩ := hj
  exact ⟨i, x, hx⟩

end

end AlgebraicGeometry
