/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.Algebra.Category.Grp.FilteredColimits
import Mathlib.Algebra.Homology.DerivedCategory.Ext.MapBijective
import Mathlib.AlgebraicGeometry.Morphisms.Separated
import Mathlib.CategoryTheory.Abelian.Injective.Ext
import AlgebraicJacobian.Cohomology.AffineSerreVanishing
import AlgebraicJacobian.Cohomology.HigherDirectImagePresheaf
import AlgebraicJacobian.Cohomology.AcyclicResolution

/-!
# Higher direct images along open immersions of affine opens

This file establishes `lem:open_immersion_pushforward_comp`:

1. `higherDirectImage_openImmersion_acyclic`: for an open immersion `j : U ↪ X` of an
   affine open `U` into a separated scheme `X`, the higher direct images `R^q j_* H` vanish
   for `q ≥ 1` and any quasi-coherent `O_U`-module `H`.

2. `higherDirectImage_openImmersion_comp` (pinned declaration): consequently, for any
   morphism `f : X ⟶ S` and quasi-coherent `H` on `U`, there is a canonical isomorphism
   `R^k f_*(j_* H) ≅ R^k (f ∘ j)_* H`.

Blueprint: `lem:open_immersion_pushforward_comp`.
Source: Stacks Project, Cohomology of Schemes, `lemma-relative-affine-vanishing`.
-/

universe u

open CategoryTheory Limits

/-! ## Project-local Mathlib supplement — reflecting `IsZero` through a faithful functor -/

namespace CategoryTheory.Functor

/-- **A faithful functor that preserves zero morphisms reflects the zero object.**
If `F` is faithful and preserves zero morphisms and `F.obj X` is a zero object, then `X`
is a zero object. (Three-line proof off `IsZero.iff_id_eq_zero` + `Functor.map_injective`.)

Project-local Mathlib supplement (category theory).  A copy of the same lemma in
`CechAugmentedResolution.lean`; reproduced here because that sibling file is not in this
file's import chain. -/
lemma isZero_of_faithful_preservesZeroMorphisms
    {C D : Type*} [Category C] [Category D] [Limits.HasZeroMorphisms C] [Limits.HasZeroMorphisms D]
    (F : C ⥤ D) [F.PreservesZeroMorphisms] [F.Faithful] {Y : C}
    (h : Limits.IsZero (F.obj Y)) : Limits.IsZero Y := by
  rw [Limits.IsZero.iff_id_eq_zero] at h ⊢
  apply F.map_injective
  rw [F.map_id, F.map_zero]
  exact h

end CategoryTheory.Functor

/-! ## Project-local Mathlib supplement — sheafification of a sectionwise-locally-zero presheaf -/

namespace CategoryTheory.GrothendieckTopology

open Opposite in
/-- **The sheafification of a presheaf whose sections are locally zero vanishes.**
If for every object `U` and every section `s : Q(U)` there is a covering sieve `S ∈ J U`
on which `s` restricts to `0`, then the sheafification of `Q` is a zero object.

This is the *sectionwise* (local-injectivity) strengthening of
`isZero_presheafToSheaf_of_locally_isZero`: that lemma requires the *objectwise* vanishing
`Q.obj (op V) = 0` for every member `V` of a single covering sieve, which forces the
vanishing to hold on a downward-closed family.  Here only the restricted *section* need
vanish, so the witnessing sieve can be generated by a cofinal *basis* of "good" opens
(e.g. the affine opens, where the section group vanishes) even though the basis itself is
not downward closed.  The local injectivity of `0 : Q ⟶ Z` (`Z` the constant zero
presheaf) is read off from the hypothesis applied to `x - y`; local surjectivity is free.
Project-local Mathlib supplement (site theory). -/
lemma isZero_presheafToSheaf_of_sections_locally_zero {C : Type u} [Category C]
    (J : GrothendieckTopology C) [HasSheafify J AddCommGrpCat.{u}]
    [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
    {Q : Cᵒᵖ ⥤ AddCommGrpCat.{u}}
    (h : ∀ (U : C) (s : ToType (Q.obj (op U))), ∃ S : Sieve U, S ∈ J U ∧
      ∀ ⦃V : C⦄ ⦃g : V ⟶ U⦄, S.arrows g → (ConcreteCategory.hom (Q.map g.op)) s = 0) :
    IsZero ((presheafToSheaf J AddCommGrpCat.{u}).obj Q) := by
  let Z : Cᵒᵖ ⥤ AddCommGrpCat.{u} := (Functor.const Cᵒᵖ).obj (AddCommGrpCat.of PUnit)
  have hZobj : ∀ x : Cᵒᵖ, IsZero (Z.obj x) := by
    intro x
    change IsZero (AddCommGrpCat.of PUnit)
    exact AddCommGrpCat.isZero_of_subsingleton _
  have hZ : IsZero Z := (Functor.isZero_iff Z).mpr hZobj
  haveI hli : Presheaf.IsLocallyInjective J (0 : Q ⟶ Z) := by
    refine ⟨?_⟩
    intro X x y _
    obtain ⟨S, hS, hSzero⟩ := h X.unop (x - y)
    apply J.superset_covering _ hS
    intro V g hg
    change (ConcreteCategory.hom (Q.map g.op)) x = (ConcreteCategory.hom (Q.map g.op)) y
    have h0 : (ConcreteCategory.hom (Q.map g.op)) (x - y) = 0 := hSzero hg
    rw [map_sub] at h0
    exact sub_eq_zero.mp h0
  haveI hls : Presheaf.IsLocallySurjective J (0 : Q ⟶ Z) := by
    refine ⟨?_⟩
    intro U s
    refine J.superset_covering (fun V g _ => ?_) (J.top_mem U)
    refine ⟨0, ?_⟩
    haveI : Subsingleton (Z.obj (op V)) := AddCommGrpCat.subsingleton_of_isZero (hZobj (op V))
    exact Subsingleton.elim _ _
  exact isZero_presheafToSheaf_obj_of_isLocallyBijective J (0 : Q ⟶ Z) hZ

end CategoryTheory.GrothendieckTopology

namespace AlgebraicGeometry

open Scheme.Modules Opposite

-- Re-activate the (file-local) `HasExt` instance from `AbsoluteCohomology.lean` so that the
-- `Ext`-based transport below resolves it without the slow `HasSmallLocalizedHom` search.
attribute [local instance] hasExtModules

variable {U X S : Scheme.{u}}

/-! ## Project-local Mathlib supplement — corepresentability of the sections functor

The sections functor `Γ(V, -)` on `X.Modules` is corepresented by the Form-B object
`jShriekOU V`.  Consequently its right derived functors agree, degreewise, with those of the
Hom-functor `Hom(jShriekOU V, -)` — the homological half of the identification
`Rᵠ Γ(V, -) ≅ Ext^q(jShriekOU V, -)` (the deep "Bridge (1)/(2)" connecting the higher-direct-image
presheaf homology to absolute cohomology). -/

/-- **Naturality of `jShriekOU_homEquiv` in the coefficient sheaf** (reproduced here; the version
in `AbsoluteCohomology.lean` is `private`). Composing a map `jShriekOU V ⟶ F₁` with `g : F₁ ⟶ F₂`
corresponds, under corepresentability, to applying `g` on sections over `V`. -/
private lemma jShriekOU_homEquiv_nat (V : TopologicalSpace.Opens X)
    {F₁ F₂ : X.Modules} (h : jShriekOU V ⟶ F₁) (g : F₁ ⟶ F₂) :
    jShriekOU_homEquiv V F₂ (h ≫ g)
      = (ConcreteCategory.hom (((Scheme.Modules.toPresheafOfModules X).map g).app (op V)))
          (jShriekOU_homEquiv V F₁ h) := by
  have hs : sheafificationHomAddEquiv V F₂ (h ≫ g)
        = sheafificationHomAddEquiv V F₁ h ≫ (Scheme.Modules.toPresheafOfModules X).map g :=
      (PresheafOfModules.sheafificationAdjunction
        (𝟙 X.ringCatSheaf.obj)).homEquiv_naturality_right h g
  change freeYonedaHomEquiv V _ (sheafificationHomAddEquiv V F₂ (h ≫ g)) = _
  rw [hs, freeYonedaHomEquiv_apply, PresheafOfModules.comp_app, ModuleCat.comp_apply]
  rfl

/-- `Scheme.Modules.toPresheafOfModules X` is additive (it is the additive composite
`forget ⋙ restrictScalars (𝟙)`). Project-local instance so `sectionsFunctor` is additive. -/
noncomputable instance toPresheafOfModules_additive :
    (Scheme.Modules.toPresheafOfModules X).Additive :=
  inferInstanceAs (SheafOfModules.forget X.ringCatSheaf ⋙
    PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).Additive

/-- The sections functor `Γ(V,-) : X.Modules ⥤ Ab` is additive. Project-local instance (the flat
triple composite does not infer additivity automatically). -/
noncomputable instance sectionsFunctor_additive (V : TopologicalSpace.Opens X) :
    (AlgebraicGeometry.sectionsFunctor V).Additive := by
  unfold AlgebraicGeometry.sectionsFunctor
  haveI i2 : (PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (op V)).Additive :=
    Functor.instAdditiveComp _ _
  exact Functor.instAdditiveComp _ _

/-- **The sections functor `Γ(V,-)` is corepresented by `jShriekOU V`.** A natural isomorphism
`sectionsFunctor V ≅ preadditiveCoyoneda.obj (op (jShriekOU V))`, assembled from the additive
corepresentability bijection `jShriekOU_homEquiv` and its naturality. Project-local: the functorial
upgrade of `jShriekOU_homEquiv`, the geometric input to the absolute-cohomology bridge. -/
noncomputable def sectionsFunctorCorepIso (V : TopologicalSpace.Opens X) :
    AlgebraicGeometry.sectionsFunctor V ≅ preadditiveCoyoneda.obj (op (jShriekOU V)) :=
  NatIso.ofComponents
    (fun F => (AddEquiv.toAddCommGrpIso (jShriekOU_homEquiv V F)).symm)
    (by
      intro F₁ F₂ g
      ext s
      simp only [AddEquiv.toAddCommGrpIso, comp_apply, Iso.symm_hom, AddCommGrpCat.hom_ofHom,
        AddEquiv.coe_toAddMonoidHom]
      rw [AddEquiv.symm_apply_eq]
      change (ConcreteCategory.hom ((AlgebraicGeometry.sectionsFunctor V).map g)) s
        = jShriekOU_homEquiv V F₂ ((jShriekOU_homEquiv V F₁).symm s ≫ g)
      rw [jShriekOU_homEquiv_nat V ((jShriekOU_homEquiv V F₁).symm s) g, AddEquiv.apply_symm_apply]
      rfl)

/-- **Right derived functors transport along a natural isomorphism of additive functors.**
Project-local: assembled from `NatTrans.rightDerived` of `τ.hom`/`τ.inv` and functoriality
(`NatTrans.rightDerived_comp`, `NatTrans.rightDerived_id`). -/
noncomputable def rightDerivedNatIso {C D : Type*} [Category C] [Category D] [Abelian C]
    [HasInjectiveResolutions C] [Abelian D] {F G : C ⥤ D} [F.Additive] [G.Additive]
    (τ : F ≅ G) (n : ℕ) : F.rightDerived n ≅ G.rightDerived n where
  hom := NatTrans.rightDerived τ.hom n
  inv := NatTrans.rightDerived τ.inv n
  hom_inv_id := by rw [← NatTrans.rightDerived_comp, τ.hom_inv_id, NatTrans.rightDerived_id]
  inv_hom_id := by rw [← NatTrans.rightDerived_comp, τ.inv_hom_id, NatTrans.rightDerived_id]

/-! ## Project-local Mathlib supplement — `Ext` transport along the spectrum equivalence (Need #1)

The whole-scheme spectrum isomorphism `U ≅ Spec Γ(U,𝒪)` (`Scheme.isoSpec`, a genuine iso because
`U` is affine) induces an *equivalence* of module categories `U.Modules ≌ (Spec Γ U).Modules`,
assembled from `Scheme.Modules.pushforward` along the iso and its coherences. An equivalence functor
is fully faithful, exact, and preserves injective objects, so
`Functor.mapExt_bijective_of_preservesInjectiveObjects` upgrades `Ext.mapExactFunctor` along it
to an *isomorphism* of `Ext`-groups. This transports the residual general-affine-open Serre
vanishing for `U` to the `Spec`-developed `affine_serre_vanishing_general_open`.

The pushforward-of-an-iso construction is generic in the scheme isomorphism `φ : X ≅ Y`. -/

/-- **A scheme isomorphism induces an equivalence of module categories.** For `φ : X ≅ Y`, the
pushforward `Scheme.Modules.pushforward φ.hom` is an equivalence with quasi-inverse the pushforward
along `φ.inv`; the unit/counit are supplied by the
`pushforwardId`/`pushforwardComp`/`pushforwardCongr` coherences. Project-local: Mathlib packages the
pushforward functor and its coherences but not the equivalence assembled from an iso (the genuine
equivalence used to transport `Ext` for Need #1). -/
noncomputable def Scheme.Modules.pushforwardEquivOfIso {X Y : Scheme.{u}} (φ : X ≅ Y) :
    X.Modules ≌ Y.Modules :=
  CategoryTheory.Equivalence.mk
    (Scheme.Modules.pushforward φ.hom) (Scheme.Modules.pushforward φ.inv)
    ((Scheme.Modules.pushforwardId X).symm ≪≫ Scheme.Modules.pushforwardCongr φ.hom_inv_id.symm ≪≫
      (Scheme.Modules.pushforwardComp φ.hom φ.inv).symm)
    (Scheme.Modules.pushforwardComp φ.inv φ.hom ≪≫ Scheme.Modules.pushforwardCongr φ.inv_hom_id ≪≫
      Scheme.Modules.pushforwardId Y)

/-- The functor of `pushforwardEquivOfIso φ` is (defeq) the additive `pushforward φ.hom`. -/
noncomputable instance pushforwardEquivOfIso_functor_additive {X Y : Scheme.{u}} (φ : X ≅ Y) :
    (Scheme.Modules.pushforwardEquivOfIso φ).functor.Additive :=
  inferInstanceAs (Scheme.Modules.pushforward φ.hom).Additive

/-- **`Ext` transport along a scheme isomorphism.** For `φ : X ≅ Y` and `A B : X.Modules`, the
equivalence `pushforwardEquivOfIso φ` (whose functor is fully faithful, exact, and injective-object
preserving) upgrades the additive map `Ext.mapExactFunctor` to an isomorphism of `Ext`-groups
`Ext A B n ≃+ Ext (φ_* A) (φ_* B) n`, via `Functor.mapExt_bijective_of_preservesInjectiveObjects`.
Project-local: the `Ext`-isomorphism half of Need #1 (the spectrum-equivalence transport). -/
noncomputable def Scheme.Modules.pushforwardExtAddEquiv {X Y : Scheme.{u}} (φ : X ≅ Y)
    [EnoughInjectives X.Modules] (A B : X.Modules) (n : ℕ) :
    CategoryTheory.Abelian.Ext A B n ≃+
      CategoryTheory.Abelian.Ext ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj A)
        ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj B) n :=
  AddEquiv.ofBijective ((Scheme.Modules.pushforwardEquivOfIso φ).functor.mapExtAddHom A B n)
    (Functor.mapExt_bijective_of_preservesInjectiveObjects
      (Scheme.Modules.pushforwardEquivOfIso φ).functor A B n)

/-- **Need #1 — `Ext` transport along the whole-scheme spectrum equivalence.** For an affine scheme
`U`, the canonical iso `U ≅ Spec Γ(U,𝒪)` (`Scheme.isoSpec`) induces, for every `q`, an isomorphism
`Ext^q_U(A, B) ≅ Ext^q_{Spec Γ U}(φ_* A, φ_* B)`. In particular the residual `Ext` over `U` vanishes
iff its transport over `Spec Γ U` does. Project-local target of `lem:modules_isoSpec_ext_transport`.

The remaining identification of the transported arguments — `φ_*(jShriekOU V) ≅ jShriekOU V'` for
`V'` the (affine) image open, and quasi-coherence of `φ_* H` — is handed off (see the task-result
file); it is orthogonal to this transport and is the geometric naturality of `j_!` under a scheme
iso. -/
noncomputable def modulesIsoSpecExtTransport (U : Scheme.{u}) [IsAffine U]
    [EnoughInjectives U.Modules] (A B : U.Modules) (n : ℕ) :
    CategoryTheory.Abelian.Ext A B n ≃+
      CategoryTheory.Abelian.Ext
        ((Scheme.Modules.pushforwardEquivOfIso U.isoSpec).functor.obj A)
        ((Scheme.Modules.pushforwardEquivOfIso U.isoSpec).functor.obj B) n :=
  Scheme.Modules.pushforwardExtAddEquiv U.isoSpec A B n

/-! ## Project-local Mathlib supplement — `Ext`-vanishing ⟹ coyoneda right-derived vanishing

The homological-algebra half of the relative-affine vanishing argument (Bridge (1)/(2) remainder).
The `q`-th right derived functor of the additive Hom-functor `Hom(P,-) = preadditiveCoyoneda(op P)`,
evaluated at `H`, is computed (via the chosen injective resolution `I•` of `H`,
`InjectiveResolution.isoRightDerivedObj`) as the homology at degree `q` of the cochain complex of
abelian groups `n ↦ (P ⟶ Iⁿ)`.  By `InjectiveResolution.extMk` / `extMk_eq_zero_iff`, that homology
*is* `Ext P H q`: a degree-`q` cocycle is a map `f : P ⟶ Iq` with `f ≫ d = 0`, and it is a
coboundary
iff the class `extMk f` vanishes in `Ext`.  Hence if every class of `Ext P H q` vanishes (`q ≥ 1`),
the Hom-complex is exact at `q` and the right-derived object is a zero object.  Project-local:
Mathlib's `Ext` is built on the derived category, not on `Functor.rightDerived`, so this bridge is
absent. -/

/-- The differential of the Hom-cochain-complex `n ↦ (P ⟶ Iⁿ)` (the image of a cochain complex `K`
under `preadditiveCoyoneda(op P)`) acts by post-composition with the differential of `K`. -/
private lemma preadditiveCoyoneda_mapHomologicalComplex_d_apply {C : Type*} [Category C]
    [Preadditive C] (P : C) (K : CochainComplex C ℕ) (i j : ℕ) (g : P ⟶ K.X i) :
    (((preadditiveCoyoneda.obj (op P)).mapHomologicalComplex (ComplexShape.up ℕ)).obj K).d i j g
      = g ≫ K.d i j := by
  rw [Functor.mapHomologicalComplex_obj_d]
  rfl

/-- **`Ext`-vanishing forces the coyoneda right-derived object to vanish.** If every class of
`Ext P H q` is zero (`q ≥ 1`), then `(Hom(P,-)).rightDerived q` is a zero object at `H`. The
homological-algebra bridge between the project's `Ext`-based Serre vanishing and the
`Functor.rightDerived` description of the higher-direct-image presheaf homology. Project-local. -/
lemma isZero_coyoneda_rightDerived_of_forall_ext_eq_zero {C : Type*} [Category C]
    [Abelian C] [HasInjectiveResolutions C] [CategoryTheory.HasExt C] (P H : C) (q : ℕ) (hq : 0 < q)
    (hExt : ∀ e : CategoryTheory.Abelian.Ext P H q, e = 0) :
    IsZero (((preadditiveCoyoneda.obj (op P)).rightDerived q).obj H) := by
  obtain ⟨p, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hq.ne'
  refine IsZero.of_iso ?_ ((injectiveResolution H).isoRightDerivedObj
    (preadditiveCoyoneda.obj (op P)) (p + 1))
  set R := injectiveResolution H with hR
  refine HomologicalComplex.ExactAt.isZero_homology ?_
  rw [HomologicalComplex.exactAt_iff' _ p (p + 1) (p + 2) (by simp) (by simp),
    ShortComplex.ab_exact_iff]
  intro x₂ hx₂
  have hf : x₂ ≫ R.cocomplex.d (p + 1) (p + 2) = 0 := by
    rw [← preadditiveCoyoneda_mapHomologicalComplex_d_apply P R.cocomplex (p + 1) (p + 2) x₂]
    exact hx₂
  obtain ⟨g, hg⟩ := (R.extMk_eq_zero_iff x₂ (p + 2) rfl hf p rfl).mp (hExt _)
  refine ⟨g, ?_⟩
  rw [← hg]
  exact preadditiveCoyoneda_mapHomologicalComplex_d_apply P R.cocomplex p (p + 1) g

/-- **`[HasInjectiveResolutions C]` provides enough injectives.** The degree-`0` term of the chosen
injective resolution, with its quasi-iso unit, is an injective presentation. Project-local connector
(Mathlib derives `HasInjectiveResolutions` from `EnoughInjectives` + `Abelian`, not conversely);
needed to feed `[EnoughInjectives U.Modules]` to the spectrum `Ext`-transport from
`[HasInjectiveResolutions U.Modules]`. -/
lemma enoughInjectives_of_hasInjectiveResolutions {C : Type*} [Category C] [Abelian C]
    [HasInjectiveResolutions C] : EnoughInjectives C where
  presentation X := by
    obtain ⟨R⟩ := (HasInjectiveResolutions.out X).out
    exact ⟨{ J := R.cocomplex.X 0, injective := R.injective 0, f := R.ι.f 0
             mono := CategoryTheory.InjectiveResolution.instMonoFNatι R 0 }⟩

/-- **An isomorphism in the first `Ext`-argument transfers subsingletons.** If `Ext B Y q` is a
subsingleton and `φ : A ≅ B`, then so is `Ext A Y q` (every class is the `φ.hom`-precomposite of its
`φ.inv`-precomposite, which vanishes). Project-local: the contravariant `Ext`-functoriality packaged
for the Serre-vanishing transport along the `jShriekOU` transport iso. -/
lemma subsingleton_ext_of_iso_fst {C : Type*} [Category C] [Abelian C] [CategoryTheory.HasExt C]
    {A B : C} (φ : A ≅ B) (Y : C) (q : ℕ)
    [Subsingleton (CategoryTheory.Abelian.Ext B Y q)] :
    Subsingleton (CategoryTheory.Abelian.Ext A Y q) := by
  refine ⟨fun a b => ?_⟩
  suffices h : ∀ z : CategoryTheory.Abelian.Ext A Y q, z = 0 by rw [h a, h b]
  intro z
  have hw : (Abelian.Ext.mk₀ φ.inv).comp z (zero_add q) = 0 := Subsingleton.elim _ _
  have hz : z = (Abelian.Ext.mk₀ φ.hom).comp
      ((Abelian.Ext.mk₀ φ.inv).comp z (zero_add q)) (zero_add q) := by
    rw [Abelian.Ext.mk₀_comp_mk₀_assoc, φ.hom_inv_id, Abelian.Ext.mk₀_id_comp]
  rw [hz, hw, Abelian.Ext.comp_zero]

/-- **Serre `Ext`-vanishing over an affine scheme via the spectrum transport.** Let `U` be a scheme,
`φ : U ≅ Spec R` a scheme isomorphism, `V ⊆ U` an open and `H` an `𝒪_U`-module.  If the pushforward
`Φ(j_!𝒪_V)` of the corepresenting object is isomorphic to `j_!𝒪_{V'}` for an *affine* open
`V' ⊆ Spec R`, and `Φ H` is quasi-coherent, then every class of `Ext^q_U(j_!𝒪_V, H)` vanishes for
`q ≥ 1`.  Assembled from `pushforwardExtAddEquiv` (the spectrum transport), the contravariant
`Ext`-transfer `subsingleton_ext_of_iso_fst`, and the now-unconditional
`affine_serre_vanishing_general_open` on `Spec R`.  Project-local: the Bridge (2) Serre-vanishing
leaf of the open-immersion acyclicity, parameterized over the geometric transport data so that the
residual `jShriekOU`/quasi-coherence transport sub-lemmas are isolated. -/
lemma ext_jShriekOU_eq_zero_of_specIso {R : CommRingCat.{u}} (U : Scheme.{u})
    [HasInjectiveResolutions U.Modules] (φ : U ≅ Spec R) (V : U.Opens) (H : U.Modules)
    (q : ℕ) (hq : 0 < q) (V' : (Spec R).Opens) (hV' : IsAffineOpen V')
    (hjt : (Scheme.Modules.pushforwardEquivOfIso φ).functor.obj (jShriekOU V) ≅ jShriekOU V')
    (hqc : ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).IsQuasicoherent)
    (e : Abelian.Ext (jShriekOU V) H q) : e = 0 := by
  haveI : EnoughInjectives U.Modules := enoughInjectives_of_hasInjectiveResolutions
  set Φ := Scheme.Modules.pushforwardEquivOfIso φ with hΦ
  haveI : EnoughInjectives (Spec R).Modules := EnoughInjectives.of_equivalence Φ.inverse
  haveI : (Φ.functor.obj H).IsQuasicoherent := hqc
  haveI hsub0 : Subsingleton (Abelian.Ext (jShriekOU V') (Φ.functor.obj H) q) :=
    ⟨fun a b => (affine_serre_vanishing_general_open _ V' hV' q hq a).trans
      (affine_serre_vanishing_general_open _ V' hV' q hq b).symm⟩
  haveI hsub1 : Subsingleton (Abelian.Ext (Φ.functor.obj (jShriekOU V)) (Φ.functor.obj H) q) :=
    subsingleton_ext_of_iso_fst hjt (Φ.functor.obj H) q
  have htr := Scheme.Modules.pushforwardExtAddEquiv φ (jShriekOU V) H q
  exact htr.injective (Subsingleton.elim (htr e) (htr 0))

/-! ## Project-local Mathlib supplement — `jShriekOU` transport along a scheme iso (Need #1)

The corepresenting object `jShriekOU V` of `Γ(V,-)` is carried along a scheme isomorphism
`φ : X ≅ Y` by the induced pushforward equivalence:
`Φ.functor (jShriekOU V) ≅ jShriekOU (φ.inv⁻¹V)`.
The argument is pure corepresentability transport — `jShriekOU V` is never unfolded.  Both sides
corepresent the *same* `Type`-valued sections functor `Γ(φ.inv⁻¹V,-)`: the right side directly (the
additive corepresentability `jShriekOU_homEquiv`), the left side via the pushforward adjunction
(`Φ.functor ⊣ Φ.inverse`) composed with the definitional identity "sections of a pushforward =
sections over the preimage open".  `CorepresentableBy.uniqueUpToIso` then produces the iso. -/

/-- **`jShriekOU V` corepresents the `Type`-valued sections functor `Γ(V,-)`.**  Repackages the
additive corepresentability `jShriekOU_homEquiv` as a `CorepresentableBy` of `sectionsFunctor V`
post-composed with the forgetful functor to types. Project-local. -/
private noncomputable def sectionsCorep {X : Scheme.{u}} (V : TopologicalSpace.Opens X) :
    (sectionsFunctor V ⋙ forget AddCommGrpCat).CorepresentableBy (jShriekOU V) where
  homEquiv {B} := (jShriekOU_homEquiv V B).toEquiv
  homEquiv_comp g f := jShriekOU_homEquiv_nat V f g

/-- **The pushforward of `jShriekOU V` corepresents `Γ(φ.inv⁻¹V,-)`.**  Via the pushforward
adjunction `Φ.functor ⊣ Φ.inverse` and the definitional identity "sections of `φ.inv`-pushforward
over `V` = sections over `φ.inv⁻¹V`", the object `Φ.functor (jShriekOU V)` corepresents the same
`Type`-valued sections functor as `jShriekOU (φ.inv⁻¹V)`.  Project-local. -/
private noncomputable def sectionsCorepPushforward {X Y : Scheme.{u}} (φ : X ≅ Y)
    (V : TopologicalSpace.Opens X) :
    (sectionsFunctor (φ.inv ⁻¹ᵁ V) ⋙ forget AddCommGrpCat).CorepresentableBy
      ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj (jShriekOU V)) where
  homEquiv {B} :=
    ((Scheme.Modules.pushforwardEquivOfIso φ).toAdjunction.homEquiv (jShriekOU V) B).trans
      (jShriekOU_homEquiv V ((Scheme.Modules.pushforwardEquivOfIso φ).inverse.obj B)).toEquiv
  homEquiv_comp {B B'} g f := by
    simp only [Equiv.trans_apply]
    rw [(Scheme.Modules.pushforwardEquivOfIso φ).toAdjunction.homEquiv_naturality_right]
    erw [jShriekOU_homEquiv_nat V
      ((Scheme.Modules.pushforwardEquivOfIso φ).toAdjunction.homEquiv (jShriekOU V) B f)
      ((Scheme.Modules.pushforwardEquivOfIso φ).inverse.map g)]

/-- **A scheme isomorphism carries `jShriekOU` along** (blueprint
`lem:jshriek_transport_along_iso`). For `φ : X ≅ Y` and an open `V ⊆ X`, the pushforward
equivalence sends the corepresenting object of
`Γ(V,-)` to that of `Γ(φ.inv⁻¹V,-)`:
`Φ.functor (jShriekOU V) ≅ jShriekOU (φ.inv⁻¹V)`.  Project-local: the geometric naturality
of `j_!` under a scheme iso (the first-`Ext`-argument transport of Need #1). -/
noncomputable def jShriekOU_transport_along_iso {X Y : Scheme.{u}} (φ : X ≅ Y)
    (V : TopologicalSpace.Opens X) :
    (Scheme.Modules.pushforwardEquivOfIso φ).functor.obj (jShriekOU V) ≅
      jShriekOU (φ.inv ⁻¹ᵁ V) :=
  (sectionsCorepPushforward φ V).uniqueUpToIso (sectionsCorep (φ.inv ⁻¹ᵁ V))

/-! ## Project-local Mathlib supplement — quasi-coherence transport along a scheme iso (`hqc`) -/

/-- **A scheme isomorphism transports an open cover.** If a family `Z` of opens covers `X`
(in the sense of the opens Grothendieck topology, i.e. `CoversTop`), then the preimage family
`φ.inv ⁻¹ᵁ (Z i)` covers `Y`.  Project-local: the cover-transport half of
`pushforward_iso_preserves_qcoh` (Need #1 `hqc`). -/
private lemma coversTop_preimage_of_iso {X Y : Scheme.{u}} (φ : X ≅ Y) {I : Type*}
    (Z : I → X.Opens) (hZ : (Opens.grothendieckTopology X).CoversTop Z) :
    (Opens.grothendieckTopology Y).CoversTop (fun i => φ.inv ⁻¹ᵁ Z i) := by
  intro W x hx
  obtain ⟨U', f, hf, hU'⟩ := hZ ⊤ (φ.inv.base x) (by trivial)
  obtain ⟨i, ⟨g⟩⟩ := hf
  have hxZ : φ.inv.base x ∈ Z i := (leOfHom g) hU'
  refine ⟨W ⊓ (φ.inv ⁻¹ᵁ Z i), homOfLE inf_le_left,
    ⟨i, ⟨homOfLE inf_le_right⟩⟩, ⟨hx, ?_⟩⟩
  exact hxZ

set_option synthInstance.maxHeartbeats 1000000 in
-- `of_coversTop` synthesizes instances for doubly sliced opens beyond the default budget.
set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 2000000 in
-- The heartbeat bumps are required: `SheafOfModules.IsQuasicoherent.of_coversTop` triggers
-- synthesis of the doubly-sliced opens `HasSheafify`/`WEqualsLocallyBijective` instances
-- `((J.over X).over Y)…`, whose default-heartbeat search times out (it succeeds when bumped).
/-- **Reduction of quasi-coherence of an iso-pushforward to the per-slice case** (Need #1 `hqc`,
`of_coversTop` wiring). Given a quasi-coherence datum `q` for `H` and quasi-coherence of the
restricted pushforward `(φ_* H).over (φ.inv ⁻¹ᵁ (q.X i))` over each preimage cover member, the
pushforward `φ_* H` is quasi-coherent.  Project-local: wires Mathlib's
`IsQuasicoherent.of_coversTop` to the cover-transport `coversTop_preimage_of_iso`, isolating the
residual per-slice obligation. -/
lemma pushforward_iso_qcoh_of_slice_qcoh {X Y : Scheme.{u}} (φ : X ≅ Y) (H : X.Modules)
    (q : SheafOfModules.QuasicoherentData.{u, u, u, u} H)
    (hslice : ∀ i, (((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).over
        (φ.inv ⁻¹ᵁ q.X i)).IsQuasicoherent) :
    ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).IsQuasicoherent := by
  haveI : ∀ i, (((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).over
      (φ.inv ⁻¹ᵁ q.X i)).IsQuasicoherent := hslice
  exact SheafOfModules.IsQuasicoherent.of_coversTop
    ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H) (fun i => φ.inv ⁻¹ᵁ q.X i)
    (coversTop_preimage_of_iso φ q.X q.coversTop)

/-! ## Project-local Mathlib supplement — the slice structure-sheaf ring map `ψ_r` (Need #1 `hqc`)

The genuine wall of `hqc`: a single cross-ring slice structure-sheaf ring map `ψ_r` from which the
colimit-preserving `SheafOfModules.pullback ψ_r` is built.  For a scheme iso `φ : X ≅ Y` and an open
`Uᵢ ⊆ X` with image `Vᵢ = φ.inv⁻¹ᵁ Uᵢ ⊆ Y`, the underlying opens-equivalence functor is
`F₀ = Opens.map φ.inv.base : Opens X ⥤ Opens Y` (sending `Uᵢ` to `Vᵢ` by `rfl`).  Its slice version
`Over.post F₀ : Over Uᵢ ⥤ Over Vᵢ` is continuous and final (both because `F₀` is an equivalence,
`φ` being an iso).  The map `ψ_r` is the slice of the structure-sheaf comparison
`φ.inv.toRingCatSheafHom : 𝒪_X ⟶ (F₀.sheafPushforwardContinuous _ _ _).obj 𝒪_Y`, obtained simply by
applying the over-pullback functor `(Opens.grothendieckTopology X).overPullback RingCat Uᵢ`; the
codomain matches the desired sliced pushforward by the Beck–Chevalley identity
`Over.post F₀ ⋙ Over.forget Vᵢ = Over.forget Uᵢ ⋙ F₀` (`rfl`). -/

section SlicePsi

open TopologicalSpace

variable {X Y : Scheme.{u}} (φ : X ≅ Y) (Ui : X.Opens)

/-- `Opens.map φ.inv.base` is an equivalence (its base is the homeomorphism underlying `φ`).
Project-local instance feeding the continuity and finality of the slice functor `Over.post`. -/
instance opensMapInvBase_isEquivalence : (Opens.map φ.inv.base).IsEquivalence :=
  inferInstanceAs (Opens.mapMapIso (Scheme.forgetToTop.mapIso φ).symm).functor.IsEquivalence

/-- The slice functor `Over.post (Opens.map φ.inv.base) : Over Uᵢ ⥤ Over Vᵢ` is continuous for the
over-Grothendieck-topologies.  Project-local: from `coverPreserving_opens_map` lifted to the slices
via `CoverPreserving.overPost`, plus `compatiblePreservingOfFlat` (the slice functor is flat, being
an equivalence). -/
instance overPost_slice_isContinuous :
    (Over.post (X := Ui) (Opens.map φ.inv.base)).IsContinuous
      ((Opens.grothendieckTopology X).over Ui)
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui)) :=
  Functor.isContinuous_of_coverPreserving
    (compatiblePreservingOfFlat _ _)
    (CoverPreserving.overPost Ui (coverPreserving_opens_map φ.inv.base))

set_option linter.style.longLine false in
/-- **The slice structure-sheaf ring map `ψ_r`** (blueprint `lem:slice_structureSheaf_hom`).  The
over-pullback (to the slice `Over Uᵢ`) of the structure-sheaf comparison `φ.inv.toRingCatSheafHom`.
Its codomain is the sliced pushforward of `𝒪_Y` along `Over.post (Opens.map φ.inv.base)`, identified
with the over-pullback of the un-sliced pushforward by the Beck–Chevalley `rfl`-equality
`Over.post F ⋙ Over.forget = Over.forget ⋙ F`.  Project-local: the single cross-ring datum from
which `SheafOfModules.pullback ψ_r` (Need #1 `hqc`) is built. -/
noncomputable def sliceStructureSheafHom : (X.ringCatSheaf.over Ui) ⟶
    ((Over.post (X := Ui) (Opens.map φ.inv.base)).sheafPushforwardContinuous RingCat
      ((Opens.grothendieckTopology X).over Ui)
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui))).obj
        (Y.ringCatSheaf.over (φ.inv ⁻¹ᵁ Ui)) :=
  ((Opens.grothendieckTopology X).overPullback RingCat Ui).map (φ.inv.toRingCatSheafHom)

/-- The presheaf-of-modules pushforward along `ψ_r.hom` admits a right adjoint (the categories are
small).  Project-local instance feeding the sheaf-level right-adjointness. -/
instance sliceStructureSheafHom_pre_isRightAdjoint :
    (PresheafOfModules.pushforward.{u} (sliceStructureSheafHom φ Ui).hom).IsRightAdjoint :=
  Functor.isRightAdjoint_of_leftAdjointObjIsDefined_eq_top
    (PresheafOfModules.pullbackObjIsDefined_eq_top.{u} (sliceStructureSheafHom φ Ui).hom)

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 4000000 in
-- Constructing the sheaf-level adjoint from the presheaf adjoint exceeds the default budget.
set_option synthInstance.maxHeartbeats 2000000 in
-- The heartbeat bumps are required: the derivation triggers synthesis of the sliced-site
-- `HasWeakSheafify`/`WEqualsLocallyBijective` instances for `(gt Y).over Vᵢ`, whose
-- default-heartbeat search times out (it succeeds when bumped).
/-- **`SheafOfModules.pushforward ψ_r` admits a right adjoint** — the obligation that makes the
left-adjoint pullback `SheafOfModules.pullback ψ_r` available (blueprint
`lem:slice_structureSheaf_hom`, the `IsRightAdjoint` clause).  Project-local instance. -/
instance sliceStructureSheafHom_isRightAdjoint :
    (SheafOfModules.pushforward.{u} (sliceStructureSheafHom φ Ui)).IsRightAdjoint :=
  inferInstance

end SlicePsi

/-! ## Project-local Mathlib supplement — slice equivalence for `φ : X ≅ Y` and its continuity

The slice equivalence `Over Uᵢ ≌ Over Vᵢ` (`Vᵢ = φ.inv⁻¹ᵁ Uᵢ`) induced by a scheme iso `φ`, with
BOTH its forward and inverse slice functors shown continuous for the over-Grothendieck-topologies.
These are the site-equivalence inputs (continuity instances) required by
`SheafOfModules.pushforwardPushforwardAdj` / `pushforwardPushforwardEquivalence` to build the
two-pushforward slice adjunction (blueprint `lem:pushforward_slice_two_adjunction`, the `hqc` wall).
The inverse continuity carries the `Over.post (Opens.map φ.hom.base) ⋙ Over.map (unitIso.inv)`
correction; `Over.map` is always continuous (`instIsContinuousOverMapOver`) and the post-factor is
cover-preserving via `coverPreserving_opens_map φ.hom.base`. -/
section SliceTwoAdj

open TopologicalSpace

variable {X Y : Scheme.{u}} (φ : X ≅ Y) (Ui : X.Opens)

/-- `Opens.map φ.hom.base` is an equivalence (twin of `opensMapInvBase_isEquivalence`). -/
instance opensMapHomBase_isEquivalence : (Opens.map φ.hom.base).IsEquivalence :=
  inferInstanceAs (Opens.mapMapIso (Scheme.forgetToTop.mapIso φ)).functor.IsEquivalence

/-- The opens-equivalence `Opens X ≌ Opens Y` induced by the scheme iso `φ`.  Built from
`mapMapIso` so that its `functor` is (defeq) `Opens.map φ.inv.base` and its `inverse` is (defeq)
`Opens.map φ.hom.base` — both honest `Opens.map`s, with known continuity. -/
noncomputable def opensEquivOfIso : TopologicalSpace.Opens X ≌ TopologicalSpace.Opens Y :=
  Opens.mapMapIso (Scheme.forgetToTop.mapIso φ).symm

/-- The slice equivalence `Over Uᵢ ≌ Over Vᵢ` (`Vᵢ = φ.inv⁻¹ᵁ Uᵢ`). -/
noncomputable def sliceOversEquiv :
    CategoryTheory.Over Ui ≌ CategoryTheory.Over (φ.inv ⁻¹ᵁ Ui) :=
  CategoryTheory.Over.postEquiv Ui (opensEquivOfIso φ)

/-- Continuity of the forward slice functor (it is `Over.post (Opens.map φ.inv.base)`). -/
instance sliceOversEquiv_functor_isContinuous :
    (sliceOversEquiv φ Ui).functor.IsContinuous
      ((Opens.grothendieckTopology X).over Ui)
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui)) :=
  overPost_slice_isContinuous φ Ui

/-- Continuity of the post-functor along the opens-equivalence inverse `(opensEquivOfIso φ).inverse`
(defeq `Opens.map φ.hom.base`), the first factor of the inverse slice functor.  Stated in the
`postEquiv`-native syntax (`Vᵢ = (opensEquivOfIso φ).functor.obj Uᵢ`) so the composite below matches
the goal coming out of `Over.postEquiv_inverse`. -/
instance overPost_slice_inverse_isContinuous :
    (Over.post (X := (opensEquivOfIso φ).functor.obj Ui) (opensEquivOfIso φ).inverse).IsContinuous
      ((Opens.grothendieckTopology Y).over ((opensEquivOfIso φ).functor.obj Ui))
      ((Opens.grothendieckTopology X).over
        ((opensEquivOfIso φ).inverse.obj ((opensEquivOfIso φ).functor.obj Ui))) :=
  Functor.isContinuous_of_coverPreserving
    (compatiblePreservingOfFlat _ _)
    (CoverPreserving.overPost ((opensEquivOfIso φ).functor.obj Ui)
      (coverPreserving_opens_map φ.hom.base))

/-- Continuity of the inverse slice functor `eqv.inverse = Over.post (Opens.map φ.hom.base) ⋙
Over.map (unitIso.inv)`, the correction-carrying composite. -/
instance sliceOversEquiv_inverse_isContinuous :
    (sliceOversEquiv φ Ui).inverse.IsContinuous
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui))
      ((Opens.grothendieckTopology X).over Ui) := by
  have key : ((Over.post (X := (opensEquivOfIso φ).functor.obj Ui) (opensEquivOfIso φ).inverse).comp
      (Over.map ((opensEquivOfIso φ).unitIso.inv.app Ui))).IsContinuous
      ((Opens.grothendieckTopology Y).over ((opensEquivOfIso φ).functor.obj Ui))
      ((Opens.grothendieckTopology X).over Ui) :=
    @Functor.isContinuous_comp _ _ _ _ _ _
      (Over.post (X := (opensEquivOfIso φ).functor.obj Ui) (opensEquivOfIso φ).inverse)
      (Over.map ((opensEquivOfIso φ).unitIso.inv.app Ui))
      ((Opens.grothendieckTopology Y).over ((opensEquivOfIso φ).functor.obj Ui))
      ((Opens.grothendieckTopology X).over
        ((opensEquivOfIso φ).inverse.obj ((opensEquivOfIso φ).functor.obj Ui)))
      ((Opens.grothendieckTopology X).over Ui)
      (overPost_slice_inverse_isContinuous φ Ui)
      (GrothendieckTopology.instIsContinuousOverMapOver (Opens.grothendieckTopology X)
        ((opensEquivOfIso φ).unitIso.inv.app Ui))
  rw [sliceOversEquiv, Over.postEquiv_inverse]
  exact key

/-- **The reverse slice ring map `φ''`** (blueprint `lem:slice_reverse_ring_map`).  The cross-ring
structure-sheaf comparison along the *corrected* inverse slice functor
`(sliceOversEquiv φ Ui).inverse`.  Object-level it is the slice restriction of
`φ.hom.toRingCatSheafHom`; the `Over.map (unitIso.inv)` correction affects only the morphism action
(absorbed by `H₁`/`H₂`).  Built as the over-pullback of `φ.hom.toRingCatSheafHom` transported along
the codomain iso induced by `unitIso.inv : φ.hom⁻¹ᵁ Vᵢ ≅ Uᵢ`. -/
noncomputable def sliceReverseRingMap :
    (Y.ringCatSheaf.over (φ.inv ⁻¹ᵁ Ui)) ⟶
      ((sliceOversEquiv φ Ui).inverse.sheafPushforwardContinuous RingCat
        ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui))
        ((Opens.grothendieckTopology X).over Ui)).obj
          (X.ringCatSheaf.over Ui) :=
  -- φ'' = the over-pullback of `φ.hom.toRingCatSheafHom` (blueprint-correct), i.e.
  -- `sliceStructureSheafHom φ.symm Vᵢ`.  It is stated along the BARE
  -- `Over.post (Opens.map φ.symm.inv.base)` in `Over (φ.symm.inv⁻¹ᵁ Vᵢ)`, but its codomain is
  -- *definitionally equal* to the codomain along the correction-carrying inverse slice functor
  -- `eqv.inverse = Over.post (Opens.map φ.symm.inv.base) ⋙ Over.map (unitIso.inv.app Uᵢ)`:
  -- both `sheafPushforwardContinuousComp` (composition of pushforward-continuous functors is
  -- `Iso.refl`) and `Over.mapForget` (`map g ⋙ forget = forget`, `rfl`) are definitional, so the
  -- "codomain bridge" of the blueprint reduces to the identity and is absorbed here by defeq.
  sliceStructureSheafHom φ.symm (φ.inv ⁻¹ᵁ Ui)

/-- **Counit compatibility square `H₁`** for the slice adjunction (blueprint
`lem:pushforward_slice_adjunction_h1`).  The reverse ring map `φ''` and the forward slice ring map
`ψ_r` satisfy the counit-naturality square required by `pushforwardPushforwardAdj`, absorbing the
`Over.map (unitIso.inv)` correction of the inverse functor (reduces to a proof-irrelevant
equality-transport identity along `φ.hom⁻¹ᵁ (φ.inv⁻¹ᵁ Uᵢ) = Uᵢ`). -/
lemma pushforwardSliceAdjunctionH1 :
    Functor.whiskerRight (NatTrans.op (sliceOversEquiv φ Ui).symm.toAdjunction.counit)
        (Sheaf.over X.ringCatSheaf Ui).obj =
      (sliceStructureSheafHom φ Ui).hom ≫
        (sliceOversEquiv φ Ui).symm.inverse.op.whiskerLeft (sliceReverseRingMap φ Ui).hom := by
  ext U x
  simp only [sliceReverseRingMap, sliceStructureSheafHom]
  simp only [Equivalence.toAdjunction_counit, Equivalence.symm_counit,
    Functor.whiskerRight_app, NatTrans.op_app, Functor.id_obj,
    Functor.sheafPushforwardContinuous_obj_obj_map, Over.forget_obj, Over.forget_map,
    ObjectProperty.ι_obj, Iso.symm_inv, NatTrans.comp_app,
    Functor.sheafPushforwardContinuous_map_hom_app, Functor.whiskerLeft_app]
  -- The two structure-sheaf comparisons `φ.inv.c` and `φ.hom.c` compose to the restriction of
  -- `𝒪_X` along the identity `φ.hom⁻¹ᵁ φ.inv⁻¹ᵁ W = W`
  -- (`comp_app` + `congr_app φ.hom_inv_id`).
  have key : φ.inv.c.app (op ((unop U).left)) ≫
      φ.hom.c.app (op (((sliceOversEquiv φ Ui).functor.obj (unop U)).left))
      = X.sheaf.obj.map (Over.Hom.left ((sliceOversEquiv φ Ui).unitInv.app (unop U))).op := by
    change φ.inv.app ((unop U).left) ≫ φ.hom.app _ = _
    rw [← Scheme.Hom.comp_app, Scheme.Hom.congr_app φ.hom_inv_id]
    simp only [Scheme.Hom.id_app]
    congr 1
  have key2 : (forget₂ CommRingCat RingCat).map (φ.inv.c.app (op ((unop U).left))) ≫
      (forget₂ CommRingCat RingCat).map
        (φ.hom.c.app (op (((sliceOversEquiv φ Ui).functor.obj (unop U)).left)))
      = (forget₂ CommRingCat RingCat).map
        (X.sheaf.obj.map (Over.Hom.left ((sliceOversEquiv φ Ui).unitInv.app (unop U))).op) := by
    rw [← (forget₂ CommRingCat RingCat).map_comp]
    exact congrArg _ key
  exact DFunLike.congr_fun (congrArg RingCat.Hom.hom key2.symm) x

/-- **Unit compatibility square `H₂`** for the slice adjunction (blueprint
`lem:pushforward_slice_adjunction_h2`).  Identical in shape to `H₁`: the unit triangle reduces to a
proof-irrelevant equality-transport identity along the same open identity. -/
lemma pushforwardSliceAdjunctionH2 :
    (sliceReverseRingMap φ Ui).hom ≫
        (sliceOversEquiv φ Ui).symm.functor.op.whiskerLeft (sliceStructureSheafHom φ Ui).hom ≫
          Functor.whiskerRight (NatTrans.op (sliceOversEquiv φ Ui).symm.toAdjunction.unit)
            (Sheaf.over Y.ringCatSheaf (φ.inv ⁻¹ᵁ Ui)).obj =
      𝟙 (Sheaf.over Y.ringCatSheaf (φ.inv ⁻¹ᵁ Ui)).obj := by
  ext U x
  simp only [sliceReverseRingMap, sliceStructureSheafHom]
  simp only [Iso.symm_inv, ObjectProperty.ι_obj, Equivalence.toAdjunction_unit,
    Equivalence.symm_unit, NatTrans.comp_app,
    Functor.sheafPushforwardContinuous_map_hom_app, Over.forget_obj,
    Functor.whiskerLeft_app, Functor.whiskerRight_app, NatTrans.op_app,
    Functor.id_obj, Functor.sheafPushforwardContinuous_obj_obj_map,
    Over.forget_map, RingCat.hom_comp, RingHom.coe_comp,
    Function.comp_apply, NatTrans.id_app]
  have key : φ.hom.c.app (op ((unop U).left)) ≫
      φ.inv.c.app (op (((sliceOversEquiv φ Ui).inverse.obj (unop U)).left)) ≫
        Y.sheaf.obj.map (Over.Hom.left ((sliceOversEquiv φ Ui).counitInv.app (unop U))).op
      = 𝟙 (Y.sheaf.obj.obj (op ((unop U).left))) := by
    rw [← Category.assoc,
      show φ.hom.c.app (op ((unop U).left)) ≫
          φ.inv.c.app (op (((sliceOversEquiv φ Ui).inverse.obj (unop U)).left))
          = (φ.inv ≫ φ.hom).app ((unop U).left) from (Scheme.Hom.comp_app φ.inv φ.hom _).symm,
      Scheme.Hom.congr_app φ.inv_hom_id]
    erw [Category.id_comp, ← CategoryTheory.Functor.map_comp]
    exact (congrArg Y.presheaf.map (Subsingleton.elim _ _)).trans
      (CategoryTheory.Functor.map_id Y.presheaf _)
  have key2 : (forget₂ CommRingCat RingCat).map (φ.hom.c.app (op ((unop U).left))) ≫
      (forget₂ CommRingCat RingCat).map
        (φ.inv.c.app (op (((sliceOversEquiv φ Ui).inverse.obj (unop U)).left))) ≫
      (forget₂ CommRingCat RingCat).map
        (Y.sheaf.obj.map (Over.Hom.left ((sliceOversEquiv φ Ui).counitInv.app (unop U))).op)
      = 𝟙 _ := by
    rw [← CategoryTheory.Functor.map_comp, ← CategoryTheory.Functor.map_comp, key]
    exact (forget₂ CommRingCat RingCat).map_id _
  exact DFunLike.congr_fun (congrArg RingCat.Hom.hom key2) x

/-- **The two-pushforward slice adjunction** (blueprint `lem:pushforward_slice_two_adjunction`):
`pushforward φ'' ⊣ pushforward ψ_r`, assembled by feeding `pushforwardPushforwardAdj` the slice
equivalence's adjunction, the two ring maps `φ''`/`ψ_r`, and the compatibility squares `H₁`/`H₂`. -/
noncomputable def pushforwardSliceTwoAdjunction :
    SheafOfModules.pushforward.{u} (sliceReverseRingMap φ Ui) ⊣
      SheafOfModules.pushforward.{u} (sliceStructureSheafHom φ Ui) := by
  haveI hF : (sliceOversEquiv φ Ui).symm.functor.IsContinuous
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui))
      ((Opens.grothendieckTopology X).over Ui) :=
    sliceOversEquiv_inverse_isContinuous φ Ui
  haveI hG : (sliceOversEquiv φ Ui).symm.inverse.IsContinuous
      ((Opens.grothendieckTopology X).over Ui)
      ((Opens.grothendieckTopology Y).over (φ.inv ⁻¹ᵁ Ui)) :=
    sliceOversEquiv_functor_isContinuous φ Ui
  exact SheafOfModules.pushforwardPushforwardAdj
    (sliceOversEquiv φ Ui).symm.toAdjunction
    (sliceReverseRingMap φ Ui) (sliceStructureSheafHom φ Ui)
    (pushforwardSliceAdjunctionH1 φ Ui) (pushforwardSliceAdjunctionH2 φ Ui)

/-- **The slice pullback comparison iso** (blueprint
`lem:pushforward_slice_pullback_iso`). Applying the pullback `pullback ψ_r` to the slice `H.over Uᵢ`
is isomorphic to the restricted pushforward `(Φ H).over Vᵢ`.  Step 1:
`pullback ψ_r ≅ pushforward φ''` by uniqueness of left adjoints
(`leftAdjointUniq` of `pullbackPushforwardAdjunction ψ_r` against `pushforwardSliceTwoAdjunction`).
Step 2: the rfl-clean section identity `(pushforward φ'').obj (H.over Uᵢ) ≅ (Φ H).over Vᵢ`
(both sides have sections `Γ(H, φ.hom⁻¹ᵁ W.left)` by `pushforward_obj_obj`). -/
noncomputable def pushforwardSlicePullbackIso (H : X.Modules) :
    (SheafOfModules.pullback.{u} (sliceStructureSheafHom φ Ui)).obj (H.over Ui) ≅
      ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).over (φ.inv ⁻¹ᵁ Ui) :=
  (Adjunction.leftAdjointUniq
    (SheafOfModules.pullbackPushforwardAdjunction.{u} (sliceStructureSheafHom φ Ui))
    (pushforwardSliceTwoAdjunction φ Ui)).app (H.over Ui) ≪≫ Iso.refl _

set_option backward.isDefEq.respectTransparency false in
set_option maxHeartbeats 4000000 in
-- Transporting a presentation through the slice pullback exceeds the default heartbeat budget.
set_option synthInstance.maxHeartbeats 2000000 in
-- Heartbeat bumps: the per-slice presentation transport triggers synthesis of the sliced/doubly
-- sliced `HasSheafify`/`WEqualsLocallyBijective`/`HasSheafCompose` instances over `(gt Y).over Vᵢ`,
-- whose default-heartbeat search times out (it succeeds when bumped).
/-- **Pushforward along a scheme iso preserves quasi-coherence** (blueprint
`lem:pushforward_iso_preserves_qcoh`; Need #1 `hqc`).  Quasi-coherence is local: move each local
presentation of `H` (over the cover member `Uᵢ`) across the colimit-preserving pullback
`pullback ψ_r`, then across the comparison iso `pushforwardSlicePullbackIso` to a presentation of
`(Φ H).over Vᵢ`; conclude per-slice quasi-coherence and glue via
`pushforward_iso_qcoh_of_slice_qcoh`. -/
lemma pushforward_iso_preserves_qcoh {X Y : Scheme.{u}} (φ : X ≅ Y) (H : X.Modules)
    (hH : H.IsQuasicoherent) :
    ((Scheme.Modules.pushforwardEquivOfIso φ).functor.obj H).IsQuasicoherent := by
  obtain ⟨qcd⟩ := hH.nonempty_quasicoherentData
  refine pushforward_iso_qcoh_of_slice_qcoh φ H qcd (fun i => ?_)
  -- Per-slice: build a presentation of `(Φ H).over (φ.inv⁻¹ᵁ qcd.X i)`.
  haveI hFinal : (sliceOversEquiv φ (qcd.X i)).functor.Final := inferInstance
  -- The unit comparison is an iso because the slice functor is final.
  have η : (SheafOfModules.pullback.{u} (sliceStructureSheafHom φ (qcd.X i))).obj
        (SheafOfModules.unit (X.ringCatSheaf.over (qcd.X i))) ≅
      SheafOfModules.unit (Y.ringCatSheaf.over (φ.inv ⁻¹ᵁ qcd.X i)) :=
    asIso (SheafOfModules.pullbackObjUnitToUnit.{u} (sliceStructureSheafHom φ (qcd.X i)))
  -- transport the local presentation of `H.over Uᵢ` across the colimit-preserving pullback...
  have P1 : ((SheafOfModules.pullback.{u} (sliceStructureSheafHom φ (qcd.X i))).obj
      (H.over (qcd.X i))).Presentation :=
    SheafOfModules.Presentation.map.{u} (qcd.presentation i)
      (SheafOfModules.pullback.{u} (sliceStructureSheafHom φ (qcd.X i))) η.symm
  -- ...then across the comparison iso to a presentation of `(Φ H).over Vᵢ`, whence quasi-coherence.
  exact (P1.ofIsIso (pushforwardSlicePullbackIso φ (qcd.X i) H).hom).isQuasicoherent

end SliceTwoAdj

/- Planner strategy:
Part (1): `R^q j_* H` is the sheafification of `V ↦ H^q(j⁻¹V, H)` (presheaf description
`higher_direct_image_presheaf`, Stacks 01XJ); for affine `V`, `j⁻¹V = U ∩ V` is affine (U affine,
X separated), so `affine_serre_vanishing` kills `H^q` for `q ≥ 1`; affine opens are a basis ⇒
`R^q j_* H = 0`. Part (2): take an injective resolution `H → I•`; `j_* I•` is a resolution of
`j_* H` (each `j_* Iⁿ` is `j_*`-acyclic by (1)) and each `j_* Iⁿ` is `f_*`-acyclic (same presheaf
+ Serre-vanishing argument on `U ∩ f⁻¹V`); so `j_* I•` is an `f_*`-acyclic resolution of `j_* H`,
and the P4 acyclic-resolution comparison (`acyclic_resolution_computes_derived` /
`rightDerivedIsoOfAcyclicResolution`) with `G = f_*` gives `R^k f_*(j_* H) ≅ H^k(f_*(j_* I•)) =
H^k((f∘j)_* I•) = R^k (f∘j)_* H`, using `f_* ∘ j_* = (f∘j)_*`. Blueprint:
`lem:open_immersion_pushforward_comp`. Source: Stacks `lemma-relative-affine-vanishing`.
-/

/-- **Higher direct images of an affine open immersion vanish** (part (1) of blueprint
`lem:open_immersion_pushforward_comp`; Stacks `lemma-relative-affine-vanishing`).

For an open immersion `j : U ↪ X` where `U` is affine and `X` is separated, the morphism
`j` is affine (since for any affine open `V ⊆ X`, `j⁻¹V = U ∩ V` is affine by separatedness).
Therefore `R^q j_* H = 0` for every `q ≥ 1` and every quasi-coherent `O_U`-module `H`.

Proof route: by `higherDirectImage_iso_sheafify_presheafHomology`, `R^q j_* H` is the
sheafification of `V ↦ H^q(j⁻¹V, H)`. For affine `V`, `j⁻¹V = U ∩ V` is affine (`U` affine
+ `X` separated), and `affine_serre_vanishing` kills `H^q` for `q ≥ 1`. Since affine opens
form a basis, the presheaf homology is locally zero, and the site lemmas
`isZero_presheafToSheaf_obj_of_isLocallyBijective` (in `CechHigherDirectImage.lean`,
importable via `AffineSerreVanishing`) collapse the sheafification to zero. -/
private lemma isAffineHom_of_affine_separated (j : U ⟶ X) [IsAffine U] [X.IsSeparated] :
    IsAffineHom j := by
  have hg : IsSeparated (terminal.from X) := Scheme.IsSeparated.isSeparated_terminal_from
  have hcomp : IsAffineHom (j ≫ terminal.from X) := by
    have he : j ≫ terminal.from X = terminal.from U := terminal.hom_ext _ _
    rw [he]; infer_instance
  exact IsAffineHom.of_comp j (terminal.from X)

/-- The sections-over-`j⁻¹W` functor on `U`-modules, `M ↦ Γ(W, j_* M) = Γ(j⁻¹W, M)`,
realised as the composite `pushforward j ⋙ forget ⋙ restrictScalars 𝟙 ⋙ toPresheaf ⋙ eval(W)`.
Its `q`-th right derived functor applied to `H` is the absolute cohomology `Hᵠ(j⁻¹W, H)`.
Project-local: a named composite so its additivity instance is synthesised once at the top
level (the 5-fold composite defeats in-proof instance search). -/
noncomputable def pushforwardSectionsFunctor (j : U ⟶ X) (W : TopologicalSpace.Opens X) :
    U.Modules ⥤ AddCommGrpCat :=
  Scheme.Modules.pushforward j ⋙ SheafOfModules.forget X.ringCatSheaf ⋙
    PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj) ⋙
    PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
    (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W)

noncomputable instance pushforwardSectionsFunctor_additive
    (j : U ⟶ X) (W : TopologicalSpace.Opens X) : (pushforwardSectionsFunctor j W).Additive := by
  unfold pushforwardSectionsFunctor
  -- The flat 5-fold composite defeats instance search; build it as an explicit `instAdditiveComp`
  -- chain (every individual factor is additive).
  haveI hpf : (Scheme.Modules.pushforward j).Additive := inferInstance
  haveI i4 : (PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W)).Additive :=
    Functor.instAdditiveComp _ _
  haveI i3 : (PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj) ⋙
      PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W)).Additive :=
    Functor.instAdditiveComp _ _
  haveI i2 : (SheafOfModules.forget X.ringCatSheaf ⋙
      PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj) ⋙
      PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W)).Additive :=
    Functor.instAdditiveComp _ _
  -- Instance search will not pick up `i2` automatically here, so we pass it explicitly.
  exact @CategoryTheory.Functor.instAdditiveComp _ _ _ _ _ _
    (Scheme.Modules.pushforward j) hpf _ _ _ _ i2

theorem higherDirectImage_openImmersion_acyclic [HasInjectiveResolutions U.Modules]
    (j : U ⟶ X) [IsOpenImmersion j] [IsAffine U] [X.IsSeparated]
    (H : U.Modules) (hH : H.IsQuasicoherent) (q : ℕ) (hq : 0 < q) :
    IsZero (higherDirectImage j q H) := by
  -- `j` is an affine morphism (open immersion of an affine into a separated scheme),
  -- so the preimage of every affine open `V ⊆ X` is the affine open `j⁻¹V = U ∩ V`.
  haveI : IsAffineHom j := isAffineHom_of_affine_separated j
  -- Presheaf description (Stacks 01XJ): `Rᵠ j_* H ≅ sheafify(V ↦ Hᵠ((j_* I•)(V)))`
  -- for any injective resolution `I` of `H`. Reduce to the vanishing of that sheafification.
  refine IsZero.of_iso ?_
    (higherDirectImage_iso_sheafify_presheafHomology j q (injectiveResolution H))
  set α : X.ringCatSheaf.obj ⟶ X.ringCatSheaf.obj := 𝟙 X.ringCatSheaf.obj with hα
  set P := (pushforwardResolutionPresheafComplex j (injectiveResolution H)).homology q with hP
  -- Reflect `IsZero` through the faithful, zero-preserving forgetful functor `toSheaf`.
  apply Functor.isZero_of_faithful_preservesZeroMorphisms (SheafOfModules.toSheaf X.ringCatSheaf)
  -- Transport across the sheafification square
  -- `toSheaf ∘ sheafification ≅ presheafToSheaf ∘ toPresheaf`.
  refine IsZero.of_iso ?_ ((PresheafOfModules.sheafificationCompToSheaf α).app P)
  set Q := (PresheafOfModules.toPresheaf X.ringCatSheaf.obj).obj P with hQ
  -- KEY VANISHING (genuine cohomological gap): the presheaf homology `Q` is a *zero object*
  -- over every affine open `W ⊆ X`, because `j⁻¹W` is affine (`j` is an affine morphism) and
  -- `affine_serre_vanishing` kills `Hᵠ(j⁻¹W, H)` for `q ≥ 1`.
  have hSec : ∀ (W : TopologicalSpace.Opens X), IsAffineOpen W →
      IsZero (Q.obj (Opposite.op W)) := by
    intro W hW
    -- Evaluate-at-`W` the presheaf complex; this functor preserves homology, so
    -- `Q.obj (op W) ≅ Hᵠ(Γ(W, f_* I•)) = Hᵠ(j⁻¹W, H)`, which vanishes for affine `j⁻¹W`.
    set GW := PresheafOfModules.toPresheaf X.ringCatSheaf.obj ⋙
      (evaluation (TopologicalSpace.Opens X)ᵒᵖ AddCommGrpCat).obj (Opposite.op W) with hGW
    set Kp := pushforwardResolutionPresheafComplex j (injectiveResolution H) with hKp
    refine IsZero.of_iso ?_ (GW.mapHomologyIso' (ComplexShape.up ℕ) Kp q).symm
    -- The section complex `n ↦ Γ(W, f_* I^n) = Γ(j⁻¹W, I^n)` is the image of the chosen
    -- injective resolution of `H` under the additive sections-over-`j⁻¹W` functor.
    have hcomplex : (GW.mapHomologicalComplex (ComplexShape.up ℕ)).obj Kp
        = ((pushforwardSectionsFunctor j W).mapHomologicalComplex (ComplexShape.up ℕ)).obj
            (injectiveResolution H).cocomplex :=
      rfl
    rw [hcomplex]
    -- `isoRightDerivedObj` recognises this homology as the `q`-th right derived sections
    -- functor `Rᵠ Γ(j⁻¹W, -)` applied to `H`, i.e. the absolute cohomology `Hᵠ(j⁻¹W, H)`.
    refine IsZero.of_iso ?_ ((injectiveResolution H).isoRightDerivedObj
      (pushforwardSectionsFunctor j W) q).symm
    -- The sections functor `Γ(j⁻¹W, -)` (here `pushforwardSectionsFunctor j W`, which is
    -- definitionally `sectionsFunctor (j ⁻¹ᵁ W)`) is corepresented by `jShriekOU (j ⁻¹ᵁ W)`, so its
    -- `q`-th right derived functor agrees with that of `Hom(jShriekOU (j ⁻¹ᵁ W), -)`.  This
    -- discharges the *geometric* corepresentability half of Bridge (1)/(2).
    refine IsZero.of_iso ?_ ((rightDerivedNatIso (sectionsFunctorCorepIso (j ⁻¹ᵁ W)) q).app H)
    -- Bridge (1)/(2) homological remainder: the lemma below reduces right-derived vanishing of
    -- `Hom(jShriekOU (j⁻¹W), -)` to `∀ e : Ext (jShriekOU (j⁻¹W)) H q, e = 0`.
    refine isZero_coyoneda_rightDerived_of_forall_ext_eq_zero (jShriekOU (j ⁻¹ᵁ W)) H q hq ?_
    intro e
    -- Discharged by `ext_jShriekOU_eq_zero_of_specIso`; all three goals (`hV'`, `hjt`, `hqc`)
    -- close axiom-cleanly below.
    refine ext_jShriekOU_eq_zero_of_specIso U U.isoSpec (j ⁻¹ᵁ W) H q hq
      (U.isoSpec.inv ⁻¹ᵁ (j ⁻¹ᵁ W)) ?hV' ?hjt ?hqc e
    -- `j⁻¹W` is affine (`j` is an affine morphism, `W` affine), and its image under the iso
    -- `U.isoSpec.inv` (= preimage along `U.isoSpec.inv`) is affine.
    case hV' => exact (hW.preimage j).preimage_of_isIso U.isoSpec.inv
    case hjt => exact jShriekOU_transport_along_iso U.isoSpec (j ⁻¹ᵁ W)
    case hqc => exact pushforward_iso_preserves_qcoh U.isoSpec H hH
  -- Since affine opens form a basis of `X`, every section of `Q` restricts to `0` on the
  -- affine opens contained in its domain, so `Q` is sectionwise locally zero and its
  -- sheafification vanishes.
  apply CategoryTheory.GrothendieckTopology.isZero_presheafToSheaf_of_sections_locally_zero
    (Opens.grothendieckTopology X) (Q := Q)
  intro U s
  refine ⟨{ arrows := fun {V} _ => ∃ W : TopologicalSpace.Opens X,
              IsAffineOpen W ∧ V ≤ W ∧ W ≤ U,
            downward_closed := ?_ }, ?_, ?_⟩
  · rintro V V' g ⟨A, hA, hVA, hAU⟩ h
    exact ⟨A, hA, le_trans (leOfHom h) hVA, hAU⟩
  · -- membership in the opens topology: every point of `U` has an affine basis neighbourhood
    intro x hx
    obtain ⟨W, hWmem, hxW, hWU⟩ :=
      (TopologicalSpace.Opens.isBasis_iff_nbhd.mp (Scheme.isBasis_affineOpens X)) hx
    exact ⟨W, homOfLE hWU, ⟨W, hWmem, le_refl W, hWU⟩, hxW⟩
  · -- the restriction of `s` to a sieve member `V ≤ A ≤ U` (with `A` affine) factors through
    -- `Q.obj (op A) = 0`, hence vanishes.
    rintro V g ⟨A, hA, hVA, hAU⟩
    haveI : Subsingleton (ToType (Q.obj (Opposite.op A))) :=
      AddCommGrpCat.subsingleton_of_isZero (hSec A hA)
    have hgfac : g.op = (homOfLE hAU).op ≫ (homOfLE hVA).op := by
      rw [← op_comp]; congr 1
    rw [hgfac, Q.map_comp, ConcreteCategory.comp_apply,
      Subsingleton.elim ((ConcreteCategory.hom (Q.map (homOfLE hAU).op)) s) 0, map_zero]

/-- **Composition formula for higher direct images across an open immersion** (pinned
declaration; blueprint `lem:open_immersion_pushforward_comp`, part (2); Stacks
`lemma-relative-affine-vanishing`).

Let `j : U ↪ X` be an open immersion of an affine open `U` into a separated scheme `X`,
and `f : X ⟶ S` any morphism. For every quasi-coherent `O_U`-module `H` and every `k ≥ 0`:
```
  R^k f_*(j_* H) ≅ R^k (f ∘ j)_* H.
```
Proof route: choose an injective resolution `H → I•` in `U.Modules`; apply `j_*`
degreewise to get an `f_*`-acyclic resolution `j_* I•` of `j_* H`
(`higherDirectImage_openImmersion_acyclic` for `j_*`-acyclicity, extended to
`f_*`-acyclicity via the same Serre-vanishing argument on `U ∩ f⁻¹V`); then
`Functor.rightDerivedIsoOfAcyclicResolution` with `G = (pushforward f)` and the identity
`(pushforward f) ∘ (pushforward j) = pushforward (j ≫ f)` give the stated isomorphism. -/
noncomputable def higherDirectImage_openImmersion_comp
    [HasInjectiveResolutions X.Modules] [HasInjectiveResolutions U.Modules]
    (j : U ⟶ X) [IsOpenImmersion j] [IsAffine U] [X.IsSeparated]
    (f : X ⟶ S) (H : U.Modules) (hH : H.IsQuasicoherent) (k : ℕ) :
    higherDirectImage f k ((pushforward j).obj H) ≅
      higherDirectImage (j ≫ f) k H := by
  haveI : IsAffineHom j := isAffineHom_of_affine_separated j
  -- Structural plan (all categorical building blocks below are verified to exist):
  --   • `G := Scheme.Modules.pushforward f` is additive and preserves finite limits
  --     (`inferInstance`), so `Functor.rightDerivedIsoOfAcyclicResolution` applies to it.
  --   • The pushed-forward injective resolution `K := (pushforward j).mapHomologicalComplex I•`
  --     is a candidate acyclic resolution of `j_* H = (pushforward j).obj H`.
  --   • `pushforwardComp j f : pushforward j ⋙ pushforward f ≅ pushforward (j ≫ f)` turns
  --     `H^k(G(K))` into `H^k((j ≫ f)_* I•) = R^k (j ≫ f)_* H`.
  -- `hacyc`: adjoint route — `pushforward j` preserves injectives via
  -- `Injective.injective_of_adjoint (restrictAdjunction j)`, so `j_* Iⁿ` is injective and
  -- `(pushforward f)`-acyclic (`IsRightAcyclic.ofInjective`).  Resolution/exactness from
  -- `higherDirectImage_openImmersion_acyclic`; transport via `pushforwardComp`.
  -- Skeleton: apply the acyclic-resolution comparison `rightDerivedIsoOfAcyclicResolution` to
  -- `G = pushforward f` and `K = (pushforward j)(I•)`, then transport via `pushforwardComp`.
  set K := ((Scheme.Modules.pushforward j).mapHomologicalComplex (ComplexShape.up ℕ)).obj
    (injectiveResolution H).cocomplex with hK
  -- Part (b): each `j_* Iⁿ` is `f_*`-acyclic (`R^{≥1} f_*(j_* Iⁿ) = 0`).  Adjoint route: `j_*`
  -- preserves injectives (right adjoint of the mono-preserving `restrictFunctor j`), so `j_* Iⁿ` is
  -- injective, hence `f_*`-acyclic for any additive `f_*` (`IsRightAcyclic.ofInjective`).
  haveI hacyc : ∀ n, (Scheme.Modules.pushforward f).IsRightAcyclic (K.X n) := by
    intro n
    -- `restrictFunctor j` is a right adjoint (it is the pushforward of (pre)sheaves of modules
    -- along the open-immersion opens functor), hence preserves monomorphisms.
    haveI : (Scheme.Modules.restrictFunctor j).IsRightAdjoint := by
      unfold Scheme.Modules.restrictFunctor
      exact inferInstanceAs (SheafOfModules.pushforward _).IsRightAdjoint
    -- Its right adjoint `pushforward j` (via `restrictAdjunction`) therefore preserves injectives;
    -- `K.X n = (pushforward j).obj Iⁿ` with `Iⁿ` injective, so `K.X n` is injective.
    haveI : Injective (K.X n) :=
      Injective.injective_of_adjoint (Scheme.Modules.restrictAdjunction j)
        ((injectiveResolution H).cocomplex.X n)
    -- An injective object is `(pushforward f)`-acyclic (`IsRightAcyclic.ofInjective` instance).
    infer_instance
  refine Functor.rightDerivedIsoOfAcyclicResolution (Scheme.Modules.pushforward f) K
    ((Scheme.Modules.pushforward j).obj H) ?eRes ?hexact k ≪≫ ?transport
  -- `e`: the pushforward of the resolution augmentation `H ≅ (I•).cycles 0`, transported through
  -- the left-exact (finite-limit-preserving) `pushforward j` which preserves the degree-`0` cycles
  -- (`gCosyzygyIsoCocycles`).
  case eRes =>
    refine (Scheme.Modules.pushforward j).mapIso ?_ ≪≫
      (Scheme.Modules.pushforward j).gCosyzygyIsoCocycles (injectiveResolution H).cocomplex 0
    -- `H ≅ (I•).cycles 0`: the resolution augmentation, factored through homology 0 (the
    -- incoming differential at degree `0` is zero, so `cycles 0 ≅ homology 0`).
    exact (HomologicalComplex.singleObjHomologySelfIso _ _ _).symm ≪≫
      isoOfQuasiIsoAt (injectiveResolution H).ι 0 ≪≫
      (injectiveResolution H).cocomplex.isoHomologyπ₀.symm
  -- `hexact`: `K = j_*(I•)` is exact in positive degrees (i.e. `j_* I•` resolves `j_* H`); this is
  -- residual (a), the `j_*`-acyclicity of each injective `Iⁿ` (`_acyclic` applied to `Iⁿ`).
  -- `K.homology (n+1) ≅ R^{n+1} j_* H = higherDirectImage j (n+1) H`, which vanishes by Part (1).
  case hexact =>
    intro n
    rw [HomologicalComplex.exactAt_iff_isZero_homology]
    exact IsZero.of_iso (higherDirectImage_openImmersion_acyclic j H hH (n + 1) (Nat.succ_pos n))
      ((injectiveResolution H).isoRightDerivedObj (Scheme.Modules.pushforward j) (n + 1)).symm
  -- transport: `Hᵏ((pushforward f)(K)) ≅ R^k (j≫f)_* H` via `pushforwardComp j f`
  -- (`pushforward j ⋙ pushforward f ≅ pushforward (j≫f)`) + `isoRightDerivedObj`.
  -- `(pushforward f)(j_* I•) = (pushforward j ⋙ pushforward f)(I•)` (defeq); transport the
  -- homology across `pushforwardComp j f` to `(pushforward (j≫f))(I•)`, recognised as `R^k g_* H`.
  case transport =>
    refine (HomologicalComplex.homologyFunctor S.Modules (ComplexShape.up ℕ) k).mapIso
      ((NatIso.mapHomologicalComplex (Scheme.Modules.pushforwardComp j f) (ComplexShape.up ℕ)).app
        (injectiveResolution H).cocomplex) ≪≫
      ((injectiveResolution H).isoRightDerivedObj (Scheme.Modules.pushforward (j ≫ f)) k).symm

end AlgebraicGeometry
