/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.RiemannRoch.SectionSpaces

/-!
# DD-F brick 5 — functional bookkeeping: multiplication spans and annihilator kernels

The pure linear algebra of the bpf-span proof (`informal/dd-f-probe-verdict.md` §3a,
inventory brick 5), over the function field `K(X)` of the curve bundle:

* `Scheme.mulSpan K U T` — the span of the products `h · f` (`h ∈ U`, `f ∈ T`): the
  submodule the carve `(♦)` bounds, and the `span(H_s · K)` of the bpf-span statement;
* `Submodule.le_of_forall_dual_ker` — the **separating shell**: to prove `W ≤ S` it
  suffices that every functional killing `S` kills `W` (a nonzero functional on `V ⧸ S`
  exists since vector spaces are projective — no finiteness needed);
* `Scheme.annKernel K U V Λ` — the annihilator kernel
  `N_Λ = {h ∈ U : Λ(h · V) = 0}` of a functional `Λ` against a multiplier space `U` and
  a source space `V`;
* `finrank_le_finrank_annKernel_add` (★) — **the codimension bound** (probe 3a): if `Λ`
  kills every product `U · T` with `T ≤ V` of codimension `c`, then
  `dim U ≤ dim N_Λ + c` — the map `h ↦ Λ(h · –)|_V` lands in the annihilator of `T`
  inside `Dual(V)`, which has dimension `c`; rank–nullity finishes.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits Opposite TopologicalSpace

attribute [local instance] AlgebraicGeometry.Scheme.functionFieldOverModule
  AlgebraicGeometry.Scheme.overModule

namespace AlgebraicGeometry

open Scheme

/-! ## The separating shell (generic linear algebra) -/

section Shell

variable {K : Type u} [Field K] {V : Type u} [AddCommGroup V] [Module K V]

/-- **The separating shell**: `W ≤ S` follows once every functional killing `S` kills
`W`. If some `w ∈ W` escaped `S`, a functional on `V ⧸ S` nonzero at `⟦w⟧` (vector
spaces are projective) would kill `S` but not `w`. No finiteness assumptions. -/
theorem Submodule.le_of_forall_dual_ker {S W : Submodule K V}
    (h : ∀ Λ : Module.Dual K V, S ≤ LinearMap.ker Λ → W ≤ LinearMap.ker Λ) :
    W ≤ S := by
  intro w hw
  by_contra hws
  have hq : S.mkQ w ≠ 0 := by
    rw [Submodule.mkQ_apply, Ne, Submodule.Quotient.mk_eq_zero]
    exact hws
  obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_ne_zero K hq
  have hker : S ≤ LinearMap.ker (φ.comp S.mkQ) := by
    intro s hs
    rw [LinearMap.mem_ker, LinearMap.comp_apply, Submodule.mkQ_apply,
      (Submodule.Quotient.mk_eq_zero S).mpr hs, map_zero]
  have hwk := h (φ.comp S.mkQ) hker hw
  rw [LinearMap.mem_ker, LinearMap.comp_apply] at hwk
  exact hφ hwk

end Shell

/-! ## Multiplication spans -/

section MulSpan

variable (K : Type u) [Field K] {X : Scheme.{u}} [X.Over (Spec (CommRingCat.of K))]
  [IsIntegral X]

/-- **The multiplication span** `span(U · T)`: the submodule of `K(X)` generated by the
products `h · f` with `h ∈ U`, `f ∈ T`. The `span(H_s · K_M)` of the carve `(♦)`. -/
noncomputable def Scheme.mulSpan (U T : Submodule K X.functionField) :
    Submodule K X.functionField :=
  Submodule.span K {w : X.functionField | ∃ h ∈ U, ∃ f ∈ T, w = h * f}

lemma Scheme.mul_mem_mulSpan {U T : Submodule K X.functionField}
    {h f : X.functionField} (hh : h ∈ U) (hf : f ∈ T) :
    h * f ∈ Scheme.mulSpan K U T :=
  Submodule.subset_span ⟨h, hh, f, hf, rfl⟩

/-- Eliminating a multiplication span into any submodule containing the products. -/
lemma Scheme.mulSpan_le {U T W : Submodule K X.functionField}
    (h : ∀ a ∈ U, ∀ f ∈ T, a * f ∈ W) : Scheme.mulSpan K U T ≤ W := by
  refine Submodule.span_le.mpr ?_
  rintro w ⟨a, ha, f, hf, rfl⟩
  exact h a ha f hf

/-- A fixed factor `f ∈ T` embeds `f · U` into the multiplication span. -/
lemma Scheme.map_mulLinear_le_mulSpan {U T : Submodule K X.functionField}
    {f : X.functionField} (hf : f ∈ T) :
    Submodule.map (Scheme.mulLinear K f) U ≤ Scheme.mulSpan K U T := by
  rintro _ ⟨h, hh, rfl⟩
  rw [Scheme.mulLinear_apply, mul_comm]
  exact Scheme.mul_mem_mulSpan K hh hf

end MulSpan

/-! ## The annihilator kernel -/

section AnnKernel

variable (K : Type u) [Field K] {X : Scheme.{u}} [X.Over (Spec (CommRingCat.of K))]
  [IsIntegral X]

/-- **The annihilator kernel** `N_Λ = {h ∈ U : Λ(h · V) = 0}` of a functional
`Λ : K(X)* → K` against the multiplier space `U` and the source space `V` — the `N_L` of
the probe's step (3a). -/
noncomputable def Scheme.annKernel (U V : Submodule K X.functionField)
    (Λ : Module.Dual K X.functionField) : Submodule K X.functionField where
  carrier := {h | h ∈ U ∧ ∀ f ∈ V, Λ (h * f) = 0}
  zero_mem' := ⟨U.zero_mem, fun f _ => by rw [zero_mul, map_zero]⟩
  add_mem' := fun {a b} ha hb =>
    ⟨U.add_mem ha.1 hb.1, fun f hf => by
      rw [add_mul, map_add, ha.2 f hf, hb.2 f hf, add_zero]⟩
  smul_mem' := fun r a ha =>
    ⟨U.smul_mem r ha.1, fun f hf => by
      rw [Scheme.functionFieldOverModule_smul_def, mul_assoc,
        ← Scheme.functionFieldOverModule_smul_def, map_smul, ha.2 f hf, smul_zero]⟩

lemma Scheme.mem_annKernel {U V : Submodule K X.functionField}
    {Λ : Module.Dual K X.functionField} {h : X.functionField} :
    h ∈ Scheme.annKernel K U V Λ ↔ h ∈ U ∧ ∀ f ∈ V, Λ (h * f) = 0 :=
  Iff.rfl

lemma Scheme.annKernel_le (U V : Submodule K X.functionField)
    (Λ : Module.Dual K X.functionField) : Scheme.annKernel K U V Λ ≤ U :=
  fun _ hh => hh.1

/-- **The codimension bound** (★, probe 3a): if `Λ` kills every product `U · T` for a
subspace `T ≤ V` of codimension `c` (`dim T + c = dim V`), then
`dim U ≤ dim N_Λ + c`. The map `Φ : U → Dual(V)`, `h ↦ Λ(h · –)`, has kernel `N_Λ` and
range inside the annihilator of `T` in `Dual(V)`, of dimension `c`. -/
theorem finrank_le_finrank_annKernel_add {U V T : Submodule K X.functionField}
    [Module.Finite K ↥U] [Module.Finite K ↥V]
    {Λ : Module.Dual K X.functionField} {c : ℕ}
    (hTV : T ≤ V) (hc : Module.finrank K ↥T + c = Module.finrank K ↥V)
    (hkill : ∀ h ∈ U, ∀ f ∈ T, Λ (h * f) = 0) :
    Module.finrank K ↥U ≤ Module.finrank K ↥(Scheme.annKernel K U V Λ) + c := by
  classical
  -- the bilinear evaluation `Φ : U →ₗ Dual(V)`, `h ↦ Λ(h · –)`
  set Φ : ↥U →ₗ[K] Module.Dual K ↥V :=
    { toFun := fun h => (Λ.comp (Scheme.mulLinear K (h : X.functionField))).domRestrict V
      map_add' := fun a b => by
        refine LinearMap.ext (fun f => ?_)
        simp only [LinearMap.domRestrict_apply, LinearMap.comp_apply,
          Scheme.mulLinear_apply, LinearMap.add_apply, Submodule.coe_add]
        rw [add_mul, map_add]
      map_smul' := fun r a => by
        refine LinearMap.ext (fun f => ?_)
        simp only [LinearMap.domRestrict_apply, LinearMap.comp_apply,
          Scheme.mulLinear_apply, RingHom.id_apply, LinearMap.smul_apply,
          Submodule.coe_smul]
        rw [Scheme.functionFieldOverModule_smul_def, mul_assoc,
          ← Scheme.functionFieldOverModule_smul_def, map_smul] } with hΦ
  -- the kernel of `Φ` is the annihilator kernel
  have hker : Submodule.map U.subtype (LinearMap.ker Φ) = Scheme.annKernel K U V Λ := by
    apply le_antisymm
    · rintro _ ⟨h, hh, rfl⟩
      have hval : ∀ f : ↥V, Λ ((h : X.functionField) * f) = 0 := fun f =>
        DFunLike.congr_fun (LinearMap.mem_ker.mp hh) f
      exact ⟨h.2, fun f hf => hval ⟨f, hf⟩⟩
    · rintro h ⟨hhU, hann⟩
      refine Submodule.mem_map.mpr ⟨⟨h, hhU⟩, ?_, rfl⟩
      rw [LinearMap.mem_ker]
      refine LinearMap.ext (fun f => ?_)
      exact hann f f.2
  -- the range of `Φ` lies in the annihilator of `T` inside `Dual(V)`
  set T' : Submodule K ↥V := T.comap V.subtype with hT'
  have hrange : LinearMap.range Φ ≤ T'.dualAnnihilator := by
    rintro _ ⟨h, rfl⟩
    rw [Submodule.mem_dualAnnihilator]
    intro w hw
    simp only [hΦ, LinearMap.coe_mk, AddHom.coe_mk, LinearMap.domRestrict_apply,
      LinearMap.comp_apply, Scheme.mulLinear_apply]
    exact hkill h h.2 w hw
  -- dimension of the annihilator of `T'`: `c`
  have hT'rank : Module.finrank K ↥T' = Module.finrank K ↥T :=
    (Submodule.comapSubtypeEquivOfLe hTV).finrank_eq
  have hannrank := Subspace.finrank_add_finrank_dualAnnihilator_eq T'
  -- rank–nullity
  have hrn := LinearMap.finrank_range_add_finrank_ker Φ
  have hkerrank : Module.finrank K ↥(LinearMap.ker Φ)
      = Module.finrank K ↥(Scheme.annKernel K U V Λ) := by
    rw [← hker]
    exact (Submodule.equivSubtypeMap U (LinearMap.ker Φ)).finrank_eq
  have hrle : Module.finrank K ↥(LinearMap.range Φ)
      ≤ Module.finrank K ↥T'.dualAnnihilator :=
    Submodule.finrank_mono hrange
  have hdual : Module.finrank K (Module.Dual K ↥V) = Module.finrank K ↥V :=
    Subspace.dual_finrank_eq
  omega

end AnnKernel

end AlgebraicGeometry
