/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.RingTheory.Invariant.Basic
import AlgebraicJacobian.Picard.GaloisQuotientGlue

/-!
# Stable opens on affine Galois quotient charts

Let `L/K` be a finite extension, let `X` carry a semilinear `Gal(L/K)`-action,
and let `U` be a stable affine open of `X`.  The affine quotient chart is
`Spec (Γ(U)^Gal(L/K))`.  If `V ≤ U` is stable, the invariant norm construction
of `GaloisQuotientGlue` covers `V` by basic opens `D(N)` for invariant sections
`N ∈ Γ(U)`.

This file constructs the corresponding open of the quotient chart as the union
of the basic opens cut out by those same elements in `Γ(U)^Gal(L/K)`.  Its main
result is the exact saturation identity

`stableAffineQuotientMap ⁻¹(V/Gal(L/K)) = U.ι ⁻¹(V)`.

The affine quotient map is surjective, so this open is also exactly the image of
`V` and the image is open.  Thus stable overlaps already determine honest opens
on the affine quotient charts.  Constructing and gluing the resulting overlap
isomorphisms is a separate step.

## Main declarations

* `SemilinearAction.affineQuotientMap` is the canonical map
  `Spec A ⟶ Spec (A^Gal(L/K))`.
* `SemilinearGalAction.quotientOpenOfStableSubopen` is the quotient-chart open
  generated by invariant basic opens contained in `V`.
* `SemilinearGalAction.stableAffineQuotientMap` is the quotient map on a stable
  affine chart.
* `SemilinearGalAction.stableAffineQuotientMap_preimage_quotientOpen` proves the
  saturation identity above.
* `SemilinearGalAction.stableAffineQuotientMap_image_stableSubopen` identifies
  the constructed open with the actual image of the stable subopen.
-/

set_option autoImplicit false

universe u

open CategoryTheory Limits AlgebraicGeometry TopologicalSpace

namespace AlgebraicJacobian.GaloisDescent

namespace SemilinearAction

variable (K L : Type u) [Field K] [Field L] [Algebra K L]
variable (A : Type u) [CommRing A] [Algebra K A] [Algebra L A] [IsScalarTower K L A]
variable [MulSemiringAction (L ≃ₐ[K] L) A] [IsSemilinear K L A]

/-- The canonical affine quotient map `Spec A ⟶ Spec (A^Gal(L/K))`, induced by
the inclusion of the invariant subalgebra. -/
noncomputable def affineQuotientMap :
    Spec (CommRingCat.of A) ⟶ Spec (CommRingCat.of (invariantsSubalgebra K L A)) :=
  Spec.map (CommRingCat.ofHom (invariantsSubalgebra K L A).val)

/-- The affine quotient map is surjective on points for a finite Galois-automorphism
group.  The inclusion `A^Gal(L/K) ⟶ A` is integral because every element satisfies
its orbit polynomial, so lying over applies.

Only finiteness of the automorphism group is used; no `IsGalois K L` instance is
needed for this topological conclusion. -/
theorem affineQuotientMap_surjective [FiniteDimensional K L] :
    Function.Surjective (affineQuotientMap K L A).base := by
  let I := invariantsSubalgebra K L A
  letI : SMulCommClass (L ≃ₐ[K] L) I A :=
    ⟨fun γ n a => by
      change γ • ((n : A) * a) = (n : A) * (γ • a)
      rw [smul_mul', n.2 γ]⟩
  letI : Algebra.IsInvariant I A (L ≃ₐ[K] L) :=
    ⟨fun a ha => ⟨⟨a, ha⟩, rfl⟩⟩
  letI := Algebra.IsInvariant.isIntegral I A (L ≃ₐ[K] L)
  change Function.Surjective (PrimeSpectrum.comap (algebraMap I A))
  exact Algebra.IsIntegral.comap_surjective I A

end SemilinearAction

namespace SemilinearGalAction

variable {K L : Type u} [Field K] [Field L] [Algebra K L]
variable {X : Scheme.{u}} {f : X ⟶ Spec (CommRingCat.of L)}
variable (ρ : SemilinearGalAction K L X f) {U : X.Opens} (hU : ρ.IsStableOpen U)

/-- The open of the affine quotient chart generated by invariant basic opens
`D(N) ≤ V`.  Each index supplies the invariant element
`⟨N, hN⟩ : Γ(U)^Gal(L/K)` cutting out the corresponding quotient-side basic open. -/
noncomputable def quotientOpenOfStableSubopen (V : X.Opens) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    (Spec (CommRingCat.of
      (SemilinearAction.invariantsSubalgebra K L Γ(X, U)))).Opens := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  exact ⨆ i : InvariantBasicOpenIndex ρ hU V,
    PrimeSpectrum.basicOpen
      (⟨i.1, i.2.1⟩ : SemilinearAction.invariantsSubalgebra K L Γ(X, U))

/-- The canonical quotient map from a stable affine chart to the spectrum of
the invariant subalgebra of its section ring. -/
noncomputable def stableAffineQuotientMap (hUa : IsAffineOpen U) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    U.toScheme ⟶ Spec (CommRingCat.of
      (SemilinearAction.invariantsSubalgebra K L Γ(X, U))) := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  exact hUa.isoSpec.hom ≫ SemilinearAction.affineQuotientMap K L Γ(X, U)

/-- **A stable subopen is the pullback of an open on the affine quotient chart.**

The quotient-side open is the union of basic opens defined by invariant sections
whose source-side basic opens lie in `V`.  The invariant-basic-open covering
theorem identifies their source-side union with `V`; functoriality of basic opens
under `Spec` then gives the claimed equality. -/
theorem stableAffineQuotientMap_preimage_quotientOpen [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V : X.Opens} (hVU : V ≤ U)
    (hV : ρ.IsStableOpen V) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    (stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ quotientOpenOfStableSubopen ρ hU V =
      U.ι ⁻¹ᵁ V := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  rw [stableAffineQuotientMap, Scheme.Hom.comp_preimage,
    quotientOpenOfStableSubopen, Scheme.Hom.preimage_iSup,
    Scheme.Hom.preimage_iSup]
  simp only [SemilinearAction.affineQuotientMap]
  rw [hUa.isoSpec_hom]
  calc
    (⨆ i : InvariantBasicOpenIndex ρ hU V,
        U.toSpecΓ ⁻¹ᵁ
          (PrimeSpectrum.basicOpen (i.1 : Γ(X, U)) :
            (Spec (CommRingCat.of Γ(X, U))).Opens))
        = ⨆ i : InvariantBasicOpenIndex ρ hU V,
            U.ι ⁻¹ᵁ X.basicOpen i.1 := by
              congr 1
              funext i
              exact U.toSpecΓ_preimage_basicOpen i.1
    _ = U.ι ⁻¹ᵁ (⨆ i : InvariantBasicOpenIndex ρ hU V, X.basicOpen i.1) :=
      (Scheme.Hom.preimage_iSup U.ι _).symm
    _ = U.ι ⁻¹ᵁ V := by rw [ρ.iSup_invariantBasicOpen_eq hU hUa hVU hV]

/-- The quotient map of a stable affine chart is surjective on points. -/
theorem stableAffineQuotientMap_surjective [FiniteDimensional K L]
    (hUa : IsAffineOpen U) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    Function.Surjective (stableAffineQuotientMap ρ hU hUa).base := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  rw [stableAffineQuotientMap]
  exact (SemilinearAction.affineQuotientMap_surjective K L Γ(X, U)).comp
    (CategoryTheory.ConcreteCategory.bijective_of_isIso hUa.isoSpec.hom.base).2

/-- The quotient open attached to the whole stable affine chart is the whole
quotient chart. -/
theorem quotientOpenOfStableSubopen_self [FiniteDimensional K L]
    (hUa : IsAffineOpen U) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    quotientOpenOfStableSubopen ρ hU U = ⊤ := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  apply Opens.ext
  apply Set.preimage_injective.mpr
    (stableAffineQuotientMap_surjective ρ hU hUa)
  change (↑((stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ
      quotientOpenOfStableSubopen ρ hU U) : Set U.toScheme) =
    (↑((stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ ⊤) : Set U.toScheme)
  rw [stableAffineQuotientMap_preimage_quotientOpen ρ hU hUa le_rfl hU]
  simp

/-- Quotient opens of stable subopens preserve binary intersections.  This is
the common-target identity used for triple overlaps in the quotient gluing
datum. -/
theorem quotientOpenOfStableSubopen_inf [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V W : X.Opens} (hVU : V ≤ U) (hWU : W ≤ U)
    (hV : ρ.IsStableOpen V) (hW : ρ.IsStableOpen W) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    quotientOpenOfStableSubopen ρ hU (V ⊓ W) =
      quotientOpenOfStableSubopen ρ hU V ⊓
        quotientOpenOfStableSubopen ρ hU W := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  have hVW : ρ.IsStableOpen (V ⊓ W) := by
    intro γ
    rw [Scheme.Hom.preimage_inf, hV γ, hW γ]
  apply Opens.ext
  apply Set.preimage_injective.mpr
    (stableAffineQuotientMap_surjective ρ hU hUa)
  change (↑((stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ
      quotientOpenOfStableSubopen ρ hU (V ⊓ W)) : Set U.toScheme) =
    (↑((stableAffineQuotientMap ρ hU hUa) ⁻¹ᵁ
      (quotientOpenOfStableSubopen ρ hU V ⊓
        quotientOpenOfStableSubopen ρ hU W)) : Set U.toScheme)
  rw [Scheme.Hom.preimage_inf,
    stableAffineQuotientMap_preimage_quotientOpen ρ hU hUa
      (le_trans inf_le_left hVU) hVW,
    stableAffineQuotientMap_preimage_quotientOpen ρ hU hUa hVU hV,
    stableAffineQuotientMap_preimage_quotientOpen ρ hU hUa hWU hW,
    Scheme.Hom.preimage_inf]

/-- The quotient-open construction is monotone on stable subopens of a fixed
stable affine chart. -/
theorem quotientOpenOfStableSubopen_mono [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V W : X.Opens}
    (hVU : V ≤ U) (hWU : W ≤ U) (hVW : V ≤ W)
    (hV : ρ.IsStableOpen V) (hW : ρ.IsStableOpen W) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    quotientOpenOfStableSubopen ρ hU V ≤
      quotientOpenOfStableSubopen ρ hU W := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  intro y hy
  obtain ⟨x, rfl⟩ := stableAffineQuotientMap_surjective ρ hU hUa y
  have hxV : x ∈ U.ι ⁻¹ᵁ V := by
    rw [← stableAffineQuotientMap_preimage_quotientOpen
      ρ hU hUa hVU hV]
    exact hy
  have hxW : x ∈ U.ι ⁻¹ᵁ W := hVW hxV
  rw [← stableAffineQuotientMap_preimage_quotientOpen
    ρ hU hUa hWU hW] at hxW
  exact hxW

/-- **The quotient-side open is exactly the image of the stable subopen.**

Surjectivity upgrades `stableAffineQuotientMap_preimage_quotientOpen` from a
saturation statement to an image equality. -/
theorem stableAffineQuotientMap_image_stableSubopen [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V : X.Opens} (hVU : V ≤ U)
    (hV : ρ.IsStableOpen V) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    (stableAffineQuotientMap ρ hU hUa).base ''
        ((U.ι ⁻¹ᵁ V : U.toScheme.Opens) : Set U.toScheme) =
      (quotientOpenOfStableSubopen ρ hU V : Set _) := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  rw [← stableAffineQuotientMap_preimage_quotientOpen ρ hU hUa hVU hV]
  change (stableAffineQuotientMap ρ hU hUa).base ''
      ((stableAffineQuotientMap ρ hU hUa).base ⁻¹'
        (quotientOpenOfStableSubopen ρ hU V : Set _)) =
      (quotientOpenOfStableSubopen ρ hU V : Set _)
  exact Set.image_preimage_eq _ (ρ.stableAffineQuotientMap_surjective hU hUa)

/-- The image of a stable subopen under its affine invariant-ring quotient map is
open. -/
theorem isOpen_image_stableSubopen [FiniteDimensional K L]
    (hUa : IsAffineOpen U) {V : X.Opens} (hVU : V ≤ U)
    (hV : ρ.IsStableOpen V) :
    letI := ρ.sectionsMulSemiringAction hU
    letI := sectionsAlgebra f U
    letI := sectionsAlgebraK (K := K) f U
    letI := sections_isScalarTower (K := K) f U
    letI := ρ.isSemilinear_sections hU
    IsOpen ((stableAffineQuotientMap ρ hU hUa).base ''
      ((U.ι ⁻¹ᵁ V : U.toScheme.Opens) : Set U.toScheme)) := by
  letI := ρ.sectionsMulSemiringAction hU
  letI := sectionsAlgebra f U
  letI := sectionsAlgebraK (K := K) f U
  letI := sections_isScalarTower (K := K) f U
  letI := ρ.isSemilinear_sections hU
  rw [ρ.stableAffineQuotientMap_image_stableSubopen hU hUa hVU hV]
  exact (quotientOpenOfStableSubopen ρ hU V).2

end SemilinearGalAction

end AlgebraicJacobian.GaloisDescent
