/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.Algebra.DualNumber
import Mathlib.RingTheory.Ideal.Operations
import AlgebraicJacobian.Picard.NilpotentThickeningFree

/-!
# Chart triviality over the dual numbers

The **first input of the tangent/`H¹` geometric middle** of
`Picard/Pic0AbelianVariety.lean` (`semilinearComparison_cotangentSpaceDual_h1Cok`), in the
concrete dual-number spelling: *an invertible module over `A[ε]` whose restriction along
`ε ↦ 0` is trivial is itself trivial.*

Geometrically this is the statement that an invertible sheaf on `C ×_k Spec k[ε]` trivial
along `ε ↦ 0` is trivial on each base-changed affine chart of a 2-affine cover — which is
what turns the class into a single transition unit on the overlap and so feeds the two-chart
Čech unit-cocycle engine of `Picard/Pic0DualNumberCocycle.lean` §6. On an affine chart
`V = Spec A` the base change is `Spec A[ε]` (`DualNumber.baseChangeAlgEquiv` of that file,
combined with mathlib's `pullbackSpecIso`), so the geometric statement reduces to the
algebra proved here.

## Main results

* `DualNumber.augIdeal_mul_self_eq_bot` — the augmentation ideal `ker(A[ε] → A)` is
  **square-zero**. This is where "first-order deformation" enters, and it is the only
  property of the dual numbers the argument uses.
* `DualNumber.ker_fstHom_eq_span_eps` — that kernel is exactly `(ε)`, so a consumer holding
  either spelling can use the other.
* `DualNumber.isNilpotent_ker_fstHom` / `DualNumber.isNilpotent_span_eps` — nilpotency, the
  hypothesis of the general statement in `Picard/NilpotentThickeningFree.lean`.
* `DualNumber.free_of_cyclic_mod_eps` — the chart statement: an invertible `A[ε]`-module in
  which every element agrees with a multiple of a fixed `m` modulo `(ε)·M` is free.
* `Submodule.exists_sub_smul_mem_of_quotient_cyclic` and its converse
  `Submodule.quotient_cyclic_of_exists_sub_smul_mem` — **the generator obligation, closed**
  (run 0067 r4). See §"The generator is not an extra hypothesis" below: both projects had
  recorded "produce `m`" as open geometric work, and it is a one-line lift of the generator of
  a cyclic quotient. Stated for an arbitrary submodule of an arbitrary module over a
  commutative ring; nothing about dual numbers, curves or covers enters.
* `DualNumber.free_of_quotient_eps_cyclic` — the consumable form: an invertible `A[ε]`-module
  with **cyclic** reduction `M ⧸ (ε)·M` is free, generator supplied internally.

## What this does and does not close

It closes the *chart-triviality* clause of the geometric middle, for arbitrary affine charts
and with no finiteness hypothesis on the sections (see the discussion in
`Picard/NilpotentThickeningFree.lean` — the nilpotent Nakayama iteration is what buys that),
and as of run 0067 r4 it closes that clause **without assuming a generator**.

The two remaining clauses of the middle are the identification
`Γ(V ×_k Spec k[ε], 𝒪) ≅ Γ(V, 𝒪)[ε]` — already available as
`DualNumber.baseChangeAlgEquiv` — and the statement that under these identifications a
kernel element goes to its transition unit, which is the genuinely cocycle-level step and
is still open.

As recorded in the docstring of `semilinearComparison_cotangentSpaceDual_h1Cok` and
confirmed from the sibling project (inbox I-0495, 2026-07-28), none of this needs Hilbert 90
or any henselian cover-splitting brick: the thickening is square-zero, which is precisely
the hypothesis discharged by `augIdeal_mul_self_eq_bot` here.
-/

set_option autoImplicit false

universe u v

open TrivSqZeroExt DualNumber

namespace DualNumber

variable (A : Type u) [CommRing A]

/-- **The augmentation ideal of the dual numbers is square-zero.** The kernel of
`A[ε] → A`, `x ↦ x.fst`, consists of the elements with vanishing constant term, and the
product of two such has both components zero: the `fst` component is a product of `fst`s,
and the `snd` component of a product is `a.fst * b.snd + b.fst * a.snd`.

This is the single property of the dual numbers that the chart-triviality argument uses —
everything else is the general nilpotent statement of
`Picard/NilpotentThickeningFree.lean`. -/
theorem augIdeal_mul_self_eq_bot :
    RingHom.ker (TrivSqZeroExt.fstHom A A A) * RingHom.ker (TrivSqZeroExt.fstHom A A A) = ⊥ := by
  refine le_antisymm (Ideal.mul_le.mpr fun a ha b hb => ?_) bot_le
  have ha' : a.fst = 0 := ha
  have hb' : b.fst = 0 := hb
  refine Ideal.mem_bot.mpr (TrivSqZeroExt.ext ?_ ?_)
  · simp [TrivSqZeroExt.fst_mul, ha']
  · simp [TrivSqZeroExt.snd_mul, ha', hb']

/-- **The augmentation ideal is `(ε)`.** Both spellings occur in practice — the
representability side produces the kernel of the restriction along `ε ↦ 0`, the cocycle side
produces the ideal generated by `ε` — so the identification is recorded once here.

Left to right: an element `x` with `x.fst = 0` is `ε · inl x.snd`. Right to left: `ε` has
vanishing constant term. -/
theorem ker_fstHom_eq_span_eps :
    RingHom.ker (TrivSqZeroExt.fstHom A A A) = Ideal.span {(ε : DualNumber A)} := by
  refine le_antisymm (fun x hx => ?_) (Ideal.span_le.mpr ?_)
  · have hx' : x.fst = 0 := hx
    refine Ideal.mem_span_singleton.mpr ⟨TrivSqZeroExt.inl x.snd, ?_⟩
    refine TrivSqZeroExt.ext ?_ ?_
    · simp [TrivSqZeroExt.fst_mul, hx']
    · simp [TrivSqZeroExt.snd_mul]
  · intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    change (ε : DualNumber A).fst = 0
    simp

/-- The augmentation ideal is nilpotent, being square-zero. -/
theorem isNilpotent_ker_fstHom : IsNilpotent (RingHom.ker (TrivSqZeroExt.fstHom A A A)) :=
  Ideal.isNilpotent_of_mul_self_eq_bot (augIdeal_mul_self_eq_bot A)

/-- `(ε)` is nilpotent — the `span`-spelling of `isNilpotent_ker_fstHom`. -/
theorem isNilpotent_span_eps : IsNilpotent (Ideal.span {(ε : DualNumber A)}) := by
  rw [← ker_fstHom_eq_span_eps]
  exact isNilpotent_ker_fstHom A

/-- **Chart triviality over the dual numbers.** An invertible `A[ε]`-module `M` in which
every element agrees with some multiple of a fixed `m` modulo `(ε) · M` — i.e. whose
restriction along `ε ↦ 0` is generated by the image of `m`, hence trivial — is free.

This is the affine-chart form of "an invertible sheaf on `C ×_k Spec k[ε]` trivial along
`ε ↦ 0` is trivial on each base-changed chart". Note what is *not* assumed: `A` is an
arbitrary commutative ring, and the sections are not assumed finitely generated over the
base field — affine charts of a curve do not have finite-dimensional section spaces, so any
version of this requiring that would be useless here. -/
theorem free_of_cyclic_mod_eps
    (M : Type v) [AddCommGroup M] [Module (DualNumber A) M]
    [Module.Invertible (DualNumber A) M] (m : M)
    (h : ∀ x : M, ∃ r : DualNumber A,
      x - r • m ∈ Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)) :
    Module.Free (DualNumber A) M :=
  Module.Invertible.free_of_nilpotent_of_exists_sub_smul_mem (isNilpotent_span_eps A) h

end DualNumber

/-! ## The generator is not an extra hypothesis

`free_of_cyclic_mod_eps` above, and the sibling project's
`Opens.cechPicMap_ι_eq_one_of_dualNumberChart`
(`Algebraic-Jacobian-Challenge-Rebuild`, `Tangent/DualNumberChartPic.lean:127`), both take the
generator `m` **and** the pointwise binder `∀ x, ∃ r, x - r • m ∈ (ε)·M` as *given*. Both
projects' docstrings then name "produce `m` from the hypothesis that `L` is trivial on `C`" as
the remaining obligation — AJCR carrying it as a hypothesis rather than a `sorry`
(their worksheet §0(4): never register a staged fact), AJC inside the `sorry` of
`semilinearComparison_cotangentSpaceDual_h1Cok`. Surveyed and read on 2026-07-28: it is
character-for-character the same obligation on both sides, and neither side had discharged it.

**It is not a geometric obligation at all.** The pointwise binder is nothing more than
*cyclicity of the quotient* `M ⧸ (ε)·M` written without naming a quotient, so producing `m`
from the module-theoretic hypothesis is a one-line surjectivity argument on
`Submodule.Quotient.mk` — no cover, no scheme, no dual numbers. That is what this section
proves, and both directions are given, so `exists_sub_smul_mem_of_quotient_cyclic` is a genuine
**reduction** of the binder rather than a restatement of it (the safeguard of inbox `I-0571`).

The residual geometric content of the clause is therefore *only* the identification of
"`L` restricts trivially along `ε ↦ 0`" with "`M ⧸ (ε)·M` is cyclic" — which is the trivialising
section on the chart, i.e. the freeness of the restriction, not a statement about generators.
-/

namespace Submodule

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- **The generator of a cyclic quotient can be lifted** — so the "fixed `m` with
`∀ x, ∃ r, x - r • m ∈ N`" binder of `DualNumber.free_of_cyclic_mod_eps` follows from the
quotient `M ⧸ N` being cyclic, with no further input.

Both this project and the sibling had recorded producing `m` as open work on the tangent lane's
chart-triviality clause. The proof is `Submodule.Quotient.mk_surjective` on the generator
followed by `Submodule.Quotient.mk_eq_zero`: pick any preimage `m` of the generator `y`, and for
`x : M` take the `r` with `⟦x⟧ = r • y`; then `⟦x - r • m⟧ = ⟦x⟧ - r • ⟦m⟧ = r • y - r • y = 0`,
which is membership in `N`. -/
theorem exists_sub_smul_mem_of_quotient_cyclic (N : Submodule R M)
    (h : ∃ y : M ⧸ N, ∀ z : M ⧸ N, ∃ r : R, z = r • y) :
    ∃ m : M, ∀ x : M, ∃ r : R, x - r • m ∈ N := by
  obtain ⟨y, hy⟩ := h
  obtain ⟨m, hm⟩ := Submodule.Quotient.mk_surjective N y
  refine ⟨m, fun x => ?_⟩
  obtain ⟨r, hr⟩ := hy (Submodule.Quotient.mk x)
  refine ⟨r, ?_⟩
  have hq : (Submodule.Quotient.mk (x - r • m) : M ⧸ N) = 0 := by
    rw [Submodule.Quotient.mk_sub, Submodule.Quotient.mk_smul, hm, hr, sub_self]
  exact (Submodule.Quotient.mk_eq_zero N).mp hq

/-- **The converse**, which is what makes the lemma above a reduction rather than a
restatement: the pointwise binder *implies* that `M ⧸ N` is cyclic, generated by the class of
`m`. So "there is a generator satisfying the binder" and "the quotient is cyclic" are
equivalent, and replacing one by the other loses nothing.

Recorded per inbox `I-0571`: a restatement is only a reduction if the converse holds. -/
theorem quotient_cyclic_of_exists_sub_smul_mem (N : Submodule R M)
    (m : M) (h : ∀ x : M, ∃ r : R, x - r • m ∈ N) :
    ∀ z : M ⧸ N, ∃ r : R, z = r • (Submodule.Quotient.mk m : M ⧸ N) := by
  intro z
  obtain ⟨x, hx⟩ := Submodule.Quotient.mk_surjective N z
  obtain ⟨r, hr⟩ := h x
  refine ⟨r, ?_⟩
  have hz : (Submodule.Quotient.mk (x - r • m) : M ⧸ N) = 0 :=
    (Submodule.Quotient.mk_eq_zero N).mpr hr
  rw [Submodule.Quotient.mk_sub, Submodule.Quotient.mk_smul, sub_eq_zero] at hz
  rw [← hx, hz]

end Submodule

namespace DualNumber

variable (A : Type u) [CommRing A]

/-- **Chart triviality with the generator produced, not assumed** — the form of
`free_of_cyclic_mod_eps` that a consumer holding only "the restriction along `ε ↦ 0` is
trivial" can actually use.

An invertible `A[ε]`-module whose reduction `M ⧸ (ε)·M` is **cyclic** is free. This closes the
gap that both this project and the sibling recorded as the open half of the chart-triviality
clause: `Submodule.exists_sub_smul_mem_of_quotient_cyclic` supplies `m`, and
`free_of_cyclic_mod_eps` finishes.

Still no finiteness on `M` and no hypothesis on `A` beyond commutativity — the nilpotent
Nakayama iteration of `Picard/NilpotentThickeningFree.lean` is what buys that, and cyclicity of
the reduction is exactly the input it needs. -/
theorem free_of_quotient_eps_cyclic
    (M : Type v) [AddCommGroup M] [Module (DualNumber A) M]
    [Module.Invertible (DualNumber A) M]
    (h : ∃ y : M ⧸ (Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)),
      ∀ z, ∃ r : DualNumber A, z = r • y) :
    Module.Free (DualNumber A) M := by
  obtain ⟨m, hm⟩ := Submodule.exists_sub_smul_mem_of_quotient_cyclic
    (Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)) h
  exact free_of_cyclic_mod_eps A M m hm

end DualNumber
