/-
Copyright (c) 2026 StacksPart07Lib authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The StacksPart07Lib Contributors
-/

import StacksPart07Lib.RelationGroupoid

/-!
# Functoriality of relation groupoids and orbit quotients

A map which preserves relations induces a functor between the associated thin
groupoids.  When the relation is generated by an arbitrary relation, the same
map induces a map on orbit quotients.  These are the elementary functorial
shadows of pullback and quotient constructions in the groupoid chapters.
-/

namespace StacksPart07Lib

open CategoryTheory

universe u v

variable {α β γ : Type u}

namespace RelationCategory

/-- A relation-preserving map on objects induces a functor of relation
groupoids. -/
def map (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y)) :
    RelationCategory r ⥤ RelationCategory s where
  obj := f
  map {x y} g := homOfRel s (hf (relOfHom r g))
  map_id := by
    intro x
    exact hom_ext s _ _
  map_comp := by
    intro x y z g h
    exact hom_ext s _ _

@[simp]
theorem map_obj (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y)) (x : RelationCategory r) :
    (map r s f hf).obj x = f x := rfl

@[simp]
theorem map_homOfRel (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y))
    {x y : RelationCategory r} (h : r.r x y) :
    (map r s f hf).map (homOfRel r h) =
      homOfRel s (hf h) := by
  rfl

/-- Relation functors compose by composing their object maps and proofs. -/
def mapComp (r : Setoid α) (s : Setoid β) (t : Setoid γ)
    (f : α → β) (g : β → γ)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y))
    (hg : ∀ ⦃x y : β⦄, s.r x y → t.r (g x) (g y)) :
    map r t (g ∘ f) (fun {_ _} h => hg (hf h)) =
      map r s f hf ⋙ map s t g hg := by
  apply Functor.ext (fun x => rfl)

@[simp]
theorem map_id_functor (r : Setoid α) :
    map r r id (fun {_ _} h => h) = 𝟭 (RelationCategory r) := by
  apply Functor.ext (fun x => rfl)

end RelationCategory

namespace RelationQuotient

/-- The map on orbit quotients induced by a relation-preserving map. -/
def map (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y)) :
    Quotient r → Quotient s :=
  Quotient.lift (fun x => Quotient.mk s (f x)) (fun _ _ h => Quotient.sound (hf h))

@[simp]
theorem map_mk (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y)) (x : α) :
    map r s f hf (Quotient.mk r x) = Quotient.mk s (f x) := rfl

/-- Quotienting after the identity relation map gives the identity map. -/
@[simp]
theorem map_id (r : Setoid α) :
    map r r id (fun {_ _} h => h) = id := by
  funext q
  refine Quotient.inductionOn q ?_
  intro x
  rfl

/-- Quotient maps induced by relation-preserving maps compose. -/
theorem map_comp (r : Setoid α) (s : Setoid β) (t : Setoid γ)
    (f : α → β) (g : β → γ)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y))
    (hg : ∀ ⦃x y : β⦄, s.r x y → t.r (g x) (g y)) :
    map r t (g ∘ f) (fun {_ _} h => hg (hf h)) =
      map s t g hg ∘ map r s f hf := by
  funext q
  refine Quotient.inductionOn q ?_
  intro x
  rfl

/-- Orbit-quotient maps commute with the canonical quotient projections. -/
theorem map_mk_comp (r : Setoid α) (s : Setoid β) (f : α → β)
    (hf : ∀ ⦃x y : α⦄, r.r x y → s.r (f x) (f y)) :
    map r s f hf ∘ Quotient.mk r = Quotient.mk s ∘ f := by
  funext x
  rfl

end RelationQuotient

end StacksPart07Lib
