/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Tangent.DualNumberChartTriviality

/-!
# The generator of a cyclic quotient, and chart triviality without a chosen generator

`DualNumber.free_of_cyclic_mod_eps` (`Tangent/DualNumberChartTriviality.lean`) takes a **fixed**
`m` together with `∀ x, ∃ r, x - r • m ∈ (ε) · M`. This file shows that binder is exactly
*cyclicity of the reduction* `M ⧸ (ε)·M` written without naming the quotient, and gives the
consumable form:

```
Module.Invertible A[ε] M,  M ⧸ (ε)·M cyclic  ⟹  Module.Free A[ε] M
```

(`DualNumber.free_of_quotient_eps_cyclic`).

## Provenance (cross-project port, and why the port is legitimate)

**Ported from `Algebraic-Jacobian-Challenge`,
`AlgebraicJacobian/Picard/DualNumberChartTriviality.lean` (sorry-free, commit `c1ed5be8b`),
posted as portable on the cross-project thread `I-0495` by the `ajc-pic0av` lane.**

Both projects had recorded "produce the generator `m`" as the open half of the chart-triviality
clause of the tangent/`H¹` comparison — AJCR as the `hcyc` binder of
`Scheme.Opens.cechPicMap_ι_eq_one_of_dualNumberChart` (`Tangent/DualNumberChartPic.lean`), AJC as
the `h` binder of its own `free_of_cyclic_mod_eps`. They are the same obligation, and it is not
geometry: it is `Submodule.Quotient.mk_surjective` plus `Submodule.Quotient.mk_eq_zero`. Porting
rather than re-deriving is the point of the shared workspace.

The statements are in the `Submodule` namespace over an arbitrary `R`-module, so nothing
project-specific crosses the boundary.

## Why this is a reduction and not a restatement

`Submodule.quotient_cyclic_of_exists_sub_smul_mem` is the **converse**: the pointwise binder
implies the quotient is cyclic, generated by the class of `m`. So the two formulations are
equivalent and replacing one by the other loses nothing — the standing requirement of inbox
`I-0571` (*a restatement is only a reduction if you prove the converse*).

## What this does and does not close

It closes "produce `m`". It does **not** close the remaining geometric input of clause
(iii-c2-aff): identifying *"`L` restricts trivially along `ε ↦ 0`"* with *"`M ⧸ (ε)·M` is
cyclic"* — that is freeness of the **restriction** on the chart, and it is untouched here. Do not
read this file as closing (iii-c2-aff).

## Main declarations

* `Submodule.exists_sub_smul_mem_of_quotient_cyclic` — lift the generator of a cyclic quotient.
* `Submodule.quotient_cyclic_of_exists_sub_smul_mem` — its converse.
* `DualNumber.free_of_quotient_eps_cyclic` — chart triviality from cyclicity of the reduction.

Reference: Kleiman, "The Picard scheme", §5 Thm. 5.11 (arXiv:math/0504020);
`informal/w5-t4-worksheet.md` §6.16.
-/

set_option autoImplicit false

universe u v

open TrivSqZeroExt DualNumber

namespace Submodule

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- **The generator of a cyclic quotient can be lifted** — so the "fixed `m` with
`∀ x, ∃ r, x - r • m ∈ N`" binder of `DualNumber.free_of_cyclic_mod_eps` follows from `M ⧸ N`
being cyclic, with no further input.

The proof is `Submodule.Quotient.mk_surjective` on the generator followed by
`Submodule.Quotient.mk_eq_zero`: pick any preimage `m` of the generator `y`, and for `x : M` take
the `r` with `⟦x⟧ = r • y`; then `⟦x - r • m⟧ = ⟦x⟧ - r • ⟦m⟧ = r • y - r • y = 0`, which is
membership in `N`. -/
theorem exists_sub_smul_mem_of_quotient_cyclic (N : Submodule R M)
    (h : ∃ y : M ⧸ N, ∀ z : M ⧸ N, ∃ r : R, z = r • y) :
    ∃ m : M, ∀ x : M, ∃ r : R, x - r • m ∈ N := by
  obtain ⟨y, hy⟩ := h
  obtain ⟨m, hm⟩ := Submodule.Quotient.mk_surjective N y
  refine ⟨m, fun x => ?_⟩
  obtain ⟨r, hr⟩ := hy (Submodule.Quotient.mk x)
  refine ⟨r, ?_⟩
  have hq : (Submodule.Quotient.mk (x - r • m) : M ⧸ N) = 0 := by
    rw [Submodule.Quotient.mk_sub, Submodule.Quotient.mk_smul, hm, hr, sub_self]
  exact (Submodule.Quotient.mk_eq_zero N).mp hq

/-- **The converse**, which is what makes the lemma above a reduction rather than a restatement:
the pointwise binder *implies* that `M ⧸ N` is cyclic, generated by the class of `m`. So "there
is a generator satisfying the binder" and "the quotient is cyclic" are equivalent.

Recorded per inbox `I-0571`: a restatement is only a reduction if the converse holds. -/
theorem quotient_cyclic_of_exists_sub_smul_mem (N : Submodule R M) (m : M)
    (h : ∀ x : M, ∃ r : R, x - r • m ∈ N) :
    ∀ z : M ⧸ N, ∃ r : R, z = r • (Submodule.Quotient.mk m : M ⧸ N) := by
  intro z
  obtain ⟨x, hx⟩ := Submodule.Quotient.mk_surjective N z
  obtain ⟨r, hr⟩ := h x
  refine ⟨r, ?_⟩
  have hz : (Submodule.Quotient.mk (x - r • m) : M ⧸ N) = 0 :=
    (Submodule.Quotient.mk_eq_zero N).mpr hr
  rw [Submodule.Quotient.mk_sub, Submodule.Quotient.mk_smul, sub_eq_zero] at hz
  rw [← hx, hz]

end Submodule

namespace DualNumber

variable (A : Type u) [CommRing A]

/-- **Chart triviality with the generator produced, not assumed** — the form of
`free_of_cyclic_mod_eps` that a consumer holding only "the restriction along `ε ↦ 0` is trivial"
can actually use.

An invertible `A[ε]`-module whose reduction `M ⧸ (ε)·M` is **cyclic** is free.
`Submodule.exists_sub_smul_mem_of_quotient_cyclic` supplies `m`, and `free_of_cyclic_mod_eps`
finishes.

Still no finiteness on `M` and no hypothesis on `A` beyond commutativity — the nilpotent Nakayama
iteration of `Tangent/NilpotentThickeningFree.lean` is what buys that, and cyclicity of the
reduction is exactly the input it needs.

**One deviation from the sibling's statement, and it is not cosmetic.** AJC states this at
`M : Type v` with `A : Type u` independent; AJCR's `free_of_cyclic_mod_eps`
(`Tangent/DualNumberChartTriviality.lean`) is universe-**monomorphic** — it binds
`M : Type u`, the same universe as `A`. So the port is pinned to `Type u` here. This costs nothing
at the call site (the chart module lives in the same universe as the section ring), but it means
the port is *not* byte-identical, and a later session should not "restore" `Type v` without also
generalising `free_of_cyclic_mod_eps`. The `Submodule` lemmas above are genuinely
universe-polymorphic and were transcribed unchanged. -/
theorem free_of_quotient_eps_cyclic
    (M : Type u) [AddCommGroup M] [Module (DualNumber A) M]
    [Module.Invertible (DualNumber A) M]
    (h : ∃ y : M ⧸ (Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)),
      ∀ z, ∃ r : DualNumber A, z = r • y) :
    Module.Free (DualNumber A) M := by
  obtain ⟨m, hm⟩ := Submodule.exists_sub_smul_mem_of_quotient_cyclic
    (Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)) h
  exact free_of_cyclic_mod_eps A M m hm

end DualNumber
