/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import Mathlib.Algebra.DualNumber
import Mathlib.RingTheory.Ideal.Operations
import AlgebraicJacobian.Tangent.NilpotentThickeningFree

/-!
# Chart triviality over the dual numbers

The **first input of the tangent/`H¹` geometric middle** of
`Picard/Pic0AbelianVariety.lean` (`semilinearComparison_cotangentSpaceDual_h1Cok`), in the
concrete dual-number spelling: *an invertible module over `A[ε]` whose restriction along
`ε ↦ 0` is trivial is itself trivial.*

Geometrically this is the statement that an invertible sheaf on `C ×_k Spec k[ε]` trivial
along `ε ↦ 0` is trivial on each base-changed affine chart of a 2-affine cover — which is
what turns the class into a single transition unit on the overlap and so feeds the two-chart
Čech unit-cocycle engine of `Picard/Pic0DualNumberCocycle.lean` §6. On an affine chart
`V = Spec A` the base change is `Spec A[ε]` (`DualNumber.baseChangeAlgEquiv` of that file,
combined with mathlib's `pullbackSpecIso`), so the geometric statement reduces to the
algebra proved here.

## Main results

* `DualNumber.augIdeal_mul_self_eq_bot` — the augmentation ideal `ker(A[ε] → A)` is
  **square-zero**. This is where "first-order deformation" enters, and it is the only
  property of the dual numbers the argument uses.
* `DualNumber.ker_fstHom_eq_span_eps` — that kernel is exactly `(ε)`, so a consumer holding
  either spelling can use the other.
* `DualNumber.isNilpotent_ker_fstHom` / `DualNumber.isNilpotent_span_eps` — nilpotency, the
  hypothesis of the general statement in `Picard/NilpotentThickeningFree.lean`.
* `DualNumber.free_of_cyclic_mod_eps` — the chart statement: an invertible `A[ε]`-module in
  which every element agrees with a multiple of a fixed `m` modulo `(ε)·M` is free.

## What this does and does not close

It closes the *chart-triviality* clause of the geometric middle, for arbitrary affine charts
and with no finiteness hypothesis on the sections (see the discussion in
`Picard/NilpotentThickeningFree.lean` — the nilpotent Nakayama iteration is what buys that).
The two remaining clauses of the middle are the identification
`Γ(V ×_k Spec k[ε], 𝒪) ≅ Γ(V, 𝒪)[ε]` — already available as
`DualNumber.baseChangeAlgEquiv` — and the statement that under these identifications a
kernel element goes to its transition unit, which is the genuinely cocycle-level step and
is still open.

As recorded in the docstring of `semilinearComparison_cotangentSpaceDual_h1Cok` and
confirmed from the sibling project (inbox I-0495, 2026-07-28), none of this needs Hilbert 90
or any henselian cover-splitting brick: the thickening is square-zero, which is precisely
the hypothesis discharged by `augIdeal_mul_self_eq_bot` here.
-/

set_option autoImplicit false

universe u v

open TrivSqZeroExt DualNumber

namespace DualNumber

variable (A : Type u) [CommRing A]

/-- **The augmentation ideal of the dual numbers is square-zero.** The kernel of
`A[ε] → A`, `x ↦ x.fst`, consists of the elements with vanishing constant term, and the
product of two such has both components zero: the `fst` component is a product of `fst`s,
and the `snd` component of a product is `a.fst * b.snd + b.fst * a.snd`.

This is the single property of the dual numbers that the chart-triviality argument uses —
everything else is the general nilpotent statement of
`Picard/NilpotentThickeningFree.lean`. -/
theorem augIdeal_mul_self_eq_bot :
    RingHom.ker (TrivSqZeroExt.fstHom A A A) * RingHom.ker (TrivSqZeroExt.fstHom A A A) = ⊥ := by
  refine le_antisymm (Ideal.mul_le.mpr fun a ha b hb => ?_) bot_le
  have ha' : a.fst = 0 := ha
  have hb' : b.fst = 0 := hb
  refine Ideal.mem_bot.mpr (TrivSqZeroExt.ext ?_ ?_)
  · simp [TrivSqZeroExt.fst_mul, ha']
  · simp [TrivSqZeroExt.snd_mul, ha', hb']

/-- **The augmentation ideal is `(ε)`.** Both spellings occur in practice — the
representability side produces the kernel of the restriction along `ε ↦ 0`, the cocycle side
produces the ideal generated by `ε` — so the identification is recorded once here.

Left to right: an element `x` with `x.fst = 0` is `ε · inl x.snd`. Right to left: `ε` has
vanishing constant term. -/
theorem ker_fstHom_eq_span_eps :
    RingHom.ker (TrivSqZeroExt.fstHom A A A) = Ideal.span {(ε : DualNumber A)} := by
  refine le_antisymm (fun x hx => ?_) (Ideal.span_le.mpr ?_)
  · have hx' : x.fst = 0 := hx
    refine Ideal.mem_span_singleton.mpr ⟨TrivSqZeroExt.inl x.snd, ?_⟩
    refine TrivSqZeroExt.ext ?_ ?_
    · simp [TrivSqZeroExt.fst_mul, hx']
    · simp [TrivSqZeroExt.snd_mul]
  · intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    change (ε : DualNumber A).fst = 0
    simp

/-- The augmentation ideal is nilpotent, being square-zero. -/
theorem isNilpotent_ker_fstHom : IsNilpotent (RingHom.ker (TrivSqZeroExt.fstHom A A A)) :=
  Ideal.isNilpotent_of_mul_self_eq_bot (augIdeal_mul_self_eq_bot A)

/-- `(ε)` is nilpotent — the `span`-spelling of `isNilpotent_ker_fstHom`. -/
theorem isNilpotent_span_eps : IsNilpotent (Ideal.span {(ε : DualNumber A)}) := by
  rw [← ker_fstHom_eq_span_eps]
  exact isNilpotent_ker_fstHom A

/-- **Chart triviality over the dual numbers.** An invertible `A[ε]`-module `M` in which
every element agrees with some multiple of a fixed `m` modulo `(ε) · M` — i.e. whose
restriction along `ε ↦ 0` is generated by the image of `m`, hence trivial — is free.

This is the affine-chart form of "an invertible sheaf on `C ×_k Spec k[ε]` trivial along
`ε ↦ 0` is trivial on each base-changed chart". Note what is *not* assumed: `A` is an
arbitrary commutative ring, and the sections are not assumed finitely generated over the
base field — affine charts of a curve do not have finite-dimensional section spaces, so any
version of this requiring that would be useless here. 
## Provenance (cross-project port, T4 clause (i))

Ported from `Algebraic-Jacobian-Challenge`,
`AlgebraicJacobian/Picard/DualNumberChartTriviality.lean` (sorry-free), posted as
portable on the cross-project thread `I-0495`. See the provenance note of
`Tangent/NilpotentThickeningFree.lean`.

Note `DualNumber.augIdeal_mul_self_eq_bot` below: it is the square-zero fact on
which the whole "no Hilbert 90, no henselian brick" verdict of
`informal/w5-t4-worksheet.md` rests, so that verdict now stands on a theorem rather
than an observation.
-/
theorem free_of_cyclic_mod_eps
    (M : Type u) [AddCommGroup M] [Module (DualNumber A) M]
    [Module.Invertible (DualNumber A) M] (m : M)
    (h : ∀ x : M, ∃ r : DualNumber A,
      x - r • m ∈ Ideal.span {(ε : DualNumber A)} • (⊤ : Submodule (DualNumber A) M)) :
    Module.Free (DualNumber A) M :=
  Module.Invertible.free_of_nilpotent_of_exists_sub_smul_mem (isNilpotent_span_eps A) h

end DualNumber
