/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Tangent.DualNumberCarrierReduction
import Mathlib.RingTheory.QuotSMulTop

/-!
# The `ε ↦ 0` map is the quotient by `(ε)` (W5-T4, the bridge (iii-c2-aff-geo) needs)

`informal/w5-t4-worksheet.md` names **(iii-c2-aff-geo)** as T4's last mathematical residue:
identifying *"`L` restricts trivially along `ε ↦ 0`"* with *"the chart module's reduction
`M ⧸ (ε)·M` is cyclic"*. The algebra above that line is entirely landed —
`Tangent/CyclicQuotientGenerator.lean` turns cyclicity of the reduction into the generator, and
`Tangent/NilpotentThickeningFree.lean` turns that into freeness with no finiteness hypothesis. What
was missing is the step *below*: the two sides talk about different things.

* "restricts trivially along `ε ↦ 0`" is about `CommRing.Pic.mapRingHom fstRingHom`, i.e. the
  **base change along `fst : A[ε] → A`**, which by `mapAlgebra` is `A ⊗[A[ε]] M`;
* "`M ⧸ (ε)·M`" is a **quotient**, and mathlib relates quotients to base change only along the
  *ring* quotient: `QuotSMulTop.equivQuotTensor r M : M ⧸ r·M ≃ₗ (R ⧸ (r)) ⊗[R] M`.

So the bridge is a statement about `A[ε]` and nothing else: **`A` is `A[ε] ⧸ (ε)`**, i.e.
`fst : A[ε] → A` is surjective with kernel exactly `Ideal.span {ε}`. That is what this file proves.

## The two facts, and why the kernel one is not `simp`

`fstRingHom_surjective` is `inl` as a section — one line. `ker_fstRingHom` is the content: for
`x : A[ε]` with `fst x = 0`, the witness of `x ∈ (ε)` is `x = ε * inl x.snd`, proved componentwise
(`TrivSqZeroExt.ext`). The `fst` component uses the hypothesis and `fst_eps = 0`; the `snd`
component is `snd (ε * inl b) = fst ε * b + fst (inl b) * snd ε`, which collapses because
`fst ε = 0` and `snd (inl b) = 0`.

`simp` alone does **not** close either component here: unfolding `ε` to `inr 1` inside
`TrivSqZeroExt` arithmetic makes `simp` loop (measured: "maximum recursion depth has been reached").
Naming `TrivSqZeroExt.fst_mul` / `snd_mul` and `DualNumber.fst_eps` / `snd_eps` explicitly is what
makes it three `rw`s.

## What this does and does not close

It closes the **algebraic** half of the crossing: with `A ≃+* A[ε] ⧸ (ε)` available, the base change
`A ⊗[A[ε]] M` and the reduction `M ⧸ (ε)·M` are the same module, so a triviality statement about the
former transports to a cyclicity statement about the latter.

It does **not** close (iii-c2-aff-geo). That obligation is stated at the level of a `CechPic` class
on a chart of the thickened curve, and still owes the identification of `Opens.cechPicClass` of the
restricted bundle with the base change of the class upstairs. This file removes the *ring-theoretic*
excuse for that gap; what remains is genuinely about the chart. Recorded so no successor reads this
as the residue's closure — the standing lesson of inbox `I-0630`/`I-0679`.

## Main declarations

* `AlgebraicGeometry.TruncExpCech.fstRingHom_surjective` — `fst : A[ε] → A` is surjective.
* `AlgebraicGeometry.TruncExpCech.ker_fstRingHom` — its kernel is `Ideal.span {ε}`.
* `AlgebraicGeometry.TruncExpCech.quotientSpanEpsRingEquiv` — hence `A[ε] ⧸ (ε) ≃+* A`.

Reference: `informal/w5-t4-worksheet.md` §§6.15, 6.17, 6.26, 6.27.
-/

set_option autoImplicit false

universe u

open TrivSqZeroExt DualNumber

namespace TruncExpCech

variable {A : Type u} [CommRing A]

/-- **`fst : A[ε] → A` is surjective**, with `inl` as a section. -/
theorem fstRingHom_surjective : Function.Surjective (fstRingHom (R := A)) := fun a =>
  ⟨inl a, by rw [fstRingHom_apply, TrivSqZeroExt.fst_inl]⟩

/-- **The kernel of `ε ↦ 0` is exactly the ideal generated by `ε`.**

This is the bridge the tangent computation needs: it makes `A` *the quotient* `A[ε] ⧸ (ε)`, which is
the only form in which mathlib's `QuotSMulTop.equivQuotTensor` will identify the base change
`A ⊗[A[ε]] M` with the reduction `M ⧸ (ε)·M`. See the module docstring for why the reverse inclusion
is three explicit `rw`s rather than a `simp`. -/
theorem ker_fstRingHom :
    RingHom.ker (fstRingHom (R := A)) = Ideal.span {(ε : DualNumber A)} := by
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker, fstRingHom_apply] at hx
    rw [Ideal.mem_span_singleton]
    refine ⟨inl x.snd, ?_⟩
    apply TrivSqZeroExt.ext
    · rw [hx, TrivSqZeroExt.fst_mul, DualNumber.fst_eps, zero_mul]
    · rw [TrivSqZeroExt.snd_mul, DualNumber.fst_eps, DualNumber.snd_eps,
        TrivSqZeroExt.fst_inl, TrivSqZeroExt.snd_inl]
      simp
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    show fstRingHom (ε : DualNumber A) = 0
    rw [fstRingHom_apply, DualNumber.fst_eps]

/-- **`A[ε] ⧸ (ε) ≃+* A`** — the first isomorphism theorem applied to `ε ↦ 0`, with the kernel
identified by `ker_fstRingHom`.

This is the form a consumer feeds to `QuotSMulTop.equivQuotTensor`: reducing an `A[ε]`-module
modulo `ε` **is** tensoring with `A` over `A[ε]`. -/
noncomputable def quotientSpanEpsRingEquiv :
    (DualNumber A ⧸ Ideal.span {(ε : DualNumber A)}) ≃+* A :=
  (Ideal.quotEquivOfEq ker_fstRingHom.symm).trans
    (RingHom.quotientKerEquivOfSurjective fstRingHom_surjective)

end TruncExpCech
