/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Tangent.CyclicQuotientGenerator
import Mathlib.LinearAlgebra.TensorProduct.Quotient

/-!
# Triviality of the reduction gives cyclicity (W5-T4, the last algebraic link of (iii-c2-aff))

`Tangent/CyclicQuotientGenerator.lean` reduces chart triviality to *"the reduction `M ⧸ (ε)·M` is
cyclic"*. This file shows that cyclicity follows from what the geometry actually delivers —
*"the base change of `M` along `A[ε] → A` is **free**"*, i.e. the invertible sheaf is trivial after
restricting along `ε ↦ 0`:

```
Module.Free (R ⧸ I) ((R ⧸ I) ⊗[R] M)   ⟹   M ⧸ I·M  is cyclic
```

(`Module.Invertible.quotient_smul_cyclic_of_free_baseChange`, stated for an arbitrary ideal `I`),
and its dual-number instance
`DualNumber.free_of_free_baseChange_eps` — *an invertible `A[ε]`-module whose reduction along
`ε ↦ 0` is free is itself free*.

## Why this is the honest end of the algebraic chain

Clause (iii-c2-aff) says: an `ε`-kernel Picard class is trivial on each thickened affine chart.
"`L` lies in the `ε`-kernel" means precisely that its restriction along `ε ↦ 0` is **trivial** —
and triviality of an invertible module is `Module.Free` (`CommRing.Pic.mk_eq_one_iff_free`). So
freeness of the base change is the hypothesis the geometry hands over, and the chain

* freeness of the base change ⟹ cyclicity of `M ⧸ (ε)·M` (**this file**),
* cyclicity ⟹ a generator (`Submodule.exists_sub_smul_mem_of_quotient_cyclic`),
* generator ⟹ `Module.Free A[ε] M` (`DualNumber.free_of_cyclic_mod_eps`),
* freeness ⟹ the chart class is `1` (`CommRing.Pic.eq_one_of_cyclic_mod_eps`),
* chart class `1` ⟹ `CechPic.map (V s).ι L = 1` (`Opens.cechPicMap_ι_eq_one_of_cechPicClass_eq_one`)

is complete **at the module level**. What remains of (iii-c2-aff) is therefore *only* the
sheaf-to-module identification: that the chart module of the `ε`-kernel class base-changes to the
chart module of its restriction. That is a statement about `Opens.cechPicClass` commuting with the
`ε ↦ 0` pullback, not about dual numbers or freeness — see worksheet §6.17.

## Implementation notes

Two mathlib facts do the work, and neither was obvious to find:

* `TensorProduct.quotTensorEquivQuotSMul M I : (R ⧸ I) ⊗[R] M ≃ₗ[R] M ⧸ I • ⊤` — the base change
  along `R → R ⧸ I` **is** the quotient by `I·M`. This is what lets a hypothesis about a tensor
  product be used as a hypothesis about `M ⧸ (ε)·M`.
* `Module.Invertible.free_iff_linearEquiv : Module.Free R M ↔ Nonempty (M ≃ₗ[R] R)` — an
  invertible module is free exactly when it *is* the ring, which is what makes it cyclic
  (`Module.Invertible.cyclic_of_free`): generated by the preimage of `1`.

The scalar bookkeeping at the end is the only fiddly part: the generator produced over `R ⧸ I`
carries an `R ⧸ I`-action, while the conclusion is stated with an `R`-action. They agree by
`Ideal.Quotient.algebraMap_eq` + `algebraMap_smul`, which is the `IsScalarTower` for the quotient
in disguise.

## Main declarations

* `Module.Invertible.cyclic_of_free` — an invertible free module is cyclic.
* `Module.Invertible.quotient_smul_cyclic_of_free_baseChange` — freeness of the base change along
  `R → R ⧸ I` gives cyclicity of `M ⧸ I·M`.
* `DualNumber.free_of_free_baseChange_eps` — the dual-number instance, chaining into
  `free_of_quotient_eps_cyclic`.

Reference: Kleiman, "The Picard scheme", §5 Thm. 5.11 (arXiv:math/0504020);
`informal/w5-t4-worksheet.md` §6.17.
-/

set_option autoImplicit false

universe u

open TensorProduct TrivSqZeroExt DualNumber

namespace Module.Invertible

variable (S : Type u) [CommRing S] (N : Type u) [AddCommGroup N] [Module S N]

/-- **An invertible module that is free is cyclic.** Invertibility plus freeness means `N ≃ₗ S`
(`Module.Invertible.free_iff_linearEquiv`), and `S` is generated by `1`, so `N` is generated by the
preimage of `1`.

Stated as the raw "some `y` generates" rather than through `Submodule.IsPrincipal` because that is
the shape `Submodule.exists_sub_smul_mem_of_quotient_cyclic` consumes. -/
theorem cyclic_of_free [Module.Invertible S N] [Module.Free S N] :
    ∃ y : N, ∀ z : N, ∃ r : S, z = r • y := by
  obtain ⟨e⟩ := (Module.Invertible.free_iff_linearEquiv (R := S) (M := N)).mp ‹_›
  refine ⟨e.symm 1, fun z => ⟨e z, ?_⟩⟩
  calc z = e.symm (e z) := (e.symm_apply_apply z).symm
    _ = e.symm (e z • (1 : S)) := by rw [smul_eq_mul, mul_one]
    _ = e z • e.symm 1 := map_smul _ _ _

end Module.Invertible

namespace Module.Invertible

variable {R : Type u} [CommRing R] {M : Type u} [AddCommGroup M] [Module R M]

set_option maxHeartbeats 1000000 in
/-- **Freeness of the base change gives cyclicity of the reduction.** For an invertible
`R`-module `M` and an ideal `I`, if `(R ⧸ I) ⊗[R] M` is free over `R ⧸ I` then `M ⧸ I·M` is cyclic
as an `R`-module.

This is the step that turns what the geometry supplies — *the sheaf is trivial after restriction*,
i.e. the base change is **free** — into the hypothesis
`Submodule.exists_sub_smul_mem_of_quotient_cyclic` wants.

`TensorProduct.quotTensorEquivQuotSMul` identifies the base change with `M ⧸ I·M`, and
`cyclic_of_free` supplies the generator on the tensor side; the rest is transporting the generator
across that equivalence and reconciling the `R ⧸ I`-action with the `R`-action
(`Ideal.Quotient.algebraMap_eq` + `algebraMap_smul`).

The raised heartbeat budget is for the `TensorProduct`/`Submodule.Quotient` instance towers on
`(R ⧸ I) ⊗[R] M`, which are deep; the proof itself is six steps. -/
theorem quotient_smul_cyclic_of_free_baseChange [Module.Invertible R M] (I : Ideal R)
    (hfree : Module.Free (R ⧸ I) ((R ⧸ I) ⊗[R] M)) :
    ∃ y : M ⧸ (I • (⊤ : Submodule R M)), ∀ z, ∃ r : R, z = r • y := by
  obtain ⟨y, hy⟩ := Module.Invertible.cyclic_of_free (R ⧸ I) ((R ⧸ I) ⊗[R] M)
  set E := TensorProduct.quotTensorEquivQuotSMul M I with hE
  refine ⟨E y, fun z => ?_⟩
  obtain ⟨r, hr⟩ := hy (E.symm z)
  obtain ⟨r', rfl⟩ := Ideal.Quotient.mk_surjective r
  refine ⟨r', ?_⟩
  have key : E (E.symm z) = E (Ideal.Quotient.mk I r' • y) := congrArg E hr
  rw [E.apply_symm_apply] at key
  rw [key]
  have hsm : (Ideal.Quotient.mk I r') • y = r' • y := by
    rw [← Ideal.Quotient.algebraMap_eq, algebraMap_smul]
  rw [hsm, E.map_smul]

end Module.Invertible

namespace DualNumber

variable (A : Type u) [CommRing A]

/-- **Chart triviality from freeness of the reduction** — the form clause (iii-c2-aff) hands over.

An invertible `A[ε]`-module whose base change along `ε ↦ 0` is free is itself free. "Free after
restriction" is exactly "the restricted class is trivial in the Picard group"
(`CommRing.Pic.mk_eq_one_iff_free`), so this is the module-level statement of *"an `ε`-kernel class
is trivial on the chart"*.

Composite of `Module.Invertible.quotient_smul_cyclic_of_free_baseChange` (freeness of the base
change ⟹ cyclic reduction) with `free_of_quotient_eps_cyclic` (cyclic reduction ⟹ free), the
latter itself the sibling-ported generator step. Note the base change is taken along
`A[ε] ⧸ (ε)`, not along `A` — the two are isomorphic but the statement is phrased on the quotient
so that no ring identification is needed here. -/
theorem free_of_free_baseChange_eps
    (M : Type u) [AddCommGroup M] [Module (DualNumber A) M]
    [Module.Invertible (DualNumber A) M]
    (hfree : Module.Free (DualNumber A ⧸ Ideal.span {(ε : DualNumber A)})
      ((DualNumber A ⧸ Ideal.span {(ε : DualNumber A)}) ⊗[DualNumber A] M)) :
    Module.Free (DualNumber A) M :=
  free_of_quotient_eps_cyclic A M
    (Module.Invertible.quotient_smul_cyclic_of_free_baseChange
      (Ideal.span {(ε : DualNumber A)}) hfree)

end DualNumber
