/-
Copyright (c) 2026 The AlgebraicJacobian authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AlgebraicJacobian Contributors
-/
import AlgebraicJacobian.Picard.GaloisDescent.SemilinearModules

/-!
# The Galois splitting of the self-tensor `L ⊗[K] L ≃ Gal(L/K) → L`

For a **finite Galois** extension `L/K` with group `G = Gal(L/K) = L ≃ₐ[K] L`, the
`L`-algebra map

`a ⊗ b ↦ (γ ↦ a * γ b) : L ⊗[K] L → (G → L)`

is an isomorphism (`galoisSelfTensorEquiv`).  Geometrically this is the statement
that `Spec L ×_{Spec K} Spec L` is `G` copies of `Spec L` — the fact that makes
the two pullback legs of a one-element Galois cover computable, and hence the
algebra input of the *invariance* half of Galois descent for the étale-sheafified
relative Picard functor.

## Why this file exists

`Picard/EtaleFieldCover.lean` builds the covering sieve generated by the single
morphism `Spec k' ⟶ Spec k`, and `Picard/PicEtDescentAssembly.lean` proves that a
*compatible family* on that cover has a unique amalgamation.  What stands between
a `Gal(k'/k)`-**invariant** `k'`-class and such a compatible family is agreement
on the two pullback legs of the sieve, and those legs live over
`Spec (k' ⊗[k] k')`.  Identifying that ring with `Gal(k'/k) → k'` is what turns
the group-theoretic hypothesis (invariance under each `γ`) into the sheaf-theoretic
one (agreement of two restrictions).

Measured absent before being built (`ajc-p1`, run 0083 r6, and independently by
`ajc-p2` in inbox `I-1367`): `exact?` fails on `Function.Bijective` of exactly
this map, and no name-shaped search over Mathlib or either project returns it.
Mathlib's two nearest relatives are genuinely different statements:

* `Algebra.Etale.iff_exists_algEquiv_prod` — an étale algebra is *some* finite
  product of finite separable extensions, with no identification of the index set
  with `Gal(L/K)` and no formula for the map;
* `Algebra.FormallyEtale.equivPiOfIsSepClosed` (`Mathlib/RingTheory/Etale/Field.lean`)
  — splits an étale algebra over a **separably closed** base, which is not the
  hypothesis here (if `K` were separably closed, `L = K`).

## Main results

* `galoisSelfTensorHom` — the `L`-algebra homomorphism `a ⊗ b ↦ (γ ↦ a * γ b)`.
* `galoisSelfTensorHom_bijective` — it is bijective.
* `galoisSelfTensorEquiv` — the resulting `L`-algebra equivalence, with
  `galoisSelfTensorEquiv_tmul` and `galoisSelfTensorEquiv_apply_tmul` for computing.
* `card_aut_eq_finrank_of_galoisSelfTensorHom_bijective` — the converse dimension
  count, and
* `galoisSelfTensorHom_bijective_iff_isGalois` — bijectivity **iff** Galois, for an
  arbitrary finite extension, which is what makes `[IsGalois K L]` the theorem's
  content rather than a hypothesis it merely uses.

## Proof

Surjectivity is Dedekind independence in the *column* form already in this
directory: `galoisCol_span` (`GaloisDescent/SemilinearModules.lean`) says the
vectors `(γ ↦ γ (b i))` span `G → L` over `L` for a `K`-basis `b` of `L`, and
those vectors are exactly the images `galoisSelfTensorHom (1 ⊗ₜ b i)`.  Injectivity
is then a dimension count: both sides have `L`-dimension `[L : K]`
(`Module.finrank_baseChange` on the left, `#G = [L:K]` on the right by
`IsGalois.card_aut_eq_finrank`), so a surjective `L`-linear map between them is
injective.

No hypothesis beyond `[FiniteDimensional K L] [IsGalois K L]`, and in particular
nothing about `K` being perfect or separably closed.

## What is measured, and what it does NOT buy

Every declaration here is `sorry`-free and axiom-clean
`[propext, Classical.choice, Quot.sound]`, against
`Scheme.fgaPicardRepresentability` as a control that correctly reports `sorryAx`
(the first five, being computations rather than proofs, do not even need
`Classical.choice`).

**Non-vacuity is measured at a nontrivial extension, not argued.** Three probes at
`ℂ/ℝ`, `lake env lean` `EXIT=0` (the `IsGalois ℝ ℂ` instance is not in Mathlib and
was assembled from `Normal` + separability for the probe): the equivalence is
inhabited there; the index group has **two** elements
(`IsGalois.card_aut_eq_finrank` + `Complex.finrank_real_complex`), so the statement
is not the one-copy identity in disguise; and the `conj`-component differs from the
identity-component at `1 ⊗ₜ I`, so the equivalence is not a relabelled diagonal.

**The Galois hypothesis is exactly the content, not merely consumed** — §3, and
this is the point a binder-deletion control cannot reach: bijectivity of the
splitting map holds **iff** `L/K` is Galois
(`galoisSelfTensorHom_bijective_iff_isGalois`, for an arbitrary finite extension).
So no proof could drop or weaken `[IsGalois K L]`.

**This discharges no antecedent of `Scheme.fgaPicardRepresentability`.** It is the
algebra input of *one* of the two steps between the landed sheaf axiom
(`Picard/EtaleFieldCover.lean`) and a descended `k`-class; the other is the
scheme-level Galois quotient, and `k'`-side representability — the Milne–Kollár
campaign's undischarged output — is untouched. Nothing here mentions `picEt`, and
supplying the *compatible family* from an invariant class still requires
identifying the sieve's two pullback legs through this equivalence, which is
`AJC.picrep.etale-rep.invariance` (`ajc-p2`) and not done here.

**ZERO CODE CONSUMERS at the time of writing** (`I-1399`, measured by grep of all
declaration names across the project): the three hits outside this file are
docstring prose in `Picard/PicEtDescentExistence.lean`. The file is rooted so it
builds; nothing reads it. That is not a vacuity — the statement is true and
non-vacuous — but the honest description is that a named absent brick is now
present, *not* that anything already written is unblocked. The value has moved to
the consumer step.

**And do not infer a binder on the descent from the `iff`** — an earlier revision of
this paragraph's release note did, and `ajc-p2` refuted it by reading the binder
lists (`I-1368`). Descent of `picEt`-**classes** runs at any finite *separable*
level: `isSheafFor_picEt_singleton_coverMap` and
`exists_unique_descend_picEt_of_projections` carry `[Algebra.IsSeparable]` and
`[Module.Finite]` and **no** `IsGalois`. Étaleness is all the sheaf side consumes,
and it does not need normality. Galois enters the route **exactly once**, at the
invariance bridge — and there because this file's `iff` makes the splitting *false*
below Galois, not for want of a lemma. The `iff` constrains where the splitting can
be used; it says nothing about what the sheaf theory requires.
-/

universe u v

open scoped TensorProduct
open Module

namespace AlgebraicJacobian.GaloisDescent

variable (K L : Type u) [Field K] [Field L] [Algebra K L]

/-! ## §1. The map -/

/-- The `K`-algebra map `L →ₐ[K] (Gal(L/K) → L)` sending `b` to `γ ↦ γ b`.

This is the "second leg" of the splitting: the copy of `L` that the Galois group
acts on.  It is a `K`-algebra map and not an `L`-algebra map, which is exactly why
the target is a product over `G` rather than a single copy of `L`.

It is `Pi.algHom` at the family `γ ↦ (γ : L →ₐ[K] L)`, and is *defined* that way:
an earlier revision hand-wrote the six `AlgHom` field proofs, which a fresh-context
audit measured `rfl`-equal to the library term (`I-1399`) — 11 lines re-deriving a
mathlib combinator this lane's own feasibility probe had used correctly. The
abbreviation is kept only because the name reads at the use sites. -/
def galoisEvalHom : L →ₐ[K] ((L ≃ₐ[K] L) → L) :=
  Pi.algHom _ _ fun γ : L ≃ₐ[K] L => (γ : L →ₐ[K] L)

@[simp] lemma galoisEvalHom_apply (b : L) (γ : L ≃ₐ[K] L) :
    galoisEvalHom K L b γ = γ b := rfl

/-- **The Galois splitting map** `L ⊗[K] L →ₐ[L] (Gal(L/K) → L)`,
`a ⊗ b ↦ (γ ↦ a * γ b)`.

The `L`-algebra structure on the source is the one on the **left** tensor factor,
and on the target it is the diagonal (constant functions); the left factor is
carried across untwisted, the right factor by evaluation at each `γ`. -/
noncomputable def galoisSelfTensorHom : L ⊗[K] L →ₐ[L] ((L ≃ₐ[K] L) → L) :=
  Algebra.TensorProduct.lift (Algebra.ofId L _) (galoisEvalHom K L)
    fun _ _ => Commute.all _ _

@[simp] lemma galoisSelfTensorHom_tmul (a b : L) :
    galoisSelfTensorHom K L (a ⊗ₜ[K] b) = fun γ => a * γ b := by
  ext γ
  simp [galoisSelfTensorHom, Algebra.ofId_apply, Algebra.algebraMap_eq_smul_one]

lemma galoisSelfTensorHom_tmul_apply (a b : L) (γ : L ≃ₐ[K] L) :
    galoisSelfTensorHom K L (a ⊗ₜ[K] b) γ = a * γ b := by
  rw [galoisSelfTensorHom_tmul]

/-! ## §2. Bijectivity -/

section Galois

variable [FiniteDimensional K L] [IsGalois K L]

/-- The `L`-dimension of the target `Gal(L/K) → L` is `[L : K]`.

`#Gal(L/K) = [L:K]` is `IsGalois.card_aut_eq_finrank`; this is the only place the
Galois hypothesis (as opposed to mere finite separability) enters the dimension
count, and it is what makes the index set of the splitting the Galois group rather
than an unnamed finite set. -/
theorem finrank_pi_aut : finrank L ((L ≃ₐ[K] L) → L) = finrank K L := by
  haveI : Fintype (L ≃ₐ[K] L) := AlgEquiv.fintype K L
  rw [Module.finrank_fintype_fun_eq_card, ← Nat.card_eq_fintype_card,
    IsGalois.card_aut_eq_finrank K L]

/-- The splitting map is **surjective**: Dedekind independence, column form.

`galoisCol_span` says the vectors `(γ ↦ γ (b i))` span `Gal(L/K) → L` over `L`;
those vectors are the images of `1 ⊗ₜ b i`, so the range — an `L`-submodule
containing them — is everything. -/
theorem galoisSelfTensorHom_surjective :
    Function.Surjective (galoisSelfTensorHom K L) := by
  classical
  set ι := Fin (finrank K L) with hι
  let b : Basis ι K L := Module.finBasis K L
  -- the range of the `L`-linear map underlying `galoisSelfTensorHom`
  set S : Submodule L ((L ≃ₐ[K] L) → L) :=
    LinearMap.range (galoisSelfTensorHom K L).toLinearMap with hS
  have hspan : Submodule.span L
      (Set.range (fun i : ι => (fun γ => γ (b i) : (L ≃ₐ[K] L) → L))) = ⊤ :=
    galoisCol_span b
  have hsub : Submodule.span L
      (Set.range (fun i : ι => (fun γ => γ (b i) : (L ≃ₐ[K] L) → L))) ≤ S := by
    rw [Submodule.span_le]
    rintro x ⟨i, rfl⟩
    exact ⟨(1 : L) ⊗ₜ[K] b i, by ext γ; simp⟩
  have htop : S = ⊤ := top_le_iff.mp (hspan ▸ hsub)
  intro y
  have : y ∈ S := htop ▸ Submodule.mem_top
  obtain ⟨x, hx⟩ := this
  exact ⟨x, hx⟩

/-- The splitting map is **bijective**.

Injectivity is not proved directly: it follows from surjectivity because the two
`L`-modules have the same finite dimension `[L : K]` — `Module.finrank_baseChange`
on the source, `finrank_pi_aut` on the target. -/
theorem galoisSelfTensorHom_bijective :
    Function.Bijective (galoisSelfTensorHom K L) := by
  haveI : Fintype (L ≃ₐ[K] L) := AlgEquiv.fintype K L
  have hdim : finrank L (L ⊗[K] L) = finrank L ((L ≃ₐ[K] L) → L) := by
    rw [Module.finrank_baseChange, finrank_pi_aut]
  refine ⟨?_, galoisSelfTensorHom_surjective K L⟩
  exact (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hdim).mpr
    (galoisSelfTensorHom_surjective K L)

/-- **The Galois splitting of the self-tensor.** For a finite Galois extension
`L/K`, the `L`-algebra map `a ⊗ b ↦ (γ ↦ a * γ b)` is an isomorphism

`L ⊗[K] L ≃ₐ[L] (Gal(L/K) → L)`.

Scheme-theoretically: `Spec L ×_{Spec K} Spec L ≅ ⨿_{γ ∈ Gal(L/K)} Spec L`. This
is the computation of the two pullback legs of a one-element Galois cover, i.e.
the algebra input of the invariance half of Galois descent. -/
noncomputable def galoisSelfTensorEquiv : (L ⊗[K] L) ≃ₐ[L] ((L ≃ₐ[K] L) → L) :=
  AlgEquiv.ofBijective (galoisSelfTensorHom K L) (galoisSelfTensorHom_bijective K L)

@[simp] lemma galoisSelfTensorEquiv_tmul (a b : L) :
    galoisSelfTensorEquiv K L (a ⊗ₜ[K] b) = fun γ => a * γ b :=
  galoisSelfTensorHom_tmul K L a b

lemma galoisSelfTensorEquiv_apply_tmul (a b : L) (γ : L ≃ₐ[K] L) :
    galoisSelfTensorEquiv K L (a ⊗ₜ[K] b) γ = a * γ b :=
  galoisSelfTensorHom_tmul_apply K L a b γ

end Galois

/-! ## §3. The Galois hypothesis is necessary, not merely consumed

The usual control for "does this proof use hypothesis `H`" — delete the binder and
watch elaboration fail — shows only that `H` is *named*. What is proved here is
strictly stronger and it is an equivalence:

`galoisSelfTensorHom_bijective_iff_isGalois` — for **any** finite extension,
bijectivity of `a ⊗ b ↦ (γ ↦ a * γ b)` holds **iff** `L/K` is Galois.

So `[IsGalois K L]` cannot be dropped or weakened by any proof, and the theorem is
not merely "true under a hypothesis it happens to consume" — the hypothesis is
exactly its content. The forward direction is the dimension count
(`card_aut_eq_finrank_of_galoisSelfTensorHom_bijective`); the converse is Mathlib's
Galois criterion `IsGalois.of_card_aut_eq_finrank` (Stacks 09I1, "if" part).

**Stated as an `iff` rather than as prose about a counterexample, on purpose.** An
earlier revision of this section argued necessity by asserting that
`ℚ(2^(1/3))/ℚ` has `#Aut = 1 < 3 = [L:K]` — true, and *unverified in Lean*, i.e.
exactly the shape of claim this project keeps having refuted. The equivalence is
machine-checked and needs no witness. -/

/-- **The converse dimension count**: if the splitting map is bijective then the
automorphism group has order `[L : K]`.

Fed to Mathlib's Galois criterion this gives the `iff` below, which is what makes
`[IsGalois K L]` the content of `galoisSelfTensorHom_bijective` rather than a
hypothesis it happens to consume.

**No finiteness binder**, and that is measured, not stylistic (`I-1397`): an earlier
revision carried `[FiniteDimensional K L]` and the proof never touched it — the body
verbatim elaborates without it, `lake env lean` `EXIT=0`. `finrank` of a
non-finite-dimensional module is `0` by definition, so both sides degenerate
consistently; the only finiteness the statement reads is `[Fintype (L ≃ₐ[K] L)]`,
already explicit. The `iff` below *does* need `[FiniteDimensional K L]`
(`AlgEquiv.fintype`, and Mathlib's criterion), so the two are stated separately
rather than bundled.

Note for whoever checks the next one of these: `lean_minimal_hypotheses` **cannot
see this defect** — it skips instance binders by design, and it reported this
theorem clean. Instance binders have to be probed by re-elaborating the body with
the binder deleted. -/
theorem card_aut_eq_finrank_of_galoisSelfTensorHom_bijective
    [Fintype (L ≃ₐ[K] L)]
    (h : Function.Bijective (galoisSelfTensorHom K L)) :
    Fintype.card (L ≃ₐ[K] L) = finrank K L := by
  have hlin : Function.Bijective ((galoisSelfTensorHom K L).toLinearMap) := h
  have hrk := (LinearEquiv.ofBijective _ hlin).finrank_eq
  rw [Module.finrank_baseChange, Module.finrank_fintype_fun_eq_card] at hrk
  exact hrk.symm

/-- **The splitting is bijective if and only if `L/K` is Galois.**

This is the sharp form of "the hypothesis is necessary", and it is what the
dimension count above buys once it is paired with Mathlib's Galois criterion
`IsGalois.of_card_aut_eq_finrank` (Stacks 09I1, "if" part). No separability or
normality hypothesis appears: for *any* finite extension, bijectivity of
`a ⊗ b ↦ (γ ↦ a * γ b)` is equivalent to being Galois.

So `[IsGalois K L]` in `galoisSelfTensorHom_bijective` cannot be weakened by any
proof whatsoever — not merely "is used by this proof". Stating it as an `iff`
rather than as prose about `ℚ(2^(1/3))/ℚ` is deliberate: an unverified
counterexample in a docstring is an assertion, and this direction is
machine-checked instead. -/
theorem galoisSelfTensorHom_bijective_iff_isGalois [FiniteDimensional K L] :
    Function.Bijective (galoisSelfTensorHom K L) ↔ IsGalois K L := by
  haveI : Fintype (L ≃ₐ[K] L) := AlgEquiv.fintype K L
  refine ⟨fun h => IsGalois.of_card_aut_eq_finrank K L ?_,
    fun _ => galoisSelfTensorHom_bijective K L⟩
  rw [Nat.card_eq_fintype_card]
  exact card_aut_eq_finrank_of_galoisSelfTensorHom_bijective K L h

section Galois

variable [FiniteDimensional K L] [IsGalois K L]

/-- The `γ`-component of the splitting, as an algebra map: `a ⊗ b ↦ a * γ b`.

Recorded because the consumer does not usually want the whole product — it wants
the two legs of the sieve separately, which are the components at `1` and at a
general `γ`. -/
lemma galoisSelfTensorEquiv_comp_apply (γ : L ≃ₐ[K] L) (x : L ⊗[K] L) :
    galoisSelfTensorEquiv K L x γ =
      (Algebra.TensorProduct.lift (AlgHom.id L L) (γ : L →ₐ[K] L)
        fun _ _ => Commute.all _ _) x := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul a b => simp [galoisSelfTensorEquiv_apply_tmul]
  | add x y hx hy => simp [hx, hy]

end Galois

end AlgebraicJacobian.GaloisDescent
